### ISSUE TITLE
中文域名后台设置

### ISSUE THREAD

**Issue by RainshawGao** [typecho/typecho#1000]
### 1. 该问题的重现步骤是什么？
使用中文域名

### 2. 你期待的结果是什么？实际看到的又是什么？
期待后台设置中填入中文域名没有警告，实际会解析为punycode码

### 3. 问题出现的环境

- 操作系统版本：ubuntu20
- Apache/NGINX 版本：1.18
- 数据库版本：mysql5.7
- PHP 版本：7.2
- Typecho 版本：1.1
- 浏览器版本：Edge

[//]: # (如有图片请附上截图)
<img width="551" alt="QQ20200806-222201@2x" src="https://user-images.githubusercontent.com/23495403/89543245-458cab80-d833-11ea-9b52-a110c6ac1fc6.png">

**Comment by jrotty** [comment]
感觉填写punycode码就行了，因为中文域名实际在浏览器访问时也是被转码处理的吧
