### ISSUE TITLE
官网的下载有问题

### ISSUE THREAD

**Issue by wangdaodao** [typecho/typecho#1002]
### 1. 该问题的重现步骤是什么？
不显示版本和打包时间

### 2. 你期待的结果是什么？实际看到的又是什么？
希望官方修复。

### 3. 问题出现的环境

- 操作系统版本：win10
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：火狐

![](http://pic.wangdaodao.com/markdown/20200811091210.png)

**Comment by fenbox** [comment]
latest 不影响
