### ISSUE TITLE
pingback 功能异常

### ISSUE THREAD

**Issue by ADD-SP** [typecho/typecho#1007]
### 1. 该问题的重现步骤是什么？

nginx 配置如下（部分内容被隐去）
```text
server {
        server_name   example.com;
        root   /path/to/typecho;
        index           index.html index.htm index.php;
	listen	443 ssl http2;
        add_header X-Frame-Options "DENY";
        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        ssl_certificate /path/to/crt
        ssl_certificate_key /path/to/key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
        ssl_prefer_server_ciphers on;

        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.php$1 last;
        }

        location ~ .*\.php(\/.*)*$ {
            fastcgi_pass    unix:/run/php/php7.4-fpm.sock;  
            fastcgi_split_path_info ^(.+?.php)(/.*)$;
            fastcgi_param   SCRIPT_FILENAME  $document_root$fastcgi_script_name;  
            include         fastcgi_params;  
            include         fastcgi.conf;
        }
}
```

#### **使用 Typecho 自带的功能发送 pingback**

1. 建立两个 typecho 博客，分别称为 A 博客和 B 博客。
2. 在 A 博客中新发布一个文章，文章中包含指向 B 博客的一篇文章的链接。下面是截取的文章内容片段
```text
[link](https://B.com/archives/1)
<a href="https://B.com/archives/1">link</a>
https://B.com/archives/1
````
3. 发布文章。
4. B 博客后台未出现 pingback 引用评论。

***

1. 在博客内新发布一个文章。
2. 文章的内容包含该博客的另一篇文章的网址
```text
[link](https://example.com/archives/1)
<a href="https://example.com/archives/1">link</a>
https://example.com/archives/1
```
3. 发布文章。
4. 博客后台未出现 pingback 引用评论。

#### **使用在线工具发送 pingback**

1. 使用[reqbin](https://reqbin.com/)发送 XML-RPC 请求。
2. 请求体内容见下
```xml
<?xml version=\"1.0\"?>
<methodCall>
    <methodName>pingback.ping</methodName>
    <params>
        <param>
            <value>
                <string>https://example.com/archives/12/</string>
            </value>
        </param>
        <param>
            <value>
                <string>https://example.com/archives/20/</string>
            </value>
        </param>
    </params>
</methodCall>
```
3. 请求地址为`https://example.com/action/xmlrpc`
4. 请求方法为`POST`
5. 发送请求后的返回内容为
```xml
<?xml version="1.0"?>
<methodResponse>
  <params>
    <param>
      <value>
        <string>7</string>
      </value>
    </param>
  </params>
</methodResponse>
```
6. 后台出现 pingback 引用评论。

#### **使用 Typecho 自带的功能发送 pingback**

期待的结果：B 博客的后台出现 pingback 引用评论。
实际看到的结果：B 博客的后台没有变化。

*** 

期待的结果：博客的后台出现 pingback 引用评论。
实际看到的结果：博客的后台没有变化。

#### **使用在线工具发送 pingback**

该测试中 pingback 正常工作。

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 18.04 LTS
- Apache/NGINX 版本：nginx 1.18.0
- 数据库版本： Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)
- PHP 版本：PHP 7.4.9
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Microsoft Edge 版本 85.0.564.44 (官方内部版本) (64 位)

[//]: # (如有图片请附上截图)

**Comment by Seevil** [comment]
这个上次我也使用了一次好像也是没消息没仔细测试后来后台关了

**Comment by joyqi** [comment]
出现这个返回证明你的pingback已经被存入，可能进入了垃圾箱或者待审核列表，你可以查看下。

**Comment by Seevil** [comment]
> 出现这个返回证明你的pingback已经被存入，可能进入了垃圾箱或者待审核列表，你可以查看下。
哦豁，以前都没用过这东西

**Comment by ShangJixin** [comment]
pingback的收功能是好使的，不知道发功能，是否好使。我这两天发了个文，文章里包含链接，格式为markdown（对方是WordPress），然后那个引用的那个编辑框我也输入了（这个应该是Trackback吧），两者双管齐下，对方的评论区内未见pingback/trackback。

应该就是Typecho的发pingback的功能可能....可能有点问题吧
