### ISSUE TITLE
网站使用https时网站后台排版混乱及无法登录问题

### ISSUE THREAD

**Issue by littledoge** [typecho/typecho#1017]
### 1. 该问题的重现步骤是什么？
在https协议下登录网站后台即出现此问题
### 2. 你期待的结果是什么？实际看到的又是什么？
网站后台正常加载且可登录
实际情况：
![](https://pic.downk.cc/item/5f7b2fac160a154a67baafd5.png)
后台登录时无返回，且无法登录
![](https://pic.downk.cc/item/5f7b2fe8160a154a67bac1bf.jpg)
### 3. 问题出现的环境

- 操作系统版本：Ubuntu 18.04.2 LTS
- Apache/NGINX 版本：Nginx-Tengine 2.2.4
- 数据库版本：MySQL 5.7.31
- PHP 版本：PHP 7.1
- Typecho 版本：稳定版1.1 (17.10.30)
- 浏览器版本：Mozilla Firefox 60.8.0 ESR、华为内置浏览器11.0.2.301均复现此问题

### 4.问题分析
Typecho_Common类将资源路径转化为链接时并未考虑http及https协议的问题，客户端在获取数据时获取到的是http链接(可能相对路径被自动转换为http？)，而https内混合http传输的脚本属于不安全行为，会被浏览器自动拦截，后台便无法正常工作。
![](https://pic.downk.cc/item/5f7b31c5160a154a67bb48be.jpg)
[//]: # (如有图片请附上截图)

**Comment by littledoge** [comment]
图片插不进去...？
实际情况图片：https://pic.downk.cc/item/5f7b2fac160a154a67baafd5.png
https://pic.downk.cc/item/5f7b2fe8160a154a67bac1bf.jpg
客户端获取数据截图：
https://pic.downk.cc/item/5f7b31c5160a154a67bb48be.jpg

**Comment by forever8938** [comment]
网站目录下的config.inc.php文件里加一行

```
define('__TYPECHO_SECURE__',true);
```
