### ISSUE TITLE
目前Markdown不支持数学公式，不支持流程图、甘特图。

### ISSUE THREAD

**Issue by UIdoer** [typecho/typecho#1020]
希望typecho可以向csdn学习

**Comment by UIdoer** [comment]
KaTeX数学公式:https://khan.github.io/KaTeX/
甘特图：https://mermaid-js.github.io/mermaid/#/gantt
UML图：https://mermaid-js.github.io/mermaid/#/sequenceDiagram
流程图：https://mermaid-js.github.io/mermaid/#/flowchart?id=graph
Flowchart流程图:http: //flowchart.js.org/

**Comment by UIdoer** [comment]
csdn的Markdown: https://editor.csdn.net/md/

**Comment by scvoet** [comment]
欢迎向 Typecho 解析引擎 [SegmentFault/HyperDown](https://github.com/segmentfault/hyperdown) 提供贡献

**Comment by UIdoer** [comment]
@scvoet  这个是说明文档？？？ [https://github.com/segmentfault/hyperdown](SegmentFault/HyperDown)

**Comment by UIdoer** [comment]
@scvoet 这个是说明文档？[SegmentFault/HyperDown](https://github.com/segmentfault/hyperdown)

**Comment by scvoet** [comment]
> @scvoet 这个是说明文档？[SegmentFault/HyperDown](https://github.com/segmentfault/hyperdown)

解析引擎的上游

**Comment by scvoet** [comment]
话说 mermaid 只是和 markdown 类似而已，似乎不应该加入。

**Comment by UIdoer** [comment]
@scvoet  我说的是这个：
![image](https://user-images.githubusercontent.com/23623217/96346409-457c1800-10ce-11eb-978a-f7c7c3cd2ec6.png)

**Comment by scvoet** [comment]
> @scvoet 我说的是这个：
> ![image](https://user-images.githubusercontent.com/23623217/96346409-457c1800-10ce-11eb-978a-f7c7c3cd2ec6.png)

这些并不是 Markdown 而是由 mermaid 扩展出来的

**Comment by scvoet** [comment]
> @scvoet 我说的是这个：
> ![image](https://user-images.githubusercontent.com/23623217/96346409-457c1800-10ce-11eb-978a-f7c7c3cd2ec6.png)

这些并不是 Markdown 而是由 mermaid 扩展出来的

**Comment by UIdoer** [comment]
@scvoet 这就是我的需求呀。希望可以在新版本中加入

**Comment by greenhat616** [comment]
你完全可以使用插件来实现

**Comment by greenhat616** [comment]
通用的 Markdown 标准一般也就 CommonMark 和 GitHub Flavored Markdown 了吧

**Comment by mrgeneralgoo** [comment]
> @scvoet 这就是我的需求呀。希望可以在新版本中加入

可以试试 [Markdown Plugin for Typecho](https://github.com/mrgeneralgoo/typecho-markdown)

**Comment by ArielHeleneto** [comment]
请考虑vditor
