### ISSUE TITLE
远程图片链接无法加载

### ISSUE THREAD

**Issue by Jamesbing-wu** [typecho/typecho#1023]
### 1. 该问题的重现步骤是什么？
撰写新文章，插入远程图片的链接，然后在预览里查看图片是否显示。
### 2. 你期待的结果是什么？实际看到的又是什么？
预览中显示图片。
实际并未显示。
### 3. 问题出现的环境

- 操作系统版本：ubuntu18.04
- Apache/NGINX 版本：2.4.29
- 数据库版本： mysql5.7.30
- PHP 版本：
- Typecho 版本：1.1
- 浏览器版本：
![](http://jamesbing.cn/image/20201023155817.png)
预览：
![](http://jamesbing.cn/image/20201023155834.png)
图片未显示
[//]: # (如有图片请附上截图)

**Comment by scvoet** [comment]
http://jamesbing.cn/image/20201023152107.png/
以你图片中的链接为例，打开为
![图片](https://user-images.githubusercontent.com/45708948/96987290-653f9000-1555-11eb-9bdc-fb6d5f1363a2.png)

根据提示，显而易见是你的链接没有传递 key 参数。这与 Typecho 无关

**Comment by Jamesbing-wu** [comment]
谢谢，因为我已关闭了这个oss，因此访问无效了

**Comment by pelapi** [comment]
遇到了相同的问题，求教如何解决
