### ISSUE TITLE
密码保护的文章不论输入密码是否正确都报错

### ISSUE THREAD

**Issue by asd-a** [typecho/typecho#1029]
### 1. 该问题的重现步骤是什么？
进入带密码的文章页面，输入密码即可
### 2. 你期待的结果是什么？实际看到的又是什么？
输入正确直接跳转，结果报错（提示密码错误）

现有的主题都试过了，都有问题，应该是接口出的问题

### bonus: 密码错误提示能不能优化一下，每次输错都要点回去，希望设计登陆界面的错误提示

**Comment by fenbox** [comment]
无法复现呢
