### ISSUE TITLE
 版本1.2 (18.1.29)插入代码会404

### ISSUE THREAD

**Issue by Echocipher** [typecho/typecho#1031]
### 1. 该问题的重现步骤是什么？
编辑文章 ，然后输入下列代码

\```
import requests

m3u8_url = 'https://demo.com/drm/v..m3u8'
headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'
}
r = requests.get(url=m3u8_url,headers=headers)

print(r.text)

\```

然后保存草稿
### 2. 你期待的结果是什么？实际看到的又是什么？

正常保存草稿，实际会提示

```
404 Not Found
openresty/1.15.8.1
```

### 3. 问题出现的环境

- 操作系统版本：CentOS Linux release 7.3.1611 (Core)
- Apache/NGINX 版本：Nginx 1.15
- 数据库版本：Mysql 5.7.27
- PHP 版本：PHP 7.3.8
- Typecho 版本： 版本1.2 (18.1.29)
- 浏览器版本：Microsoft Edge 87.0.664.41

[//]: # (如有图片请附上截图)

**Comment by dyt5AAUI** [comment]
版本不是18.10.23

**Comment by Echocipher** [comment]
> 版本不是18.10.23

后台显示 由 Typecho 强力驱动, 版本 1.2 (18.1.29)

**Comment by dyt5AAUI** [comment]
由 Typecho 强力驱动, 版本 1.2 (18.10.23)
这是我的后台

**Comment by scvoet** [comment]
在 https://github.com/typecho/typecho/commit/1cc30665697805ab49f8aac901bb898b78284e80 下无法复现，建议更新到 https://github.com/typecho/typecho/commit/1cc30665697805ab49f8aac901bb898b78284e80 并开启 `debug` 重新测试。

**Comment by Echocipher** [comment]
> 在 [1cc3066](https://github.com/typecho/typecho/commit/1cc30665697805ab49f8aac901bb898b78284e80) 下无法复现，建议更新到 [1cc3066](https://github.com/typecho/typecho/commit/1cc30665697805ab49f8aac901bb898b78284e80) 并开启 `debug` 重新测试。

谢谢 我试试

**Comment by Alex-NKG** [comment]
你是否安装了防火墙？大概率防火墙拦截

**Comment by Echocipher** [comment]
重置环境后问题已经消失，大概率是防火墙拦截
