### ISSUE TITLE
PHP-8.0.0无法管理评论

### ISSUE THREAD

**Issue by BapiGso** [typecho/typecho#1033]
### 1. 该问题的重现步骤是什么？
无
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：NGINX1.19.2
- 数据库版本：sqlite3
- PHP 版本：8.0.0
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Chrome 86&Firefox 83.0

[//]: # (如有图片请附上截图)
<a href="https://imgchr.com/i/DdwzuT"><img src="https://s3.ax1x.com/2020/11/25/DdwzuT.png" alt="DdwzuT.png" border="0" /></a>

**Comment by BapiGso** [comment]
/var/json.php中花括号改为中括号解决了

**Comment by chengs2035** [comment]
+1 ，我也遇到了
