### ISSUE TITLE
https

### ISSUE THREAD

**Issue by luckywords** [typecho/typecho#1035]
### 1. 该问题的重现步骤是什么？
https无法访问，只能配置http
### 2. 你期待的结果是什么？实际看到的又是什么？
https可以访问，现在只能配置http
### 3. 问题出现的环境
nginx1.18 php7.4 MySQL5.5
- 操作系统版本：
- Apache/NGINX 版本：1.18
- 数据库版本：MySQL5.5
- PHP 版本：7.4
- Typecho 版本：
- 浏览器版本：Chrome82

[//]: # (如有图片请附上截图)

**Comment by chengs2035** [comment]
这是nginx配置的问题，跟typecho没关系。
