### ISSUE TITLE
怎么使用自己的 Widget 

### ISSUE THREAD

**Issue by turnmind** [typecho/typecho#1036]
**在个人插件目录如何调用自己的 Widget 类**

**Comment by huoqiefei** [comment]
使用$this->widget()可以调用自己写的widget.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: turnmind <notifications@github.com>
发送时间: Thursday, December 3, 2020 4:29:48 PM
收件人: typecho/typecho <typecho@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [typecho/typecho] 怎么使用自己的 Widget (#1036)


在个人插件目录如何调用自己的 Widget 类

―
