### ISSUE TITLE
PHP 8.0 无法登陆后台

### ISSUE THREAD

**Issue by Vndroid** [typecho/typecho#1037]
### 1. 该问题的重现步骤是什么？

升级环境到 PHP 8.0 正式版

### 2. 你期待的结果是什么？实际看到的又是什么？

期待：能正常登陆后台
实际：无法登陆后台，提示密码错误，后台可看到 debug 日志如下

```
nginx_1      | 2020/12/04 03:33:15 [error] 19#19: *20 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/dynamic/admin/common.php on line 32PHP message: PHP Stack trace:PHP message: PHP   1. {main}() /var/www/dynamic/admin/login.php:0PHP message: PHP   2. include() /var/www/dynamic/admin/login.php:2" while reading response header from upstream, client: 14.58.15.55, server: www.xxx.net, request: "GET /admin/login.php?referer=https%3A%2F%2Fwww.xxx.net%2Fadmin%2Fwelcome.php HTTP/2.0", upstream: "fastcgi://172.21.0.5:9000", host: "www.vvave.net", referrer: "https://www.xxx.net/admin/login.php?referer=https%3A%2F%2Fwww.xxx.net%2Fadmin%2Fwelcome.php"
```

### 3. 问题出现的环境

- 操作系统版本：Debian 10
- Apache/NGINX 版本：1.18.0
- 数据库版本：MariaDB 10.15
- PHP 版本：8.0
- Typecho 版本：(f9dfb1bb85fbc93d5da9aff491b08cec70ed6dd7)
- 浏览器版本：Chrome 87

[//]: # (如有图片请附上截图)

**Comment by qu5** [comment]
不仅是后台页面，文章页面也不支持php8。希望能尽快支持php8，并以此为契机发布新版typecho。
> 念念不忘，必有回响
> 三年 Typecho 沉淀，现在，回应您的等待
2017年之后又三年沉淀，希望真的能有回想。

**Comment by qu5** [comment]
> 念念不忘，必有回响
> 三年 Typecho 沉淀，现在，回应您的等待

希望经过又三年的沉淀，typecho可以以此为契机发布兼容php8的新版本。

**Comment by CberYellowstone** [comment]
支持,希望尽快支持php8.0

**Comment by sy3tem** [comment]
安装程序的锅，数据库密码字段只有个*。。。
![微信截图_20201207195757.png](https://i.loli.net/2020/12/07/xmIDn2W7GEcLz4i.png)

**Comment by joyqi** [comment]
我在php 8上无法复现这个错误

**Comment by rakiy** [comment]
已经修复，#1039

**Comment by Vndroid** [comment]
相比之下，我更好奇为什么作者没复现这个问题（狗头

**Comment by rakiy** [comment]
他是新装的吧😬
