### ISSUE TITLE
发现安全问题，index.php不是最新版

### ISSUE THREAD

**Issue by Candz** [typecho/typecho#1047]
### 1. 该问题的重现步骤是什么？
![CUTuKT](https://gitee.com/candz/imgBed/raw/master/uPic/CUTuKT.png)
你好，升级报错“发现安全问题，index.php不是最新版”

### 2. 你期待的结果是什么？实际看到的又是什么？
希望可以正常升级
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：5.6
- Typecho 版本：1.1
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by scvoet** [comment]
手动覆盖啊

**Comment by Candz** [comment]
已经按照要求把服务器上admin、var、index.php和install.php删除后，把下载的开发版的包里面的对应文件和目录上传到服务器啊。而且index.php两年多没更新了，按道理不应该报这个错啊

**Comment by Candz** [comment]
> 手动覆盖啊

已经按照要求把服务器上admin、var、index.php和install.php删除后，把下载的开发版的包里面的对应文件和目录上传到服务器啊。而且index.php两年多没更新了，按道理不应该报这个错

**Comment by joyqi** [comment]
你是不是用的 ftp 上传的文件，可以把传输模式改为二进制试试

**Comment by Candz** [comment]
> 你是不是用的 ftp 上传的文件，可以把传输模式改为二进制试试

谢谢，按照你说的FTP改为二进制解决了，已经升级到左新版本版本 1.2 (18.1.29)
