### ISSUE TITLE
根据现有的公安备案需求，tp的程序已经不能满足，希望可以进行优化

### ISSUE THREAD

**Issue by noisky** [typecho/typecho#1054]
目前已知现有的公安交互备案审核要求如下：
网站审核包括：
1、评论是否经过审核后发布；
2、网站后台是否能查看评论用户IP和端口；
3、网站注册是否有手机号验证；
4、能否对用户评论进行关键字、敏感词过滤。

评论审核的功能已经有了，评论的IP也有了，但是端口是没有记录的；
现在国内对实名验证的要求也是硬性的，所以也需要评论的实名验证/伪实名验证功能，例如手机号验证等....
敏感词过滤功能现在可以通过评论插件实现，但是也希望官方增加相应的评论增强功能。

一点建议，希望可以增加以上的功能。

**Comment by gogobody** [comment]
这个应该留给第三方插件去做，手机号验证这种是要付费的

**Comment by joyqi** [comment]
首先，根据我的理解，应该是不要求记录端口的。其次，手机号注册和关键字过滤，应该交给插件去解决，后者已经有一些插件了。
