### ISSUE TITLE
文章在编辑后无法访问

### ISSUE THREAD

**Issue by itzdrli** [typecho/typecho#1057]
### 3. arm处理器，树莓派zero w

- 操作系统版本：Linux version 5.4.83+
- Apache/NGINX 版本：nginx 1.14.2
- 数据库版本：SQLite version 3.27.2
- PHP 版本：PHP 7.3.19
- Typecho 版本： 1.1 (17.10.30)
- 浏览器版本：google chrome 87.0.4280.141(64位)

[//]: # (如有图片请附上截图)

**Comment by llt12213** [comment]
补充：版本 1.2 (18.10.23)
后台设置里的允许上传的文件类型里中的其他格式中无法填入py

**Comment by TML233** [comment]
你看一下文章的发布时间，不知道为什么，发布时间在编辑后会变成错误时间，导致误触发定时发布功能
