### ISSUE TITLE
关于版本问题

### ISSUE THREAD

**Issue by dyt5AAUI** [typecho/typecho#1059]
### 1. 该问题的重现步骤是什么？
版本号现在是 1.2 (18.10.23)与 1.2 (18.1.29)哪个版本新呢
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by Edmunddz** [comment]
括号里面的 是版本日期 (18.10.23)是2018.10.23更新，(18.1.29)是2018.1.29更新

**Comment by dyt5AAUI** [comment]
> 括号里面的 是版本日期 (18.10.23)是2018.10.23更新，(18.1.29)是2018.1.29更新

谢谢。
