### ISSUE TITLE
关于Default主题在渲染KaTeX时公式中字符错位

### ISSUE THREAD

**Issue by ViXbob** [typecho/typecho#1060]
### 1. 该问题的重现步骤是什么？

使用KaTeX渲染数学公式

### 2. 你期待的结果是什么？实际看到的又是什么？

期望渲染效果：

![](https://my-own-picture.oss-cn-beijing.aliyuncs.com/uPic/2021013022503016120182301612018230290LEEe8b.png)

实际渲染效果：

![](https://my-own-picture.oss-cn-beijing.aliyuncs.com/uPic/20210130225156161201831616120183161136ZbmsY.png)

### 3. 问题出现的环境

- 操作系统版本：CentOS 8.0 64bit
- Apache/NGINX 版本：Nginx 1.18.0
- 数据库版本：MySQL 5.6.50
- PHP 版本：PHP-5.6
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Chrome 88.0.4324.96

### 4.问题初步分析

Default主题使用`float:left`进行页面布局，而KaTeX渲染出的代码中使用了`top:...`，导致公式中的字符出现了错位。

寻求一个解决方法！谢谢！

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
已修复 https://github.com/typecho/typecho/commit/3f14d6e1381913e0cd847c77b7ab29a1ba866560
