### ISSUE TITLE
插入一个𤛭字，后面内容全没了

### ISSUE THREAD

**Issue by DavidChann** [typecho/typecho#1063]
此前出现过两次，保存全文，再打开少了大半截内容。
时间较久，已经不能够准确记得是从什么字符以后丢掉的。
一不小心，又中标了。
这次是𤛭字，写完文章最后润色的时候调皮了一下，在文章开头插了个𤛭字祝读者多牛。然后，𤛭及后面的内容全没了。
这篇万字文章是直接写的，没打草稿没备份，哭了。
挂着眼泪反馈一下。

**Comment by scvoet** [comment]
![图片](https://user-images.githubusercontent.com/45708948/107017574-469a9780-67da-11eb-9e45-6acd1f55ef66.png)
没能复现

**Comment by chengs2035** [comment]
我直接报错。。。

**Comment by benzBrake** [comment]
![图片](https://user-images.githubusercontent.com/11323774/108467101-a0618e00-72bf-11eb-9932-fd659040b060.png)
这是你数据库编码的问题，我用 utf8mb4 没有问题

**Comment by awslblog** [comment]
数据库转换成utf8_mb4编码，我是这样搞定的 https://awsl.blog/typecho/utf8_mb4
参考了https://blog.zt2qmq.top/archives/241/

**Comment by joyqi** [comment]
如上所述，使用 `utf8_mb4` 编码即可解决这个问题
