### ISSUE TITLE
什么时候更新啊？

### ISSUE THREAD

**Issue by s-Ruthless** [typecho/typecho#1067]
什么时候发布新版本啊，都三年了！

**Comment by xiaoluhong** [comment]
三年都没更新了

**Comment by fenbox** [comment]
![image](https://user-images.githubusercontent.com/360618/108827542-b5605900-7600-11eb-8837-65f4d11732d8.png)

**Comment by puzzle9** [comment]
> 三年 Typecho 沉淀，现在，回应您的等待

人家不是已经回答了呀

可是 还要更新什么呢

**Comment by sjl511** [comment]
不晓得，优化之类的吧！
