### ISSUE TITLE
1.1更新到最新开发版出现错误

### ISSUE THREAD

**Issue by Xunflash** [typecho/typecho#1069]
### 1. 该问题的重现步骤是什么？
将新版文件覆盖进老版后上传服务器进入管理面板提示更新，点击完成升级报错
SQLSTATE[HY000]: General error: 1 table typecho_comments already exists
再次点击完成升级是另外报错SQLSTATE[HY000]: General error: 1 no such table: typecho_metas
把db文件拖出来发现确实少了这个表，还多了一堆comments加乱码的表

![image](https://user-images.githubusercontent.com/71567536/108584440-79b55d00-737c-11eb-8b83-e36af008ab44.png)

我之前备份的文件是有这个表的，应该是点击完成升级按钮出现错误了
### 2. 你期待的结果是什么？实际看到的又是什么？
期待能顺利升级到开发版

![image](https://user-images.githubusercontent.com/71567536/108584392-eda33580-737b-11eb-9487-ce6bc68b81d5.png)

### 3. 问题出现的环境

- 操作系统版本：OpenWrt SNAPSHOT 09.26.2020 by GaryPang / LuCI openwrt-19.07 branch git-c1fc83b（linux）
- Apache/NGINX 版本：使用uhttpd
- 数据库版本：sqlite3 3330000-1
- PHP 版本：7.4.10-1
- Typecho 版本：1.1~最新开发版
- 浏览器版本：Google Chrome 88.0.4324.182

[//]: # (如有图片请附上截图)

**Comment by BambOvC** [comment]
同样的问题,same problem

**Comment by joyqi** [comment]
你是从哪个版本升级上来的

**Comment by Xunflash** [comment]
> 你是从哪个版本升级上来的

标题写了是从1.1也就是正式版升级上来的时候出现错误

**Comment by xlsw** [comment]
建议重装

**Comment by BambOvC** [comment]
之前解决了，方法https://blog.csdn.net/wulinncom/article/details/107775271
