### ISSUE TITLE
Typecho 1.1 不支持PHP8.0（附上报错）请问换到最新开发版能不能正常使用？

### ISSUE THREAD

**Issue by zhibisora** [typecho/typecho#1071]
### 1. 该问题的重现步骤是什么？
PHP8.0按官方步骤安装
### 2. 你期待的结果是什么？实际看到的又是什么？
期待安装成功，像PHP5.6那样

实际：
![微信截图_20210304152004](https://user-images.githubusercontent.com/73344387/109925887-43bd9480-7cfd-11eb-8bf3-5b86adeea563.png)
![微信截图_20210304153122](https://user-images.githubusercontent.com/73344387/109927146-b8dd9980-7cfe-11eb-822d-629a54d7d645.png)
![微信截图_20210304152037](https://user-images.githubusercontent.com/73344387/109925919-4d46fc80-7cfd-11eb-8bae-727f828ec557.png)

### 3. 问题出现的环境

- 操作系统版本：CentOS 7.7.1908
- Apache/NGINX 版本： nginx 1.19.7
- 数据库版本： MySQL 8.0.23
- PHP 版本： PHP 8.0
- Typecho 版本： 1.1(17.10.30)
- 浏览器版本： edge  88.0.705.74

我想知道如果换成最新开发版能不能够正常使用Typecho。。。

**Comment by scvoet** [comment]
之前有修复 PHP8.0 下错误的 PR 被合并，但可能还是有问题，你可以试试。

**Comment by zhibisora** [comment]
> 之前有修复 PHP8.0 下错误的 PR 被合并，但可能还是有问题，你可以试试。

试了一下（换到了最新的版本），暂时是没有遇到任何的问题了，安装的时候没有报错，期待后续使用。
