### ISSUE TITLE
带密码文章在filter中cid指向错误

### ISSUE THREAD

**Issue by asd-a** [typecho/typecho#1074]
### 1. 该问题的重现步骤是什么？
创建两个带密码文章
在cid较小的那个中输入正确密码
会提示密码错误，但能进入页面

经调试，发现是 /var/Widget/Abstract/Content.php 中 处理密码保护流程 中 `$value['cid']`值并非当前文章cid

**Comment by benzBrake** [comment]
和 #966 应该是一样的
