### ISSUE TITLE
更换服务器后typecho访问全部空白

### ISSUE THREAD

**Issue by tlerbao** [typecho/typecho#1075]
### 问题

今天给博客更换服务器，更换服务器后访问所有页面空白，伪静态已经设置了，也不报错。
移除index.php@include_once 'config.inc.php' 后报错 Warning: require_once(Typecho/Common.php): failed to open stream: No such file or directory。

看来是require不到Common.php，**那可能就是和deployer不兼容了。**

deployer是一个很棒的部署工具，一条命令就可以把代码部署到服务器，并且可以保存最近的几个版本，快速rollback。

deployer 的目录结构和以往的项目不太一样，目录结构如下，以下目录针对网站根目录：

current - 它是指向一个具体的版本的软链接，你的 nginx 配置中 root 应该指向它
releases - 部署的历史版本文件夹，里面可能有很多个最近部署的版本，一个文件夹一个版本
shared - 共享文件夹，作用就是存储我们项目中版本间共享的文件，比如数据库配置文件，上传目录等等，config.inc.php就在这个目录。

![image](https://user-images.githubusercontent.com/20442232/111276277-229c6280-8672-11eb-8e4d-bfa9574d1057.png)

![image](https://user-images.githubusercontent.com/20442232/111276351-3778f600-8672-11eb-9fd3-7c5e74bbe4dd.png)

config.inc.php里面的，这段代码把include path固定在了/shared目录下所以肯定找不到common.php的。
```
@set_include_path(get_include_path() . PATH_SEPARATOR .
__TYPECHO_ROOT_DIR__ . '/var' . PATH_SEPARATOR .
__TYPECHO_ROOT_DIR__ . __TYPECHO_PLUGIN_DIR__);
```

### 问题出现的环境

- 操作系统版本：centos 7.6
- NGINX 版本：1.15
- 数据库版本：5.5
- PHP 版本：7.3
- Typecho 版本：1.2
- 浏览器版本：chome

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
你可以把 `__TYPECHO_ROOT_DIR__` 改成当前的绝对路径

**Comment by tlerbao** [comment]
> 你可以把 `__TYPECHO_ROOT_DIR__` 改成当前的绝对路径

我把config.inc.php里的数据库配置部分独立出来了，这样根据config.inc.php的路径就都对了，而数据库配置host password啥的从另一个文件配置就行了哈。
