### ISSUE TITLE
获取文章最后修改的时间比实际时间提前了八小时

### ISSUE THREAD

**Issue by saucer-man** [typecho/typecho#1090]
### 1. 该问题的重现步骤是什么？

使用docker-compose搭建的typecho，宿主机和docker container时区已经修改为Shanghai ，已经在typecho后台设置时区为
```
北京时间 香港,新加坡,越南 (GMT +8)
```

但是获取文章的最后修改时间比实际情况提前了八小时，而文章发表时间是正确的。

### 2. 问题出现的环境

- 操作系统版本：debian10
- Apache/NGINX 版本：nginx:1.19.10
- 数据库版本：mysql 5.7
- PHP 版本：php:7.2.3-fpm
- Typecho 版本：1.2 (18.10.23)
- 浏览器版本：chrome google 87.0.4280.66

![image](https://user-images.githubusercontent.com/32133080/115705640-5ff5bd80-a39f-11eb-9a87-d00044e88ba2.png)

[//]: # (如有图片请附上截图)

**Comment by Urban-Ash** [comment]
PHP中有个时区设置，把那个改成中国时区即可
date.timezone = PRC

**Comment by Hsiao-Feng** [comment]
可能是主题代码的问题，试着找到主题显示修改时间的地方，并把这个时间戳 `-28800`（8小时）。

**Comment by saucer-man** [comment]
> PHP中有个时区设置，把那个改成中国时区即可
> date.timezone = PRC

按照此种方式解决了，感谢
