### ISSUE TITLE
安装失败!

### ISSUE THREAD

**Issue by Wolfxin** [typecho/typecho#1092]
### 1. 该问题的重现步骤是什么？
https://blog.csdn.net/YourMr/article/details/107617509, 我做了跟这个博客一样的步骤. 但就是有问题!!! 哀莫大于心死, 我换Halo吧.
### 2. 你期待的结果是什么？实际看到的又是什么？
安装程序捕捉到以下错误: "Table 'typecho.typecho_options' doesn't exist". 程序被终止, 请检查您的配置信息.

### 3. 问题出现的环境

- 操作系统版本：CentOS Linux release 7.9.2009 (Core)
- Apache/NGINX 版本：Apache/2.4.6 (CentOS)
- 数据库版本：mysql  Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
看起来应该是安装到一半就出错了，导致某个表没有写入

**Comment by clenji** [comment]
权限问题？
有更详细一点的信息嘛，你可以按你发的教程一样截图，我可以试着复现一下问题
