### ISSUE TITLE
疑似安裝失敗

### ISSUE THREAD

**Issue by YuukiAyano** [typecho/typecho#1096]
### 1. 该问题的重现步骤是什么？
正常安裝
裝完發現壞了
### 2. 你期待的结果是什么？实际看到的又是什么？
正常執行
實際看到的是登入後台白畫面
前台看起來跟沒套CSS一樣
### 3. 问题出现的环境

- 操作系统版本：Ubuntu 20.04.2 LTS Server
- Apache/NGINX 版本：Apache/2.4.46 nginx/1.18.0
- 数据库版本：10.5.9-MariaDB
- PHP 版本：PHP 8.0.3 fpm-fcgi Linux
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Microsoft Edge 90.0.818.56

[//]: # (如有图片请附上截图)
前台：
![front](https://user-images.githubusercontent.com/34113239/118312095-6d781080-b523-11eb-84e5-fbe27aa4137b.png)
後台：
![cp](https://user-images.githubusercontent.com/34113239/118312100-6ea93d80-b523-11eb-91b4-533e17bbff5c.png)
PHP版本：
![phpinfo](https://user-images.githubusercontent.com/34113239/118312102-6ea93d80-b523-11eb-8f92-966366213084.png)

**Comment by shiertx** [comment]
![image](https://user-images.githubusercontent.com/67832651/118388129-18d4b280-b655-11eb-8780-8e9bfa2a510d.png)
安装时网址设置是否为https？看起来像安装时设置成了http罢——降个PHP版本试试？

**Comment by YuukiAyano** [comment]
怎麼設成https

**Comment by joyqi** [comment]
应该是你安装的时候是用`http`安装，访问的时候用`https`，但数据库里记录的还是你安装时候的`http`网址，由于安全性原因，浏览器不允许`https`网页引用`http`的资源。

最简单的办法，用编辑器打开`config.inc.php`，最后面加上一行

```
define('__TYPECHO_SECURE__', true);
```

**Comment by YuukiAyano** [comment]
好的我晚點試試

**Comment by YuukiAyano** [comment]
前台正常
後台掛掉
![image](https://user-images.githubusercontent.com/34113239/118468872-c61ff700-b737-11eb-90da-14b2cadc1890.png)

**Comment by YuukiAyano** [comment]
嗯...不只後台掛掉
文章全空白@@

**Comment by joyqi** [comment]
我看到你的服务器显示了500错误，有错误日志提供么

**Comment by YuukiAyano** [comment]
![Uploading image.png…]()

**Comment by YuukiAyano** [comment]
![image](https://user-images.githubusercontent.com/34113239/118595101-0d13f800-b7dd-11eb-91b0-de4ce0351904.png)

**Comment by YuukiAyano** [comment]
APACHE
![image](https://user-images.githubusercontent.com/34113239/118596707-51ec5e80-b7de-11eb-815c-dd0de44ca553.png)
ERROR_APACHE
![image](https://user-images.githubusercontent.com/34113239/118596756-5dd82080-b7de-11eb-8c41-a2bc93c14574.png)
NGINX
![image](https://user-images.githubusercontent.com/34113239/118596785-67fa1f00-b7de-11eb-90c8-841bbb24c31c.png)

**Comment by joyqi** [comment]
请用开发版尝试，这个bug由于php 8的兼容性引起，已经在开发版里修复

**Comment by YuukiAyano** [comment]
@joyqi 從官網那邊重載嗎？

**Comment by joyqi** [comment]
http://typecho.org/download
这里下载开发版即可

**Comment by joyqi** [comment]
错误日志是啥
