### ISSUE TITLE
无法登录！

### ISSUE THREAD

**Issue by waltxxx** [typecho/typecho#1099]
### 1. 该问题的重现步骤是什么？
登录页面确定后还是会回到/admin/login.php页面
### 2. 你期待的结果是什么？实际看到的又是什么？
修复问题
### 3. 问题出现的环境

- 操作系统版本：win10
- 数据库版本：phpMyAdmin 3.5.8.2
- PHP 版本：7.3.7
- Typecho 版本：1.1-17.10.30
- 浏览器版本：Microsoft Edge
版本 90.0.818.66 (官方内部版本) (64 位)

**Comment by biuaxia** [comment]
> ### 1. 该问题的重现步骤是什么？
> 登录页面确定后还是会回到/admin/login.php页面
> 
> ### 2. 你期待的结果是什么？实际看到的又是什么？
> 修复问题
> 
> ### 3. 问题出现的环境
> * 操作系统版本：win10
> * 数据库版本：phpMyAdmin 3.5.8.2
> * PHP 版本：7.3.7
> * Typecho 版本：1.1-17.10.30
> * 浏览器版本：Microsoft Edge
>   版本 90.0.818.66 (官方内部版本) (64 位)

官方我记得只是配到了 PHP7.2 来着吧。

**Comment by dextercai** [comment]
猜测可能是和Session相关？

**Comment by soundghost** [comment]
我也是一样无法登录。
服务器是euserv，phpinfo里session的选项是enabled的。
开启了cloudflare的cdn。

**Comment by soundghost** [comment]
``> ### 1. 该问题的重现步骤是什么？
> 登录页面确定后还是会回到/admin/login.php页面
> 
> ### 2. 你期待的结果是什么？实际看到的又是什么？
> 修复问题
> 
> ### 3. 问题出现的环境
> * 操作系统版本：win10
> * 数据库版本：phpMyAdmin 3.5.8.2
> * PHP 版本：7.3.7
> * Typecho 版本：1.1-17.10.30
> * 浏览器版本：Microsoft Edge
>   版本 90.0.818.66 (官方内部版本) (64 位)

刚刚解决了。

[官方网站的常见问题](http://docs.typecho.org/faq)里有解决方案。

我尝试了将
`location ~ \.php$ {`
改为
`location ~ \.php(\/.*)*$ {`
之后就可以登陆后台了。
