### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [typecho/typecho#1100]
Hello,

We recently received a vulnerability disclosure against your repository. I couldn't find an e-mail to contact or a security process to follow, so created this issue instead.

If you would like me to e-mail over the details or put them on the GitHub Issue, I'm more than happy to facilitate this for you. Otherwise, you can access the advisory [here](https://huntr.dev/bounties/2-other-typecho/typecho).

It is private to you and the discloser of the report.

If you have any questions, let me know.

-- Jamie from huntr.dev

**Comment by joyqi** [comment]
Hi,

Please send the details to `info@joyqi.com`, and I will confirm if it's a security issue. Thanks a lot.

**Comment by JamieSlome** [comment]
Awesome will get that sorted for you now!

**Comment by JamieSlome** [comment]
Just sent an e-mail over to you!

**Comment by joyqi** [comment]
Got it, thanks!

**Comment by joyqi** [comment]
I'll fix it ASAP

**Comment by l2dy** [comment]
HTML purification must be done on the server-side to be safe. Bad actors can still craft malicious HTTP requests with XSS payload.
