### ISSUE TITLE
更新到最新的开发板后台多了一个菜单的按钮

### ISSUE THREAD

**Issue by wtxly521** [typecho/typecho#1103]
### 1. 该问题的重现步骤是什么？
覆盖更新后就出现了，而且 每个选项下面多一个无用的返回按钮 
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.18
- 数据库版本：mysql8
- PHP 版本：7.3
- Typecho 版本：1.2 (18.10.23)
- 浏览器版本：chrome 89.0.4389.114 以及 edeg 91.0.864.37 

![image](https://user-images.githubusercontent.com/45901696/120647659-6e122000-c4ad-11eb-87c0-7e695b30e8db.png)
![image](https://user-images.githubusercontent.com/45901696/120647893-ac0f4400-c4ad-11eb-9b86-a4dabb283e16.png)

**Comment by joyqi** [comment]
清除浏览器缓存再刷新

**Comment by wtxly521** [comment]
我尝试下。

**Comment by wtxly521** [comment]
依然有。  新装 火狐浏览器也存在这个问题

**Comment by nmgliangwei** [comment]
@wtxly521 你是不直接拿的master的代码，覆盖的，我前几天也是直接用master覆盖出现了这个菜单,从http://typecho.org/download这里下载开发版就可以了。

**Comment by wtxly521** [comment]
> @wtxly521 你是不直接拿的master的代码，覆盖的，我前几天也是直接用master覆盖出现了这个菜单,从http://typecho.org/download 这里下载开发版就可以了。

确实  你用开发板有遇到出现  404页面报 502错误么

**Comment by nmgliangwei** [comment]
> > @wtxly521 你是不直接拿的master的代码，覆盖的，我前几天也是直接用master覆盖出现了这个菜单,从http://typecho.org/download 这里下载开发版就可以了。
> 
> 确实  你用开发板有遇到出现  404页面报 502错误么

没出现过，应该是你的404页面的php代码有问题吧，你把php的日志打开，然后排查一下就可以了。一般都可以找到问题

**Comment by wtxly521** [comment]
> 面的php代码有问题吧，你把php的日志打开，然后排查一下就可以了。一般都可以找到问题

我尝试用过官方模板的 404页面 也一样不行 应该是其他地方出错的

**Comment by wtxly521** [comment]
> > > @wtxly521 你是不直接拿的master的代码，覆盖的，我前几天也是直接用master覆盖出现了这个菜单,从http://typecho.org/download 这里下载开发版就可以了。
> > 
> > 
> > 确实  你用开发板有遇到出现  404页面报 502错误么
> 
> 没出现过，应该是你的404页面的php代码有问题吧，你把php的日志打开，然后排查一下就可以了。一般都可以找到问题

 找到问题了。。 一个反代服务器出问题了
