### ISSUE TITLE
How to get in touch about a security issue?

### ISSUE THREAD

**Issue by zidingz** [typecho/typecho#1105]
Hey there,

As there isn't a SECURITY.md or contact address in your repository, I am not sure how to contact you regarding a potential security issue.

Would you kindly provide an email so I can send you the details? Else, simply add a SECURITY.md file with an e-mail to your repository. GitHub recommends this as the best way to ensure security issues are responsibly disclosed.

Look forward to hearing from you, thanks!

**Comment by perrsig** [comment]
You can find feedback emails for security issues that the owner has replied to under other issues.

https://github.com/typecho/typecho/issues/1100#issuecomment-852320281

**Comment by fenbox** [comment]
SECURITY.md file updated https://github.com/typecho/typecho#security-ov-file
