### ISSUE TITLE
我没问题，我是代表广大typecho家人们来催更了！~

### ISSUE THREAD

**Issue by ChiehJang** [typecho/typecho#1106]
![27729CA3F81679F5C5A42E2489F7C3D3](https://user-images.githubusercontent.com/11803185/123199795-1ed67280-d4e2-11eb-8cc9-81bcf2e3953d.jpg)
**快四年了**，正式版快点更新啊，期待typecho大军崛起，碾压WP，耀我中华！

**Comment by clenji** [comment]
前阵子开会遇到joyqi大佬，大佬讲近期会有小版本更新

**Comment by opswill** [comment]
不用催，开发版一直维护就行了，发不发版没有关系

**Comment by flypigxyz** [comment]
> 前阵子开会遇到joyqi大佬，大佬讲近期会有小版本更新

但愿能把我的slug编号需求加进去。
