### ISSUE TITLE
Deprecated: Function get_magic_quotes_gpc() 

### ISSUE THREAD

**Issue by duimxc** [typecho/typecho#1107]
Deprecated: Function get_magic_quotes_gpc() is deprecated in /www/wwwroot/www.duimxc.club/var/Typecho/Common.php on line 208
### 1. 该问题的重现步骤是什么？
PHP7.4
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
你该升级typecho版本了，用开发版吧

**Comment by RalstonLiu** [comment]
提示不推荐使用get_magic_quotes_gpc函数，禁用即可，宝塔面板中在php设置——禁用函数，添加get_magic_quotes_gpc，然后重启php

**Comment by DeanShiDirect** [comment]
暂时解决安装过程中出现的这个问题 Deprecated: Function get_magic_quotes_gpc()

题主，后续还出现了问题吗
