### ISSUE TITLE
如何修改系统默认的起始slug编号？

### ISSUE THREAD

**Issue by flypigxyz** [typecho/typecho#1112]
事情是这样的，我在发布文章的过程中其间删除过几篇文章，导致了slug号不连续，后来又手动强制在数据库里将全部slug号改成连续的了，但是问题来了，当我再发布新文章时，系统默认给的起始slug号，是按照原来没有删除文章时顺序编的号，（作为强迫症的我）每次还要手动修改，非常麻烦。

比如原来发布了1、2、3、4、5篇，后来把其中的第2篇删除了，变成了1、3、4、5，我又手动强制把slug编号改成了1、2、3、4，共4篇文章，这样当发布第5篇文章的时候，系统自动给的slug编号是6，而不是5，因为系统认为我已经发布过5篇文章了。我想问的是怎么把系统默认给的编号改成5。不知道我说明白没有，请大佬们指教。

**Comment by nmgliangwei** [comment]
应该是数据库自增id导致的，你改一下数据库自增id那个值就可以了。

**Comment by flypigxyz** [comment]
> 应该是数据库自增id导致的，你改一下数据库自增id那个值就可以了。

感谢！我也考虑是自增cid的问题，但是这里面有独立页面掺和着，独立页面也占cid，没法调整。如果先给独立页面从最低号（比如1号）开始赋与cid号，那最后一篇文章的cid号=文章数+独立文章数，大于实际文章数，再发布新文章系统默认编号必须是大于实际文章数的。我是技术小白，不懂怎么弄。

**Comment by nmgliangwei** [comment]
> > 应该是数据库自增id导致的，你改一下数据库自增id那个值就可以了。
> 
> 感谢！我也考虑是自增cid的问题，但是这里面有独立页面掺和着，独立页面也占cid，没法调整。如果先给独立页面从最低号（比如1号）开始赋与cid号，那最后一篇文章的cid号=文章数+独立文章数，大于实际文章数，再发布新文章系统默认编号必须是大于实际文章数的。我是技术小白，不懂怎么弄。

首先
1.没必要改那个id就让系统自动增加即可，不影响你前端页面的显示.
2.如果直接从库里改，还需要改关系表，我记得有几个关系表，存了文章和分类，标签的关系，还有评论等，你只改文章表里的id会有问题的
3.如果你的前端文章展示用的是cid，你改的话还会影响搜索引擎的收录。
结论:不要修改id这类东西，除非你对这个系统很熟悉，以及第3点对你没影响

**Comment by flypigxyz** [comment]
> > > 应该是数据库自增id导致的，你改一下数据库自增id那个值就可以了。
> > 
> > 
> > 感谢！我也考虑是自增cid的问题，但是这里面有独立页面掺和着，独立页面也占cid，没法调整。如果先给独立页面从最低号（比如1号）开始赋与cid号，那最后一篇文章的cid号=文章数+独立文章数，大于实际文章数，再发布新文章系统默认编号必须是大于实际文章数的。我是技术小白，不懂怎么弄。
> 
> 首先
> 1.没必要改那个id就让系统自动增加即可，不影响你前端页面的显示.
> 2.如果直接从库里改，还需要改关系表，我记得有几个关系表，存了文章和分类，标签的关系，还有评论等，你只改文章表里的id会有问题的
> 3.如果你的前端文章展示用的是cid，你改的话还会影响搜索引擎的收录。
> 结论:不要修改id这类东西，除非你对这个系统很熟悉，以及第3点对你没影响

1.我不是想改cid，我是改的slug，主要是强迫症患者看到站点地图中的文件名和实际文章数不符，而且是跳跃的，很别扭。
2.我是直接从库里改的slug，设定的前端显示也是显示slug号
3.主要是自动增加的cid号和slug号不对应，和文章篇数也不对应，看着难受。

**Comment by nmgliangwei** [comment]
嗯，目前系统就是这个样子，文章和页面在一个表里，都会用cid这个自增id，如果你slug自己编了号想和文章的cid对上按照你要的那个顺序对上，目前估计不太行，除非你把程序改一下把文章和page分开表存储。这样都会有自己的id。或者让作者改一下设计，我估计不太会，主要没必要，哈哈。

**Comment by flypigxyz** [comment]
> 嗯，目前系统就是这个样子，文章和页面在一个表里，都会用cid这个自增id，如果你slug自己编了号想和文章的cid对上按照你要的那个顺序对上，目前估计不太行，除非你把程序改一下把文章和page分开表存储。这样都会有自己的id。或者让作者改一下设计，我估计不太会，主要没必要，哈哈。

感谢！我主要是严重强迫症患者，哈哈！！

**Comment by LemoFire** [comment]
> > 嗯，目前系统就是这个样子，文章和页面在一个表里，都会用cid这个自增id，如果你slug自己编了号想和文章的cid对上按照你要的那个顺序对上，目前估计不太行，除非你把程序改一下把文章和page分开表存储。这样都会有自己的id。或者让作者改一下设计，我估计不太会，主要没必要，哈哈。
> 
> 感谢！我主要是严重强迫症患者，哈哈！！

一样强迫症...久了就好了 几年后就会发现其实自己啥都没做...( /dog
