### ISSUE TITLE
官网访问不了了哦

### ISSUE THREAD

**Issue by Skywt2003** [typecho/typecho#1114]
typecho.org  docs.typecho.org  forum.typecho.org
都访问不了了
话说都 1202 年了还没有 https 合适吗

**Comment by kecrily** [comment]
cc @joyqi 

---

不过这个应该更适合发在 discussions 中

**Comment by jiyeme** [comment]
似乎被墙了~科学之后就打开了

**Comment by kecrily** [comment]
> 
> 
> 似乎被墙了~科学之后就打开了

我之前看的时候是一片空白，可惜没 archive

**Comment by Skywt2003** [comment]
貌似是的……开代理就可以 https 了
