### ISSUE TITLE
网站URL中的index.php无法去除

### ISSUE THREAD

**Issue by yj920** [typecho/typecho#1121]
版本 1.1 (17.10.30)
使用宝塔面板，配置了伪静态和配置文件，按网上的教程试过了，链接还是 `{{doname}}/index.php/archives/{cid}/` 这样的

**Comment by SHIERTX** [comment]
修改永久链接了吗

**Comment by mhcyong** [comment]
> 版本 1.1 (17.10.30)
> 使用宝塔面板，配置了伪静态和配置文件，按网上的教程试过了，链接还是 `{{doname}}/index.php/archives/{cid}/` 这样的

看看这里：https://pangsuan.com/p/typecho_rewrite_url.html

**Comment by joyqi** [comment]
rewrite配好了就直接去"后台->设置->永久链接"里开启，忽略警告提示
