### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by yaki99x** [typecho/typecho#1130]
exception 'Typecho_Db_Query_Exception' with message 'SQLSTATE[HY000]: General error: 1 no such function: now' in /home/allyouxy/public_html/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /home/allyouxy/public_html/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo-&gt;query('SELECT *  FROM ...', Object(PDO), 1, 'SELECT')
#1 /home/allyouxy/public_html/var/Typecho/Db.php(384): Typecho_Db-&gt;query(Object(Typecho_Db_Query), 1)
#2 /home/allyouxy/public_html/usr/themes/spimes/functions.php(1139): Typecho_Db-&gt;fetchAll(Object(Typecho_Db_Query))
#3 /home/allyouxy/public_html/usr/themes/spimes/sidebar.php(129): getHotPosts('5')
#4 /home/allyouxy/public_html/var/Widget/Archive.php(1937): require('/home/allyouxy/...')
#5 /home/allyouxy/public_html/usr/themes/spimes/index.php(63): Widget_Archive-&gt;need('sidebar.php')
#6 /home/allyouxy/public_html/var/Widget/Archive.php(2022): require_once('/home/allyouxy/...')
#7 /home/allyouxy/public_html/var/Typecho/Router.php(138): Widget_Archive-&gt;render()
#8 /home/allyouxy/public_html/index.php(23): Typecho_Router::dispatch()

**Comment by joyqi** [comment]
这是这个主题的问题
