### ISSUE TITLE
为啥数据库地址填写localhost的时候，数据库端口可以随便填

### ISSUE THREAD

**Issue by TaiChi01** [typecho/typecho#1133]
### 1. 该问题的重现步骤是什么？
删除config.inc.php里的  'port' => '3307',或者随便填写
### 2. 你期待的结果是什么？实际看到的又是什么？
数据库应该无法连接，但实际都没问题，不影响正常数据库连接
### 3. 问题出现的环境

- 操作系统版本：centos8.2
- Apache/NGINX 版本：1.21.0
- 数据库版本：5.6.50
- PHP 版本：5.6
- Typecho 版本：1.1

[//]: # (如有图片请附上截图)
  
![image](https://user-images.githubusercontent.com/28525186/130042055-ad870755-4649-4b5e-b8ab-0b6e6b699c74.png)

**Comment by joyqi** [comment]
3306是默认端口，不指定任何端口的时候的时候会默认使用3306。

**Comment by joyqi** [comment]
localhost默认是本地通过mysql socket连接的，你改成127.0.0.1才会通过网络
