### ISSUE TITLE
切换主题时原主题配置会丢失

### ISSUE THREAD

**Issue by yikesoftware** [typecho/typecho#1141]
### 1. 该问题的重现步骤是什么？

使用主题A时进行一定的配置，然后切换到主题B；再切换回A时配置就丢失了（在我安装的所有主题中均存在此情况）

### 2. 你期待的结果是什么？实际看到的又是什么？

最好是能够在切换主题时保留主题配置（虽然我不清楚这是typecho负责的还是主题模板自己实现的）

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 20.04 （使用宝塔面板）
- Apache/NGINX 版本：Nginx 1.19.8
- 数据库版本：MySQL 5.6.50
- PHP 版本：PHP 7.4
- Typecho 版本：1.2.0
- 浏览器版本：Edge/Chrome 最新版

[//]: # (如有图片请附上截图)

**Comment by kecrily** [comment]
这是一个特性，而不是 bug。但有些主题提供了切换主题仍能保存原主题配置的方法。

**Comment by yikesoftware** [comment]
> 这是一个特性，而不是 bug。但有些主题提供了切换主题仍能保存原主题配置的方法。

感谢，
所以说储存方式是模板开发者自定义的对吧。如果有啥通用方式的话我倒是想手动去备份一下

**Comment by yikesoftware** [comment]
> 这是一个特性，而不是 bug。但有些主题提供了切换主题仍能保存原主题配置的方法。

啊我知道了，被反序列化存在数据库里面了，感觉是个可以改进的点

**Comment by cuixiping** [comment]
typecho 1.2.1 这样改可以保留主题配置:
`var\Widget\Themes\Edit.php` 文件的 `public function changeTheme` 函数内:

1) 注释掉 `$this->delete` 这行, 让它不删除旧主题的配置:

```
// $this->delete($this->db->sql()->where('name = ?', 'theme:' . $oldTheme));
```

2) 插入新主题的配置前, 先检查是否已经存在:
`$this->insert` 这行外面套一层 if 判断

```
if (!$this->options->__get('theme:' . $theme)) {  // 新加的
    $this->insert([
        'name'  => 'theme:' . $theme,
        'value' => serialize($options),
        'user'  => 0
    ]);
}  // 新加的
```
