### ISSUE TITLE
关于插件升级的需求

### ISSUE THREAD

**Issue by kraity** [typecho/typecho#1142]
joyqi大佬, 您好, 看见Typecho有新版本计划, 我们大家都欣喜若狂, 相信新版本给我们带来很多惊喜。这里我有个功能建议说给大佬听听, 那么就是关于 插件升级计划

一般的插件的 `deactivate` 方法都为空, 所以在没有禁用插件情况下直接删除插件文件都不会造成博客异常, 但是有些插件在 `activate` 方法里(创建表、添加路由、钩子之类) 它的 `deactivate` 方法也有相应的回收代码。

这里大多用户一般都是直接删除插件文件或者覆盖为新版本的插件, 以此完成插件升级, 从而会造成博客异常。因为很多用户不明白为什么需要先禁用, 所以都是粗鲁的直接删除文件再覆盖新版本的插件。

这是我们插件开发者一直困扰的地方, 特此希望joyqi大佬能够加入 插件升级 的开发计划。

**Comment by kecrily** [comment]
在 activate 中可以对插件自行增加的表结构进行判断，如果不同就更新。其实开发者自己就可以做些处理，当然 Typecho 直接内嵌的话体验会更好些。

**Comment by joyqi** [comment]
系统最多只能在出现加载异常的时候拦截一下，但是实现完全的删除即卸载不太现实。因为除了一些标准动作外，很多插件在安装的时候还会有很多特殊动作，比如创建数据表，移动文件等等。
