### ISSUE TITLE
1、在撰写文章的时候插入阿里云盘分享链接  这个🚀之后的内容都会消失。

### ISSUE THREAD

**Issue by ShuaiKb** [typecho/typecho#1146]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by ShuaiKb** [comment]
1.在撰写文章的时候插入阿里云盘的分享口令。

2.正常在你的文章写完发布之后,会全部显示。
实际你的文章在这个🚀图标之后的就会全部消失

3、centos7   nginx1.20.1  php7.4  mysql5.5.62  typecho1.1-17.10.30-release  谷歌浏览器92.0.4515.159

**Comment by SHIERTX** [comment]
这个明显是数据库格式问题，建议修改为UTF8mb4后重试:)

**Comment by ShuaiKb** [comment]
好的,明白了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "typecho/typecho"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月2日(星期四) 晚上11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [typecho/typecho] 1、在撰写文章的时候插入阿里云盘分享链接  这个🚀之后的内容都会消失。 (#1146)





 这个明显是数据库格式问题，建议修改为UTF8mb4后重试:)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShuaiKb** [comment]
我已经将mysql的字符编码改为了utf8mb4但是还是无法存储图标   而且我又发现了一个问题，joe编辑器里的 ”回复可见“ 功能我用不了
![](https://gitee.com/Shuaikb/blog-picture/raw/master/image/202109132137604.png)

这里是我在编辑器里写的   
![](https://gitee.com/Shuaikb/blog-picture/raw/master/image/202109132138009.png)

实际的效果
![](https://gitee.com/Shuaikb/blog-picture/raw/master/image/202109132138990.png)

**Comment by ShuaiKb** [comment]
@SHIERTX

**Comment by SHIERTX** [comment]
这个我在我的Joe中测试是可以的；
修改数据库格式后还需要修改站点根目录 ./config.inc.php 大概34行charset为utf8mb4；
建议检查下配置哦

**Comment by ShuaiKb** [comment]
感谢，问题已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "typecho/typecho"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 凌晨1:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [typecho/typecho] 1、在撰写文章的时候插入阿里云盘分享链接  这个🚀之后的内容都会消失。 (#1146)





 
这个我在我的Joe中测试是可以的；
 修改数据库格式后还需要修改站点根目录 ./config.inc.php 大概34行charset为utf8mb4；
 建议检查下配置哦
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
