### ISSUE TITLE
更新到Typecho1.2后插件无法使用

### ISSUE THREAD

**Issue by 79-blog** [typecho/typecho#1147]
更新到Typecho1.2后插件无法使用

**Comment by SHIERTX** [comment]
建议补充详细信息:)

**Comment by 79-blog** [comment]
> 建议补充详细信息:)

基本所有插件都启用报错

**Comment by jssycszyj** [comment]
可能因为`__TYPECHO_ADMIN_DIR__`、`pluginPath`和`adminUrl`现在改为没有`/`结尾了
