### ISSUE TITLE
数据表建立失败，插件启用失败，错误信息：SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes。

### ISSUE THREAD

**Issue by Yaklo** [typecho/typecho#1148]
### 1. 该问题的重现步骤是什么？
启用该插件 Access  获取访客信息，生成统计图表，由@一名宅 部分优化重构。 版本 2.0.2
https://github.com/kokororin/typecho-plugin-Access
### 2. 你期待的结果是什么？实际看到的又是什么？
了解导致问题发生的核心
### 3. 问题出现的环境
- 操作系统版本：
- NGINX 版本：1.18.0
- 数据库版本：5.6.44
- PHP 版本：7.3.0
- Typecho 版本：f40c5c178e068a993538f560a71838a809ed1a32

**Comment by opswill** [comment]
这个应该是数据库的问题，试试下面
1. 升级到mysql 5.7 
2. 数据库的字符集改成utf8mb4

**Comment by Yaklo** [comment]
用的轻量应用服务器太拉了装不了5.7，没法测试了不好意思
