### ISSUE TITLE
1.2版本所有删除按钮无法使用

### ISSUE THREAD

**Issue by yoogg** [typecho/typecho#1149]
### 1. 管理页面的删除点击没有反应，包括不限于删除文章、删除附件、删除评论等，其他功能正常
![image](https://user-images.githubusercontent.com/46551698/132092021-d309eb14-16d7-420e-a9c7-cebb895a87b8.png)

### 2. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：mysql8.0
- PHP 版本：7.4/8.0
- Typecho 版本：1.2
- 浏览器版本：Microsoft Edge 92.0.902.84

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
已修复
