### ISSUE TITLE
RSS报错

### ISSUE THREAD

**Issue by jssycszyj** [typecho/typecho#1150]
### 1. 该问题的重现步骤是什么？
Argument 1 passed to Typecho_Feed::setSubTitle() must be of the type string, null given, called in /home/wwwroot/XXXXX/var/Widget/Archive.php on line 1441
### 3. 问题出现的环境

- 操作系统版本：Ubuntu20.04
- Apache/NGINX 版本：1.20.1
- 数据库版本：mariadb10.3
- PHP 版本：7.4
- Typecho 版本：latest
- 浏览器版本：chrome

[//]: # (如有图片请附上截图)

**Comment by jssycszyj** [comment]
同时这个插件也无法使用
[https://github.com/jzwalk/TeStore](https://github.com/jzwalk/TeStore)
问题出在`/var/Typecho/Router.php`，master分支8月18日之前的版本没有问题

**Comment by jssycszyj** [comment]
`pluginPath`和`adminUrl`现在改为没有`/`结尾了

**Comment by joyqi** [comment]
参数的问题我修复了，路径问题确实是考虑这么修改，一般标准的路径后面都没有`/`结尾

**Comment by joyqi** [comment]
已修复
