### ISSUE TITLE
默认主题白屏

### ISSUE THREAD

**Issue by benzBrake** [typecho/typecho#1156]
### 1. 该问题的重现步骤是什么？
禁用所有插件，更换回默认主题，访问网站
### 2. 你期待的结果是什么？实际看到的又是什么？
访问网站白屏，查看日志。
```
[08-Sep-2021 22:52:21 Asia/Shanghai] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 13343568 bytes) in Unknown on line 0
```
非默认主题都可以看见网页内容
### 3. 问题出现的环境
Typecho 1.2 master branch，已经 fetch，我是从 commit 93b5656109ab13b4c985df76bf3f0f40f294c480 升级上来的
- 操作系统版本：Windows
- Apache/NGINX 版本： 2.4.39
- 数据库版本：8.0.12
- PHP 版本：7.4.3
- Typecho 版本：1.2 beta 1
- 浏览器版本：Firefox 91

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
你的默认主题是老版还是新版

**Comment by benzBrake** [comment]
最细版，master 里最新版版本的所有文件我都替换到 Typecho 的安装目录里了

**Comment by coolarec** [comment]
+1
