### ISSUE TITLE
更新到最新的 Dev 版本后原加密文章无法正常加密

### ISSUE THREAD

**Issue by Vndroid** [typecho/typecho#1157]
### 1. 该问题的重现步骤是什么？

更新到 [最新版](https://github.com/typecho/typecho/commit/519e84e74ca55ef12f4274256050ed6d1ebbc1a3)

### 2. 你期待的结果是什么？实际看到的又是什么？

加密文章可以正常隐藏输入框，实际情况是文章变成非隐藏标题，可以正常点击进入，进入后刷新页面提示报错 

```
Argument 1 passed to Widget\Security::getToken() must be of the type string, null given, called in /var/www/dynamic/usr/themes/pinghsu/comments.php on line 86
```

主题使用的是 [Pinghsu](https://github.com/chakhsu/pinghsu/blob/master/comments.php)

### 3. 问题出现的环境

- 操作系统版本：Debian 11
- Apache/NGINX 版本：1.20.1
- 数据库版本：MariaDB 10.5
- PHP 版本：7.4
- Typecho 版本：[#519e84e](https://github.com/typecho/typecho/commit/519e84e74ca55ef12f4274256050ed6d1ebbc1a3)
- 浏览器版本：Chrome 93

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
这个错误提示已经修复了，而无法加密可能是因为你登录了管理员账号

**Comment by Vndroid** [comment]
加密正常显示确实是用户的问题，但匿名用户访问时会跳转到错误页面，提示信息

```
Call to undefined method Typecho\Widget\Request::getUrlPrefix()
```

而非输入密码的界面。

**Comment by joyqi** [comment]
这应该不是默认主题吧

**Comment by Vndroid** [comment]
> 这应该不是默认主题吧

不是，使用的是上述主题。

**Comment by joyqi** [comment]
我把这个方法暴露出来了，更新下再试试

**Comment by Vndroid** [comment]
已恢复正常。
