### ISSUE TITLE
typecho默认主题 katex公式排版错乱问题修复

### ISSUE THREAD

**Issue by AlexVagrant** [typecho/typecho#1161]
### 1. 该问题的重现步骤是什么？
默认主题下，创建新文章输入
```
$$
R=
\begin{bmatrix}
x_{11} & x_{12} & x_{13} \\\\
x_{21} & x_{22} & x_{23} \\\\
x_{31} & x_{32} & x_{33}
\end{bmatrix}
$$
```
### 2. 你期待的结果是什么？实际看到的又是什么？
实际看到的
![image](https://user-images.githubusercontent.com/25078327/132654441-3da92308-ee5c-4a36-ac09-953946a2dbca.png)
期待看到的
![image](https://user-images.githubusercontent.com/25078327/132654642-551ea769-5aac-408a-a72b-e059a49ee7fb.png)

### 3. 修复步骤
修改 /usr/themes/default/grid.css 中 `.row [class*="col-"]`为 `.row > [class*="col-"]`

**Comment by joyqi** [comment]
已修复 https://github.com/typecho/typecho/commit/3f14d6e1381913e0cd847c77b7ab29a1ba866560
