### ISSUE TITLE
插件接收post数据报错

### ISSUE THREAD

**Issue by Moidea** [typecho/typecho#1169]
报错内容如下：

`Typecho\Widget::__construct(): Argument #1 ($request) must be of type Typecho\Widget\Request, Typecho\Request given`

插件内原代码：

`$publish = @new Publish(Typecho_Request::getInstance(),Typecho_Response::getInstance());`

**Comment by joyqi** [comment]
不要用new去创建一个widget直接用`Publish::alloc()`
