### ISSUE TITLE
master最新版创建分类如果没有文章的话，访问分类会出500错误

### ISSUE THREAD

**Issue by ilifelog** [typecho/typecho#1170]
### 1. 该问题的重现步骤是什么？
master最新版创建分类如果没有文章的话，访问分类会出500错误
### 2. 你期待的结果是什么？实际看到的又是什么？
友好的提示，看到的是具体的路径错误
### 3. 问题出现的环境

- 操作系统版本：Ubuntu lts 20.04
- Apache/NGINX 版本：nginx 1.20
- 数据库版本：MySQL 5.7
- PHP 版本：7.4
- Typecho 版本：typecho 20210910合并的开发版本
- 浏览器版本：chrome 93

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/39217177/132967802-0505a688-359e-4c95-929f-86974bbb91c3.png)

**Comment by joyqi** [comment]
这不是默认主题吧

**Comment by ilifelog** [comment]
> 这不是默认主题吧

是默认主题，我改了改。

**Comment by ilifelog** [comment]
打扰了，我改的出问题了。
