### ISSUE TITLE
更新typecho后Typecho\Db\Query::order()报错

### ISSUE THREAD

**Issue by zclab** [typecho/typecho#1174]
### 1. 该问题的重现步骤是什么？
不是默认主题，设置文章置顶时出错，错误处是$select1->order(null,"(case cid$order end)");  

Argument 1 passed to Typecho\Db\Query::order() must be of the type string, null given

### 2. 你期待的结果是什么？实际看到的又是什么？

Argument 1 passed to Typecho\Db\Query::order() must be of the type string, null given

### 3. 问题出现的环境

- 操作系统版本：ubuntu 20.04
- Apache/NGINX 版本：
- 数据库版本：mariadb
- PHP 版本：7.2.3
- Typecho 版本：最新
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
这不是一个标准写法，我不太建议主题的作者这么写

**Comment by zclab** [comment]
好的，明白了
