### ISSUE TITLE
目前如何设置插件的 dependence 

### ISSUE THREAD

**Issue by RainshawGao** [typecho/typecho#1175]
### 1. 该问题的重现步骤是什么？
之前使用的  `@dependence 17.12.8-* ` 现在失效了，应该改成什么？
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
现在用 `@since 1.2.0`
