### ISSUE TITLE
最新开发版缺少user/uploads文件夹，导致安装报错

### ISSUE THREAD

**Issue by lhuang001** [typecho/typecho#1178]
### 1. 该问题的重现步骤是什么？
1.下载最新开发版本，并解压
2.网页打开安装界面，点击“开始下一步”
3.页面提示“上传目录无法写入”
### 2. 你期待的结果是什么？实际看到的又是什么？
期待：进入下一步安装界面
实际：上传目录无法写入
### 3. 问题出现的环境

- 操作系统版本：centos7
- Apache/NGINX 版本：docker caddy：2.4.5-alpine
- 数据库版本：mysql 5.7
- PHP 版本：php 7.2
- Typecho 版本：5d20d57be93560cdcd4833be5794bc7be7f69401
- 浏览器版本：chrome 93.0.4577.63
![安装报错](https://user-images.githubusercontent.com/21240907/133246473-3b869390-480c-4445-8f40-f39dbe8646b0.png)
![正式版与开发板对比](https://user-images.githubusercontent.com/21240907/133246478-95ae4b15-9dd6-4007-b831-055a06cafe72.png)

[//]: # (如有图片请附上截图)

**Comment by lhuang001** [comment]
建议解决方案：
方案一：开发版下载包包含该文件夹
方案二：install脚本中创建该文件夹

**Comment by joyqi** [comment]
实际上之前的代码包含了uploads目录，但是由于github actions的artifact无法保存空目录，所以被它自动忽略了。我们已经用新的方法打包了目录，并替换了链接。

**Comment by lhuang001** [comment]
新打包的版本已经包含uploads文件夹，感谢您的工作。
但uploads文件夹权限被错误设为777，这可能会导致安全风险，请尽快修复。
