### ISSUE TITLE
网站后台标题显示异常

### ISSUE THREAD

**Issue by Vndroid** [typecho/typecho#1182]
### 1. 该问题的重现步骤是什么？

更新到 最新 Dev 版

### 2. 你期待的结果是什么？实际看到的又是什么？

访问 https://www.domain.com/admin 时，页面显示正常，但 Chrome 标题页上显示 【 - XXXX  - Powered by Typecho】，手动点击【控制台 - 摘要】 才能重定向到 index.php ，显示正确的信息【网站摘要 - XXXX  - Powered by Typecho】。

记忆中几个版本前是正常的。

### 3. 问题出现的环境

- 操作系统版本：Debian 11
- Apache/NGINX 版本：1.20.1
- 数据库版本：MariaDB 10.5
- PHP 版本：7.4
- Typecho 版本：[#fc9aaf6](https://github.com/typecho/typecho/commit/fc9aaf66f3fcaae69f075cf5dc1fae9482af6e03)
- 浏览器版本：Chrome 93

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
无法复现，目录跳转应该是web服务器控制的，跟php没啥关系，访问admin时会自动跳转到带斜杠的地址。出现这种错误一般是rewrite规则写的有问题。

**Comment by Vndroid** [comment]
> 无法复现，目录跳转应该是web服务器控制的，跟php没啥关系，访问admin时会自动跳转到带斜杠的地址。出现这种错误一般是rewrite规则写的有问题。

Chrome 标签的显示应该是和后端相关的吧，用的就是官方的重写规则。

```
    location / {
        index index.html index.php;
        if (-f $request_filename/index.html) {
            rewrite (.*) $1/index.html break;
        }
        if (-f $request_filename/index.php) {
            rewrite (.*) $1/index.php;
        }
        if (!-f $request_filename) {
            rewrite (.*) /index.php;
        }
    }
```

**Comment by joyqi** [comment]
官方规则在这里 http://docs.typecho.org/faq

**Comment by Vndroid** [comment]
因为如果将私有的静态文件放置在 typecho ，git 更新时会有新文件提示，所以将私有静态资源拆分到了别的文件夹，在使用上述官方规则的话，首页访问正常，访问页面会报错 404。

还有一个问题，是否有官方规则可以将管理后台的链接也实现伪静态呢？

**Comment by joyqi** [comment]
后台不会做伪静态，后台必须保证在任何情况下的最大可访问性。

至于前面的问题应该是你的配置问题，我已将此问题移至讨论区讨论。
