### ISSUE TITLE
创建子分类后,访问报错

### ISSUE THREAD

**Issue by linyicode** [typecho/typecho#1190]
在刚刚的无法创建子分类被修复后,尝试访问子分类时报错

报错信息 

Argument 1 passed to Typecho\Widget::allocWithAlias() must be of the type string, null given, called in /data/mystack/sites/www.aqk4.cn/www/var/Widget/Base/Contents.php on line 820

**Comment by joyqi** [comment]
这应该不是默认皮肤吧
