### ISSUE TITLE
“下次自动登录”不像期待中的那样

### ISSUE THREAD

**Issue by Charolf** [typecho/typecho#1201]
### 1. 该问题的重现步骤是什么？
登录，然后登出，再立即尝试登录。

### 2. 你期待的结果是什么？实际看到的又是什么？
期待的结果是能自动登录（期待“下次自动登录”自动打勾，但是没有）。

### 3. 问题出现的环境

- 操作系统版本：客户端Win 10，服务器端Debian 10 (Linux version 5.10.0-0.bpo.8-cloud-amd64)
- Apache/NGINX 版本：Nginx 1.20.1
- 数据库版本：Sqlite 2.8.17
- PHP 版本：8.0
- Typecho 版本：1.2.0-rc.1
- 浏览器版本：Microsoft Edge 94.0.992.50，Google Chrome 94.0.4606.81.

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
你的意思是，这个勾选项没有自动打勾？
