### ISSUE TITLE
1.2RC版本中於usr資料夾中建立langs並放入語言文件後出現錯誤

### ISSUE THREAD

**Issue by lee89tw14** [typecho/typecho#1203]
### 1. 该问题的重现步骤是什么？
上傳語言文件mo後進入後台即報錯
(只上傳了zh_tw.mo及ja_jp.mo)
### 2. 你期待的结果是什么？实际看到的又是什么？
實際看到的：Return value of Typecho\I18n\GetText::ngettext() must be of the type string, null returned
期待看到的：正常的後台環境
### 3. 问题出现的环境
- 操作系统版本：Ubuntu 20.4 LTS
- Apache/NGINX 版本：Apache2
- 数据库版本：mariadb(版本不確定)
- PHP 版本：7.4
- Typecho 版本：1.2 RC
- 浏览器版本：Microsoft edge 版本 94.0.992.50 

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/22855239/138259725-76d08eff-fd32-492a-9977-c5218935e855.png)

**Comment by joyqi** [comment]
看起来应该是日语的部分语言档翻译缺失导致，不过这个报错确实是个bug

**Comment by lee89tw14** [comment]
剛才測試了一下，如果只留zh_tw的話正常，所以有問題的確定是ja_jp的檔案，不過關於時間的部分我應該是沒有動過的，而且在poedit中他被歸類為單複數合併譯文，我直接用複數的寫法也是會出錯
