### ISSUE TITLE
管理文章无法编辑

### ISSUE THREAD

**Issue by QYKing233** [typecho/typecho#1222]
X86 docker搭建typecho网站，撰写的文章和独立页面，当在管理文章中编辑时会直接新建一个，无法对已有的文章进行编辑。

- Typecho 版本：joyqi/typecho:nightly-php7.4-apache

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
已修复，Docker镜像需要等待nightly build之后再更新

**Comment by QYKing233** [comment]
干的漂亮

**Comment by ramaox** [comment]
给大佬递茶
