### ISSUE TITLE
http3下无法成功登录

### ISSUE THREAD

**Issue by zuohl** [typecho/typecho#1230]
### 1. 该问题的重现步骤是什么？
nginx安装http3支持,启用
 listen 443 http3 quic reuseport;
注释该段配置后正常

- 操作系统版本：
- Apache/NGINX 版本：nginx version: nginx/1.21.0 (nginx-quic-1.21.0-1.el8.ac0398da8f23.88df13d73d5a74505f046f0bf37fb2fb3e1f1a58)
- PHP 版本：7.4
- Typecho 版本：最新开发版本
- 浏览器版本：Microsoft Edge
版本 95.0.1020.40 (官方内部版本) (64 位)

[//]: # (如有图片请附上截图)

**Comment by zuohl** [comment]
还有一个我想请教下,这个项目的运行时日志在哪个目录啊,我找了半天没找到,对php不太熟悉

**Comment by opswill** [comment]
http3应该对登录没有影响，无法登录排查方向：
1. session files文件夹是否有权限写入
2. 如果注释掉正常，也可能是https的配置有误
3. 查看后台的站点地址配置是不是https
4. 数据库连接是否正常
基本就上面几种情况了
typecho不是thinkphp这类的框架，默认没有打应用日志，php的日志要开error report

**Comment by xlsw** [comment]
会不会是你的浏览器不支持HTTP3，欸嘿嘿
