### ISSUE TITLE
文章发布接口调用异常

### ISSUE THREAD

**Issue by imycard** [typecho/typecho#1231]
### 1. 该问题的重现步骤是什么？
主题functions.php引入
```
\Typecho\Plugin::factory('\Widget\Contents\Post\Edit')->finishPublish = array('myplugin', 'post_update');
class myplugin {

    public static function post_update($contents, $class)
    {
    xxxxxx
    }
}
```

### 2. 你期待的结果是什么？实际看到的又是什么？
期待的结果是在文章发布时执行post_update函数。
实际未执行，
确认函数没写错，将相同函数直接放在`\Widget\Contents\Post\Edit.php`中`self::pluginHandle()->finishPublish($contents, $this);`后面是可以正常执行的
### 3. 问题出现的环境

- 操作系统版本：windows11
- IIS 版本：10
- 数据库版本：MariaDB 10.5
- PHP 版本：7.4
- Typecho 版本：2021/11/8 同步版本
- 浏览器版本：EDGE V95

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
目前皮肤的`functions.php`里定义的插件接口，仅能在皮肤展现的页面生效

**Comment by imycard** [comment]
> 目前皮肤的`functions.php`里定义的插件接口，仅能在皮肤展现的页面生效

明白了，谢谢，那我做进插件里使用。
