### ISSUE TITLE
登录界面报错

### ISSUE THREAD

**Issue by goodbigtree** [typecho/typecho#1244]
### 1. 该问题的重现步骤是什么？
注册账号之后登录；
报错信息
Notice: Undefined offset: 1 in D:\Program Files\xampp\htdocs\typecho\admin\common.php on line 31
Notice: Trying to access array offset on value of type null in D:\Program Files\xampp\htdocs\typecho\admin\common.php on line 32

### 2. 你期待的结果是什么？实际看到的又是什么？
不要报错
### 3. 问题出现的环境
https://user-images.githubusercontent.com/28706672/141872280-b4170c86-83d0-49e7-abdf-77b9eb26f66b.png

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：.7
- PHP 版本：7.4
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)
![fehelper-localhost-typecho-admin-login-php-1637021397874](https://user-images.githubusercontent.com/28706672/141872280-b4170c86-83d0-49e7-abdf-77b9eb26f66b.png)

**Comment by joyqi** [comment]
你这用的是1.1版吧？

**Comment by goodbigtree** [comment]
用的是Typecho 1.1(17.10.30) 版本；版本问题吗？要换到哪个版本？？

**Comment by joyqi** [comment]
在新的开发版中已经修复了，如果你想等待稳定版，可以等新版发布了再换
