### ISSUE TITLE
文章审核不通过

### ISSUE THREAD

**Issue by goodbigtree** [typecho/typecho#1245]
### 1. 该问题的重现步骤是什么？
贡献者角色创建的文章，自己不能审核，管理员那边也没法看到和审核
### 2. 你期待的结果是什么？实际看到的又是什么？
管理员可以进行审核
不要报错
### 3. 问题出现的环境
Typecho 1.1(17.10.30)

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：.7
- PHP 版本：7.4
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)
![fehelper-localhost-typecho-admin-login-php-1637021397874](https://user-images.githubusercontent.com/28706672/141873254-6ae9e2ca-54a6-4522-92d9-eff2ee476464.png)

![fehelper-localhost-typecho-admin-manage-posts-php-1637022181055](https://user-images.githubusercontent.com/28706672/141873371-5f5516da-49a0-425c-9d86-8dd81333a4f8.png)

**Comment by jrotty** [comment]
管理员点右上角所有按钮就能看到了，然后点击去文章在右下角高级设置中把文章状态设置成公开即可

**Comment by goodbigtree** [comment]
点击所有--->高级设置--->设置为公开解决了问题
