### ISSUE TITLE
开启伪静态报错

### ISSUE THREAD

**Issue by qu5** [typecho/typecho#1246]
### 1. 该问题的重现步骤是什么？
后台设置，开启伪静态保存后保存
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：caddy 2.4.6
- 数据库版本：sqilte3
- PHP 版本：php 8.1
- Typecho 版本：typecho 1.2

[//]: # (如有图片请附上截图)
![屏幕截图 2021-11-16 232634](https://user-images.githubusercontent.com/39921677/142014365-e9482503-d17e-40f1-b202-c7aff7093bb9.png)

**Comment by qu5** [comment]
> 在服务器上运行如下命令，看看结果
> 
> ```shell
> curl -H "x-requested-with: XMLHttpRequest" -H "user-agent: Typecho 1.2.0" -i "<你的网址>/action/ajax?do=remoteCallback"
> ```
> 
> 把`<你的网址>`替换成你的博客地址

```
HTTP/2 200
content-type: text/html; charset=UTF-8
server: Caddy
x-powered-by: PHP/8.1.0RC6
content-length: 2
date: Wed, 17 Nov 2021 07:48:09 GMT
```

**Comment by joyqi** [comment]
你的php有装curl扩展么

**Comment by qu5** [comment]
> 你的php有装curl扩展么

装上了，新版本一切正常。caddy2无需设置就可以兼容wp和typecho的伪静态，如果能兼容caddy2，不要提示下面内容就好了。

> 重写功能检测失败, 请检查你的服务器设置
>  如果你仍然想启用此功能, 请勾选这里
