### ISSUE TITLE
使用1.1正式版无法升级至最新开发版

### ISSUE THREAD

**Issue by wanvfx** [typecho/typecho#1253]
### 1. 该问题的重现步骤是什么？
PHP5.6使用1.1正式版无法升级至最新开发版v1.2.0-rc.1

后，清空服务器重新安装，用php5.6安装v1.2.0-rc.1开发版无法进入安装程序。

### 2. 你期待的结果是什么？实际看到的又是什么？
希望能够正常以php5.6版本安装体验新版本的typecho

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Nginx 1.20.1
- 数据库版本：MySQL 5.6.50
- PHP 版本：PHP-5.6
- Typecho 版本：v1.1正式版
- 浏览器版本：edge

[//]: # (如有图片请附上截图)

**Comment by jrotty** [comment]
最新版需要php7.2及以上

**Comment by joyqi** [comment]
1.2.0以后的版本不再支持php7.2以下的环境了，请及时升级
