### ISSUE TITLE
1.2版本编辑文章出现500错误：Non-static method Typecho\Widget::__call() cannot be called statically

### ISSUE THREAD

**Issue by dinphy** [typecho/typecho#1254]
### 1. 该问题的重现步骤是什么？

后台文章管理，编辑文章时出现，但很奇怪的是，有些文章编辑时不会出现这个错误

### 2. 你期待的结果是什么？实际看到的又是什么？

修复BUG 

### 3. 问题出现的环境

typecho 1.2 版本，typecho 1.1正常

- 操作系统版本：Apache/2.4.7 (CentOS)
- Apache/NGINX 版本：Apache/2.4.7 (CentOS)
- 数据库版本： 5.6.40 - MySQL Community Server (GPL)
- PHP 版本：7.2
- Typecho 版本：1.2
- 浏览器版本：edge 最新稳定版本，360极速X最新版本，谷歌浏览器最新稳定版

[//]: # (如有图片请附上截图)

页面500：
Non-static method Typecho\Widget::__call() cannot be called statically

**Comment by joyqi** [comment]
用了插件了么？

**Comment by joyqi** [comment]
你在config.inc.php里加入一行

```
define('__TYPECHO_DEBUG__', true);
```

然后再编辑文章，把完整的报错信息贴上来

**Comment by dinphy** [comment]
> 你在config.inc.php里加入一行
> 
> ```
> define('__TYPECHO_DEBUG__', true);
> ```
> 
> 然后再编辑文章，把完整的报错信息贴上来

Non-static method Typecho\Widget::__call() cannot be called statically
Error: Non-static method Typecho\Widget::__call() cannot be called statically in /home/ftp/3/3h7h8nj29i222/web/usr/plugins/GithubFile/Plugin.php:22
Stack trace:
#0 [internal function]: GithubFile_Plugin::_handler(Array, NULL)
#1 /home/ftp/3/3h7h8nj29i222/web/var/Typecho/Plugin.php(446): call_user_func_array(Array, Array)
#2 /home/ftp/3/3h7h8nj29i222/web/var/Widget/Upload.php(52): Typecho\Plugin->__call('Widget_Upload:a...', Array)
#3 /home/ftp/3/3h7h8nj29i222/web/var/Widget/Base/Contents.php(561): Widget\Upload::attachmentHandle(Array)
#4 /home/ftp/3/3h7h8nj29i222/web/var/Widget/Base/Contents.php(486): Widget\Base\Contents->filter(Array)
#5 [internal function]: Widget\Base\Contents->push(Array)
#6 /home/ftp/3/3h7h8nj29i222/web/var/Typecho/Db.php(427): array_map(Array, Array)
#7 /home/ftp/3/3h7h8nj29i222/web/var/Widget/Contents/Attachment/Admin.php(86): Typecho\Db->fetchAll(Object(Typecho\Db\Query), Array)
#8 /home/ftp/3/3h7h8nj29i222/web/var/Typecho/Widget.php(155): Widget\Contents\Attachment\Admin->execute()
#9 /home/ftp/3/3h7h8nj29i222/web/var/Typecho/Widget.php(187): Typecho\Widget::widget('Widget\\Contents...', NULL, NULL, true)
#10 /home/ftp/3/3h7h8nj29i222/web/admin/manage-medias.php(7): Typecho\Widget::alloc()
#11 {main}

**Comment by dinphy** [comment]
> > 你在config.inc.php里加入一行
> > ```
> > define('__TYPECHO_DEBUG__', true);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后再编辑文章，把完整的报错信息贴上来
> 
> Non-static method Typecho\Widget::__call() cannot be called statically Error: Non-static method Typecho\Widget::__call() cannot be called statically in /home/ftp/3/3h7h8nj29i222/web/usr/plugins/GithubFile/Plugin.php:22 Stack trace: #0 [internal function]: GithubFile_Plugin::_handler(Array, NULL) #1 /home/ftp/3/3h7h8nj29i222/web/var/Typecho/Plugin.php(446): call_user_func_array(Array, Array) #2 /home/ftp/3/3h7h8nj29i222/web/var/Widget/Upload.php(52): Typecho\Plugin->__call('Widget_Upload:a...', Array) #3 /home/ftp/3/3h7h8nj29i222/web/var/Widget/Base/Contents.php(561): Widget\Upload::attachmentHandle(Array) #4 /home/ftp/3/3h7h8nj29i222/web/var/Widget/Base/Contents.php(486): Widget\Base\Contents->filter(Array) #5 [internal function]: Widget\Base\Contents->push(Array) #6 /home/ftp/3/3h7h8nj29i222/web/var/Typecho/Db.php(427): array_map(Array, Array) #7 /home/ftp/3/3h7h8nj29i222/web/var/Widget/Contents/Attachment/Admin.php(86): Typecho\Db->fetchAll(Object(Typecho\Db\Query), Array) #8 /home/ftp/3/3h7h8nj29i222/web/var/Typecho/Widget.php(155): Widget\Contents\Attachment\Admin->execute() #9 /home/ftp/3/3h7h8nj29i222/web/var/Typecho/Widget.php(187): Typecho\Widget::widget('Widget\Contents...', NULL, NULL, true) #10 /home/ftp/3/3h7h8nj29i222/web/admin/manage-medias.php(7): Typecho\Widget::alloc() #11 {main}

我找到原因了，是githubfile这个插件的原因导致的，谢谢你了
