### ISSUE TITLE
[功能请求]支持 IDN

### ISSUE THREAD

**Issue by cherinyy** [typecho/typecho#1260]
### 1. 该问题的重现步骤是什么？
将“站点地址”修改为 IDN 等。

### 2. 你期待的结果是什么？实际看到的又是什么？
![image](https://user-images.githubusercontent.com/9050713/145216299-4305bdbe-edc7-4f62-8301-8db7c2c1ab38.png)
![image](https://user-images.githubusercontent.com/9050713/145216335-2f61c751-f5c7-4fa1-8c52-e30f37869c4d.png)

### 3. 问题出现的环境

- 操作系统版本：Debian 11 (Docker)
- Apache/NGINX 版本：1.21.4-quic ([Build](https://www.nginx.com/blog/our-roadmap-quic-http-3-support-nginx/))
- 数据库版本：10.6.5 ([mariadb:latest](https://hub.docker.com/_/mariadb/))
- PHP 版本：8.0.13 (Build [joyqi/typecho](https://hub.docker.com/r/joyqi/typecho/):nightly-php8.0-fpm + intl)
- Typecho 版本：[joyqi/typecho](https://hub.docker.com/r/joyqi/typecho/)
- 浏览器版本：Google Chrome 96.0.4664.45 (64 Bit)

[//]: # (如有图片请附上截图)
我注意到 PHP 扩展 Intl [支持](https://www.php.net/manual/ref.intl.idn.php)转换 IDN。如果能 Typecho 能够支持的话，就再好不过了，看着 Punycode 域名总觉得怪怪的。

**Comment by dss-saber** [comment]
11
