### ISSUE TITLE
[功能请求]为表单助手类参数添加禁用表单自动填充的参数

### ISSUE THREAD

**Issue by wordlesswind** [typecho/typecho#1261]
### 1. 该问题的重现步骤是什么？
打开插件配置页面，点击输入框

### 2. 你期待的结果是什么？实际看到的又是什么？
不触发浏览器的表单自动填充
![image](https://user-images.githubusercontent.com/9050713/145328079-da354f68-574c-499b-a8fc-edc04293d047.png)

### 3. 问题出现的环境

- 操作系统版本：Debian 11 (Docker)
- Apache/NGINX 版本：1.21.4-quic ([Build](https://www.nginx.com/blog/our-roadmap-quic-http-3-support-nginx/))
- 数据库版本：10.6.5 ([mariadb:latest](https://hub.docker.com/_/mariadb/))
- PHP 版本：8.0.13 (Build [joyqi/typecho](https://hub.docker.com/joyqi/typecho/):nightly-php8.0-fpm + intl)
- Typecho 版本：[joyqi/typecho](https://hub.docker.com/joyqi/typecho/)
- 浏览器版本：Google Chrome 96.0.4664.45 (64 Bit)

[//]: # (如有图片请附上截图)
部分插件需要填写 API 密钥，Typecho 没有禁用表单自动填充，导致浏览器收录了密钥内容。
https://developer.mozilla.org/docs/Web/HTML/Attributes/autocomplete

**Comment by SHIERTX** [comment]
插件可将设置项form的type设置为password（好像是这个项）以禁用自动填充

**Comment by joyqi** [comment]
是否设置`autocomplete`是插件作者在生成表单时自由控制的，Typecho不会做统一控制，但我们提供了设置属性的接口。

**Comment by wordlesswind** [comment]
> 插件可将设置项form的type设置为password（好像是这个项）以禁用自动填充

修改为 Password 会触发浏览器的密码填充，并且询问你是否要保存用户名和密码。我有想过要自己改，但我没看懂怎么改🤣
去问问插件作者好了
