### ISSUE TITLE
无法新增分类

### ISSUE THREAD

**Issue by LeviMarvin** [typecho/typecho#1264]
### 1. 该问题的重现步骤是什么？
打开管理后台，选择“管理”，点击“新增分类”。
删除默认分类，在新增分类页面填好内容后点击“增加分类”/
### 2. 你期待的结果是什么？实际看到的又是什么？
添加分类成功
`Widget\Base\Metas::getMaxOrder(): Return value must be of type int, null returned`
### 3. 问题出现的环境

- 操作系统版本：Ubuntu 20.04 LTS x64
- Apache/NGINX 版本：1.21.4
- 数据库版本：MySQL MariaDB 10.5
- PHP 版本：8.0
- Typecho 版本：1.2.0 RC
- 浏览器版本：Edge 96.0.1054.43 (官方内部版本) (64 位)

[//]: # (如有图片请附上截图)

**Comment by LeviMarvin** [comment]
手动在数据库metas表中新建分类后，在管理后台新建分类正常

**Comment by joyqi** [comment]
#1207 已经修复了，看来我需要重新发布一个rc
