### ISSUE TITLE
分类查询无法获得分类数量

### ISSUE THREAD

**Issue by SamuNatsu** [typecho/typecho#1267]
### 1. 该问题的重现步骤是什么？
```php
\Widget\Metas\Category\Rows::alloc()->to($cates);
$cates->length;
```

### 2. 你期待的结果是什么？实际看到的又是什么？
此时获得的length永远为0，但是实际上可以通过next()迭代获得所有分类的内容

如果是同类似的API去获得Pages列表，length又可以正常返回页面数量

不知道是不是不能这样去获得分类数量，如果不能那又可以通过什么方法获得？

### 3. 问题出现的环境

- 操作系统版本：CentOS 7
- Apache/NGINX 版本：1.17.10
- 数据库版本：8.0.19
- PHP 版本：7.4.6
- Typecho 版本：commit c0476699003fc8d4437a6c4b79a9024157eaac7d
- 浏览器版本：Chrome

[//]: # (如有图片请附上截图)

**Comment by benzBrake** [comment]
我记得不是 ->size() 吗
