### ISSUE TITLE
似乎用 PHP 8.1 会有一堆报错？

### ISSUE THREAD

**Issue by JohnsonRan** [typecho/typecho#1268]
### 1. 该问题的重现步骤是什么？
使用 PHP 8.1
### 2. 你期待的结果是什么？实际看到的又是什么？
无报错
### 3. 问题出现的环境

- 操作系统版本：alpine (Docker)
- Apache/NGINX 版本：caddy:latest
- 数据库版本：mariadb:latest
- PHP 版本：php:8.1.0-fpm-alpine
- Typecho 版本： c0476699003fc8d4437a6c4b79a9024157eaac7d
- 浏览器版本：96.0.4664.93

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/89735151/145734090-df436d1d-4cfa-4155-8389-44b5cb63d4dd.png)
![R3N~%UG@L@TOLN%4D1H4@UK](https://user-images.githubusercontent.com/89735151/145734099-213167f5-6ab5-49e2-b055-db5a111cf527.png)

**Comment by JohnsonRan** [comment]
貌似还是有问题
![image](https://user-images.githubusercontent.com/89735151/145811189-09bb1f67-8bfe-47de-b39e-e5737f3c31db.png)

**Comment by joyqi** [comment]
我找时间集中看一下吧，8.1刚release，估计废弃不少特性

**Comment by iCoACN** [comment]
我说一下，我的解决思路吧：
把 common.php 和 Json.php 里的{*} 替换成[*]，好像是8.1不支持大括号访问数组等。

但是还有一个问题无法解决，一开始是后台无法登陆，提示用户和密码错误。后来通过数据库直接修改的密码。然后就是后台无法修改密码，改了就出错。应该跟 PasswordHash.php 有关，但是不会改。
