### ISSUE TITLE
如何在编辑文章时使用php代码并不被解析掉？

### ISSUE THREAD

**Issue by jeffreyouni** [typecho/typecho#1271]
### 2. 你期待的结果是什么？
编辑文章时如果要输入html代码的话可以用！！！隔开。
请问如果我要编辑文章的时候输入php代码，不要被解析掉，有什么办法吗？可以修改哪个文件下面的代码呢？或者有什么插件还是说可以在系统里设置的呢？
打个比方，比如在编辑文章时，我可以用php代码echo出数据库里的数据，每次阅读文章时的数据就是数据库里的。（主要就是想在编辑文章时写的php代码在阅读的时候可以跑起来）
谢谢你的帮忙！

**Comment by joyqi** [comment]
文章内容里的代码是无法执行的，我们并不提供这样的功能，如果代码执行的逻辑建议放到模版文件的代码里
