### ISSUE TITLE
如何给 HyperDown.js 新增HTML标签白名单

### ISSUE THREAD

**Issue by benzBrake** [typecho/typecho#1278]
比如我想新增 `<photos>`标签，但是 HyperDown.js 会把 `<photos>` 转换成空白。
尝试往下面这一行加入 `|photos` 不管用
https://github.com/typecho/typecho/blob/157fc05265ad05008198498d4f8cd89189414db8/admin/src/js/hyperdown.js#L13
因为这是src文件，改了我不会编译，我实际是修改
https://github.com/typecho/typecho/blob/157fc05265ad05008198498d4f8cd89189414db8/admin/editor-js.php#L63
加入了
```
converter.commonWhiteList = converter.commonWhiteList + '|photos';
converter.blockHtmlTags = converter.blockHtmlTags + '|photos';
```
来添加白名单的，但是这样不起作用

**Comment by wuxianucw** [comment]
编译 JS 大概是在 `tools` 目录下先 `npm i` 再 `npm run build_js`
