### ISSUE TITLE
Function get_magic_quotes_gpc() is deprecated in /www/wwwroot/xxxxxxx.com/var/Typecho/Common.php on line 208

### ISSUE THREAD

**Issue by DeanShiDirect** [typecho/typecho#1286]
### 1. 该问题的重现步骤是什么？
PHP7.4

### 2. 你期待的结果是什么？实际看到的又是什么？
不用修改PHP7.4版本，就能进行安装

### 3. 问题出现的环境

- 操作系统版本：CentOS7.4
- Apache/NGINX 版本：Nginx 1.18.0
- 数据库版本：MySQL 5.6.50	
- PHP 版本：PHP7.4
- Typecho 版本：官网最新版 1.1-17.10.30-release.tar.gz
- 浏览器版本：

[//]: # (如有图片请附上截图)
![0112111435](https://user-images.githubusercontent.com/94027516/149058349-8a24fc9c-088e-48a3-95b2-f4cf2aec8b37.jpg)

解决方法：
提示不推荐使用get_magic_quotes_gpc函数，禁用即可，宝塔面板中在php设置——禁用函数，添加get_magic_quotes_gpc，然后重启php

可有其他方法。

另外一个主机是，Ubuntu20  
Nginx 1.20.1 
MySQL 5.6.50
PHP-5.6
phpMyAdmin 4.4
安装时候秒过

**除了禁用函数，可有其他方法。**

**Comment by DeanShiDirect** [comment]
在论坛看见解决方法是https://forum.typecho.org/viewtopic.php?t=14096

在首页 index.php 文件最上一行 加一句 define('MAGIC_QUOTES_GPC',ini_set("magic_quotes_runtime",0)?True:False); 即可

这个解决方法一点用都没有。
问问题的问了问题，别人回答了，没有用，然后没有问问题的也没有反馈


后期升级typecho或者php7.4，或者安装博客插件，是否有隐患呢？
php7.4这个有问题，为什么官网不提示呢?

**Comment by joyqi** [comment]
请使用新的rc版，或者等待正式版发布

https://github.com/typecho/typecho/releases/tag/v1.2.0-rc.1

**Comment by DeanShiDirect** [comment]
> 请使用新的rc版，或者等待正式版发布
> 
> https://github.com/typecho/typecho/releases/tag/v1.2.0-rc.1

原来新版本在这里。

宝塔上传解压缩的网站文件后，不上传 usr/uploads 空文件夹，安装网站时候报错，
uploads 文件夹 需要手动创建

**Comment by DeanShiDirect** [comment]
安装rc版，我先创建的数据库 引擎是MyISAM 字符utf8  适配器是Mysql原生函数，结果出错。在安装程序中 只能用默认 引擎InnoDB  字符utf8mb4_general_ci  适配器默认是Pdo驱动Mysql适配器 吗？因为如果我用引擎MyISAM 字符utf8就安装报错。

**Comment by joyqi** [comment]
贴上报错信息
