### ISSUE TITLE
1.2正式版发布时，记得同时发布一个能把旧数据库结构升级的upgrade文件

### ISSUE THREAD

**Issue by sluke** [typecho/typecho#1287]
### 1. 该问题的重现步骤是什么？
用 1.2 RC版本文件直接覆盖1.1版本，数据库使用的是sqlite

### 2. 你期待的结果是什么？实际看到的又是什么？
期待：正常读取数据库，登录后台正常
实际：文章现实正常，后台登录出现：Error establishing a database connection
推测：表结构有细微差异

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：8.0
- Typecho 版本：1.2RC1
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
1.1到1.2的数据结构并没改变啊，把debug打开看看具体报错信息是啥

**Comment by sluke** [comment]
问题找到了，是我服务器配置有点问题，数据库表的细微差异确实有

如：typcho_users表的字段类型

### 1.2

mail varchar(150)
url varchar(150)

### 1.1

mail varchar(200)
url varchar(200)
