### ISSUE TITLE
本地写好后粘贴到网站就卡住

### ISSUE THREAD

**Issue by fjhechuan** [typecho/typecho#1288]
### 1. 该问题的重现步骤是什么？
本地写好后粘贴到网站就卡住

### 3. 问题出现的环境

- 操作系统版本：ubuntu20.04
- Apache/NGINX 版本：nginx 1.8
- 数据库版本：5.6
- PHP 版本：7.4
- Typecho 版本：最新版的
- 浏览器版本：谷歌浏览器最新版的

[![7lcf1K.gif](https://s4.ax1x.com/2022/01/13/7lcf1K.gif)](https://imgtu.com/i/7lcf1K)

**Comment by joyqi** [comment]
你用的这是第三方编辑器插件吧，看提示是浏览器的前端脚本卡住了
