### ISSUE TITLE
报错Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/install.php:202) in /var/www/html/var/Typecho/Cookie.php on line 102  Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/install.php:202) in /var/www/html/install.php on line 584

### ISSUE THREAD

**Issue by Simplefish666** [typecho/typecho#1291]
### 1. 该问题的重现步骤是什么？
按照步骤来的之后报错(截图)
### 2. 你期待的结果是什么？实际看到的又是什么？
不出现报错
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本： nginx/1.21.5
- 数据库版本：mysql 5.7
- PHP 版本：7.4-fpm
- Typecho 版本：1.1(17.10.30)
- 浏览器版本：Google Chrome(97.0.4692.71) 正式版

使用docker搭建的nginx php mysql环境都是docker环境 php已安装pdo和pdo_mysql 数据库配置确定没有问题
[// ]: # (如有图片请附上截图)
![error](https://user-images.githubusercontent.com/88495409/149626475-73752300-57e7-4cb0-858b-95c2d33fa36e.png)
![微信截图_20220115230539](https://user-images.githubusercontent.com/88495409/149626565-0430eaa5-a74b-4223-86e1-46a844d5d0ce.png)

**Comment by joyqi** [comment]
这个错误已经在1.2.0里修复，如果你用docker，可以使用官方的镜像

https://hub.docker.com/r/joyqi/typecho

**Comment by Simplefish666** [comment]
> 这个错误已经在 1.2.0 修复，如果你用 docker，可以使用官方的镜像
> 
> https://hub.docker.com/r/joyqi/typecho

好的 谢谢
