### ISSUE TITLE
后台管理文章有个小问题

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#1295]
在管理文章**所有文章**状态下，翻页到最后一页，这是点**我的**就有可能会显示没有文章，因为地址栏中的page参数还是定位在最后一页，而不是第一页

使用的是typecho最新开发板，感觉1.1版应该也有这个问题

**Comment by sunkangchina** [comment]
自己改下用吧。 参考下 https://github.com/sunkangchina/typecho/commit/940ba7ad6d4da3c17618ce8fd25d7b6de80e8dd9
提交pull了

**Comment by jrotty** [comment]
ok
