### ISSUE TITLE
admin/menu.php中有一个默认样式的菜单按钮

### ISSUE THREAD

**Issue by allyxmiko** [typecho/typecho#1313]
### 1. 该问题的重现步骤是什么？
1. 插件激活menu
![image](https://user-images.githubusercontent.com/53589496/152595045-651bf3f4-a02b-4928-ac8b-5d0ece5ae5a6.png)
2. 左上角出现一个默认样式的菜单按钮
### 2. 你期待的结果是什么？实际看到的又是什么？
期待结果：
admin页面左上角不会出现一个默认样式的菜单按钮
原因：
在admin/menu.php中有一个button
![image](https://user-images.githubusercontent.com/53589496/152594598-d96fb455-b469-4eed-9413-56fe226fb86f.png)

### 3. 问题出现的环境

- 操作系统版本：centos 7.6
- Apache/NGINX 版本：nginx 1.21
- 数据库版本：mysql 5.7
- PHP 版本：7.4
- Typecho 版本：master
- 浏览器版本：chrome 98.0.4758.81

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
原作者的插件写的有问题，它完全覆盖掉了默认样式，导致错位，请联系插件作者解决
