### ISSUE TITLE
第三方主题 404.php 打开空白

### ISSUE THREAD

**Issue by plumlis** [typecho/typecho#1316]
使用非官方的主题，几乎所有第三方主题在目录下的 404.php 会失效。

我用的是 https://github.com/Hanson/typecho_material_theme 的主题，但是找了下目前能用的其他第三方主题，都有这个问题。

我做了一些测试，发现：

- 访问不存在的 route 可以跳转到 404.php，这个功能正常
-  将 404.php 修改为纯文本，也可以打开和正常显示
-  删除掉 404.php 中的 `<?php $this->header(); ?>` ，其他内容也可以正常显示
- 不使用那个 header 函数，手动将 css 等 header 信息复制到 404.php，自己写个简陋的 head 加载 css，也是正常的
- 其他页面和功能都正常，包括 post page 之类的

我不知道是这个参数本身有什么问题，还是兼容性导致的，不过官方默认的主题是正常的。

**Comment by ZiXia1** [comment]
请注明typecho版本，可能是与老版本主题的兼容问题

**Comment by plumlis** [comment]
最新的 typecho 1.2 RC
PHP 8.1

**Comment by MBRjun** [comment]
我的是正常的捏 Typecho Release 1.2
