### ISSUE TITLE
无法新建分类

### ISSUE THREAD

**Issue by zddue** [typecho/typecho#1317]
### 1. 该问题的重现步骤是什么？
点击分类，选择新建分类，显示Widget\Base\Metas::getMaxOrder(): Return value must be of type int, null returned
### 2. 你期待的结果是什么？实际看到的又是什么？
新建分类成功。实际看到Widget\Base\Metas::getMaxOrder(): Return value must be of type int, null returned
### 3. 问题出现的环境

- 操作系统版本：Ubuntu20.04
- Apache/NGINX 版本：Nginx 1.20.2
- 数据库版本：MySQL 5.6.50
- PHP 版本：php8.0
- Typecho 版本：1.20 rc
- 浏览器版本：chrome

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
请尝试rc2版本
https://github.com/typecho/typecho/releases/tag/v1.2.0-rc.2
