### ISSUE TITLE
第一次进入文章公式颜色不渲染

### ISSUE THREAD

**Issue by xiongminghao** [typecho/typecho#1325]
### 2. 你期待的结果是什么？实际看到的又是什么？
第一次进入文章页面，代码块颜色没有渲染，我还有一个数学公式渲染插件，第一次进入也没有渲染，刷新了一次后都渲染了
### 3. 问题出现的环境

- 操作系统版本：CentOS 7.6.1810 x86_64(Py3.7.9)　
- Apache/NGINX 版本：1,14.2
- 数据库版本：mysql5.5
- PHP 版本：5.6
- Typecho 版本：1.2.0()
- 浏览器版本：Chrome

[//]: # (如有图片请附上截图)

截图在下面

**Comment by xiongminghao** [comment]
<img width="1728" alt="截屏2022-02-15 19 00 37" src="https://user-images.githubusercontent.com/59282149/154049280-02126314-d65b-4cca-9695-422a7f52396b.png">
<img width="1728" alt="截屏2022-02-15 19 00 50" src="https://user-images.githubusercontent.com/59282149/154049290-80f1f7c5-bb01-4878-90fa-23a8a6e8eb3e.png">

**Comment by yczheng0** [comment]
推测：应该是你采用的主题应用了Pjax，并且没有适配数学公式渲染，在complete回调函数中没有加入MathJax或者Katex的渲染，所以只有在刷新重载页面时，相应js脚本才被调用。

**Comment by zwying0814** [comment]
和你使用的主题有关系，可以咨询主题作者，若使用了类似Pjax的技术，请在回调函数里补充相关脚本

**Comment by joyqi** [comment]
这个应该是插件的问题
