### ISSUE TITLE
咨询发布接口问题 Widget_Contents_Post_Edit->write

### ISSUE THREAD

**Issue by gogobody** [typecho/typecho#1328]
### 1. 该问题的重现步骤是什么？
之前在 `Typecho_Plugin::factory('Widget_Contents_Post_Edit')->write_1000` 这个接口中实现过一些功能，在1.2 rc 中，在接口函数中testfunc($content, $obj) 访问 $obj->author 出现以下错误：
```
TypeError: Argument 1 passed to Typecho\Widget::allocWithAlias() must be of the type string, null given, called in D:\phpstudy_pro\WWW\typecho\var\Widget\Base\Contents.php on line 827 and defined in D:\phpstudy_pro\WWW\typecho\var\Typecho\Widget.php:199
Stack trace:
xxx
```

### 2. 你期待的结果是什么？实际看到的又是什么？
应该是可以访问到作者信息

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：7.2
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
我的这个修复其实对你的问题治标不治本，引起你这段错误的根本原因是，你在使用`$obj->author`之前，没有用`$obj->have()`来判断数据是否存在
