### ISSUE TITLE
细分 MySQL 报错

### ISSUE THREAD

**Issue by bestony** [typecho/typecho#1338]
### 1. 该问题的重现步骤是什么？

不创建数据库，使用正确的数据库密码进行安装

### 2. 你期待的结果是什么？实际看到的又是什么？

期待提示数据库不存在，是否要进行创建；或直接探测是否有权限创建，如果有则直接创建，无则提示用户手动创建

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：PHP 8.1.1
- Typecho 版本：git 0edb48fae0cc5b9feb686c7367974190074be334

**Comment by sy-records** [comment]
应该是

**Comment by sy-records** [comment]
https://github.com/typecho/typecho/commit/17fcb2f08b5dd1efe84877143c901c741ba2e938 修复了异常捕获，没有数据库时或者配置错误时提示信息是 `对不起, 无法连接数据库, 请先检查数据库配置再继续进行安装`。
之前在下一行捕获的，会有一些错误信息可以判断具体错误。
