### ISSUE TITLE
如何通过api请求相关数据

### ISSUE THREAD

**Issue by MYXXTS** [typecho/typecho#1345]
请问下1.2版本的typecho删除了json相关功能吗？
如何通过api请求相关数据以在其余地方做数据展示呢

**Comment by joyqi** [comment]
目前没有api接口，我们正在收集这一块的需求

**Comment by MYXXTS** [comment]
该功能需求还是比较高的，还望添加，辛苦

**Comment by fenbox** [comment]
Duplicate of #1225
