### ISSUE TITLE
1.2.0正式版 后台版本提醒无法关闭

### ISSUE THREAD

**Issue by Seevil** [typecho/typecho#1354]
### 1. 该问题的重现步骤是什么？

覆盖更新1.2.0 正式版 后台一直提示这个 也没有忽视、取消提醒的按钮
![image](https://user-images.githubusercontent.com/7334510/161176091-4ae92626-d83f-4c24-acf5-feaa2b0addc6.png)

### 2. 你期待的结果是什么？实际看到的又是什么？

希望 版本号一致时不提醒 ，低于最新版时可选择忽略提醒

### 3. 问题出现的环境

- 操作系统版本：win10
- Apache/NGINX 版本：1.12
- 数据库版本：5.7
- PHP 版本：8.1
- Typecho 版本：1.2.0
- 浏览器版本：chrome 100

[//]: # (如有图片请附上截图)

**Comment by hizyw** [comment]
你不是一个人，我也有同样的问题

**Comment by Seevil** [comment]
> 你不是一个人，我也有同样的问题

😂 强迫症很难受

**Comment by hizyw** [comment]
> 我们重要的改进有如下几点：
> 
> 新的编辑器实时预览自动跟随效果，以及主题内预览功能

这个功能在我这里也没有实现，跟之前版本一样的编辑器界面

**Comment by Seevil** [comment]
> > 我们重要的改进有如下几点：
> > 新的编辑器实时预览自动跟随效果，以及主题内预览功能
> 
> 这个功能在我这里也没有实现，跟之前版本一样的编辑器界面

😏 说不定是过愚人节呢

**Comment by YLL21** [comment]
我是登不进后台

**Comment by julyliao** [comment]
> > > 我们重要的改进有如下几点：
> > > 新的编辑器实时预览自动跟随效果，以及主题内预览功能
> > 
> > 
> > 这个功能在我这里也没有实现，跟之前版本一样的编辑器界面
> 
> 😏 说不定是过愚人节呢

啊这...

**Comment by fungjcode** [comment]
那还好，我以为只是我的有问题。

RC.2升级到正式版，登录后台也并没有提示“点击升级”等。

**Comment by w22gb8** [comment]
> 

同样没升级提示，后台还显示版本号，我还以为有问题呢。

**Comment by Seevil** [comment]
找到问题了
#1355  大佬之前更新重构的时候导致的  >= 改成 > 就好了🤣

**Comment by YLL21** [comment]
> 找到问题了 #1355 大佬之前更新重构的时候导致的 >= 改成 > 就好了🤣

在哪个地方

**Comment by julyliao** [comment]
> > 找到问题了 #1355 大佬之前更新重构的时候导致的 >= 改成 > 就好了🤣
> 
> 在哪个地方

https://github.com/typecho/typecho/pull/1356/files
