### ISSUE TITLE
1.2.0版本后台一直提示有新版本

### ISSUE THREAD

**Issue by leeska** [typecho/typecho#1359]
### 1. 该问题的重现步骤是什么？
1.1.0升级1.2.0，登录后台确认升级后还是会提示新版本
![image](https://user-images.githubusercontent.com/60788782/161195294-29dc596a-c417-486b-a85b-3f672980b0d4.png)

### 2. 你期待的结果是什么？实际看到的又是什么？
提示新版本
### 3. 问题出现的环境
![image](https://user-images.githubusercontent.com/60788782/161195415-047ecb29-9359-4b19-aa2d-4bd57a0a4bff.png)

此处修改为>后正常

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
Fixed via #1356
