### ISSUE TITLE
Typecho 1.2.0 控制台的屏幕阅读器可访问性降低

### ISSUE THREAD

**Issue by cary-rowen** [typecho/typecho#1361]
### 1. 该问题的重现步骤是什么？
1. 用 admin 账户登录 typecho 控制台。
2. 使用 Tab 键尝试在后台中的菜单之间移动。

#### 预期效果

菜单类别被 **Focus** 后自动展开，屏幕阅读器焦点可以顺序访问二级子菜单内的条目，如“管理”菜单被 Focus 后可访问到其中的如下菜单项：

* 文章
* 独立页面
* 评论
* 分类
* 标签
* 文件
* 用户

#### 实际效果
当前使用 Tab 键访问到的菜单没有展开，无法获知二级菜单内的菜单项，登录控制台后使用 Tab 键访问，只能访问到如下条目：

- 控制台
- 撰写
- 管理
- 设置
- User Name
- 登出
- 网站
- 官方最新版本是 1.2.0
- 撰写新文章
- 更换外观
- 插件管理
- 系统设置

### 3. 问题出现的环境

- 操作系统版本： ubuntu20.4
- Apache/NGINX 版本： nginx1.18.0
- 数据库版本： mysql 8.2
- PHP 版本： 7.4
- Typecho 版本： 1.2.0
- 浏览器版本： chrome 100.0.4896.60（正式版本） （64 位）
- 重现问题所使用的屏幕阅读器： [NVDA2021.3.5](https://github.com/nvaccess/nvda)

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/21048245/161229577-3a2a415b-ffab-4772-8985-9591f9371b58.png)

**Comment by xingkong013** [comment]
> ### 1. 该问题的重现步骤是什么？
> 1. 用 admin 账户登录 typecho 控制台。
> 2. 使用 Tab 键尝试在后台中的菜单之间移动。
> 
> ### 2. 你期待的结果是什么？实际看到的又是什么？
> #### 预期效果
> 菜单类别被 **Focus** 后自动展开，屏幕阅读器焦点可以顺序访问二级子菜单内的条目，如“管理”菜单被 Focus 后可访问到其中的如下菜单项：
> 
> * 文章
> * 独立页面
> * 评论
> * 分类
> * 标签
> * 文件
> * 用户
> 
> #### 实际效果
> 当前使用 Tab 键访问到的菜单没有展开，无法获知二级菜单内的菜单项，登录控制台后使用 Tab 键访问，只能访问到如下条目：
> 
> * 控制台
> * 撰写
> * 管理
> * 设置
> * User Name
> * 登出
> * 网站
> * 官方最新版本是 1.2.0
> * 撰写新文章
> * 更换外观
> * 插件管理
> * 系统设置
> 
> ### 3. 问题出现的环境
> * 操作系统版本： ubuntu20.4
> * Apache/NGINX 版本： nginx1.18.0
> * 数据库版本： mysql 8.2
> * PHP 版本： 7.4
> * Typecho 版本： 1.2.0
> * 浏览器版本： chrome 100.0.4896.60（正式版本） （64 位）
> * 重现问题所使用的屏幕阅读器： [NVDA2021.3.5](https://github.com/nvaccess/nvda)
> 
> ![image](https://user-images.githubusercontent.com/21048245/161229577-3a2a415b-ffab-4772-8985-9591f9371b58.png)

遇到这个问题已经很久了！
测试环境：
操作系统
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-107-generic x86_64)
网站环境
oneinstack 最新 latest
nginx
nginx version: nginx/1.21.6
php版本
php8.1.2
屏幕阅读器
关于 - 争渡读屏
版本: 2022 贺岁版
内部版本: 1.6.3.1 Patch 0
@joyqi

**Comment by cary-rowen** [comment]
@joyqi  感谢，问题已修复。
