### ISSUE TITLE
使用PostgreSQL数据库恢复数据后id没有自增

### ISSUE THREAD

**Issue by hurui200320** [typecho/typecho#1362]
### 1. 该问题的重现步骤是什么？

从已有Typecho中导出备份文件，然后导入到一个全新安装的Typecho中。我的旧Typecho安装中cid已经自增到了923，而恢复数据后在新的Typecho上发布新的文章，将会覆盖原有的旧文章，此时查看数据库发现cid的自增没有一并恢复。

### 2. 你期待的结果是什么？实际看到的又是什么？

恢复数据后自增也应当一并恢复，即当在新的Typecho安装上发布新文章时，应当分配cid为924。

### 3. 问题出现的环境

- 操作系统版本：openSUSE Leap 15.3
- Apache/NGINX 版本：1.20.1
- 数据库版本：PostgreSQL 14.2 （docker）
- PHP 版本：8.0.8
- Typecho 版本：1.2.0
- 浏览器版本：Chrome

**Comment by hurui200320** [comment]
忘记说了，旧的Typecho是安装在MySQL数据库上的。

**Comment by sy-records** [comment]
MySQL 换到 PostgreSQL？

**Comment by hurui200320** [comment]
是的。

**Comment by hurui200320** [comment]
虽然可以手动设置自增的起点，但是一般用户不注意的话大概率会覆盖到以前的旧文章。
