### ISSUE TITLE
1.2.0 上传目录无法写入, 请手动将安装目录下的 /usr/uploads 目录的权限设置为可写然后继续升级

### ISSUE THREAD

**Issue by starsareintherose** [typecho/typecho#1365]
### 1. 该问题的重现步骤是什么？
I package typecho 1.2.0 for AUR

use this source https://github.com/typecho/typecho/archive/refs/tags/v1.2.0.zip

and I found usr/uploads haven't been made, I mkdir it

and then chown and chmod 755 and http:http to all the folders

Now report `上传目录无法写入, 请手动将安装目录下的 /usr/uploads 目录的权限设置为可写然后继续升级`

### 2. 你期待的结果是什么？实际看到的又是什么？

can install 

### 3. 问题出现的环境

- 操作系统版本：Arch Linux
- Apache/NGINX 版本：nginx version: nginx/1.20.2
- 数据库版本：Server version: 10.7.3-MariaDB Arch Linux
- PHP 版本：PHP 7.4.28 (cli) (built: Feb 16 2022 13:41:30) ( NTS )
- Typecho 版本：1.2.0
- 浏览器版本：chromium version 100.0.4896.60
```
ls -al
drwxr-xr-x 5 http http 4096 Apr  1 20:48 .
drwxr-xr-x 7 http http 4096 Apr  1 16:57 ..
drwxr-xr-x 3 http http 4096 Apr  1 16:57 plugins
drwxr-xr-x 3 http http 4096 Apr  1 16:57 themes
drwxr-xr-x 2 http http 4096 Apr  1 20:48 uploads
```
[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
暂时无法复现这个问题，我们使用`is_dir`和`is_writeable`两个函数来判断是否可写

**Comment by starsareintherose** [comment]
十分奇怪，我在我的服务器上不停复现，我不知道是不是 Arch 独有的 `usr/uploads` 文件夹下面可以塞个 markdown 这样之，就可以让 source code 保有这个文件夹

**Comment by alluLinger** [comment]
复现 +1 
环境：
Ubuntu 20.04 focal
PHP 7.4.3 (cli) (built: Mar  2 2022 15:36:52) ( NTS )
caddy sock
![图片](https://user-images.githubusercontent.com/21037233/161387807-33d96184-3086-4300-b77e-7b76e2f81186.png)

直接chmod +777 后显示
![](https://user-images.githubusercontent.com/21037233/161387779-8849754c-1d5b-496c-9a4d-f5c6de8d2701.png)

**Comment by alluLinger** [comment]
> 十分奇怪，我在我的服务器上不停复现，我不知道是不是 Arch 独有的 `usr/uploads` 文件夹下面可以塞个 markdown 这样之，就可以让 source code 保有这个文件夹

是不是用php-fpm跑的，php默认用户是www-data。

**Comment by starsareintherose** [comment]
> > 十分奇怪，我在我的服务器上不停复现，我不知道是不是 Arch 独有的 `usr/uploads` 文件夹下面可以塞个 markdown 这样之，就可以让 source code 保有这个文件夹
> 
> 是不是用php-fpm跑的，php默认用户是www-data。

Arch Linux 下 默认是 http，我最初展示的是 Nginx 和php-fpm 都是 http 运行，文件权限也都是 http

**Comment by joyqi** [comment]
```php
<?php

$dir = __DIR__ . '/usr/uploads';

echo "{$dir}<br>\n";
echo 'is_dir: ' . var_export(is_dir($dir), true) . "<br>\n";
echo 'is_writeable: ' . var_export(is_writeable($dir), true) . "<br>\n";
```

把这个php文件放到网站根目录下，然后用浏览器访问看看结果

**Comment by starsareintherose** [comment]
```
/usr/share/webapps/typecho/usr/uploads
is_dir: true
is_writeable: false
```
but
```
drwxrwxrwx 2 http http 4096 Apr  2 20:06 uploads
```

**Comment by joyqi** [comment]
你是不是打开了`SELinux`

**Comment by starsareintherose** [comment]
我觉得不是，Arch Linux 没有 `getenforce` 等命令

**Comment by joyqi** [comment]
查看你的`php-fpm.service`文件，看看里面是不是有`ProtectSystem=full`，把这行注释掉再重启服务

**Comment by starsareintherose** [comment]
soga，是这样。但是有没有更好的方法去使用

**Comment by starsareintherose** [comment]
现在 Arch Linux 用户可以通过 [AUR](https://aur.archlinux.org/packages/typecho) 安装 typecho 了。

**Comment by leewp14** [comment]
> soga，是这样。但是有没有更好的方法去使用

毕竟/usr被systemd的ProtectSystem给保护起来不能写入，应该另有安全考虑
我查了查，arch的/var/www在/srv/http 所以我将所有网站的文件包括typecho搬到/srv/http里头，就没有问题了。不必修改php-fpm.service文件

参见：
https://man.archlinux.org/man/file-hierarchy.7
https://unix.stackexchange.com/questions/106504/where-is-var-www-in-arch-linux
https://man.archlinux.org/man/systemd.exec.5.en

**Comment by starsareintherose** [comment]
理论上只能在 /usr/share/typecho 或者 /usr/share/webapps/typecho

**Comment by leewp14** [comment]
> 理论上只能在 /usr/share/typecho 或者 /usr/share/webapps/typecho

？？我从来没有看到说必须放在 /usr/share/typecho 还是 /usr/share/webapps/typecho 这两个地方，如有人说必须放着两个地方你给个链接让我读读
如果你仔细读看我给的第一个链接https://man.archlinux.org/man/file-hierarchy.7以及其他两个链接的话，看看archlinux对/usr的解释，和我提到的/srv的解释 还有/usr/share的解释
我的理解是/usr能不碰就不碰 archlinux中www的文件放在/srv 就好像debian的话就放在/var/www 
如果能放在那边的话 也不用去改ProtectSystem了啦。。。

我真的不明白你说什么理论上只能放在那两边..

**Comment by starsareintherose** [comment]
https://wiki.archlinux.org/title/Web_application_package_guidelines

这里 并且详情见 archlinux  的 https://archlinux.org/packages/community/any/mediawiki/ and https://archlinux.org/packages/community/any/wordpress/

**Comment by leewp14** [comment]
> https://wiki.archlinux.org/title/Web_application_package_guidelines
> 
> 这里 并且详情见 archlinux 的 https://archlinux.org/packages/community/any/mediawiki/ and https://archlinux.org/packages/community/any/wordpress/

web application *package* guidelines
我们是用户自己安装typecho 不是在package typecho让用户安装。。。package放在usr，package是developer（vendor）提供的，只放着for readonly access， 所以肯定没问题呀 这完全跟着我的第一个链接的解释
你maintain aur package的 你懂比较多，我没有这样的经验 我只靠读网上和官网资源。。也许你对吧

**Comment by starsareintherose** [comment]
就像 aur 里的东西正常维护者是不会放到 /usr/local 这样的目录的...因为会被视作系统的
