### ISSUE TITLE
加入 MongoDB 支持

### ISSUE THREAD

**Issue by hmsjy2017** [typecho/typecho#1368]
尝试连接 MongoDB 数据库，出现 `Error establishing a database connection` 错误，可能还没有支持。

**Comment by joyqi** [comment]
我们暂时不会支持`RDBMS`以外类型的数据库。

**Comment by JIeJaitt** [comment]
> 我们暂时不会支持`RDBMS`以外类型的数据库。

有希望在未来支持嘛
