### ISSUE TITLE
删除第一篇默认的文章后，博客首页打不开，报错：array_key_exists(): Argument #2 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by reaper0s** [typecho/typecho#1371]
删除第一篇默认的文章后，博客首页打不开，报错：array_key_exists(): Argument #2 ($array) must be of type array, null given
博客后台正常显示

- 操作系统版本：
- Apache/NGINX 版本：nginx1.20
- 数据库版本：mysql5.7
- PHP 版本：php8.0
- Typecho 版本：typecho1.20
- 浏览器版本：chrome

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
应该是你的主题问题吧，用默认主题看看
