### ISSUE TITLE
[问题] 更新Typecho 1.2.0后的预览文章咋搞

### ISSUE THREAD

**Issue by jyc-jyc** [typecho/typecho#1372]
### 1. 该问题的重现步骤是什么？
点击文章预览

### 2. 你期待的结果是什么？实际看到的又是什么？
文章预览页面，实际看到报错提示 `Call to a member function adminStaticUrl() on null`

### 3. 问题出现的环境

- 操作系统版本：Windows 10 21H2
- Apache/NGINX 版本：1.19.8
- 数据库版本：5.7.34
- PHP 版本：7.3
- Typecho 版本：1.2.0
- 浏览器版本：Chrome 99.0.4844.84

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
没复现，打开debug模式，完整堆栈可以发出来。
