### ISSUE TITLE
从1.1升级到官网1.2后一片空白

### ISSUE THREAD

**Issue by 1619052214** [typecho/typecho#1385]
大大，就从1.1更新到1.2后网站打开就白屏了，然后我就准备重装还是白屏，我用宝塔安装提示
Parse error: syntax error, unexpected ':', expecting '{' in /www/wwwroot/www.qqfh.cc/install.php on line 31

我用1.1版本一点问题没有，我也不知道哪里出问题了
- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：7.0
- Typecho 版本：1.2最新版
- 博客网址 http://qqfh.cc
![Screenshot_20220405_010551](https://user-images.githubusercontent.com/40537163/161595399-0359b1f5-3dc9-44a0-bb99-edf32e0d72b7.jpg)

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
1.2 需要 PHP 7.2以上的环境，请仔细阅读说明

**Comment by 1619052214** [comment]
好的，谢谢joyqi大大
