### ISSUE TITLE
游客新注册用户也会看到后台的welcome.php

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#1386]
网站新注册用户也会输出welcome.php页面
```
欢迎您使用 "Hello World" 管理后台:
[强烈建议更改你的默认密码](http://test.zezeshe.com/admin/profile.php#change-password)
[撰写第一篇日志](http://test.zezeshe.com/admin/write-post.php)
[查看我的站点](http://test.zezeshe.com/)
```
内容最后一句查看我的站点，感觉不对，也不是用户的网站，我记得之前1.1的版本好像用户注册不会进welcome.php页面吧，也许是我记错了

**Comment by sy-records** [comment]
新注册的没有写权限，不会有`撰写第一篇日志`

<img width="678" alt="image" src="https://user-images.githubusercontent.com/33931153/161900330-e3ec54e9-9c75-48a3-813e-2fa31dedb367.png">
