### ISSUE TITLE
安装选择数据库位置，无法下一步。

### ISSUE THREAD

**Issue by yang9w** [typecho/typecho#1387]
### 1. 该问题的重现步骤是什么？
在centos的系统上安装1.2.0版本到选择数据库处，选择sqlite后，点击下一步出现“确认你的配置”，无法进行下一步。此服务器上已经安装有了typecho1.1版本，运行无问题。也是sqlite的数据库，没有问题。PHP为7.4
然后我重新开了一个Ubuntu 20版本的。lnmp一键安装环境PHP8.0的，一样出现以上问题。
### 3. 问题出现的环境
LNMP一键包

- 操作系统版本：Ubuntu 20.14
- Apache/NGINX 版本：1.20
- 数据库版本：NO
- PHP 版本：8.0
- Typecho 版本：1.2.0
- 浏览器版本：chrome最新版

[//]: # (如有图片请附上截图)

初始化配置
数据库适配器

SQLite 原生函数适配器
请根据您的数据库类型选择合适的适配器

数据库前缀
typecho_
默认前缀是 "typecho_"

数据库文件路径
/home/wwwroot/XXX/usr/624c583c68272.db
**确认您的配置**
点击安装后出现以上文字
"/home/wwwroot/XXX/usr/624c583c68272.db" 是我们为您自动生成的地址

**Comment by joyqi** [comment]
duplicate of #1358 , fixed via #1357
