### ISSUE TITLE
GitHub最新版，自带备份功能，无法正常使用

### ISSUE THREAD

**Issue by huolong12345** [typecho/typecho#1388]
### 1. 该问题的重现步骤是什么？
php7.4 ，点击开始备份，显示备份下载失败，点击重新下载，下载后的dat文件，内容确实
### 2. 你期待的结果是什么？实际看到的又是什么？
期待可正常下载备份
### 3. 问题出现的环境
php7.4
- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：7.4
- Typecho 版本：github最新版
- 浏览器版本：火狐最新版，win11

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
没复现问题，有什么详细的错误信息吗？看看错误日志

**Comment by joyqi** [comment]
这个是你自己开启的吧，官方代码里没有这一行

**Comment by huolong12345** [comment]
是，我已删除这段代码，恢复正常
