### ISSUE TITLE
文章cid不连续

### ISSUE THREAD

**Issue by lovethou** [typecho/typecho#1391]
大大，下次能不能更新一下文章的cid不连续的问题，强迫症有点难受

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：mysql5.6
- PHP 版本：7.2
- Typecho 版本：1.2
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by AkaraChen** [comment]
这个似乎就是这么设计的

**Comment by HsukqiLee** [comment]
附件 分类 都会占用cid，除非修改框架，把自增值调大，然后用slug表示附件和分类

**Comment by vndroid** [comment]
如果开启了「个人设置」-「自动保存」功能，每次触发自动保存都会占用一个 cid，因此可以关闭此功能，或者自己使用 SQL 进行创建文章；

**Comment by Leopard-C** [comment]
1. 设置自定义文章路径为 `wordpress` 格式。

![image](https://user-images.githubusercontent.com/42399105/187158020-586aa862-22d8-4422-9305-914b8518f5f1.png)

2. 编辑文件 `{安装路径}/var/Widget/Contents/Post/Edit.php`，修改该文件的 `execute()`函数，新增`else`分支

```PHP
    /**
     * 执行函数
     *
     * @throws Exception|DbException
     */
    public function execute()
    {
        /** 必须为贡献者以上权限 */
        $this->user->pass('contributor');

        /** 获取文章内容 */
        if (!empty($this->request->cid)) {
             // .......
        }
        else {    //  <--------------- 新增 else 分支
            /* 获取文章下一个(连续)自增的slug */
            $this->slug = $this->getNextPostSlug();
            $select = $this->db->select('MAX(slug + 0) AS slug_max')
                ->from('table.contents')
                ->where('table.contents.type = \'post\'');
            //echo $select->__toString();
            $res = $this->db->fetchRow($select);
            $slug_max = $res['slug_max'];
            $this->slug = $slug_max ? (string)(intval($slug_max) + 1) : '1';
        }
    }
```

3. 撰写新文章，自动填充 `slug` 的值。

![image](https://user-images.githubusercontent.com/42399105/187162707-e9a01949-1da5-4e8e-aabd-f5b1f5135917.png)
