### ISSUE TITLE
PHP8.1.4 文章编辑侧边附件报错

### ISSUE THREAD

**Issue by Seevil** [typecho/typecho#1392]
### 1. 该问题的重现步骤是什么？
文章编辑侧边附件报错
![image](https://user-images.githubusercontent.com/7334510/162421210-c312488f-2c3f-4fca-960d-eb554eb8771e.png)

`Warning: Trying to access array offset on value of type bool in /krsay.com/var/Widget/Base/Contents.php on line 557`

编辑附件报：

![image](https://user-images.githubusercontent.com/7334510/162582633-5c160c7f-df38-4f63-a3c3-7c870499c383.png)

`Typecho\Common::mimeIconType(): Argument #1 ($mime) must be of type string, null given, called in /krsay.com/admin/media.php on line 26`

### 2. 你期待的结果是什么？实际看到的又是什么？
对早期附件兼容有问题好像，部分原始文章内容如下
```

首页截图：
![www.krsay.com_.png][3]
文章页截图：
![www.krsay.com_devops_kcptun-kcp-tcp.html.png][4]
```

另外附件type好像缺失WebP
![image](https://user-images.githubusercontent.com/7334510/162422422-d138f131-4f7f-4041-a851-c90add5fcf9a.png)

### 3. 问题出现的环境

- 数据库版本：8.0
- PHP 版本：PHP8.1.4
- Typecho 版本： 997aa60

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
你这3个附件是0kb，去数据库里看看`typecho_contents`中对应`cid`的`text`是什么

**Comment by Seevil** [comment]
> 你这3个附件是0kb，去数据库里看看`typecho_contents`中对应`cid`的`text`是什么

text 核心内容我上面有附上，这是原始内容=。=

```
<!--markdown-->>西风吹老洞庭波，一夜湘君白发多。醉后不知天在水，满船清梦压星河。

  一直想给博客换个主题一直没有动，直到前几天看到PCDOTFAN 大佬写的[ARAGAKI][1]主题  感觉很不错于但是是BITCRON 博客系统下的主题看了下是Farbox新开发的系统以前也玩过Farbox不过不怎么感冒虽然当时一度想花钱买的，后来想想很没意思就被打入冷宫了=。=
  跑远了回到正题问了下ARAGAKI作者能不能移植他很爽快的说行，那行就行呗了于是就做了这个主题。
  因为各种原因和作主题这段时间的经历和心情把移植过来的主题重命名为Fantasy 
  Fantasy 取义 清梦 源于《题龙阳县青草湖》里的`醉后不知天在水，满船清梦压星河。`二句意图用来描绘现状。

GitHub 地址：https://github.com/Seevil/fantasy

1.3.0更新 2020年8月10日
评论修复见：https://www.krsay.com/typecho/fantasy-theme-update-1-3-0.html

![fantasy.png][2]

**主题截图**

首页截图：
![www.krsay.com_.png][3]

文章页截图：
![www.krsay.com_devops_kcptun-kcp-tcp.html.png][4]

打赏：
![打赏][6]


  [1]: https://github.com/PCDotFan/Aragaki
  [2]: https://www.krsay.com/usr/uploads/2018/10/3912788798.png
  [3]: https://www.krsay.com/usr/uploads/2018/10/3106983378.png
  [4]: https://www.krsay.com/usr/uploads/2018/10/1169631520.png
  [5]: https://www.krsay.com/usr/uploads/2018/10/3886745511.png
  [6]: https://www.krsay.com/usr/uploads/2020/08/2955007666.png
```

**Comment by sy-records** [comment]
附件的cid，不是文章的

**Comment by Seevil** [comment]
> 附件的cid，不是文章的

哦哦😂

```
a:5:{s:4:"name";s:41:"www.krsay.com_devops_kcptun-kcp-tcp.html.png";s:4:"path";s:35:"/usr/uploads/2018/10/1169631520.png";s:4:"size";i:76723;s:4:"type";s:3:"png";s:4:"mime";s:9:"image/png";}
a:5:{s:4:"name";s:27:"www.krsay.com_archive.html.png";s:4:"path";s:35:"/usr/uploads/2018/10/3886745511.png";s:4:"size";i:29956;s:4:"type";s:3:"png";s:4:"mime";s:9:"image/png";}
a:5:{s:4:"name";s:15:"www.krsay.com_.png";s:4:"path";s:35:"/usr/uploads/2018/10/3106983378.png";s:4:"size";i:63578;s:4:"type";s:3:"png";s:4:"mime";s:9:"image/png";}
```

**Comment by Seevil** [comment]
管理文件里面也有错误
/admin/manage-medias.php?page=3

`Typecho\Common::mimeIconType(): Argument #1 ($mime) must be of type string, null given, called in /admin/manage-medias.php on line 69`

**Comment by sy-records** [comment]
你这个序列化数据有问题，长度不对
```
s:41:"www.krsay.com_devops_kcptun-kcp-tcp.html.png";
```
应该是
```
s:44:"www.krsay.com_devops_kcptun-kcp-tcp.html.png";
```

**Comment by Seevil** [comment]
> a:5:{s:4:"name";s:15:"www.krsay.com_.png";

不是长度 问题吧 ？这个也没多长也是有问题的，应该特殊符号的原因吧？

`a:5:{s:4:"name";s:15:"www.krsay.com_.png";`

**Comment by joyqi** [comment]
这里的序列化为何出错值得探究

**Comment by w22gb8** [comment]
> 这里的序列化为何出错值得探究

我升级后也出现了此问题，手工改过来了。

**Comment by sy-records** [comment]
应该是之前编码问题，不好复现，有什么复现方式吗？@Seevil 原来有什么特殊符号

我在 #1393 处理了下

**Comment by Seevil** [comment]
> 应该是之前编码问题，不好复现，有什么复现方式吗？@Seevil 原来有什么特殊符号
> 
> 我在 #1393 处理了下

具体我也忘记了 这应该就是原始的文件名 ，`s:44:"www.krsay.com_devops_kcptun-kcp-tcp.html.png";`
我用的chrome 浏览器自带的截图工具截图保存的文件。

![image](https://user-images.githubusercontent.com/7334510/162573142-a068b3b5-a387-486a-9376-de50a2c51873.png)

我刚刚选了一个页面截图命名规则应该是一样的

![image](https://user-images.githubusercontent.com/7334510/162573218-cbff6f6b-93c5-4919-8577-9b03c60d49d5.png)

**Comment by joyqi** [comment]
一般是因为文件中带有特殊符号，比如emoji会导致序列化后的文本存储到不支持utf8mb4的数据库里出现问题。但看起来你的文件名都是ascii字符，我怀疑之前提交的文件名里是不是有斜杠？

**Comment by sy-records** [comment]
先关闭了，感觉也是换过域名导致的序列化数据错误
