### ISSUE TITLE
有没有登录按钮改到头部右上角的简易登录插件或者修改方法，默认登录进后台好别扭

### ISSUE THREAD

**Issue by MrTlyer** [typecho/typecho#1401]
[https://ntnas.top:82/typecho](https://ntnas.top:82/typecho)

**Comment by sy-records** [comment]
前台加个弹窗，复制后台的form表单，改改样式就好了

具体实现可以百度找一下，有些主题也实现了前台登录按钮

**Comment by MrTlyer** [comment]
> 前台加个弹窗，复制后台的form表单，改改样式就好了
> 
> 具体实现可以百度找一下，有些主题也实现了前台登录按钮

已经改好了，我博客里面有修改说明
