### ISSUE TITLE
版本号是最新，但是后台概览提示是红色

### ISSUE THREAD

**Issue by jlthkf22** [typecho/typecho#1402]
1. 该问题的重现步骤是什么？
更到1.2.0进入后台

2. 你期待的结果是什么？实际看到的又是什么？
版本号最新应该是绿色提示，实际是红色
![image](https://user-images.githubusercontent.com/21102489/163510501-33c2db74-cda4-4a6f-a97b-1aceec60872c.png)

**Comment by sy-records** [comment]
Duplicate of #1354
