### ISSUE TITLE
点击前台链接或者后台登录时出现 404, not found

### ISSUE THREAD

**Issue by 4566704** [typecho/typecho#1407]
### 1. 该问题的重现步骤是什么？
宝塔面板 7.5.0
安装typecho v1.2.0正式版
官方文档太旧了，还是很多年前的 http://docs.typecho.org/faq 无法解决
### 3. 问题出现的环境

- 操作系统版本：windows 10
- Apache/NGINX 版本：nginx 1.20/1.21
- 数据库版本：mysql 5.7
- PHP 版本：7.2/7.4
- Typecho 版本：v1.2.0正式版
- 浏览器版本：google Chrome 100.0.4896.88

[//]: # (如有图片请附上截图)

**Comment by Yaklo** [comment]
试试伪静态
if (-f $request_filename/index.php){
    rewrite (.*) $1/index.php;
}
if (!-f $request_filename){
    rewrite (.*) /index.php;
}
我也是刚解决的

**Comment by 4566704** [comment]
十分感谢，问题解决了。

不得吐槽一下官方文档，还是 5-10年前的文档。还在描述php5.4

**Comment by Yaklo** [comment]
(￣▽￣)👍
