### ISSUE TITLE
版本更新提示

### ISSUE THREAD

**Issue by MBRjun** [typecho/typecho#1413]
如下图，这个版本更新提示是预期行为吗？
- 如果是，能否改为仅有可用更新才能显示？
- 如果不是，为什么会出现该问题？能否消除该提示？

![IMG_20220422_025359](https://user-images.githubusercontent.com/55020690/164533026-7598d1f8-e89c-46c1-805f-99bb5d58885e.jpg)

###  问题出现的环境

- 操作系统版本：Android 11
- Apache/NGINX 版本：Nginx 1.20.1
- 数据库版本：MySQL 8.0 
- PHP 版本：8.1
- Typecho 版本：Release 1.2
- 浏览器版本：Chrome 100

**Comment by sy-records** [comment]
Duplicate of #1354
