### ISSUE TITLE
1.1.0 更新1.2.0后后台持续显示

### ISSUE THREAD

**Issue by 5ibug** [typecho/typecho#1419]
### 1. 该问题的重现步骤是什么？
1.1.0 更新1.2.0后后台持续显示
![1111](https://user-images.githubusercontent.com/38201975/164951382-68fdf699-b82c-4730-9b5d-9bcd89e80d10.png)

### 2. 你期待的结果是什么？实际看到的又是什么？
如果是最新版应该不显示.
### 3. 问题出现的环境
1.1.0 更新1.2.0
替换admin index.php install.php方式升级

**Comment by Caleeen** [comment]
我也有这个问题

**Comment by 5ibug** [comment]
> 

提pr了. 等合并就行了.

**Comment by sy-records** [comment]
Fixed via #1356
