### ISSUE TITLE
文件管理出现500

### ISSUE THREAD

**Issue by albaz64** [typecho/typecho#1421]
我写了一篇草稿上传了图片资源但没有保存,打算去文件管理清理刚刚上传的图片(大约30个文件)
这时我发现第二页打不开会报错(这是很奇怪的事情),报错信息如下:
`Typecho\Common::mimeIconType(): Argument #1 ($mime) must be of type string, null given, called in /www/wwwroot/blueeyes/admin/manage-medias.php on line 69`
随后我认为是版本更新造成的问题,登录数据库删除刚刚的数据结果变成首页报错(不管请求为空还是page=1),手动加上如page=2又可以正常操作
![image](https://user-images.githubusercontent.com/80263760/164968970-48c81324-cbd9-4b69-9362-bed0699fe340.png)
![image](https://user-images.githubusercontent.com/80263760/164968987-62b7ccf3-a5e0-4f54-9ac9-21280718f7ec.png)
看来似乎是之前的数据影响了,但我没有动过数据库.
或许和我更新版本时是直接覆盖旧文件有关,但我不确定原因.

- 操作系统版本：宝塔7.9.0
- Apache/NGINX 版本：Nginx 1.21.4
- 数据库版本：MySQL 5.6.50
- PHP 版本：PHP 8.0
- Typecho 版本：1.2.0

**Comment by joyqi** [comment]
能否在数据库的`contents`表里找到这个附件数据的原始记录并贴上来?

**Comment by XYZ-dragon** [comment]
东西有点乱,我就导出了,这是地址:https://blueeyeswhitedragon.xyz/err.csv(至少保留到四月末)
这是前25条也就是第一页本该显示的东西.如果需要其他内容请提供邮箱地址,我服务器基本上只有一个博客,无所谓这些

**Comment by XYZ-dragon** [comment]
> 能否在数据库的`contents`表里找到这个附件数据的原始记录并贴上来?
问题仍然存在,在删库测试之后定位到是两条数据引起的.type值均为attachment,这是text的值:
a:8:{s:4:"name";s:23:"2022-02-02T07:34:29.png";s:4:"path";s:35:"/usr/uploads/2022/02/2847131964.png";s:4:"size";i:188295;s:4:"type";s:3:"png";s:4:"mime";s:9:"image/png";s:7:"isImage";b:1;s:3:"url";s:53:"https://blueeyeswhitedragon.xyz/usr/uploads/2022/02/2847131964.png";s:11:"description";s:0:"";}
a:8:{s:4:"name";s:23:"2022-02-02T07:28:37.png";s:4:"path";s:35:"/usr/uploads/2022/02/1652981963.png";s:4:"size";i:1328477;s:4:"type";s:3:"png";s:4:"mime";s:9:"image/png";s:7:"isImage";b:1;s:3:"url";s:53:"https://blueeyeswhitedragon.xyz/usr/uploads/2022/02/1652981963.png";s:11:"description";s:0:"";}
这两条数据也无法通过cid单独访问.印象里我是没有动过代码的,这两条数据长度在300左右,大约是其他文件翻倍的长度.

**Comment by vanTC** [comment]
哥，解决了么？

**Comment by XYZ-dragon** [comment]
> 哥，解决了么？

定位到问题直接删了这两条记录就好了.我也看不出到底有什么不一样

**Comment by idyes** [comment]
请检查下对应url前面的（s：字符长度），例如：
```bash
s:53:"https://blueeyeswhitedragon.xyz/usr/uploads/2022/02/1652981963.png";s:11:"description";s:0:"";
其中你的url是 https://blueeyeswhitedragon.xyz/usr/uploads/2022/02/1652981963.png
但是长度明显不是53，改成正确的即可
```

**Comment by XYZ-dragon** [comment]
> 请检查下对应url前面的（s：字符长度），例如：
> 
> ```shell
> s:53:"https://blueeyeswhitedragon.xyz/usr/uploads/2022/02/1652981963.png";s:11:"description";s:0:"";
> 其中你的url是 https://blueeyeswhitedragon.xyz/usr/uploads/2022/02/1652981963.png
> 但是长度明显不是53，改成正确的即可
> ```

可能是更换域名的时候弄的, 并且发现这个会影响性能. 原来加载后台页面需要等两秒现在可以秒开.
