### ISSUE TITLE
异步调用接口问题

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#1422]
最近制作一款评论邮件提醒插件：https://github.com/jrotty/CommentNotifier
看这个文章增加了异步回调的方式：https://joyqi.com/typecho/typecho-async-service.html
但测试发现只有偶尔会成功，大部分情况都是没触发发信的...不知道是什么原因。

使用的是typecho1.2.0版本，php7.3

**Comment by joyqi** [comment]
你可以看看服务器日志，提交评论后除了当前的POST请求外，还会有个异步请求的POST。看看是否有错误日志输出，以及你的邮件服务器是否连接顺畅。可以参考这个

https://github.com/joyqi/typecho-plugins/tree/main/Mailer

**Comment by jrotty** [comment]
好的，我好像已经有方向了，明天试试

**Comment by jrotty** [comment]
@joyqi 一直没研究明白，然后今天那默认主题测试了下，功能完全正常可以发邮件了，我想问下是不是使用ajax提交评论的情况不支持异步呢
