### ISSUE TITLE
Firefox 浏览器不能粘贴上传图片

### ISSUE THREAD

**Issue by benzBrake** [typecho/typecho#1424]
### 1. 该问题的重现步骤是什么？
使用 Firefox 编辑文章，复制图片并再编辑框里粘贴
### 2. 你期待的结果是什么？实际看到的又是什么？
粘贴以后并没有反应，看了 console 没有报错
再测试了 Edge 没有问题，粘贴可以上传图片
### 3. 问题出现的环境

- 操作系统版本：Windows 11
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：7.4
- Typecho 版本：1.2.0
- 浏览器版本：Firefox 100.0 candidates build2

Firefox：
![Firefox](https://user-images.githubusercontent.com/11323774/166109714-9da6113a-93be-497e-af6a-fe6672ab3d0d.gif)
Edge：
![Edge](https://user-images.githubusercontent.com/11323774/166109708-5c406870-27e1-488c-a1e5-773745dc63d7.gif)

**Comment by sy-records** [comment]
我用macOS的测试正常，你可以检查下你的火狐设置是不是有问题

**Comment by benzBrake** [comment]
> 

我在排障模式试过，也是这样，就是不能粘贴
刚才去重新开了个空白配置，也是不行

**Comment by benzBrake** [comment]
> 我用macOS的测试正常，你可以检查下你的火狐设置是不是有问题

我在排障模式试过，也是这样，就是不能粘贴
刚才去重新开了个空白配置，也是不行

**Comment by aotuitx** [comment]
ff确实有这问题，我也碰到过，后来换了谷歌浏览器用。

**Comment by jrotty** [comment]
测试Firefox 100.0正式版，没有这个毛病

**Comment by benzBrake** [comment]
不知道是设么原因，目前104 每夜版可以用了
