### ISSUE TITLE
安装报语法错误

### ISSUE THREAD

**Issue by W01fh4cker** [typecho/typecho#1432]
### 1. 该问题的重现步骤是什么？
解压官网源码到服务器，然后打开www.example.com/install.php
### 2. 你期待的结果是什么？实际看到的又是什么？
期待是正常安装，结果出现：Parse error: syntax error, unexpected ':', expecting '{' in /www/wwwroot/www.example.com/install.php on line 31
### 3. 问题出现的环境

- 操作系统版本：ubuntu 20.04
- Apache/NGINX 版本：nginx1.20.1
- 数据库版本：mysql5.5.62
- PHP 版本：5.6
- Typecho 版本：1.2.0
- 浏览器版本：Microsoft Edge | 101.0.1210.39 (正式版本) (64 位)

[//]: # (如有图片请附上截图)
报错图：
![image](https://user-images.githubusercontent.com/101872898/167282467-f67f1ee6-0b73-4e94-97f2-01def77ab218.png)
  
我的文件截图：  
![image](https://user-images.githubusercontent.com/101872898/167282483-152fbb70-f924-4b24-87f3-4b6836902ff9.png)

**Comment by W01fh4cker** [comment]
好尴尬，自己没看仔细，我的问题，得要php7.2的

**Comment by joyqi** [comment]
是的，新版至少需要7.2，请尽快升级
