### ISSUE TITLE
没有填写站点说明的地方

### ISSUE THREAD

**Issue by xnanw** [typecho/typecho#1437]
### 1. 该问题的重现步骤是什么？

在后台基本设置那里填写站点名称以后，没有填写站点说明的地方

### 2. 你期待的结果是什么？实际看到的又是什么？

希望可以像WordPress一样能够填写站点说明，实际是没有的。个人理解的站点说明是网站首页的副标题，不是指的网站描述。
如果直接在站点名称那里填写 Your website title - your website subtitle ，因为有些主题会直接在首页输出网站标题，标题就会变得特别长，样式也破坏了。只想在首页显示 Your website title，而不是Your website title - your website subtitle，就会变得有点困难。所以希望可以分开填写，这样主题只用在首页输出 Your website title 作为首页标题就可以了。

### 3. 问题出现的环境

任何环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

**Comment by sy-records** [comment]
这可以由主题来提供配置项

**Comment by xnanw** [comment]
但是在分类页，想要显示的是 Your category - your website title 而不是Your category - your website title - your website - subtitle，也许我说的不是很明白，我的意思不是主题可以配置一个仅仅给用户看的首页标题，而是html中可以分开配置，现在的结果：首页显示 title ，分类页显示 category -  title，期望的结果：首页显示 title - subtitle 。分类页显示 category -  title ，这样我不知道主题可不可以配置。

**Comment by sy-records** [comment]
这些都是在主题中控制的 https://github.com/typecho/typecho/blob/7068b2bbe1a43fdce6672e2684f2aa034838ffaf/usr/themes/default/header.php#L8-L13

**Comment by xnanw** [comment]
是不是可以在主题中给首页添加一个配置副标题的选项？，然后html中是<title>网站名称 - 主题配置项设置的副标题<title>。不好意思，我真的不是很懂。

**Comment by xnanw** [comment]
但是我刚刚看了一下我使用的主题header.php好像是全局配置，并不能单独只让首页显示<title>网站标题 - 网站副标题<title>，其他页面，如分类显示<title>分类下的文章 - 网站标题<title>

**Comment by xnanw** [comment]
所以这里其实还要加一个判断是吗？
如果不是首页则输出
```
<title><?php $this->archiveTitle([ 
         'category' => _t('分类 %s 下的文章'), 
         'search'   => _t('包含关键字 %s 的文章'), 
         'tag'      => _t('标签 %s 下的文章'), 
         'author'   => _t('%s 发布的文章') 
     ], '', ' - '); ?><?php $this->options->title(); ?></title>
```
如果是首页则输出
```
<title><?php $this->options->title(); ?> - 第几页 - 网站副标题<title>
