### ISSUE TITLE
xmlrpc新建分类报500

### ISSUE THREAD

**Issue by Sundae97** [typecho/typecho#1440]
使用xmlrpc调用新建category方法时返回500

- 操作系统版本：centos 7
- PHP 版本：php7.2
- Typecho 版本：1.2.0

**Comment by DengJackNo1** [comment]
when i use python3 xmlrpc api to create a new category, i found a error.finally i get a  500 Internal Server Error.
for example:

```python
# !/usr/bin/python3

from xmlrpc.client import ServerProxy
url = 'http://192.168.0.125:7778/typecho/action/xmlrpc'
s = ServerProxy(url)
category = {
    'name': 'test',
    'slug':'test',
    'description':'description',
}
ret = s.wp.newCategory(1, userName, password,category)
print(ret)
```
the result is "xmlrpc.client.ProtocolError: <ProtocolError for 192.168.0.125:7778/typecho/action/xmlrpc: 500 Internal Server Error>"

i do not know how to do

**Comment by joyqi** [comment]
能否找到服务端的PHP错误日志

**Comment by DengJackNo1** [comment]
PHP 7.2.10 (cli) (built: Sep 17 2018 09:40:17) ( NTS )
没有发现php error.log

**Comment by Sundae97** [comment]
https://github.com/typecho/typecho/issues/1340 这个issue也是同样的问题
