### ISSUE TITLE
无法安装typecho

### ISSUE THREAD

**Issue by Haocen2004** [typecho/typecho#1445]
`Fatal error: Declaration of Typecho\Db\Adapter\Pdo::fetchObject($resource): ?Typecho\Db\Adapter\object must be compatible with Typecho\Db\Adapter::fetchObject($resource): ?Typecho\Db\object in /www/wwwroot/网站目录/var/Typecho/Db/Adapter/Pdo.php on line 18`

issue模板跑没了（
腾讯云轻量 宝塔预制镜像
php 7.1 mysql 5.7 nginx 1.21
计划安装 typecho 1.2.0

**Comment by sy-records** [comment]
1.2 版本依赖PHP7.2+了

**Comment by Haocen2004** [comment]
那劳烦您更新一下文档，那里还是php5
