### ISSUE TITLE
使用蜘蛛日志插件报错

### ISSUE THREAD

**Issue by FynnFbc** [typecho/typecho#1446]
### 1. 该问题的重现步骤是什么？
打开蜘蛛日志查看，页面最上面显示报错
Warning: Constant __TYPECHO_ADMIN__ already defined in /www/wwwroot/blog/admin/common.php on line 6
### 2. 你期待的结果是什么？实际看到的又是什么？
希望能改善
### 3. 问题出现的环境

- 操作系统版本：Centos 7.6
- Apache/NGINX 版本：nginx1.20
- 数据库版本：mysql 5.7
- PHP 版本：8.1
- Typecho 版本：1.2.0
- 浏览器版本：chrome 101

[//]: # (如有图片请附上截图)

**Comment by FynnFbc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "typecho/typecho"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [typecho/typecho] 使用蜘蛛日志插件报错 (Issue #1446)





 
你检查下是不是插件里定义了TYPECHO_ADMIN
 
插件没有定义这个

你可以看下附件

**Comment by sy-records** [comment]
看不到附件，你可以把插件地址之类发出来

**Comment by FynnFbc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "typecho/typecho"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [typecho/typecho] 使用蜘蛛日志插件报错 (Issue #1446)





 
看不到附件，你可以把插件地址之类发出来
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.

插件下载地址

https://plugins.typecho.me/download/392.htmlMessage ID: ***@***.***&gt;

**Comment by sy-records** [comment]
插件里面`include 'common.php'`改成`include_once`吧

**Comment by FynnFbc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "typecho/typecho"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [typecho/typecho] 使用蜘蛛日志插件报错 (Issue #1446)





 
插件里面include 'common.php'改成include_once吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.




已解决问题，非常感谢Message ID: ***@***.***&gt;

**Comment by FynnFbc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "typecho/typecho"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [typecho/typecho] 使用蜘蛛日志插件报错 (Issue #1446)





 
插件里面include 'common.php'改成include_once吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.






这个属性在哪里修改，取消colorMessage ID: ***@***.***&gt;
