### ISSUE TITLE
使用主题报错

### ISSUE THREAD

**Issue by FynnFbc** [typecho/typecho#1447]
### 1. 该问题的重现步骤是什么？
设置主题后，后台地址出现如下错误
Warning: Constant __TYPECHO_ADMIN__ already defined in /www/wwwroot/blog/admin/common.php on line 6

Warning: Undefined array key 1 in /www/wwwroot/blog/admin/common.php on line 31
### 2. 你期待的结果是什么？实际看到的又是什么？
希望能改善
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
主题问题，检查是否又加载了common.php...
