### ISSUE TITLE
我觉得很有必要加个缓存和gzip的功能

### ISSUE THREAD

**Issue by bluesky0341** [typecho/typecho#1453]
你好
我觉得很有必要加个缓存和gzip的功能
这样网站的打开速度至少比以前快一倍！
而且很多cms都有这个功能
速度是最重要的！

**Comment by dyedd** [comment]
开启Typecho的gzip：，只要在根目录下的index.php文件加入以下代码即可。

```
/** 开启gzip压缩 */  
ob_start('ob_gzhandler
```
其它缓存开启方式网上很多教程

**Comment by joyqi** [comment]
我们不会在主要代码中加入缓存和gzip逻辑，缓存可以通过插件或者系统实现，gzip只需要你在apache或者nginx设置中打开即可。

**Comment by bluesky0341** [comment]
那请问，缓存有什么插件
