### ISSUE TITLE
存在JavaScript注入问题

### ISSUE THREAD

**Issue by HYM740** [typecho/typecho#1456]
### 1. 该问题的重现步骤是什么？
撰写新文章内写入 JavaScript 脚本，例如
```html
<script>alert("!");</script>
```
### 2. 你期待的结果是什么？实际看到的又是什么？
期待结果：将特殊标签进行转义处理。
实际结果：用户写入的JavaScript被执行
### 3. 问题出现的环境

- 操作系统版本：openSuse Leap 15.3
- Docker镜像：joyqi/typecho:nightly-php7.4-apache
- 浏览器版本：Microsoft Edge 102.0.1245.33

![image](https://user-images.githubusercontent.com/71169815/172783184-29eb0ea7-83e6-4956-a308-84394b66c65c.png)
![image](https://user-images.githubusercontent.com/71169815/172783305-d853b1e9-c221-4253-9732-5613df918f4b.png)

**Comment by joyqi** [comment]
我们并不会对用户自己的文章做xss过滤，有的用户就是想在里面嵌入一些html代码，他自己有完全的控制权。只有第三方的输入，比如评论等才会处理xss。

**Comment by KawaiiZapic** [comment]
更新到1.2.0之后所有文章内的style和script标签都被过滤…  
没找到在哪里关闭, 我写的很多代码都被橄榄了
