### ISSUE TITLE
更新typecho1.2后，后台出现红色提示框

### ISSUE THREAD

**Issue by 201280097** [typecho/typecho#1463]
### 1. 该问题的重现步骤是什么？
官网下载安装包，上传覆盖
### 2. 你期待的结果是什么？实际看到的又是什么？
修复后台提示
### 3. 问题出现的环境

- 操作系统版本：CentOS 8.0
- Apache/NGINX 版本：nginx1.18
- 数据库版本：mysql5.6.50
- PHP 版本：7.3
- Typecho 版本：1.2.0
- 浏览器版本：Chrome

![image](https://user-images.githubusercontent.com/64906069/173727654-6a276991-4d2b-47ce-8c65-9c400635b37a.png)

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
Duplicate of #1354
已经在开发版修复
