### ISSUE TITLE
是否存在xss？

### ISSUE THREAD

**Issue by BoyChai** [typecho/typecho#1466]
### 1. 该问题的重现步骤是什么？
创建相关SQL文章，提交之后出现
Argument 1 passed to Typecho\Widget::allocWithAlias() must be of the type string, null given, called in /app/var/Widget/Base/Contents.php on line 822
### 2. 你期待的结果是什么？实际看到的又是什么？
希望提交文章之后不会出问题
### 3. 问题出现的环境

- 操作系统版本：centos8.5
- Apache/NGINX 版本： Apache/2.4.51 (Debian)
- 数据库版本：8.0.27 
- PHP 版本：7.4.27
- Typecho 版本：1.2.0
- 浏览器版本：Google Chrome
![E5~4C$G 7D(A86LLLDZGD](https://user-images.githubusercontent.com/88495409/173983749-898b0594-7f8c-4274-b591-5bbf5439e5c1.png)
在数据库里单独删除掉这篇文章会恢复正常
[//]: # (如有图片请附上截图)

**Comment by BoyChai** [comment]
用的容器部署

**Comment by joyqi** [comment]
请用开发版试试

**Comment by BoyChai** [comment]
> 

依旧存在问题

**Comment by joyqi** [comment]
在`config.inc.php`文件里加入如下内容，然后重复上面的步骤，把具体的报错信息贴上来

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by BoyChai** [comment]
> 
Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /app/var/Widget/Base/Contents.php on line 938
TypeError: Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /app/var/Widget/Base/Contents.php on line 938 and defined in /app/var/Utils/AutoP.php:121
Stack trace:
#0 /app/var/Widget/Base/Contents.php(938): Utils\AutoP->parse(NULL)
#1 /app/var/Widget/Base/Contents.php(895): Widget\Base\Contents->autoP(NULL)
#2 /app/var/Typecho/Widget.php(395): Widget\Base\Contents->___excerpt()
#3 /app/var/Widget/Service.php(164): Typecho\Widget->__get('excerpt')
#4 /app/var/Widget/Contents/Post/Edit.php(292): Widget\Service->sendPing(Object(Widget\Contents\Post\Edit), Array)
#5 /app/var/Widget/Contents/Post/Edit.php(979): Widget\Contents\Post\Edit->writePost()
#6 /app/var/Widget/Action.php(71): Widget\Contents\Post\Edit->action()
#7 /app/var/Typecho/Widget.php(155): Widget\Action->execute()
#8 /app/var/Typecho/Router.php(96): Typecho\Widget::widget('\\Widget\\Action', NULL, Array)
#9 /app/index.php(23): Typecho\Router::dispatch()
#10 {main}

**Comment by BoyChai** [comment]
升级后打开分类页面也出现问题 报错信息如下
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'BoyChai_Blog.typecho_contents.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Typecho\Db\Adapter\SQLException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'BoyChai_Blog.typecho_contents.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /app/var/Typecho/Db/Adapter/Pdo.php:111
Stack trace:
#0 /app/var/Typecho/Db.php(391): Typecho\Db\Adapter\Pdo->query('SELECT typecho_...', Object(PDO), 1, 'SELECT', 'typecho_content...')
#1 /app/var/Typecho/Db.php(424): Typecho\Db->query(Object(Typecho\Db\Query))
#2 /app/var/Widget/Archive.php(1539): Typecho\Db->fetchAll(Object(Typecho\Db\Query), Array)
#3 /app/var/Widget/Archive.php(763): Widget\Archive->query(Object(Typecho\Db\Query))
#4 /app/var/Typecho/Widget.php(155): Widget\Archive->execute()
#5 /app/var/Typecho/Router.php(96): Typecho\Widget::widget('\\Widget\\Archive', NULL, Array)
#6 /app/index.php(23): Typecho\Router::dispatch()
#7 {main}

**Comment by BoyChai** [comment]
中文的分类缩略名

**Comment by joyqi** [comment]
第二个问题你需要新开一个issue讨论

**Comment by BoyChai** [comment]
> 第二个问题你需要新开一个issue讨论

好的

**Comment by joyqi** [comment]
我并没有复现这个问题，是只有在特定内容的时候才会出问题么？

**Comment by BoyChai** [comment]
> 我并没有复现这个问题，是只有在特定内容的时候才会出问题么？

对的

**Comment by joyqi** [comment]
能否把你的内容贴上来

**Comment by BoyChai** [comment]
`
# SQL分类

| 类别   | 全称                         | 概述                          |
| ---- | -------------------------- | --------------------------- |
| DDL  | Data Definition Language   | 数据定义语言，用来定义数据库对象(数据库，表，字段)  |
| DML  | Data Manipulation Language | 数据操作语言，用来对数据库表中的数据进行删增改查    |
| DQL  | Data Query Language        | 数据查询语言，用来查询数据库中表的记录         |
| DCL  | Data Control Language      | 数据控制语言，用来创建数据库用户，控制数据库的访问权限 |

# DDL

## 数据库操作

### 查询

- 查询所有数据库

```
SHOW DATABASES;
```



- 查询当前数据库

```
SELECT  DATABASE();
```

### 创建

```
CREATE DATABASE [ IF NOT EXISTS ] 数据库名称 [ DEFAULT CHARSET 字符集 ] [ COLLATE 排序规则 ];
```

使用时可以在数据库名称前面加入"IF NOT EXISTS"，意为当数据库不存在则创建否则不作为。

### 删除

```
DROP DATABASE [ IF EXISTS ] 数据库名称;
```

使用时可以在数据库名称前面加入"IF EXISTS"，意为当数据库存在则删除否则不作为。

### 使用

```
USE 数据库名称;
```


`

**Comment by BoyChai** [comment]
> 能否把你的内容贴上来

我发现不止是因为这个文章，我刚才随便打了点自也出问题了
信息如下
Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /app/var/Widget/Base/Contents.php on line 938
TypeError: Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /app/var/Widget/Base/Contents.php on line 938 and defined in /app/var/Utils/AutoP.php:121
Stack trace:
#0 /app/var/Widget/Base/Contents.php(938): Utils\AutoP->parse(NULL)
#1 /app/var/Widget/Base/Contents.php(895): Widget\Base\Contents->autoP(NULL)
#2 /app/var/Typecho/Widget.php(395): Widget\Base\Contents->___excerpt()
#3 /app/var/Widget/Service.php(164): Typecho\Widget->__get('excerpt')
#4 /app/var/Widget/Contents/Post/Edit.php(292): Widget\Service->sendPing(Object(Widget\Contents\Post\Edit), Array)
#5 /app/var/Widget/Contents/Post/Edit.php(979): Widget\Contents\Post\Edit->writePost()
#6 /app/var/Widget/Action.php(71): Widget\Contents\Post\Edit->action()
#7 /app/var/Typecho/Widget.php(155): Widget\Action->execute()
#8 /app/var/Typecho/Router.php(96): Typecho\Widget::widget('\\Widget\\Action', NULL, Array)
#9 /app/index.php(23): Typecho\Router::dispatch()
#10 {main}

**Comment by BoyChai** [comment]
似乎找到了原因 我在前几天把数据库版本从5.7升级到了8.0所以回导致这个问题我回去开一个新的issue
