### ISSUE TITLE
分类缩略名出现问题

### ISSUE THREAD

**Issue by BoyChai** [typecho/typecho#1467]
### 1. 该问题的重现步骤是什么？
升级为开发版本之后使用中文分类的缩略名出现问题

### 2. 你期待的结果是什么？实际看到的又是什么？
正常访问

### 3. 问题出现的环境

- 操作系统版本：centos8.5
- Apache/NGINX 版本：Apache/2.4.51 (Debian)
- 数据库版本：8.0.27
- PHP 版本：7.4.27
- Typecho 版本：1.2.0
- 浏览器版本：Google Chrome

[//]: # (如有图片请附上截图)
打开报错信息为
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'BoyChai_Blog.typecho_contents.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Typecho\Db\Adapter\SQLException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'BoyChai_Blog.typecho_contents.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /app/var/Typecho/Db/Adapter/Pdo.php:111
Stack trace:
#0 /app/var/Typecho/Db.php(391): Typecho\Db\Adapter\Pdo->query('SELECT typecho_...', Object(PDO), 1, 'SELECT', 'typecho_content...')
#1 /app/var/Typecho/Db.php(424): Typecho\Db->query(Object(Typecho\Db\Query))
#2 /app/var/Widget/Archive.php(1539): Typecho\Db->fetchAll(Object(Typecho\Db\Query), Array)
#3 /app/var/Widget/Archive.php(763): Widget\Archive->query(Object(Typecho\Db\Query))
#4 /app/var/Typecho/Widget.php(155): Widget\Archive->execute()
#5 /app/var/Typecho/Router.php(96): Typecho\Widget::widget('\\Widget\\Archive', NULL, Array)
#6 /app/index.php(23): Typecho\Router::dispatch()
#7 {main}

**Comment by BoyChai** [comment]
容器环境部署

**Comment by BoyChai** [comment]
不仅仅是中文，英文也不行报错如下
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'BoyChai_Blog.typecho_contents.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Typecho\Db\Adapter\SQLException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'BoyChai_Blog.typecho_contents.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /app/var/Typecho/Db/Adapter/Pdo.php:111
Stack trace:
#0 /app/var/Typecho/Db.php(391): Typecho\Db\Adapter\Pdo->query('SELECT typecho_...', Object(PDO), 1, 'SELECT', 'typecho_content...')
#1 /app/var/Typecho/Db.php(424): Typecho\Db->query(Object(Typecho\Db\Query))
#2 /app/var/Widget/Archive.php(1539): Typecho\Db->fetchAll(Object(Typecho\Db\Query), Array)
#3 /app/var/Widget/Archive.php(763): Widget\Archive->query(Object(Typecho\Db\Query))
#4 /app/var/Typecho/Widget.php(155): Widget\Archive->execute()
#5 /app/var/Typecho/Router.php(96): Typecho\Widget::widget('\\Widget\\Archive', NULL, Array)
#6 /app/index.php(23): Typecho\Router::dispatch()
#7 {main}
分类不能管理不能删除

**Comment by joyqi** [comment]
这个问题的主要原因是你的mysql配置限制了`GROUP BY`操作，在 Mysql 5.7.5 之后，默认打开了这个 `sql_mode=only_full_group_by`。你需要把它关掉即可。

**Comment by BoyChai** [comment]
> 这个问题的主要原因是你的mysql配置限制了`GROUP BY`操作，在 Mysql 5.7.5 之后，默认打开了这个 `sql_mode=only_full_group_by`。你需要把它关掉即可。
关闭之后可以打开页面了但是依旧不能进行管理分类，点击这里会出现任何菜单
![image](https://user-images.githubusercontent.com/88495409/173992140-5cba841f-4765-42e6-bee0-b79a4ad3f38e.png)

**Comment by joyqi** [comment]
打开浏览器调试窗口，看看有没有js报错

**Comment by BoyChai** [comment]
![image](https://user-images.githubusercontent.com/88495409/173993766-b3bcf9f2-4a75-4a1c-a5b3-d8d71e64190d.png)
没有任何错误

**Comment by joyqi** [comment]
点开以后啥样？

**Comment by BoyChai** [comment]
> 点开以后啥样？

没有任何变化

**Comment by BoyChai** [comment]
> 点开以后啥样？

我发现不仅仅是这个文章的问题 刚才我随便打了几个字符也这样
