### ISSUE TITLE
增加表格的支持

### ISSUE THREAD

**Issue by collinsqq** [typecho/typecho#1470]
### 2.我是一个普通站长，平时喜欢整理资料，需要用到表格，虽有第三方插件，若作者停更也会出现很多大的麻烦。然HTML5用起来也显得非常杂乱。不知道作者能否在新版本当中在编辑页面默认插入表格功能。

**Comment by sy-records** [comment]
markdown 语法去写表格不就可以？

**Comment by gxusb** [comment]
> ### 1. 新版本增加对表格的支持
> ### 2.我是一个普通站长，平时喜欢整理资料，需要用到表格，虽有第三方插件，若作者停更也会出现很多大的麻烦。然HTML5用起来也显得非常杂乱。不知道作者能否在新版本当中在编辑页面默认插入表格功能。

markdown 语法不是很简单吗

**Comment by xnanw** [comment]
> markdown 语法去写表格不就可以？

#1465 新版本MarkDown 使用反斜杠没有正常转义
