### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sbmatch** [typecho/typecho#1472]
### 1. 该问题的重现步骤是什么？
typecho配置文件中启用https  ----> nginx配置ssl  ------> 新增文章  ----->  500异常
### 2. 你期待的结果是什么？实际看到的又是什么？
我期待成功发布文章且没有任何报错，实际看到了 500 ： SSL certificate problem: unable to get local issuer certificate

### 3. 问题出现的环境

- 操作系统版本：win10
- Apache/NGINX 版本：nginx-1.20.2
- 数据库版本：MariaDB 10.9
- PHP 版本： 8.1.6
- Typecho 版本：1.2
- 浏览器版本：103.0.1264.44 (正式版本) (64 位)

[//]: # (如有图片请附上截图)
url:   [https://qiniu.mpcloud.top/01.png](https://qiniu.mpcloud.top/01.png)

**Comment by sy-records** [comment]
php 需要补一下ca证书

**Comment by sbmatch** [comment]
> php 需要补一下ca证书

![解决了，感谢您的解答](https://qiniu.mpcloud.top/34567887654.png)
