### ISSUE TITLE
多级分类URL问题

### ISSUE THREAD

**Issue by xh8039** [typecho/typecho#1473]
### 3. 服务器运行环境

- 操作系统版本：null
- Apache/NGINX 版本：null
- 数据库版本：8.1
- PHP 版本：7.4
- Typecho 版本：1.20
- 浏览器版本：null

![image](https://user-images.githubusercontent.com/89853736/177136514-d9c5c513-7332-409e-9621-40442fd718a6.png)

**Comment by fenbox** [comment]
看起来已经解决了
