### ISSUE TITLE
增加个人说明支持

### ISSUE THREAD

**Issue by xnanw** [typecho/typecho#1477]
### 1. 该问题的重现步骤是什么？

后台登录 - 个人设置 - 个人资料 - 个人说明

### 2. 你期待的结果是什么？实际看到的又是什么？

我期待在个人资料这里可以添加个人说明，前台可以在文章作者昵称下方显示。实际看到不能添加个人说明，虽然在主题设置中也可以添加，但是主题只能添加博主的，不能添加编辑或贡献者的。

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：7.3
- Typecho 版本：1.2
- 浏览器版本：

![未标题-1](https://user-images.githubusercontent.com/69662838/178344691-6e45c48d-d615-4500-b940-35ba0cb50fee.png)

**Comment by kecrily** [comment]
这取决于主题是否调用了此字段的接口。

**Comment by ScarletDor** [comment]
支持！我也希望添加这一字段，不同用户可以有不同描述文字。

**Comment by sy-records** [comment]
可以使用插件来扩展这里。

https://github.com/typecho/typecho/blob/3caebb3b20da3232ad5592b257d4825de2373ab8/admin/profile.php#L50

**Comment by ScarletDor** [comment]
> 可以使用插件来扩展这里。
> 
> https://github.com/typecho/typecho/blob/3caebb3b20da3232ad5592b257d4825de2373ab8/admin/profile.php#L50

意思是1.3更新了么qaq

**Comment by sy-records** [comment]
之前就有哦

**Comment by ScarletDor** [comment]
> 之前就有哦

原来又是隐藏功能！别隐藏了快放开吧qaq
