### ISSUE TITLE
1.2版本出现后台与前台不能同时登陆

### ISSUE THREAD

**Issue by beyondtop** [typecho/typecho#1482]
### 1. 该问题的重现步骤是什么？
登陆后台，只要在前台的文章页面刷新，前台就已管理员身份登陆，后台就会自动退出，两者不能共存。
### 2. 你期待的结果是什么？实际看到的又是什么？
期待后台登陆后，前台刷新，后台不会自动退出
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：NGINX
- 数据库版本：5.6.5
- PHP 版本：7.4
- Typecho 版本：1.2
- 浏览器版本：edge

[//]: # (如有图片请附上截图)

**Comment by fenbox** [comment]
未复现
