### ISSUE TITLE
emoji表情导致文章发布/保存草稿内容缺失

### ISSUE THREAD

**Issue by inwinter04** [typecho/typecho#1486]
### 1. 该问题的重现步骤是什么？
使用windows部分emoji或手机部分emoji会导致emoji后文章内容在文章发布/保存草稿后全部丢失。具体请见视频演示

### 2. 你期待的结果是什么？实际看到的又是什么？
希望emoji表情能够加入到文章当中。

漏洞分析: 疑似提交文章后typecho将文章内容传入到Mysql数据中，由于数据库不兼容emoji而导致后面文本内容丢失。
修复思路: 可以考虑对文章进行转义后再传入数据库中。转义为纯文本类型（类似于QQ等应用的emoji表情）

### 3. 问题出现的环境

- 操作系统版本：与问题无关
- NGINX 版本：与问题无关
- 数据库版本：5.5.67-MariaDB - MariaDB Server
- PHP 版本：PHP72
- Typecho 版本：1.2
- 浏览器版本: 与问题无关

[//]: # (如有图片请附上截图)
漏洞复现视频: https://pan.iamdt.cn/zh-CN/%E5%85%B6%E4%BB%96%E7%9B%AE%E5%BD%95/Typecho%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0%E6%BC%94%E7%A4%BA.mp4

**Comment by relaxcn** [comment]
一直都有这个问题，我之前使用旧版本也会这样子。。。

所以我现在用 word press😎

**Comment by dyedd** [comment]
数据库编码是否为utf8mb4...utf8并不支持emoji，很早之前就有解决方案了
