### ISSUE TITLE
无法保存

### ISSUE THREAD

**Issue by lghbeta** [typecho/typecho#1487]
### 1. 该问题的重现步骤是什么？

没找到规律

### 2. 你期待的结果是什么？实际看到的又是什么？

修改文章后点发布并没有更新内容，先预览再发布正常

### 3. 问题出现的环境

- 操作系统版本：Linux
- Apache/NGINX 版本：2.4
- 数据库版本：mysql
- PHP 版本：7.3
- Typecho 版本：1.2
- 浏览器版本：chrome

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
缺少信息。可以打开debug模式看看有无错误信息。
