### ISSUE TITLE
后台一直有个提示红框

### ISSUE THREAD

**Issue by 201280097** [typecho/typecho#1488]
### 1. 该问题的重现步骤是什么？
后台一直有个提示红框

![image](https://user-images.githubusercontent.com/64906069/183242593-91113ff8-9b19-4dc3-b687-cf406982534d.png)

### 2. 你期待的结果是什么？实际看到的又是什么？
去除
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Nginx 1.18.0
- 数据库版本：MySQL 5.6.50
- PHP 版本：7.3
- Typecho 版本：1.2.0
- 浏览器版本：QQ浏览器11.0

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
Duplicate of https://github.com/typecho/typecho/issues/1354
已经在开发版修复。
