### ISSUE TITLE
希望首页加密文章添加不同class

### ISSUE THREAD

**Issue by lqdahv** [typecho/typecho#1490]
### 1. 该问题的重现步骤是什么？
加密文章
### 2. 你期待的结果是什么？实际看到的又是什么？
加密文章首页的a标签跟未加密的class属性相同，请求添加一个额外class给加密的a标签，用于pjax把加密文章排除
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by fenbox** [comment]
主题里直接用判断添加即可

```
<?php if ($this->hidden); ?>
    // 已加密
<?php endif; ?>
```
