### ISSUE TITLE
关于可以进后台而首页白屏的问题

### ISSUE THREAD

**Issue by Dantezcx** [typecho/typecho#1494]
### 1. 该问题的重现步骤是什么？
安装完成之后可以进后台没有任何问题，但是首页白屏
### 2. 你期待的结果是什么？实际看到的又是什么？
![image](https://user-images.githubusercontent.com/27039451/188285556-0859eb3a-5026-4b1e-af11-6251200c7f05.png)
![image](https://user-images.githubusercontent.com/27039451/188285564-b9672c86-43d9-4939-aa58-b4700393da25.png)

**Comment by sy-records** [comment]
检查PHP版本是否 >= 7.2，做好备份恢复默认主题试试。

**Comment by gch116620** [comment]
> 检查PHP版本是否 >= 7.2，做好备份恢复默认主题试试。

检查php版本是 7.3.31 ，已备份，请问通过什么方式恢复默认主题？

**Comment by sy-records** [comment]
后台切换主题。也有可能是一些插件的影响。

在config.inc.php文件里加入如下内容，查看有没有报错
```
define('__TYPECHO_DEBUG__', true);
```

**Comment by gch116620** [comment]
> 后台切换主题。也有可能是一些插件的影响。
> 
> 在config.inc.php文件里加入如下内容，查看有没有报错
> 
> ```
> define('__TYPECHO_DEBUG__', true);
> ```
加了代码后，打开前端页面控制台无error，查看dom节点，发现body标签下没有任何内容，Network下只有favicon的记录，并且favicon查找失败，报错如下

`Path '/favicon.ico' not found
Typecho_Router_Exception: Path '/favicon.ico' not found in /www/wwwroot/test.lnfuri.com/var/Typecho/Router.php:155
Stack trace:
#0 /www/wwwroot/test.lnfuri.com/index.php(23): Typecho_Router::dispatch()
#1 {main}`

您看能否联系您git上的邮箱，我们有偿请您协助解决下呢？

**Comment by sy-records** [comment]
加我微信`ob_start`帮你看看吧

**Comment by gch116620** [comment]
> ob_start
好的 我记录下来了 您可以删除这条回复 避免个人信息泄露

**Comment by sy-records** [comment]
没有正确升级版本导致的，请参考文档进行升级。

**Comment by Goooooooooood** [comment]
同样的问题，管理后台能进，其他页面空白。

php版本满足，php插件满足，7.2以上版本换了好几个呢。照着官网提示操作升级，进入后台并没有“完成升级”的按钮。禁用所有插件，切换主题并不能解决。

先去官网论坛看了下，不止一个人遇到这个问题，并没有答案。来这边碰碰运气，还是没有答案。

v1.2刚出来就升级了，当时就是这个问题，搞不定就回退了。今天又来试试，看来还是只能回退啦。

如果有大佬解决了，烦请指点一下。

**Comment by Goooooooooood** [comment]
同样的问题。

折腾了半天才发现，禁用第三方主题是没用的，得删除，删了就好了。

希望对后来者有帮助。
