### ISSUE TITLE
Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /public_html/www/var/Widget/Base/Contents.php on line 938

### ISSUE THREAD

**Issue by aiwou** [typecho/typecho#1495]
### 1. 该问题的重现步骤是什么？
新建文章或页面出现Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /public_html/www/var/Widget/Base/Contents.php on line 938
但是文章内容又是创建了的，就是跳转不回来

### 2. 你期待的结果是什么？实际看到的又是什么？
我是小白希望得到大神指点
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：postgresql14.6
- PHP 版本：7.4
- Typecho 版本：1.2
- 浏览器版本：

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/23261373/191153793-40bf22fb-0719-43de-8c60-dd326ca4fb1c.png)

**Comment by sy-records** [comment]
你新建或者编辑时，有内容吗

**Comment by aiwou** [comment]
有内容

**Comment by aiwou** [comment]
有内容，文章也是创建了的，标签没有创建成功。


---Original---
From: ***@***.***&gt;
Date: Wed, Sep 21, 2022 06:33 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [typecho/typecho] Argument 1 passed to Utils\AutoP::parse() mustbe of the type string, null given, called in/public_html/www/var/Widget/Base/Contents.php on line 938 (Issue #1495)




 
你新建或者编辑时，有内容吗
 
&mdash;
