### ISSUE TITLE
php8.1以及更新的版本在遇到htmlspecialchars函数时会出现问题

### ISSUE THREAD

**Issue by xcmm** [typecho/typecho#1497]
问题出现在标签页，就是xxx.com/tag/xxxx这种格式的页面。应该是兼容性问题

**Comment by sy-records** [comment]
使用开发版试试

**Comment by joyqi** [comment]
具体是什么问题呢？

**Comment by luoxialuo** [comment]
> 问题出现在标签页，就是xxx.com/tag/xxxx这种格式的页面。应该是兼容性问题

会出现如下的错误
![image](https://user-images.githubusercontent.com/34562325/206341946-23d5b359-09d9-4684-9dfd-70104d482591.png)
原因是：PHP 8.1不赞成将 null 作为参数传递给许多函数，如“htmlspecalchars”和“rim”等函数了，其中null不再被静默地转换为空字符串，所以在出现问题的地方给参数添加一个三元表达式即可，如下图所示
![image](https://user-images.githubusercontent.com/34562325/206342673-7e0f0270-8ceb-4b3d-ad6c-20f170ea84cd.png)
建议typcho在下一版本中修复此问题

**Comment by sy-records** [comment]
@luoxialuo 你说的这个修复过了 https://github.com/typecho/typecho/commit/88c3bfe13fea7de60334502dd3efee33cb5ea14a

**Comment by Seevil** [comment]
> @luoxialuo 你说的这个修复过了 [88c3bfe](https://github.com/typecho/typecho/commit/88c3bfe13fea7de60334502dd3efee33cb5ea14a)

/var/Typecho/Feed.php on line 367
/var/Typecho/Feed.php on line 297
/var/Typecho/Feed.php on line 221
大佬 Feed.php 文件也有这个错误 PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1
