### ISSUE TITLE
设置伪静态后，后台无法打开404

### ISSUE THREAD

**Issue by nibazshab** [typecho/typecho#1499]
### 1. 该问题的重现步骤是什么？

- 在 nginx 配置中添加伪静态代码
```s
if (-f $request_filename/index.php){
  rewrite (.) $1/index.php;
}
if (!-f $request_filename){
  rewrite (.) /index.php;
}
```
- 在后台强制启用地址重写功能

### 2. 你期待的结果是什么？实际看到的又是什么？

期待：`xxx/index.php/x.html` 变为 `xxx/x.html`，且后台能正常使用
实际：`xxx/index.php/x.html` 确实变为 `xxx/x.html`，但后台打不开，提示 404

### 3. 问题出现的环境

- 操作系统版本：`Arch Linux`
- Apache/NGINX 版本：`nginx/1.22.0 --with-http_ssl_module --with-http_v2_module`
- 数据库版本：`sqlite/3.39.3`
- PHP 版本：`php/8.1.11`
- Typecho 版本：`1.20`
- 浏览器版本：`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53`

**Comment by imycard** [comment]
个人建议使用此方式配置rewrite
try_files $uri $uri/ /index.php?$args;

**Comment by nibazshab** [comment]
ok, 谢谢 @imycard 了，解决了我的问题
