### ISSUE TITLE
禁用编辑主题函数__TYPECHO_THEME_WRITEABLE__无效

### ISSUE THREAD

**Issue by imycard** [typecho/typecho#1504]
### 1. 该问题的重现步骤是什么？

在config.inc.php中定义
defined('__TYPECHO_THEME_WRITEABLE__', false);
之后在后台依旧能编辑主题

### 2. 你期待的结果是什么？实际看到的又是什么？

希望配置后禁用后台编辑主题，实际定义函数后在后台依旧能编辑主题

### 3. 问题出现的环境

- 操作系统版本：Debian 11
- NGINX 版本：1.18
- 数据库版本：10.5
- PHP 版本：7.4.3
- Typecho 版本：1.2
- 浏览器版本：Edge 106

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
```php
define('__TYPECHO_THEME_WRITEABLE__', false);
```

**Comment by imycard** [comment]
> ```
> define('__TYPECHO_THEME_WRITEABLE__', false);
> ```

谢谢，我失误多了个d，不知道为何我发出的前后下划线都没了~~
