### ISSUE TITLE
Typecho1.0无法修改Gravata头像源

### ISSUE THREAD

**Issue by Pings1031** [typecho/typecho#1507]
### 1. 该问题的重现步骤是什么？
因为使用的主题还没适配1.2版本，所以暂时还是用的1.0版本的Typecho，但是当我想修改Gravata头像源，打开var/Typecho/Common.php，发现并没有gravatarUrl部分
### 2. 你期待的结果是什么？实际看到的又是什么？
用户能够自寻修改头像源或修改为获取QQ头像源
### 3. 问题出现的环境

- 操作系统版本：
- NGINX 版本：Nginx 1.20.2
- 数据库版本：MySQL 5.7.39
- PHP 版本：PHP 5.6
- Typecho 版本：1.0
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by jrotty** [comment]
typecho用的GRAVATR的公共头像地址，GRAVATR的服务器在美国，虽然它在全世界做镜像，但是在国内依旧很慢。然后发现有国内有很多人为其做反向代理，把头像缓存到本地，来提高速度，以前大家可能会使用插件来替换typecho的GRAVATR的默认地址，实际上不需要，我们用这个常量就可以了，比如我们替换成`https://gravatar.cat.net/avatar/`，用法如下 用法 在config.inc.php最后面插入`define('__TYPECHO_GRAVATR_PREFIX__', 'https://gravatar.cat.net/avatar'); `这样一来typecho就会替换成`https://gravatar.cat.net/avatar/`渠道的头像地址。【有些模板开发者写死的可能不支持】

**Comment by Pings1031** [comment]
好吧，感谢了。刚才把代码都看了一遍，发现模板作者写死了，而且1.0版本的typecho里var/Typecho/Common.php文件不存在get_avatar($mail)。一般都是都是模板里面的一个为:  模板名字_avatar.php文件里面:指路一下:usr/themes/模板名字/core/模板名字_avatar.php。基本都是大同小异的。总的来说还是谢谢提醒了。
