### ISSUE TITLE
Typecho连接云数据库出错

### ISSUE THREAD

**Issue by Vicoeo** [typecho/typecho#1508]
### 1. 该问题的重现步骤是什么？
Typecho安装阶段连接云数据库出错,云数据库提供商为planetscale，查看操作说明是需要开启SSL才能正常登陆，然后谷歌相关结果只有Wordpress，请问Typecho怎么连接开启了SSL的数据库，或者需要修改哪里？
![微信截图_20221024175521](https://user-images.githubusercontent.com/95205433/197500466-7913e126-dfff-47eb-8212-5693546272c5.png)

### 2. 你期待的结果是什么？实际看到的又是什么？
正常连接云数据库
### 3. 问题出现的环境

- 操作系统版本：Debian11
- Apache/NGINX 版本：NGINX1.22
- 数据库版本：8.0
- PHP 版本：8.17
- Typecho 版本：1.20
- 浏览器版本：Edge 106

[//]: # (如有图片请附上截图)
![微信截图_20221024175117](https://user-images.githubusercontent.com/95205433/197500057-439c219e-6c9c-4c37-ae7d-a37cb544a97c.png)

**Comment by joyqi** [comment]
我们还没加入对SSL的支持，我将尽快加入
