### ISSUE TITLE
1.2版本安装时提示error，无法进行下一步

### ISSUE THREAD

**Issue by nek0peko** [typecho/typecho#1509]
### 1. 重现步骤
通过服务器IP和端口，直接访问install.php
### 2. 实际结果
点击“开始下一步”按钮后，提示信息中出现error字样，且无法再次点击“开始下一步”按钮
### 3. 问题出现的环境
- 操作系统版本：CentOS 8.2 64bit
- Apache/NGINX 版本：Apache 2.4.37/Nginx 1.23.2
- PHP 版本：7.2.24
- Typecho 版本：v1.2.0

[//]: #截图
![image](https://user-images.githubusercontent.com/87629374/198184655-082ecbaf-b7c7-4a94-b906-0dbe303f5c7b.png)
![image](https://user-images.githubusercontent.com/87629374/198184947-f1f2ce73-4681-4785-802f-ed8e3f442414.png)

**Comment by joyqi** [comment]
信息太少了，你可以打开浏览器的debug，看看这个ajax请求具体返回了什么信息么？

**Comment by nek0peko** [comment]
> 信息太少了，你可以打开浏览器的debug，看看这个ajax请求具体返回了什么信息么？

remote address的7890是我本地代理的端口，前面的GET请求都是200OK，但点击下一步的POST请求报500，
![image](https://user-images.githubusercontent.com/87629374/199435129-907658c9-08a7-4cac-ac92-8f62b7a6c0ec.png)

**Comment by nek0peko** [comment]
没注意到body里的信息是Call to undefined function json_encode()，yum install -y php-json.x86_64之后解决了
