### ISSUE TITLE
已经是1.2最新版本的情况下还会提示有新版本

### ISSUE THREAD

**Issue by liyuhao97** [typecho/typecho#1510]
### 1. 该问题的重现步骤是什么？
进入控制台首页
### 2. 你期待的结果是什么？实际看到的又是什么？
已经是最新版本时不会有新版本提示
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Nginx 1.20.2
- 数据库版本：MariaDB 10.5.15
- PHP 版本：7.4.29
- Typecho 版本：1.2
- 浏览器版本：firefox 106.0.1
![图片](https://user-images.githubusercontent.com/116870423/198526472-810cb4d4-dad2-4de6-8c55-b981add29f2b.png)

**Comment by sy-records** [comment]
Duplicate of https://github.com/typecho/typecho/issues/1354
