### ISSUE TITLE
能否提供丰富的菜单功能，比如将分类设置为菜单？

### ISSUE THREAD

**Issue by itlab1024** [typecho/typecho#1511]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by itlab1024** [comment]
感觉typecho升级速度并不快，没几个人写？

**Comment by xing-chen222** [comment]
，

**Comment by joyqi** [comment]
分类是支持多级功能的，如果你要把它变成菜单，可以自己编写相关代码

**Comment by itlab1024** [comment]
额。。。不会呀。。。

**Comment by itlab1024** [comment]
谢谢 了解了。

**Comment by itlab1024** [comment]
已经收到回复
