### ISSUE TITLE
无法使用SQLite数据库

### ISSUE THREAD

**Issue by blueandstar** [typecho/typecho#1514]
### 该问题的重现步骤是什么？
安装的时候使用SQLite报错提醒`确认您的配置`，
![image](https://user-images.githubusercontent.com/105478325/201467231-f0a97bf0-a3ec-4588-bfb7-c0ee1d616484.png)

### 问题出现的环境

- 操作系统版本：Ubuntu 20
- NGINX 版本：1.22.1
- PHP 版本：7.3
- Typecho 版本：1.2.0
- 数据库：
```
# sqlite3
SQLite version 3.31.1 2020-01-27 19:55:54
```

**Comment by sy-records** [comment]
修复过了，使用开发版试试。
问题是路径里存在.
