### ISSUE TITLE
切换主题后报错Database Query Error

### ISSUE THREAD

**Issue by basfree** [typecho/typecho#1515]
###  该问题的重现步骤是什么？
切换了主题

除了使用原始主题，使用其他主题都会报错 Database Query Error

### 问题出现的环境

操作系统版本：Ubuntu
NGINX 版本：1.22.1
PHP 版本：7.4
数据库：SQLite
Typecho 版本：开发版

**Comment by sy-records** [comment]
信息不够完整，打开debug看看完整的错误信息

**Comment by sy-records** [comment]
表不存在，看起来是个插件的问题，问下插件作者
