### ISSUE TITLE
如何识别爬虫

### ISSUE THREAD

**Issue by XYZ-dragon** [typecho/typecho#1516]
我不知道 typecho 是否提供了鉴别爬虫的接口,但我发现我可能需要这个功能.某些 JS 我并不希望在爬虫访问时加载(因为某些效果可能会影响搜索引擎的收录结果),如果提供了一个判断爬虫的接口那么我可以很轻松的解决这个问题.

谢谢.

**Comment by sy-records** [comment]
没提供，一般都是从ua里获取信息来判断，这个可以自行实现~

**Comment by XYZ-dragon** [comment]
> 没提供，一般都是从ua里获取信息来判断，这个可以自行实现~

好的,能给一份代码做参考吗?还是简单粗暴的UA不含 `Mozilla` 和 `WebKit` 就可以了?

**Comment by wangyang0210** [comment]
> > 没提供，一般都是从ua里获取信息来判断，这个可以自行实现~
> 
> 好的,能给一份代码做参考吗?还是简单粗暴的UA不含 `Mozilla` 和 `WebKit` 就可以了?

可以参考[browser.js](https://github.com/mumuy/browser/blob/master/browser.js)
