### ISSUE TITLE
与 MarkText 的格式冲突

### ISSUE THREAD

**Issue by HtnrxUNc** [typecho/typecho#1517]
### 1. 该问题的重现步骤是什么？
![image](https://user-images.githubusercontent.com/66531963/202716343-98df0b24-900a-4d66-852c-e5b2ef8958d0.png)

这是在 MarkText 中的源代码模式

![image](https://user-images.githubusercontent.com/66531963/202716482-d5814150-f561-4f7f-b737-7bb0fe0088c3.png)

这是在 MarkText 中的显示效果

![image](https://user-images.githubusercontent.com/66531963/202716574-7e560278-832a-4284-894a-3ca41241f17c.png)

这是在 Typecho 中的效果

我想要将格式显示成 MarkText 中的格式，造成这种冲突的原因是因为与 MarkText 的格式不同，还是因为 MarkText 自身的问题导致？（或者说 MarkText 的格式不同于寻常的 MarkDown 语法）
对于这种问题，我是否能通过将 MarkDown 的文档导出成 html 格式然后将其上传到 Typecho？

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 20.04 LTS
- Apache/NGINX 版本：Nginx 1.18.0
- 数据库版本：MySQL 5.6.50
- PHP 版本：PHP-7.4
- Typecho 版本： 1.1 (17.10.30)
- 浏览器版本：107.0.5304.107（正式版本） （64 位）chrome
- MarkText 版本：0.17.1 windows x64 版本

**Comment by joyqi** [comment]
Typecho 用的是 HyperDown 解析库，每种库的排版都有细微不同，如果你想完全一致，需要自己去用插件实现。
