### ISSUE TITLE
后台管理版本显示bug

### ISSUE THREAD

**Issue by Niobox** [typecho/typecho#1521]
### 1. 该问题的重现步骤是什么？
创建一个新的typecho后，打开后台管理，会看见当前版本不是最新版本
![image](https://user-images.githubusercontent.com/41267713/208287989-16b5bf81-7141-42bb-ada0-0ae15e5f84dc.png)
当前已经最新版本，但是还是提醒版本更新，在版本判断里改一下

### 3. 问题出现的环境
正式环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
Duplicate of https://github.com/typecho/typecho/issues/1354
