### ISSUE TITLE
1.2.0 安装时显示"上传目录无法写入, 请手动将安装目录下的 /usr/uploads 目录的权限设置为可写然后继续升级"

### ISSUE THREAD

**Issue by tmdakm** [typecho/typecho#1524]
### 1. 该问题的重现步骤是什么？
使用LNMP安装Typecho，在安装时提示"上传目录无法写入, 请手动将安装目录下的 /usr/uploads 目录的权限设置为可写然后继续升级"。(注：谷歌云的主机)
### 2. 你期待的结果是什么？实际看到的又是什么？
成功安装Typecho
### 3. 问题出现的环境

- 操作系统版本：Debian 11
- Apache/NGINX 版本：nginx/1.22.1
- 数据库版本：MySQL 5.7.38
- PHP 版本：PHP 7.4.33
- Typecho 版本：1.2.0 稳定版
- 浏览器版本：Edge 108.0.1462.76

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/96684075/212476928-35cde948-86fa-423c-91e5-c9f3beaf5e27.png)

**Comment by sy-records** [comment]
Duplicate of #1365

**Comment by alub518** [comment]
同样的问题

**Comment by alub518** [comment]
现在解决了吗？
