### ISSUE TITLE
独立页面 - Bug

### ISSUE THREAD

**Issue by XYZ-dragon** [typecho/typecho#1528]
### 1. 该问题的重现步骤是什么？
1.新增一个独立页面,点击保存草稿.此时后台可见,但这个文章发布后会彻底消失.
2.新增一个独立页面,直接发布结果正常.
### 2. 你期待的结果是什么？实际看到的又是什么？
独立页面的草稿功能正常使用.为此我丢了一篇记录草稿,还好损失不大.
我的主题不涉及后台修改,并且用本地博客测试成功复现.

Version: 1.2.0

**Comment by joyqi** [comment]
> 1.新增一个独立页面,点击保存草稿.此时后台可见,但这个文章发布后会彻底消失.

你的意思是这个独立页面彻底消失，还是指只是草稿消失

**Comment by XYZ-dragon** [comment]
> > 1.新增一个独立页面,点击保存草稿.此时后台可见,但这个文章发布后会彻底消失.
> 
> 你的意思是这个独立页面彻底消失，还是指只是草稿消失

这个 cid 对应的文章彻底消失,无法通过xxx.html或者后台的?cid=查询到.
都消失

**Comment by Allone** [comment]
同样问题，求解决办法~

**Comment by Allone** [comment]
[撰写]页面添加页面没有问题
[管理]页面新增出现问题。

**Comment by XYZ-dragon** [comment]
> 同样问题，求解决办法~

解决办法就是用其他的编辑器或者在文章草稿中写好,然后整个复制过来直接新增,只要**不保存草稿**就不会出问题.
或者先新增一个空的占位独立页面发布,之后即使**保存草稿**也不会消失.

但毫无疑问这是一个 bug, 还是需要解决的.

**Comment by sy-records** [comment]
我本地master代码没复现问题，有谁试过master？

**Comment by XYZ-dragon** [comment]
> 我本地master代码没复现问题，有谁试过master？

master 没有问题,但我覆盖文件的时候选择跳过具有相同大小和日期依然可以复现(???

**Comment by lgl1227** [comment]
我新建页面，无论是发布页面，还是保存草稿页面都不行。试过好几次了

**Comment by ccKiven1024** [comment]
> 我新建页面，无论是发布页面，还是保存草稿页面都不行。试过好几次了

我的独立页面，都无法编辑，一直显示“网站未授权”
![image](https://user-images.githubusercontent.com/67768414/222692024-2645a096-d197-4337-8855-9c4845134ff6.png)

**Comment by joyqi** [comment]
这个bug已经在开发版中修复了
@ccKiven1024 你这个应该不是程序的问题，可以联系下你的主机商或者你是不是用了啥收费皮肤或者插件了，Typecho 主程序里没有这些字样。

**Comment by ccKiven1024** [comment]
> 这个bug已经在开发版中修复了 @ccKiven1024 你这个应该不是程序的问题，可以联系下你的主机商或者你是不是用了啥收费皮肤或者插件了，Typecho 主程序里没有这些字样。

更换主题之后确实没了这个问题，谢谢你的解释！
