### ISSUE TITLE
将 admin 目录重命名为中文后，进入后台将出现问题

### ISSUE THREAD

**Issue by wordlesswind** [typecho/typecho#1530]
### 1. 该问题的重现步骤是什么？
将 admin 目录重命名为中文，例如“后台”。

### 2. 你期待的结果是什么？实际看到的又是什么？
正常使用。
实际会出现重定向至一个不可访问的 URL 等情况。

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 22.04.1 LTS
- Apache/NGINX 版本：nginx 1.23.3
- 数据库版本：MariaDB 10.10.2
- PHP 版本：[typecho/Dockerfile](https://github.com/typecho/Dockerfile)
- Typecho 版本：[typecho/Dockerfile](https://github.com/typecho/Dockerfile)
- 浏览器版本: Google Chrome 109.0

相关 issue: #1260

**Comment by callng** [comment]
为什么要重命名?

**Comment by wordlesswind** [comment]
> 为什么要重命名?

一般是为了防止泄露后台入口。

**Comment by KawaiiSh1zuku** [comment]
> > 为什么要重命名?
> 
> 一般是为了防止泄露后台入口。

为什么要重命名成中文？

**Comment by wordlesswind** [comment]
> 为什么要重命名成中文？

因为我用的是中文域名，且我有强迫症。

**Comment by sy-records** [comment]
Duplicate of #1260 
关闭了在1260中统一跟进
