### ISSUE TITLE
当发布者修改了他的昵称时，在修改前发布的评论仍是修改前的昵称

### ISSUE THREAD

**Issue by NagatoException** [typecho/typecho#1532]
### 1. 该问题的重现步骤是什么？
在后台修改管理员的昵称
### 2. 你期待的结果是什么？实际看到的又是什么？
希望之前的评论也是新的昵称，而不是旧的昵称
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Tengine 2.2
- 数据库版本：MySQL 5.6
- PHP 版本：7.3
- Typecho 版本：1.2.0
- 浏览器版本：Chrome 103

[//]: # (如有图片请附上截图)

**Comment by xiamuguizhi** [comment]
因为数据库评论那边 存储的 名称是 “未修改之前的” 修改后存储的是 ”修改后的”  所以除非去数据库那边批量替换一下，或者在 前端评论手动替换一下，不然就是这样的了。

**Comment by xiamuguizhi** [comment]
@NagatoException 其实这个问题有一个 提交的：[修改个人信息后同步修改评论列表内信息](https://github.com/typecho/typecho/pull/1435)  只是没通过
