### ISSUE TITLE
webp文件无法识别为图片插入编辑器

### ISSUE THREAD

**Issue by Seevil** [typecho/typecho#1533]
### 1. 该问题的重现步骤是什么？
https://user-images.githubusercontent.com/7334510/220168272-a64a30ff-80ba-4a35-b46e-cc24c5393878.mp4

### 2. 你期待的结果是什么？实际看到的又是什么？

和其他图片一样识别为图片插入编辑器:  [ ]  -> ![ ]  

### 3. 问题出现的环境

- 操作系统版本：win11
- Apache/NGINX 版本：1.12
- 数据库版本：8
- PHP 版本：8
- Typecho 版本：1.2
- 浏览器版本：chrome 110

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
https://github.com/typecho/typecho/issues/1380 用master试试

**Comment by Seevil** [comment]
测试可以了，谢谢

> #1380 用master试试
