### ISSUE TITLE
header() 方式设置状态码失效

### ISSUE THREAD

**Issue by vircloud** [typecho/typecho#1540]
### 1. 该问题的重现步骤是什么？
比如，在默认主题的 header.php 中添加 `header()` 代码：
```php
<?php if (!defined('__TYPECHO_ROOT_DIR__')) exit;
header('HTTP/1.1 503 Service Unavailable');
header('X-From: Test');
var_dump(http_response_code());
 ?>
```

### 2. 你期待的结果是什么？实际看到的又是什么？

测试发现 `header('X-From: Test');` 可以设置成功，`var_dump(http_response_code());` 也确实显示是 `503`，但在前端浏览器，此时的状态码应该是 `HTTP/1.1 503 Service Unavailable`，实际是 `HTTP/1.1 200 OK`。。

### 3. 问题出现的环境

- 操作系统版本：CentOS7.4
- Apache/NGINX 版本：1.14
- 数据库版本：MySQL14
- PHP 版本：7.4
- Typecho 版本：1.2.0
- 浏览器版本：Chrome 106

[//]: # (如有图片请附上截图)

![2023-03-08_190056](https://user-images.githubusercontent.com/32838469/223696130-9d4223d5-1c59-4fe5-a6c5-8f9279d3fa06.jpg)

**Comment by sy-records** [comment]
header设置了503，不代表就不往下执行了，后面会覆盖的啊。

你需要exit或者die掉。

**Comment by vircloud** [comment]
> header设置了503，不代表就不往下执行了，后面会覆盖的啊。
> 
> 你需要exit或者die掉。

@sy-records 感谢回复，如图添加了 exit，但是还是返回了 200 OK

![2023-03-09_115234](https://user-images.githubusercontent.com/32838469/223912150-c1d01dbd-7ed3-4690-b216-340ebfda5fae.jpg)

**Comment by sy-records** [comment]
用异常代替exit吧。`throw new RuntimeException('', 503);`
<img width="315" alt="image" src="https://user-images.githubusercontent.com/33931153/224243949-f24aa2fd-716c-42ed-b0d6-8ee39d15e31f.png">

**Comment by vircloud** [comment]
> 用异常代替exit吧。`throw new RuntimeException('', 503);` <img alt="image" width="315" src="https://user-images.githubusercontent.com/33931153/224243949-f24aa2fd-716c-42ed-b0d6-8ee39d15e31f.png">

感谢回复，这个方法确实可以修改状态码，但是也会影响输出内容，测试了异常输出会自带样式，实际需求不要这个，只要纯粹返回指定状态码，因为特定状态有时候需要返回指定的内容，自带样式会产生影响。

![2023-03-12_153548](https://user-images.githubusercontent.com/32838469/224530907-c92f299a-9d4c-431c-bef8-bcce64864ec0.jpg)

**Comment by sy-records** [comment]
`\Typecho\Response::getInstance()->setStatus(503)->respond();`
