### ISSUE TITLE
不知道什么时候有应用商城呢？

### ISSUE THREAD

**Issue by livepu** [typecho/typecho#1541]
感觉现在看来很简单，编辑器需要另外下载的。

**Comment by AXFOX** [comment]
我觉得这就脱离Typecho轻量化的特性了。应用商城你打算放什么？放主题？插件？服务器谁来提供？你想要的可能不是Typecho，也许CMS化的WordPress更适合你。

**Comment by jrotty** [comment]
之前说搞的，结果咕咕了

**Comment by mrsuner** [comment]
做了应用商城就不是Typecho了，Typecho的特点是轻量，加了只会变四不像，与其加更多的功能不如做一个详细的版本计划。

**Comment by binjoo** [comment]
每当有这个问题的时候就不得不祭出2014年 @joyqi 画的大饼了。。

https://forum.typecho.org/viewtopic.php?t=5462

![image](https://user-images.githubusercontent.com/219092/236594315-b6ef336a-d069-4b2d-a28a-972e4fc1f02b.png)

**Comment by fenbox** [comment]
Duplicate of #1398
