### ISSUE TITLE
用户注册发表文章不了

### ISSUE THREAD

**Issue by hy6xing** [typecho/typecho#1548]
### 1. 该问题的重现步骤是什么？
管理员审核里看不见待审核文章
### 2. 你期待的结果是什么？实际看到的又是什么？
给了注册用户写作权限（贡献者），用户发表文章后在管理员里看不见，待审核也没有。总之，用户写的发表后，只存在用户的待审核里。而管理员那里什么都没显示
### 3. 问题出现的环境

- 操作系统版本：CentOS 8.2.2004 x86_64(Py3.7.9)
- Apache/NGINX 版本：NGINX  1.22.1
- 数据库版本：5.74.0
- PHP 版本：7.4.33
- Typecho 版本：1.2.0
- 浏览器版本：所有浏览器都是一样情况

[//]: # (如有图片请附上截图)

**Comment by jrotty** [comment]
文章管理页面右上角点击所有才能看到用户发的文章，默认是只看自己的
