### ISSUE TITLE
1.21版本后虚拟空间无法正常安装

### ISSUE THREAD

**Issue by MuZi1997** [typecho/typecho#1550]
1.20版本正常安装，1.21就不行了php7系安装报错
 error  切换php8.0就提示缺少mbstring，mbstring已经安装了，还是一直提示缺少mbstring，Apache的虚拟空间！！

**Comment by sy-records** [comment]
缺少扩展那就是真的缺，检查phpinfo里有没有

**Comment by MuZi1997** [comment]
> 错误信息发出来

![Screenshot_2023-04-04-09-05-48-641_mark via-edit](https://user-images.githubusercontent.com/112834331/229659992-bfac134d-2ad6-4dd4-b248-4e918a4e77a3.jpg)

**Comment by sy-records** [comment]
F12，看network里的请求响应

**Comment by MuZi1997** [comment]
> F12，看network里的请求响应
手机查看的可能不太清晰😂感谢哈
![IMG_20230404_091102](https://user-images.githubusercontent.com/112834331/229660518-5b6f5737-346b-4bfe-a341-2b1e4a72883e.jpg)
![Screenshot_2023-04-04-09-10-21-753_com mmbox browser-edit](https://user-images.githubusercontent.com/112834331/229660525-581d5967-b659-48e2-a2c5-f69d6b0db7e8.jpg)

**Comment by vndroid** [comment]
让你看就真就看一下啊，倒是把完整的报错贴出来啊。

**Comment by MuZi1997** [comment]
> 让你看就真就看一下啊，倒是把完整的报错贴出来啊。

已经解决了，是虚拟空间环境的问题
