### ISSUE TITLE
后台文章编辑希望支持一下markdown实时预览模式

### ISSUE THREAD

**Issue by suyunxue** [typecho/typecho#1551]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by fenbox** [comment]
后台编辑器有 markdown 预览啊，能补充下更详细的描述吗？

**Comment by xiamuguizhi** [comment]
@fenbox 应该是要 右侧 实时预览 功能，  不是需要点击 预览那种。

**Comment by xiamuguizhi** [comment]
你可以先用 ：[AAEditor 又一款 Typecho 编辑器插件](https://xiamp.net/archives/aaeditor-is-another-typecho-editor-plugin.html) 替代一下默认编辑器。

![image](https://github.com/typecho/typecho/assets/19650297/d15519fc-bfc4-4e70-82d8-08a34ebd3ba8)

下载地址：https://xiamp.net/archives/aaeditor-is-another-typecho-editor-plugin.html
