### ISSUE TITLE
docker部署typecho语言变成英文

### ISSUE THREAD

**Issue by kevvvinyao** [typecho/typecho#1552]
### 1. 该问题的重现步骤是什么？

- 使用`handsome`主题.
- 使用`docker`进行部署, 镜像为`joyqi/typecho:nightly-php7.4-apache`

### 2. 你期待的结果是什么？实际看到的又是什么？

我期待他是一个全中文界面.
实际看到的是部分元素变成了英文, 例如**首页**和**分类**变成了对应的英文.

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

使用`docker`搭建, 不涉及环境问题. 

### 自查过程

经过排查, 发现`joyqi/typecho:nightly-php7.4-apache`镜像中的`/usr`文件夹中有一个名为`langs`的文件夹, 进入之后发现为**语言配置**文件. 去官网下载 https://typecho.org/download 发现**正式稳定版**文件包的`/usr`文件夹下不含有`langs`文件夹. 

不止为何docker镜像中多出此文件夹. 

手动删除 ` rm ./langs -rf` 后, 网页语言显示变为正常.

提问: 
1. 为何docker镜像中多出此文件夹, 以及有何作用? 
2. 希望官方提供不含有`langs`文件夹, 即**与官网文件包一致**的`docker`镜像

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
docker里会默认加入多语言支持，GitHub 的 release 里没有。
