### ISSUE TITLE
CSS 使用了绝对路径而不是相对路径

### ISSUE THREAD

**Issue by char-46** [typecho/typecho#1553]
### 1. 该问题的重现步骤是什么？
还原某站点，未将源文件放置在原先域名下。

### 2. 你期待的结果是什么？实际看到的又是什么？
期待其生成的HTML代码中引用的css为相对路劲，而不是绝对路径。
通过DevTools可看到其使用了不存在的绝对路径导致样式表丢失。
![Clip_102053](https://user-images.githubusercontent.com/53117560/230750942-ae6daaf6-f660-40b3-b94d-aa5763d72f8a.png)

### 3. 问题出现的环境

- 操作系统版本：WSL Debian GNU/Linux 11 (bullseye)
- Apache/NGINX 版本：nginx-core/stable,stable-security,now 1.18.0-6.1+deb11u3
- 数据库版本：mariadb-server-10.5/stable,now 1:10.5.18-0+deb11u1 amd64
- PHP 版本：7.4
- Typecho 版本：1.2.0
- 浏览器版本：Edg/112.0.1722.34 (正式版本) (64 位) 

[//]: # (如有图片请附上截图)

**Comment by fxnetw** [comment]
你就是后台没配置对域名，一般都是用$this->options->themeUrl(');获取主题路径，这是正常的

**Comment by char-46** [comment]
这应当属于设计失误。我认为在此处使用包含域名的绝对路径会对包括但不限于迁移、重新部署站点造成困难。





 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年4月28日(周五) 晚上11:13写道:

  

 
你就是后台没配置对域名，一般都是用$this-&gt;options-&gt;themeUrl(');获取主题路径，这是正常的
