### ISSUE TITLE
可否支持下公式解析?

### ISSUE THREAD

**Issue by EPTansuo** [typecho/typecho#1555]
目前, Typecho无法支持解析公式. 
我想提出的解析公式, 并非 **完全解析渲染公式**  , 而是说, 对于 `$ a^2 + b^2 = c^2 $` 行内公式, 希望可以将其解析为`<inline-math> a^2 + b^2 =c^2 </inline-math>` , 而非目前的一个单纯的`<p>`标签.
而对于对于行间公式:
```
$$
a^2 + b^2 = c^2
$$
```
可以解析为: 
```
<interline-math> a^2 + b^2 + c^2 </interline-math>
```
这样, 对于用户自己加公式渲染插件, 或者修改css来调格式都很方便.
而且, 开发者也无须对此消耗太多经历.

**Comment by fenbox** [comment]
公式这部分建议用插件实现，Typecho 本身不会集成公式渲染。
