### ISSUE TITLE
在1.2.1版本下摘要输出失效

### ISSUE THREAD

**Issue by nagatoyk** [typecho/typecho#1556]
### 1. 该问题的重现步骤是什么？
访问feed,内容直接全文输出了,
### 2. 你期待的结果是什么？实际看到的又是什么？
根据后台设置,实现摘要输出或者全文输出
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：1.2.1
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
检查文章是否有`<!--more-->`

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/33931153/235571927-f91aca69-c992-47ab-b6ec-60a44444ddec.png">
