### ISSUE TITLE
无法发布文章

### ISSUE THREAD

**Issue by wxd11011** [typecho/typecho#1562]
### 1. 该问题的重现步骤是什么？
在后台正常编辑文章后点击发布，显示正常发布，但是回到“管理文章”页面时，刚才发布的文章标题为空、分类为空，在首页上查看，同样可以看到一个空标题的文章，点击进去是一篇没有任何内容的空文章。
### 3. 问题出现的环境

- 操作系统版本：百度云虚拟主机
- Apache/NGINX 版本：nginx
- 数据库版本：MySQL 5.7.17
- PHP 版本：7.4
- Typecho 版本：1.2.0和1.2.1-rc
- 浏览器版本：firefox v111.0 (64bit) \ chrome  v112.0.5615.86(64bit) \ edge v112.0.1722.39(64bit)

[//]: # (如有图片请附上截图)
![0](https://user-images.githubusercontent.com/7261592/232181693-26a37e22-e004-448e-bcd1-b89f4164bdf5.jpg)
![1](https://user-images.githubusercontent.com/7261592/232181698-6c6e03c0-45ba-4dfa-8c94-df66a4c06eb8.jpg)
![2](https://user-images.githubusercontent.com/7261592/232181705-61fb99d2-0c1a-42a5-9372-63ffaa10bc46.jpg)
![3](https://user-images.githubusercontent.com/7261592/232181707-ab8fee64-e759-4282-b101-0c9f4bff0caa.jpg)
![4](https://user-images.githubusercontent.com/7261592/232181715-ff180f0f-7dca-4152-9c1e-58162099be00.jpg)

**Comment by Seevil** [comment]
开着F12 点发布文章 看具体请求返回是什么

**Comment by wxd11011** [comment]
> 开着F12 点发布文章 看具体请求返回是什么
谢谢回复，返回如下图所示：
![5](https://user-images.githubusercontent.com/7261592/232197067-1dec6ee3-45ab-449b-b77f-9aa6392c8cac.jpg)

**Comment by wxd11011** [comment]
nginx版本1.16.1

**Comment by sy-records** [comment]
打开Debug模式，

```
define('__TYPECHO_DEBUG__', true);
```

重新发布一个看看有没有错误信息。

**Comment by sy-records** [comment]
打开Debug模式，

```
define('__TYPECHO_DEBUG__', true);
```

重新发布一个看看有没有错误信息。

**Comment by wxd11011** [comment]
> 打开Debug模式，
> 
> ```
> define('__TYPECHO_DEBUG__', true);
> ```
> 
> 重新发布一个看看有没有错误信息。

谢谢回复！打开调试模式后，没有错误信息输出。就跟正常发布文章时的反应一样，只是提示文章发布成功时，标题是空的。（关闭调试模式后也是这样）

**Comment by sy-records** [comment]
那建议做好备份，恢复成默认主题，不启用插件试试。

**Comment by wxd11011** [comment]
> 那建议做好备份，恢复成默认主题，不启用插件试试。

谢谢您以及网友Seevil的回复，果然是插件的问题，我关闭了Likes插件v1.0（ Typecho 版 PostLikes）后正常了。
