### ISSUE TITLE
已经升级到1.2.0版本，却出现网页版本提示。

### ISSUE THREAD

**Issue by Jason091622** [typecho/typecho#1564]
### 1. 该问题的重现步骤是什么？
打开“网站摘要（控制台»摘要）”页面。

---

### 2. 你期待的结果是什么？实际看到的又是什么？
期待的结果：不出现任何弹窗、报错信息；
实际看到的：出现红色背景的：
“您当前使用的版本是 1.2.0
[官方最新版本是 1.2.0](http://typecho.org/download)”
提示。

---

### 3. 问题出现的环境
如下。
- 操作系统版本：Linux 3.10.0-957.1.3.el7.x86_64
- Apache/NGINX 版本：kangle/3.5.21.16
- 数据库版本：MySQL 5.6.51
- PHP 版本：8.2.3
- Typecho 版本：1.2.0
- 浏览器版本：小米浏览器V14.7.64**（应该和浏览器关系不大）**
![err.jpg](https://hxsrz.weie.pro/usr/uploads/err.jpg "截图")
[//]: # (如有图片请附上截图)

**Comment by Jason091622** [comment]
截图：https://hxsrz.weie.pro/usr/uploads/err.jpg（用平板截的，不要在意）

**Comment by sy-records** [comment]
Duplicate of https://github.com/typecho/typecho/issues/1354
