### ISSUE TITLE
在最近的快照版本中，仍存在 issue #1222 所述情况

### ISSUE THREAD

**Issue by duoduoffff** [typecho/typecho#1565]
### 1. 该问题的重现步骤是什么？

正常安装 Typecho 后，在后台管理（`https://*/dashboard-mng/manage-pages.php` 和 `https://*/dashboard-mng/manage-posts.php`）中尝试编辑示例的文章和页面。

### 2. 你期待的结果是什么？实际看到的又是什么？

光标移到编辑的链接上，显示的链接形如 `https://*/dashboard-mng/write-page.php?cid=2`，没有问题。但点击进入后，实际进入的地址是 `https://*/dashboard-mng/write-page.php`，丢失了请求的参数，导致系统软件打开一个新建页面的空编辑器，其中没有任何内容。

在编辑页面和编辑文章时，均能触发此问题。查过往 issue 列表 #1222，此问题在 2021 年被触发并修复过。在实际部署的代码中仔细比对相关行的内容，确实是修改过后的内容，但问题依然存在。

另外，仔细检查 URL 伪静态相关的设置，在关闭和打开伪静态设置的情况下均能触发此问题，伪静态功能无异常，初步排除是 Nginx 配置文件或者伪静态设置不正确导致的。故而怀疑某处业务逻辑似乎仍有问题。

### 3. 问题出现的环境

- 操作系统版本
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Apache/NGINX 版本：
```
nginx version: nginx/1.22.1
```
- 数据库版本：
```
mysql  Ver 15.1 Distrib 10.11.2-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```
- PHP 版本：
```
PHP 8.2.4 (cli) (built: Mar 16 2023 14:24:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.4, Copyright (c), by Zend Technologies
```
- Typecho 版本：
![image](https://user-images.githubusercontent.com/46983115/234864945-4d8645a4-1979-4e82-bc8c-f8554a86c5e0.png)

```
版本：[bad3ef651d23154e6acc525bc193111dcda557c8](https://github.com/typecho/typecho/commit/bad3ef651d23154e6acc525bc193111dcda557c8)
```
- 浏览器版本：
```
Firefox Developer Edition Apple Intel x64 113.0b8 (64-bit)
```

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
开发版这个地址不对，不是master的。你可以用master的再试试，或者1.2.1-rc

**Comment by duoduoffff** [comment]
在 1.2.1-rc 版本，清除部署目录后使用 `rsync -raPd` 和解压压缩包的目录同步，仍可以复现此问题

**Comment by sy-records** [comment]
提供个测试环境或者镜像吧，我这没复现

**Comment by duoduoffff** [comment]
可以，给我个 PGP 公钥，我给你发可以登录服务器的 SSH 公私钥对

**Comment by duoduoffff** [comment]
没有事了，是我自己安装的火狐插件导致的，把我的网站加到白名单里面就没有问题了
