### ISSUE TITLE
无法评论，评论管理页面报错

### ISSUE THREAD

**Issue by Jason091622** [typecho/typecho#1566]
### 1. 该问题的重现步骤是什么？
进行评论，点击后无任何报错信息，但是无法评论；进入评论管理页面，如果有评论的话，会显示报错信息（但是可以正常删除评论）：`Warning: Trying to access array offset on value of type null in /home/ftp/c/cysqwe5w5o1lej/wwwroot/var/Widget/Base/Comments.php on line 396`
### 2. 你期待的结果是什么？实际看到的又是什么？
可以正常评论。
### 3. 问题出现的环境

- 操作系统版本：Linux 3.10.0-957.1.3.el7.x86_64
- Apache/NGINX 版本：kangle/3.5
- 数据库版本：MySQL 5.6.51
- PHP 版本：8.2.3
- Typecho 版本：1.2.0
- 浏览器版本：小米浏览器 v14.7.64

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
新版本应该修复了

**Comment by Jason091622** [comment]
> 新版本应该修复了

您指的是开发版还是正式版？

**Comment by sy-records** [comment]
v1.2.1rc

**Comment by Jason091622** [comment]
> 1.2.1 版

还是不行。

**Comment by sy-records** [comment]
你查查你的数据库，对应的cid是否存在
