### ISSUE TITLE
自定义字段复选框无法保存

### ISSUE THREAD

**Issue by ymc0182** [typecho/typecho#1568]
### 1. 该问题的重现步骤是什么？
复选框保存提示保存成功，自动刷新后实际没有保存，数据库也没有更新。但默认主题的复选框可以用。

我看了下数据库，应该是切换主题初始化时序列化错误，切换主题（勾选保存）序列化后的值是 N，正常应该是花括号。

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx1.21
- 数据库版本：8.0
- PHP 版本：8.0
- Typecho 版本：1.20
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by ymc0182** [comment]
但是切换到默认主题初始化时序列化又是正常的。

**Comment by sy-records** [comment]
做好备份，试试1.2.1-rc，应该是修复过的问题

**Comment by ymc0182** [comment]
> 

复选框默认值不能设置null😂，要设置空数组才行，这算是个bug吧😂，赶紧把文档重写吧，好多东西文档里都没有，得靠自己摸索

**Comment by ymc0182** [comment]
> 做好备份，试试1.2.1-rc，应该是修复过的问题

主题设置可以了，但是文章编辑页面的复选框不行，默认值设置空数组，可以发布成功，但是选项保存不了

**Comment by benzBrake** [comment]
确实不行，开发过程中新增选项也不能保存，只能重新启用主题才行

**Comment by joyqi** [comment]
我已经修复了复选框的问题，但是你们说的文章编辑页的自定义选项似乎是另一个问题，需要分别提供详细的复现步骤

**Comment by ymc0182** [comment]
> 



> 我已经修复了复选框的问题，但是你们说的文章编辑页的自定义选项似乎是另一个问题，需要分别提供详细的复现步骤

好的，我稍后重新提交一下

**Comment by sy-records** [comment]
goto #1574
