### ISSUE TITLE
如何一次提取所有的外链地址呢？

### ISSUE THREAD

**Issue by Winyer** [typecho/typecho#1573]
### 1. 该问题的重现步骤是什么？
无
### 2. 你期待的结果是什么？实际看到的又是什么？
因为以前网站用的OSS存储所以使用的外链放图片之类的，但是现在不想用OSS了，把文件取回时发现有五百多G，而其中网站所使用的可能连50G都不到，不想再把这些都上传到服务器，想把网站用到的部分提取出来，因为不懂SQL命令所以来求助下大家，谢谢谢谢
### 3. 问题出现的环境
TE1.2
- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by xiamuguizhi** [comment]
@chatGTP4 

从你的描述来看，你希望从你的Typecho博客数据库中提取出所有使用到的图片链接，然后只将这些图片从OSS迁移到新的服务器。这可以通过执行SQL查询来实现。

Typecho默认使用Markdown语法来编写文章，图片链接通常会以`![](http://example.com/path/to/image.jpg)`的形式出现在文章内容中。因此，你可以使用SQL的LIKE操作符来搜索包含这种格式的文章内容。以下是一个基本的SQL查询示例：

```sql
SELECT * FROM `typecho_contents` WHERE `text` LIKE '%![](%'
```

这个查询将返回`typecho_contents`表中所有包含Markdown图片链接的文章。

然而，这个查询只能找到包含图片链接的文章，而不能直接提取出图片链接。为了提取出图片链接，你需要使用一种编程语言（例如PHP）来处理查询结果。你可以使用正则表达式来匹配和提取Markdown图片链接。以下是一个基本的PHP示例：

```php
$pattern = '/!\[\]\((.*?)\)/';
preg_match_all($pattern, $text, $matches);
$links = $matches[1];  // $links现在包含了所有的图片链接
```

在这个PHP代码片段中，`$text`应该是你从数据库查询结果中获取的文章内容。`preg_match_all`函数会找到所有的Markdown图片链接，并将链接URL提取到`$links`数组中。

请注意，这只是一个基本的示例，并且可能需要根据你的具体需求进行修改。特别是，你可能需要考虑如何处理文章中包含多个图片链接的情况，以及如何处理链接URL不完全符合Markdown格式的情况。
