### ISSUE TITLE
將網站改成繁體中文後，無法進入後台

### ISSUE THREAD

**Issue by huangz92** [typecho/typecho#1578]
### 1. 该问题的重现步骤是什么？

1. 在 usr 資料夾下新增 langs 資料夾，並將解壓縮的 .mo 文件上傳（依照[這裡](https://github.com/typecho/languages#readme)的說明）
2. 在後台出現更改語言的選單，改選「繁體中文」
3. 點選「保存設置」。

### 2. 你期待的结果是什么？实际看到的又是什么？

- 期待可以正常地使用後台
- 實際看到的是，後台顯示「The arguments array must contain 3 items, 2 given」的錯誤訊息，但是前台可以正常顯示，而且前台已經切換成繁體中文。

### 3. 问题出现的环境

- Typecho 版本：1.2.0
- 浏览器版本：Microsoft Edge

**Comment by joyqi** [comment]
试一下这个版本：https://github.com/typecho/typecho/releases/tag/v1.2.1-rc.2
另外，你的PHP是什么版本？

**Comment by huangz92** [comment]
使用這個 1.2.1 版本可以解決問題，謝謝。
PHP 是 8.0 版
