### ISSUE TITLE
mariadb 10.6不支持

### ISSUE THREAD

**Issue by windofthecolor** [typecho/typecho#1579]
MariaDB [typecho]> CREATE TABLE `typecho_comments` (
    ->   `coid` int(10) unsigned NOT NULL auto_increment,
    ->   `cid` int(10) unsigned default '0',
    ->   `created` int(10) unsigned default '0',
    ->   `author` varchar(150) default NULL,
    ->   `authorId` int(10) unsigned default '0',
    ->   `ownerId` int(10) unsigned default '0',
    ->   `mail` varchar(150) default NULL,
    ->   `url` varchar(255) default NULL,
    ->   `ip` varchar(64) default NULL,
    ->   `agent` varchar(511) default NULL,
    ->   `text` text,
    ->   `type` varchar(16) default 'comment',
    ->   `status` varchar(16) default 'approved',
    ->   `parent` int(10) unsigned default '0',
    ->   PRIMARY KEY  (`coid`),
    ->   KEY `cid` (`cid`),
    ->   KEY `created` (`created`)
    -> ) ENGINE=%engine%  DEFAULT CHARSET=%charset%;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%engine%  DEFAULT CHARSET=%charset%' at line 19
MariaDB [typecho]>

**Comment by sy-records** [comment]
走安装程序时会进行替换，你这是直接执行吗？
