### ISSUE TITLE
如何解决评论区邮件地址和URL地址存在XSS漏洞？

### ISSUE THREAD

**Issue by Winyer** [typecho/typecho#1580]
### 1. 该问题的重现步骤是什么？
无
### 2. 你期待的结果是什么？实际看到的又是什么？
解决XSS问题
### 3. 问题出现的环境
TE1.2
- 操作系统版本：无
- Apache/NGINX 版本：无
- 数据库版本：误
- PHP 版本：无
- Typecho 版本：1.2
- 浏览器版本：无
- 

如题，听说有个反垃圾评论的插件能够直接解决问题，无需修改文件代码，有大佬提供下插件名字或者地址吗？

[//]: # (如有图片请附上截图)

**Comment by Junehck** [comment]
https://blog.mo60.cn/index.php/archives/Typecho-1-2-xss2rce.html

**Comment by sy-records** [comment]
升级1.2.1-rc2版本；或者手动打补丁，找到对应修复的commit https://github.com/typecho/typecho/compare/v1.2.1-rc...v1.2.1-rc.2
