### ISSUE TITLE
站点地址文章链接bug

### ISSUE THREAD

**Issue by 929126387** [typecho/typecho#1581]
站点地址我更新为域名+端口
![image](https://github.com/typecho/typecho/assets/77496052/b9015b0c-cdc0-4352-b06a-517b6d05963b)
然后保存，点文章链接 ，后面没有端口 是怎么回事
![image](https://github.com/typecho/typecho/assets/77496052/98c58668-b82c-400f-8739-af3ed1318b01)

**Comment by sy-records** [comment]
检查下你有没有配置`__TYPECHO_SITE_URL__`，`__TYPECHO_DYNAMIC_SITE_URL__`。
以及openresty的配置项
