### ISSUE TITLE
中文域名无法正常设设置站点地址

### ISSUE THREAD

**Issue by 11195666** [typecho/typecho#1583]
### 1. 该问题的重现步骤是什么？
站点使用中文域名，在基本设置里填写中文punycode转码域名，会提示当前站点与设置不符。
### 2. 你期待的结果是什么？实际看到的又是什么？
访问中文域名/admin后，会跳转到ip/admin，请问如何设置，才能正常使用：中文域名/admin访问后台？

**Comment by 11195666** [comment]
![图1](https://phozhen.tengzhou.ren/phozhen85B799FF-4887-412A-B343-7E1ABFD54087.jpeg-phozhen)
图1后台地址填写中文域名后报错。

![图2](https://phozhen.tengzhou.ren/phozhenC984D182-477D-491C-AAA9-B4E6C79A26FB.jpeg-phozhen)
图2，使用中文域名/admin会自动跳转到ip/admin

**Comment by sy-records** [comment]
Duplicate of #1260
