### ISSUE TITLE
“do=checkVersion”和“do=feed”参数HTTP状态码403错误

### ISSUE THREAD

**Issue by AkarinLiu** [typecho/typecho#1585]
### 1. 该问题的重现步骤是什么？
在火狐浏览器按下F12，点击“网络”选项卡，刷新页面，发现有两个403错误：
```
do=checkVersion
do=feed
```
### 2. 你期待的结果是什么？实际看到的又是什么？
期待的结果是以上两个参数的HTTP状态码为200 OK，实际上看到的是403 Forbidden

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 22.04.2 LTS
- Apache/NGINX 版本：nginx/1.18.0 (Ubuntu)
- 数据库版本：10.6.12-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04
- PHP 版本：PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
- Typecho 版本：1.2.0
- 浏览器版本：Mozilla Firefox 113.0.2 (64 位)

[//]: # (如有图片请附上截图)
![火狐浏览器版本号](https://github.com/typecho/typecho/assets/58081491/37ee7a24-c4fc-4bef-8ae4-1d4d5e44546c)
![PHP版本](https://github.com/typecho/typecho/assets/58081491/e83dcc4d-ea7c-4290-a3fd-ebff41bb4a48)

**Comment by sy-records** [comment]
403是无权限，以checkVersion为例，需要editor用户组权限，否则访问时就是403，自己检查一下。
