### ISSUE TITLE
合规化

### ISSUE THREAD

**Issue by cherinyy** [typecho/typecho#1592]
### 1. 该问题的重现步骤是什么？
N/A

### 2. 你期待的结果是什么？实际看到的又是什么？

比如若要在[全国互联网安全管理服务平台](https://www.beian.gov.cn/)备案交互式网站，则网站需要做到：

> - 实名制用户注册
> - 建立敏感字眼关键词库
> - 评论留言等功能需要人工审核
> - 日志必须留存六个月以上

再比如[《互联网用户账号名称信息管理规定（征求意见稿）》](http://www.cac.gov.cn/2021-10/26/c_1636843202454310.htm)第三章第十二条：

> 互联网用户账号服务平台应当以显著方式，在互联网用户账号信息页面展示账号IP地址属地信息。境内互联网用户账号IP地址属地信息需标注到省（区、市），境外账号IP地址属地信息需标注到国家（地区）。

以及[《互联网用户账号信息管理规定》](http://www.cac.gov.cn/2022-06/26/c_1657868775042841.htm)第二章第十二条：

> 互联网信息服务提供者应当在互联网用户账号信息页面展示合理范围内的互联网用户账号的互联网协议（IP）地址归属地信息，便于公众为公共利益实施监督。

### 3. 问题出现的环境

N/A

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
敏感词库可以通过插件实现，评论审核现在是有的。
日志在nginx上实现。
