### ISSUE TITLE
希望后台能修改访客IP获取方式

### ISSUE THREAD

**Issue by Suxiaoqinx** [typecho/typecho#1593]
> 希望typecho后续更新计划 能在后台加个像wp那样的修改后台访客IP获取(在CDN下) 
![123456](https://img1.imgtp.com/2023/06/23/EOMYoijY.png)

**Comment by Suxiaoqinx** [comment]
> 希望typecho后续更新计划 能在后台加个像wp那样的修改后台访客IP获取(在CDN下) 
![123456](https://img1.imgtp.com/2023/06/23/EOMYoijY.png)

**Comment by joyqi** [comment]
这是个非常有用的功能

**Comment by sy-records** [comment]
这个应该是主题或者插件加上吧？WordPress哪个版本的设置是这样子？

在 Typecho 中可以定义`__TYPECHO_IP_SOURCE__`来指定使用那个头来获取IP。

https://github.com/typecho/typecho/blob/02937dc51ce706097a6dd183dccc874f0a7defc9/var/Typecho/Request.php#L371-L390

**Comment by Suxiaoqinx** [comment]
> 这个应该是主题或者插件加上吧？WordPress哪个版本的设置是这样子？
> 
> 在 Typecho 中可以定义来指定使用那个头来获取IP。`__TYPECHO_IP_SOURCE__`
> 
> https://github.com/typecho/typecho/blob/02937dc51ce706097a6dd183dccc874f0a7defc9/var/Typecho/Request.php#L371-L390

不好意思 刚发现可以定义__TYPECHO_IP_SOURCE__😂
