### ISSUE TITLE
Vercel安装时出现error

### ISSUE THREAD

**Issue by BytesPirate** [typecho/typecho#1595]
### 1. 该问题的重现步骤是什么？

使用 vercel 正常部署，在安装到第三步时输入管理员账户密码之后出现 error 错误

### 2. 你期待的结果是什么？实际看到的又是什么？

期待出现成功的画面，目前不管修改数据库或者其他的也好出现了error错误

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

![image](https://github.com/typecho/typecho/assets/74055444/12f16773-e620-46f4-a41f-7a7f575872b4)

**Comment by sy-records** [comment]
需要提供下错误日志

**Comment by 24021438** [comment]
> 需要提供下错误日志

我感觉是ssl在作妖，应该默认模式关闭ssl，而不是让你自己选，vercel 配置了 'sslVerify' => false,  不会映射过去所以就安装不了err

**Comment by JIeJaitt** [comment]
我安装是没有问题的，能说下你详细的安装步骤嘛 @BytesPirate

**Comment by BytesPirate** [comment]
1. 首先fork到自己的仓库
2. 然后修改数据库配置为自己的Mysql配置
3. 部署到Vercel
4. 按照提示一步步的运行
5. 然后在创建管理员账号时出现这个问题

ps：使用的是 Vercel 进行部署的，而不是在服务器上部署。

**Comment by sy-records** [comment]
MySQL是自己的数据库，配置远程访问？

可以打开`debug`看下具体错误信息堆栈，打开 F12 看 network 里的请求。

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by JIeJaitt** [comment]
@BytesPirate 你的数据库是哪里的？查下里面是不是已经有表了，如果有的话建议删了重新建一个库

**Comment by BytesPirate** [comment]
数据库是docker安装配置的，配置了一个公网IP进行访问的。谢谢建议，等周末去试验一下。 @sy-records @JIeJaitt

**Comment by JIeJaitt** [comment]
@sy-records @BytesPirate 我感觉应该不是数据库能不能远程访问的问题，如果不能远程访问，应该直接报错连接错误的，没有注册界面了

**Comment by BytesPirate** [comment]
数据库访问应该没有问题，后来我购买了腾讯云的云数据库依旧存在这个问题。

**Comment by sy-records** [comment]
等你测试，发个错误堆栈出来。

**Comment by JIeJaitt** [comment]
@BytesPirate 你的域名解析到了vercel相关项目嘛？建议安装前不要使用cdn之类缓存啥的。

详细的debug模式看看报错更清楚一些

**Comment by BytesPirate** [comment]
有了一个新的问题 ：😅
![image](https://github.com/typecho/typecho/assets/74055444/0a1d25d0-c9d5-40fe-b67c-3b5f666e8105)

**Comment by BytesPirate** [comment]
使用这个驱动产生的报错：
![image](https://github.com/typecho/typecho/assets/74055444/6eb0ef42-5a3e-475e-bdcf-98bffbe843f1)

**Comment by BytesPirate** [comment]
部署失败，无法复现，卡死在这一部分了，但是之前的问题应该是没有出现了。
![image](https://github.com/typecho/typecho/assets/74055444/1b9c9bc3-49e5-4981-b3d0-3870a9f2a664)
