### ISSUE TITLE
编辑文章界面无法保存自定义字段

### ISSUE THREAD

**Issue by Losses** [typecho/typecho#1597]
### 1. 该问题的重现步骤是什么？

打开任意文章进行编辑，添加自定义字段
发布文章

### 2. 你期待的结果是什么？实际看到的又是什么？

自定义字段应当被添加，但实际上没有

### 3. 问题出现的环境

- 操作系统版本：Windows
- Apache/NGINX 版本：Apache/2.4.56 
- 数据库版本：SQLite Library | 3.39.2
- PHP 版本：PHP/8.2.4
- Typecho 版本：1.2.1
- 浏览器版本：Vivaldi 6.1.3035.111 (Official Build) (64-bit)

[//]: # (如有图片请附上截图)
![typecho gif](https://github.com/typecho/typecho/assets/1384036/13e46b03-2c49-4409-9994-8f857cd55b12)

检查了网络请求，发现数据已经传到 PHP 这边了，但是没存到数据库里。

![image](https://github.com/typecho/typecho/assets/1384036/0357344e-d022-4fc1-8eb9-bc8f5cd963b4)

**Comment by sy-records** [comment]
Duplicate of #1574

**Comment by Losses** [comment]
@sy-records 我检查了源代码，和你标注的并不是同一个问题，请参看：

https://github.com/typecho/typecho/pull/1598
