### ISSUE TITLE
升级后提示500错误：Return value of Widget\Archive::getFeed()..

### ISSUE THREAD

**Issue by lielanyu** [typecho/typecho#1599]
### 1. 该问题的重现步骤是什么？
升级到1.2版本后

### 2. 你期待的结果是什么？实际看到的又是什么？
期待升级正常，看到500错误，网页提示内容“Return value of Widget\Archive::getFeed() must be an instance of Typecho\Feed, null returned”
### 3. 问题出现的环境
- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：mysql
- PHP 版本：7.2
- Typecho 版本：typecho1.2
- 浏览器版本：360极速浏览器

[//]: # (如有图片请附上截图)
/

**Comment by jozxing** [comment]
I also encountered the same problem

**Comment by lielanyu** [comment]
我今天试了，重新安装也不行，新的安装程序也是这样提示

**Comment by joyqi** [comment]
在`config.inc.php`里加入

```
define('__TYPECHO_DEBUG__', true);
```

刷新网页，把完整的错误信息发上来

**Comment by lielanyu** [comment]
Return value of Widget\Archive::getFeed() must be an instance of Typecho\Feed, null returned
TypeError: Return value of Widget\Archive::getFeed() must be an instance of Typecho\Feed, null returned in /home/nyeduico/public_html/XXXX.net/var/Widget/Archive.php:502
Stack trace:
#0 /home/nyeduico/public_html/XXXX.net/usr/plugins/Textends/Contents.php(143): Widget\Archive->getFeed()
#1 [internal function]: Textends_Contents::select(Object(Widget\Archive), Object(Typecho\Db\Query))
#2 /home/nyeduico/public_html/XXXX.net/var/Typecho/Plugin.php(446): call_user_func_array(Array, Array)
#3 /home/nyeduico/public_html/XXXX.net/var/Widget/Archive.php(686): Typecho\Plugin->__call('Widget_Archive:...', Array)
#4 /home/nyeduico/public_html/XXXX.net/var/Typecho/Widget.php(155): Widget\Archive->execute()
#5 /home/nyeduico/public_html/XXXX.net/var/Typecho/Router.php(96): Typecho\Widget::widget('Widget_Archive', NULL, NULL)
#6 /home/nyeduico/public_html/XXXX.net/index.php(23): Typecho\Router::dispatch()
#7 {main}

**Comment by lielanyu** [comment]
> 在`config.inc.php`里加入
> 
> ```
> define('__TYPECHO_DEBUG__', true);
> ```
> 
> 刷新网页，把完整的错误信息发上来

Return value of Widget\Archive::getFeed() must be an instance of Typecho\Feed, null returned
TypeError: Return value of Widget\Archive::getFeed() must be an instance of Typecho\Feed, null returned in /home/nyeduico/public_html/XXXX.net/var/Widget/Archive.php:502
Stack trace:
#0 /home/nyeduico/public_html/XXXX.net/usr/plugins/Textends/Contents.php(143): Widget\Archive->getFeed()
#1 [internal function]: Textends_Contents::select(Object(Widget\Archive), Object(Typecho\Db\Query))
#2 /home/nyeduico/public_html/XXXX.net/var/Typecho/Plugin.php(446): call_user_func_array(Array, Array)
#3 /home/nyeduico/public_html/XXXX.net/var/Widget/Archive.php(686): Typecho\Plugin->__call('Widget_Archive:...', Array)
#4 /home/nyeduico/public_html/XXXX.net/var/Typecho/Widget.php(155): Widget\Archive->execute()
#5 /home/nyeduico/public_html/XXXX.net/var/Typecho/Router.php(96): Typecho\Widget::widget('Widget_Archive', NULL, NULL)
#6 /home/nyeduico/public_html/XXXX.net/index.php(23): Typecho\Router::dispatch()
#7 {main}

**Comment by joyqi** [comment]
看起来是 `Textends` 这个插件的调用问题

**Comment by lielanyu** [comment]
> 

解决了，谢谢，是我不够仔细
