### ISSUE TITLE
永久链接格式问题

### ISSUE THREAD

**Issue by wankey** [typecho/typecho#160]
我把网站安装在了/puublic_html/planet下面，首页为[http://wangqige.com/planet/](http://wangqige.com/planet/)，这个现在没有问题，但是当我进入文章页面发现，文章页面的链接是[http://wangqige.com/planet/index.php/default/start.html](http://wangqige.com/planet/index.php/default/start.html)，中间出现了**/index.php**这个多余的部分，请问如何去除？

**Comment by ykla** [comment]
同样问题，仍无法解决
