### ISSUE TITLE
SSL Support for PostgreSQL?

### ISSUE THREAD

**Issue by jerrita** [typecho/typecho#1600]
The default database provided by Vercel has SSL enabled.
Perhaps adding SSL support for PostgreSQL would be helpful.

**Comment by joyqi** [comment]
Please provide a example PostgreSQL connection URL on Vercel.

**Comment by jerrita** [comment]
Here is an js example:

```js
import pg from 'pg';

const { Pool } = pg;

const pool = new Pool({
  connectionString: process.env.PG_URL + "?sslmode=require",
})
```

with env:
```bash
PG_URL="postgres://default:xxx@xxx-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb"
```

I think maybe just add something like 'sslmode=require' in php is ok.
