### ISSUE TITLE
安装第三方主题后无法进入设置外观界面

### ISSUE THREAD

**Issue by hongjr03** [typecho/typecho#1601]
```
Typecho\I18n\GetText::translate(): Return value must be of type string, null returned
```

![image](https://github.com/typecho/typecho/assets/64763790/38a47a52-184a-4f32-89ee-79b6ed45cf59)

### 问题出现的环境

- 操作系统版本：Debian GNU/Linux 10 x86_64(Py3.7.9)
- PHP 版本：7.4和8.1均尝试过
- Typecho 版本：1.2.1

**Comment by sy-records** [comment]
请反馈给主题作者，有语言项没翻译到。
