### ISSUE TITLE
🙈如何使用php实现上传附件的功能？

### ISSUE THREAD

**Issue by ScarletDor** [typecho/typecho#1603]
我已经使用$security->getIndex('/action/upload')得到上传接口了，想使用curl将图片上传到附件

$picUrl是图片地址，
$uploadUrl是$security->getIndex的上传接口，都能正常得到想要的值

方便的话，可以创建一个ty页面模板，然后放上这些代码，访问这个页面之后，就会看到返回了403

```
    $picUrl = 'https://api.mmbkz.cn/ziyuan/ads.png';
    $picContent = file_get_contents($picUrl);
    
    Typecho_Widget::widget('Widget_Security')->to($security);
    $uploadUrl = $security->getIndex('/action/upload?cid='.$this->cid);
    
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $uploadUrl);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $picContent);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $response = curl_exec($ch);
    $HTTP = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    echo $HTTP.'<br>';
    echo $response.'<br>';
    echo $uploadUrl.'<br>';
```
为什么返回了状态码403？

我使用js的方式很容易上传图片附件，但是使用php却不行。

请问如何使用php，并搭配typecho的`$security->getIndex('/action/upload')`实现上传附件的功能呢

非常感谢！

希望有大佬帮忙解答！！

**Comment by kkdcn** [comment]
🙈

**Comment by ScarletDor** [comment]
方便的话，可以创建一个ty页面模板，然后放上这些代码，你就会看到返回了403

**Comment by air713** [comment]
返回状态码403通常表示服务器拒绝了请求，这可能是因为权限问题或者安全机制导致的。以下是几个可能的原因和解决方法：

1. 权限问题：请确保你有足够的权限进行文件上传操作。你可以检查上传接口的权限设置，确保你具有上传文件的权限。

2. 安全机制：有些网站会实施安全机制来限制文件上传操作。你可以检查你的服务器或应用程序的安全设置，确保允许文件上传操作。

3. 请求头设置：有时服务器需要特定的请求头信息才能处理上传请求。你可以尝试在curl请求中添加一些必要的请求头信息，例如User-Agent、Referer等。

4. 文件大小限制：服务器可能对上传文件的大小有限制。你可以检查服务器设置或应用程序设置，确保上传的文件大小在允许范围内。

此外，你在代码中使用了`file_get_contents()`函数来获取图片内容，并将其作为POST请求的数据发送。你可以尝试将`CURLOPT_POSTFIELDS`参数设置为数组格式，以便更好地传递文件和其他数据。例如：

```php
$picContent = file_get_contents($picUrl);

$data = array(
    'file' => new CURLFile($picContent, mime_content_type($picUrl), basename($picUrl))
);

// 设置POST数据
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
```

另外，请确保`$this->cid`的值是正确的，并且`$uploadUrl`的值是有效的上传接口地址。

**Comment by ScarletDor** [comment]
> 返回状态码403通常表示服务器拒绝了请求，这可能是因为权限问题或者安全机制导致的。以下是几个可能的原因和解决方法：
> 
> 1. 权限问题：请确保你有足够的权限进行文件上传操作。你可以检查上传接口的权限设置，确保你具有上传文件的权限。
> 2. 安全机制：有些网站会实施安全机制来限制文件上传操作。你可以检查你的服务器或应用程序的安全设置，确保允许文件上传操作。
> 3. 请求头设置：有时服务器需要特定的请求头信息才能处理上传请求。你可以尝试在curl请求中添加一些必要的请求头信息，例如User-Agent、Referer等。
> 4. 文件大小限制：服务器可能对上传文件的大小有限制。你可以检查服务器设置或应用程序设置，确保上传的文件大小在允许范围内。
> 
> 此外，你在代码中使用了`file_get_contents()`函数来获取图片内容，并将其作为POST请求的数据发送。你可以尝试将`CURLOPT_POSTFIELDS`参数设置为数组格式，以便更好地传递文件和其他数据。例如：
> 
> ```
> $picContent = file_get_contents($picUrl);
> 
> $data = array(
>     'file' => new CURLFile($picContent, mime_content_type($picUrl), basename($picUrl))
> );
> 
> // 设置POST数据
> curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
> ```
> 
> 另外，请确保`$this->cid`的值是正确的，并且`$uploadUrl`的值是有效的上传接口地址。

谢谢，gpt我也问了，没啥用，而且感觉和文件类型没有关系，因为js都没有指定文件类型

**Comment by ScarletDor** [comment]
@joyqi 求大佬百忙之中帮我解答一下，不知道是不是typecho禁止了php使用上传接口，整的头疼，谢谢大佬的帮助qaq，打扰了

**Comment by sy-records** [comment]
你要用curl的话，需要携带cookie，已经提示403了。

在Typecho中使用的话，可以使用`\Widget\Upload::uploadHandle`。

**Comment by ScarletDor** [comment]
> 你要用curl的话，需要携带cookie，已经提示403了。
> 
> 在Typecho中使用的话，可以使用`\Widget\Upload::uploadHandle`。

啊啊啊，我也是刚试出来需要cookie，刚打算放弃，就看到你提出的什么`\Widget\Upload::uploadHandle`，我赶紧试一试，太感谢了！！

**Comment by ScarletDor** [comment]
没解决啊大佬，我还没成功呢qaq

**Comment by ScarletDor** [comment]
唉，我试了半天还是不太会用，烦劳老哥可否帮我改一下代码呢。总是出现莫名其妙的错误。之所以用/action/upload我是想这样就可以直接搭配七牛那些插件了。我自己改的好像和插件也冲突了，实在不清楚怎么修改了。

真的麻烦老哥了qaq，我抠了好几天了已经，老哥辛苦啦qaq @sy-records

**Comment by ScarletDor** [comment]
> 你要用curl的话，需要携带cookie，已经提示403了。
> 
> 在Typecho中使用的话，可以使用`\Widget\Upload::uploadHandle`。

唉，我试了半天还是不太会用，烦劳老哥可否帮我改一下代码呢。总是出现莫名其妙的错误。之所以用/action/upload我是想这样就可以直接搭配七牛那些插件了。我自己改的好像和插件也冲突了，实在不清楚怎么修改了。

真的麻烦老哥了qaq，我抠了好几天了已经，老哥辛苦啦qaq

**Comment by sy-records** [comment]
不知道你想干啥。为什么要在页面模板里上传文件？？？
上传可以参考我之前写的七牛云插件。https://github.com/sy-records/KodoForTypecho/blob/master/Plugin.php

**Comment by ScarletDor** [comment]
> 不知道你想干啥。为什么要在页面模板里上传文件？？？ 上传可以参考我之前写的七牛云插件。https://github.com/sy-records/KodoForTypecho/blob/master/Plugin.php

我想使用微信公众号发图片，用php接收将图片（能得到微信的图片的临时地址）存为附件，然后再将返回的图片地址加到评论里。本来一起都很顺利的但是没想到403了。于是我就把这部分单独拿出来问问怎么解决。要是解决了的话，我就可以继续接下来的把得到的图片地址写到评论区里展示出来了qaq

**Comment by ScarletDor** [comment]
> 不知道你想干啥。为什么要在页面模板里上传文件？？？ 上传可以参考我之前写的七牛云插件。https://github.com/sy-records/KodoForTypecho/blob/master/Plugin.php

哇，成功了！感谢老哥！！亲亲抱抱举高高！

**Comment by ScarletDor** [comment]
> 你要用curl的话，需要携带cookie，已经提示403了。
> 
> 在Typecho中使用的话，可以使用`\Widget\Upload::uploadHandle`。

哇，成功了！感谢老哥！！亲亲抱抱举高高！

**Comment by ScarletDor** [comment]
> 你要用curl的话，需要携带cookie，已经提示403了。
> 
> 在Typecho中使用的话，可以使用`\Widget\Upload::uploadHandle`。

老哥打扰一下，昨天试了一晚上，但是发现了一个问题。uploadHandle方法里移动文件使用了move_uploaded_file，我这种已知图片地址而不是用post上传的图片是不是不能用了，不改ty代码的话有没有办法解决呢（我把move_uploaded_file改成copy就可以用了，但是想尽量不碰ty的代码）

ty不是很熟，实在打扰老哥啦
