### ISSUE TITLE
在打开后台时候出现获取官方日志和最新版本错误

### ISSUE THREAD

**Issue by saga0324** [typecho/typecho#1604]
### 1. 该问题的重现步骤是什么？
在打开后台时候出现获取官方日志和最新版本错误

### 2. 你期待的结果是什么？实际看到的又是什么？
可以正常获取到日志和更新版本，但实际只能得到“读取中...”提示

### 3. 问题出现的环境

- 操作系统版本：Alpine Linux v3.18.2
- Apache/NGINX 版本：1.24.0
- 数据库版本：SQLite 3.41.2
- PHP 版本：8.2.8
- Typecho 版本：1.2.1
- 浏览器版本：Edge 114

[//]: # (如有图片请附上截图)
![image](https://github.com/typecho/typecho/assets/13547503/4913c21e-7dea-4091-aeb0-0076ec7058ef)
如果打开DEBUG FEATURE则输出如图日志
直接访问ajax?do=checkVersion或者feed则会直接跳到首页
如果关闭DEBUG FEATURE则会提示403
![image](https://github.com/typecho/typecho/assets/13547503/52a77b2d-87da-4d65-b077-812d69eb346d)

**Comment by sy-records** [comment]
当前访问者的权限不够，需要订阅者或编辑以上

**Comment by saga0324** [comment]
> 当前访问者的权限不够，需要订阅者或编辑以上

是管理员权限，全新安装也是如图报错

**Comment by sy-records** [comment]
php 没有curl 扩展吧

**Comment by saga0324** [comment]
> php 没有curl 扩展吧

感谢回复，的确是因为这个原因，自己编译的PHP裁剪过了头，没有留意到这个细节

**Comment by sy-records** [comment]
看到这里发现的

https://github.com/typecho/typecho/blob/d9c54cca539a24911423a36986a69e430144ddf3/var/Typecho/Http/Client.php#L391
