### ISSUE TITLE
Class "TypechoPlugin\Markdown" not found

### ISSUE THREAD

**Issue by qt06** [typecho/typecho#1606]
### 1. 该问题的重现步骤是什么？
这个报错出现在打开不是用 markdown 编写的旧文章页面的时候。
### 2. 你期待的结果是什么？实际看到的又是什么？
预期是正常显示文章内容。而现在是出现500报错页面，就一行：Class "TypechoPlugin\Markdown" not found
### 3. 问题出现的环境

- 操作系统版本：centos8
- Apache/NGINX 版本：Caddy2.6
- 数据库版本：maridb
- PHP 版本：8.0
- Typecho 版本：最新的github仓库
- 浏览器版本：edge 114

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
是否用了什么插件，在`config.inc.php`里加上一行

```php
define('__TYPECHO_DEBUG__', true);
```

然后看看具体报错

**Comment by qt06** [comment]
已解决，的确是插件的问题。我的友情链接插件调用了 Markdown 累，因为现在这个累一动到了Utils下，所以就报错了。
