### ISSUE TITLE
评论进入待审核状态，对评论者不会有任何的提示

### ISSUE THREAD

**Issue by ShangJixin** [typecho/typecho#1608]
### 1. 该问题的重现步骤是什么？
评论一条会让其进入审核状态的评论

### 2. 你期待的结果是什么？实际看到的又是什么？
 - 期待结果：评论提交成功，评论者会在前台评论区看见自己的评论，并在该评论处提示”正在审核中“相关的字眼，而其他人无法在前台看见正在审核的评论

 - 实际结果：评论提交成功后，评论区没有评论增加，也不会提示评论者该评论正在审核

### 3. 问题出现的环境

- **切换到默认模板，问题也会是这样**

- 操作系统版本：Windows 11
- Apache/NGINX 版本：Nginx 1.22
- 数据库版本：MySQL 5.7
- PHP 版本：7.4
- Typecho 版本：1.2.1（正式版）
- 浏览器版本：版本 115.0.5790.171（正式版本） （64 位）

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
后台设置开启评论审核以后就有提示？

<img width="703" alt="image" src="https://github.com/typecho/typecho/assets/33931153/90dee8c5-29cc-4081-bbb2-f1b8efefa4ec">

**Comment by ShangJixin** [comment]
> 后台设置开启评论审核以后就有提示？
> 
> <img alt="image" width="703" src="https://user-images.githubusercontent.com/33931153/259635288-90dee8c5-29cc-4081-bbb2-f1b8efefa4ec.png">

对的是的是的就是它，但不知道是啥原因失效了

**Comment by sy-records** [comment]
检查下设置有没有开启，默认主题是有的，如果你用默认的都没有，那可能就是配置的问题了。

<img width="285" alt="image" src="https://github.com/typecho/typecho/assets/33931153/c7d69c6f-4e3f-4678-a0c1-b2cbcae3e534">

**Comment by ShangJixin** [comment]
破案了，但还是个BUG。刚才用个游客的身份评论，展示出了”等待审核“。发这个issue的时候，是用一个已登录的账号测试的（文章作者），感觉还是有BUG

**Comment by ShangJixin** [comment]
![Snipaste_2023-08-10_14-07-42](https://github.com/typecho/typecho/assets/21075413/2bdb0b9f-37c7-4521-96cb-0f84e77a26e3)
后台待审核评论列表

![Snipaste_2023-08-10_14-08-16](https://github.com/typecho/typecho/assets/21075413/8f2b5cb3-feeb-4c34-84ec-bd8ce7a23504)
游客的能正常显示

![Snipaste_2023-08-10_14-09-46](https://github.com/typecho/typecho/assets/21075413/f17bfadd-a150-4481-ab1a-8a51e1489e0d)
但对比于第一张图，少了两条已登录博主的待审核评论。第三张图是在博主登录之后截的图

**Comment by sy-records** [comment]
登录账号的权限呢？

https://github.com/typecho/typecho/blob/b989459d87df9cf0c50b010faf6123eea8c5314b/var/Widget/Feedback.php#L163-L164

**Comment by ShangJixin** [comment]
管理员权限。目前全站只有这么一个账号。但按正常来说也应该把这两条展示出来才对啊，刚才闹了个乌龙抱歉...

**Comment by sy-records** [comment]
🤔 管理员是怎么进入待审核的？

**Comment by ShangJixin** [comment]
插件判的（好吧可能从te主程序设计的这个角度来看，这个行为就不像是正常人能做出来的哈哈哈哈哈）
