### ISSUE TITLE
插件开发代码错误，导致后台无法禁用插件，显示配置信息没有找到

### ISSUE THREAD

**Issue by guugg** [typecho/typecho#1609]
### 1. 该问题的重现步骤是什么？
在测试命名空间自动导入过程中；使用未定义的变量，启动插件出错后不能恢复（把未定义的变量删除也不能恢复）。 只能先删除接口，如果我是往`Typecho\Plugin::factory('admin/menu.php')->navBar`插入的，就必须到`men.php`删除`<?php \Typecho\Plugin::factory('admin/menu.php')->navBar(); ?>`接口，才能正常进入后台禁用插件重新激活。

### 2. 你期待的结果是什么？实际看到的又是什么？
正常出错的插件是启动不了的。使用未定义的变量，插件成功启动了。

### 3. 问题出现的环境

- 操作系统版本：win11
- Apache/NGINX 版本：NGINX 1.16
- 数据库版本：mysql5..7
- PHP 版本：8.2.6
- Typecho 版本：GitHub最新
- 浏览器版本：Google Chrome

![屏幕截图 2023-08-20 222109.png](https://x.imgs.ovh/x/2023/08/20/64e223ad5f09b.png)

**Comment by sy-records** [comment]
复现代码是什么？

**Comment by guugg** [comment]
> 复现代码是什么？

- 似乎只要使用`未定义的`都会这样。比如说我先在`Plugin.php`文件添加一个未定义函数（在`option.php`文件还没有添加一个函数）：
```
require_once 'app/option.php';

class Plugin implements PluginInterface
{
...
...
...
    /**
     * 获取插件配置面板
     *
     * @param Form $form 配置面板
     */
    public static function config(Form $form)
    {
        myFunction();
    }
...
...
...

}
```

- 我以为我写了这个函数，当点启动插件后就无法禁用插件了。

>  当然如果使用编辑器敲代码一般都会提示`未定义`的错误。

出现这种错误我只能先删除插件接口，把插件禁用。添加插件接口回去，删除未定义重新激活就正常了。

**Comment by guugg** [comment]
> 

第一次的出错，我认为是我本地出现问题了，我重新安装了一般typecho。重试后才知道的。

**Comment by sy-records** [comment]
我用你的代码，后台没问题，前台访问时会提示配置信息找不到。
实际上`/var/Widget/Options.php:366`看这个代码应该就知道问题出在哪里了，配置信息没找到
