### ISSUE TITLE
typecho网站突然出现Mysql is not available

### ISSUE THREAD

**Issue by lielanyu** [typecho/typecho#1616]
### 1. 该问题的重现步骤是什么？
突然出现，毫无征兆，无论是打开网站首页还是后台，都提示Adapter \Typecho\Db\Adapter\Pdo\Mysql is not available

### 2. 你期待的结果是什么？实际看到的又是什么？
期待正常的页面显示结果

### 3. 问题出现的环境

- 操作系统版本：linux
- Apache/NGINX 版本：2.4.57
- 数据库版本：8.0.34
- PHP 版本：PHP 7.3
- Typecho 版本：1.1
- 浏览器版本：360极速浏览器
打开网站首页显示：

![微信截图_20230916211454](https://github.com/typecho/typecho/assets/138767744/cd34fca9-a48d-486c-b3c3-3165f3f8e63b)
config.inc.php第22行左右内容
![aaa_20230916212221](https://github.com/typecho/typecho/assets/138767744/ffa8f010-4671-4b3b-8aa0-54fd51f49497)

**Comment by 1Q23LYC45** [comment]
是否升级了新版php软件或改了web服务器配置？还能回忆一下出现问题之前你执行的操作吗？
看起来，像是PHP的Pdo MySQL插件挂了。不过，如果问题出现之前你没做任何操作的话，大概率是硬盘有问题了。
平时最好定时备份一下网站，要是SQLite可以把数据库也备份下，毕竟数据无价。

**Comment by sy-records** [comment]
需要更详细的信息，如果没有什么操作，那可能是你服务器被人黑了 🤔

**Comment by xiamuguizhi** [comment]
@chatgtp4

这个问题可能是由于 PHP 的 MySQL 扩展没有被正确安装或启用导致的。"Adapter \Typecho\Db\Adapter\Pdo\Mysql is not available"的错误提示意味着 Typecho 无法找到用来连接 MySQL 数据库的 PHP 扩展。

下面是一些可能的解决步骤：

1. **检查 PHP 的 MySQL 扩展是否已经安装并启用。** 你可以创建一个包含 `<?php phpinfo(); ?>` 的 PHP 文件，然后通过浏览器访问这个文件来查看 PHP 的配置信息。在输出的信息中，你应该能看到关于 PDO 和 PDO_MYSQL 的部分。如果这些部分不存在，那么就说明 PHP 的 MySQL 扩展没有被正确安装或启用。

2. **安装或启用 PHP 的 MySQL 扩展。** 如果你发现 PHP 的 MySQL 扩展没有被安装或启用，你需要根据你的操作系统和 PHP 的版本来安装或启用它。具体的步骤可能会有所不同，你可以在网上搜索相关的教程。

3. **检查 Typecho 的配置文件。** Typecho 的配置文件是 `config.inc.php`，它位于 Typecho 的安装目录下。你需要检查这个文件中的数据库配置是否正确。特别是 `adapter` 选项，它应该被设置为 `Mysql`。

4. **重启你的 web 服务器。** 在修改了 PHP 的配置或 Typecho 的配置文件之后，你需要重启你的 web 服务器以使这些改动生效。

如果以上的步骤都不能解决你的问题，那么可能需要更深入地调查问题的原因。你可以尝试查看你的服务器的错误日志，或者使用 PHP 的错误报告功能来获取更多的信息。
