### ISSUE TITLE
支持PHP8.1吗？

### ISSUE THREAD

**Issue by ymc0182** [typecho/typecho#1617]
我用php8.1一堆报错，好像大部分是数据库这块的，8.0正常。

**Comment by 1Q23LYC45** [comment]
支持呀 我用的SQLite完全没问题 MySQL未测试。

**Comment by ymc0182** [comment]
> 支持呀 我用的SQLite完全没问题 MySQL未测试。本人PHP8.2.8

我用的mysql8.0

**Comment by 1Q23LYC45** [comment]
> > 支持呀 我用的SQLite完全没问题 MySQL未测试。本人PHP8.2.8
> 
> 我用的mysql8.0

好像版本太高，我最常用的还是5.7.34和5.6.38

**Comment by ymc0182** [comment]
> > > 支持呀 我用的SQLite完全没问题 MySQL未测试。本人PHP8.2.8
> > 
> > 
> > 我用的mysql8.0
> 
> 好像版本太高，我最常用的还是5.7.34和5.6.38

我没仔细看报错，不应该是mysql的原因吧，用php8.0好着，8.1就报错了

我回头好好看下

**Comment by sy-records** [comment]
可以把错误信息贴出来。
