### ISSUE TITLE
希望把请求地址全部采用相对路径来代替

### ISSUE THREAD

**Issue by 1Q23LYC45** [typecho/typecho#1618]
### 1. 该问题的重现步骤是什么？
使用站点地址127.0.0.1安装Typecho，然后打开内网穿透。内网穿透后，用其他设备访问，网站挂了。请求全被跳转成127.0.0.1。登录后台修改站点地址后网站恢复。不过我内网穿透的地址两个小时就无效了，总不能每两个小时改一次地址吧？太麻烦了。希望请求地址全部采用相对路径来代替，摆脱网站固定地址。
### 2. 你期待的结果是什么？实际看到的又是什么？
希望正常打开网站，不用改地址。
但我打开的是纯文本网站，超链接也全挂了。
### 3. 问题出现的环境

- 操作系统版本："Linux localhost 4.14.116 SMP PREEMPT Wed Dec 1 10:44:17 CST 2021 aarch64 Android"
- Apache/NGINX 版本：lighttpd/1.4.71
- 数据库版本：SQLite3
- PHP 版本：8.2.8
- Typecho 版本：1.2.1
- 浏览器版本：所有浏览器全部这样

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
试试定义下`__TYPECHO_SITE_URL__`

**Comment by 1Q23LYC45** [comment]
不行呀，看图，图一是Frp系列（freefrp），图二是SSH系列（内网云)
![alt picture1](https://github-production-user-asset-6210df.s3.amazonaws.com/143373643/268629343-fdf3e1fa-7b5c-4610-818b-ae2e90ce21db.jpg)
![alt pic2](https://github-production-user-asset-6210df.s3.amazonaws.com/143373643/268629428-77568e33-6a04-4caf-bd71-b8016a97de76.jpg)
