### ISSUE TITLE
Centos 9 Stream 安装提示“attempt to write a readonly database”

### ISSUE THREAD

**Issue by gasensorX** [typecho/typecho#1620]
### 1. 该问题的重现步骤是什么？
在VPS Linux环境中安装1.2.1版本提示“attempt to write a readonly database”。使用sqlite原生函数连接。确认数据库文件本身可写。
所有程序（php httpd）使用系统自带源。

### 3. 问题出现的环境

- 操作系统版本：
- Centos 9 Stream x64   Linux version 5.14.0-325.el9.x86_64 (mockbuild@x86-05.stream.rdu2.redhat.com) 
- Apache/NGINX 版本： Apache/2.4.57 (CentOS Stream)
- 数据库版本：SQLite version 3.34.1 2021-01-20 14:10:07
- PHP 版本：PHP 8.0.27 (cli) (built: Jan  3 2023 16:17:26) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.27, Copyright (c), by Zend Technologies

- Typecho 版本： 1.2.1
- 浏览器版本：firefox 

[//]: # (如有图片请附上截图)
没找到上传图片的位置。

**Comment by sy-records** [comment]
检查下sqlite db的文件权限，你用原生函数链接的访问方式是cgi访问还是cli访问?

**Comment by gasensorX** [comment]
问题已解决。

Typecho不仅仅需要数据库文件本身可读可写，**数据库文件所在的目录也要有写权限**。这一点没有任何提示。
