### ISSUE TITLE
Database Query Error

### ISSUE THREAD

**Issue by atomicrema** [typecho/typecho#1621]
### 1. 该问题的重现步骤是什么？
打开我的网站之后只有 “Database Query Error” 提示，我也无法进入管理后台，之前都是正常的
### 2. 你期待的结果是什么？实际看到的又是什么？
怎么解决这个问题，我搜了一些方法但是并不适用
### 3. 问题出现的环境
使用的虚拟主机所以不是很清楚...
- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：5.0.12
- PHP 版本：7.3
- Typecho 版本：1.2
- 浏览器版本：Microsoft Edge 117.0.2045.31 (正式版本) (64 位)

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
config.inc.php中配置下debug，完整错误信息发出来
