### ISSUE TITLE
简单实现了文章编辑器按Ctrl+S保存文章，但是应该与更优雅的实现？

### ISSUE THREAD

**Issue by MFWT** [typecho/typecho#1627]
### 1. 该问题的重现步骤是什么？

在文章编辑页面（admin/write-post.php）按下键盘的Ctrl+S

### 2. 你期待的结果是什么？实际看到的又是什么？

期待：文章被保存
实际：文章并没有被保存，反而是弹出来浏览器的保存页面框

### 3. 问题出现的环境

- 操作系统版本：Debian 12.0
- Apache/NGINX 版本：NGINX 1.24.0
- 数据库版本： MySQL 5.6.51
- PHP 版本：8.2.6
- Typecho 版本：1.2.1
- 浏览器版本：Chrome 117.0.5938.89

## 我的修复步骤
在write-post.php文件末端加入：
```html
<script>
    document.getElementById('text').addEventListener('keydown',function(e)
    {
        if (83 == e.keyCode && e.ctrlKey)
        { 
            e.stopPropagation();
            e.preventDefault()
            document.getElementById('btn-save').click() //这就是页面上的保存按钮
            return true;
        }
    })
</script>
```

就可以实现在textarea区域内按Ctrl+S时保存文章

显然，这个实现不太优雅（比如全屏编辑模式下按这个组合键提交表单的时候会退出全屏），顺便问一下作者大大是否有更好地实现？

**Comment by sy-records** [comment]
手动点击保存草稿的时候也会退出

**Comment by MFWT** [comment]
> 手动点击保存草稿的时候也会退出，因为请求保存后是跳转了页面

这个是提交方式的问题了，如果改用ajax（发送formdata）可能会好些？这样就可以免刷新提交

**Comment by sy-records** [comment]
see #1628

**Comment by joyqi** [comment]
在 `/admin/src/js/pagedown.js` 里，从`3027`行开始有关于快捷键的定义，在这里加上`Ctrl+S`或者`Meta+S`的定义最合适，按下后，触发一个`save`的`hook`，然后在`write-js.php`里实现这个`hook`。

**Comment by MFWT** [comment]
> see #1628

OK，这个确实好很多，谢谢指出

**Comment by MFWT** [comment]
> 在 `/admin/src/js/pagedown.js` 里，从`3027`行开始有关于快捷键的定义，在这里加上`Ctrl+S`或者`Meta+S`的定义最合适，按下后，触发一个`save`的`hook`，然后在`write-js.php`里实现这个`hook`。

这个感觉好一些，样式比较统一，也易于管理。

昨天晚上我急着用就没仔细看代码了，简简单单打了个小补丁就用上了，还是遵守下规范的好
