### ISSUE TITLE
登入不了

### ISSUE THREAD

**Issue by lcyeric123** [typecho/typecho#1630]
### 1. 该问题的重现步骤是什么？
ip/admin

### 2. 你期待的结果是什么？实际看到的又是什么？
可以登入

### 3. 问题出现的环境

- 操作系统版本：Linux ubuntu 20.04
- Apache/NGINX 版本：last
- 数据库版本：last
- PHP 版本：8.2.0
- Typecho 版本：0.9
- 浏览器版本：

[//]: # (如有图
![Screenshot_2023-09-27-20-14-06-833_com microsoft emmx](https://github.com/typecho/typecho/assets/122712295/ff7f7ba8-7d53-4a05-9ecd-acc5667ac77e)
片请附上截图)

**Comment by sy-records** [comment]
请描述清楚你的问题。

你截图的已经是登录状态。

**Comment by lcyeric123** [comment]
登入的用戶是一個空的

**Comment by lcyeric123** [comment]
我的 typecho blog兩天前是可以登入的不過不可以登出或登入

**Comment by lcyeric123** [comment]
我的 typecho blog兩天前是可以登入的不過不可以登出或登入

**Comment by lcyeric123** [comment]
> 请描述清楚你的问题。
> 
> 你截图的已经是登录状态。

**Comment by sy-records** [comment]
怎么复现问题？

**Comment by lcyeric123** [comment]
登入admin

**Comment by lcyeric123** [comment]
登入的是admin用戶

**Comment by sy-records** [comment]
复现不了。。。 你给一个可以稳定复现的方式吧

**Comment by lcyeric123** [comment]
好的

**Comment by lcyeric123** [comment]
安裝 git后有個 git 文件夾就登入不了

**Comment by lcyeric123** [comment]
[.git.zip](https://github.com/typecho/typecho/files/12774523/default.git.zip)

.git file

**Comment by sy-records** [comment]
你有走正常的安装流程吗？

**Comment by lcyeric123** [comment]
有

**Comment by sy-records** [comment]
https://myblog.lcyeric123.repl.co/index.php

你的web server配置可能有些问题，加上index.php可以访问

**Comment by lcyeric123** [comment]
也不可以
![Screenshot_2023-09-30-20-05-54-524_com.microsoft.emmx.jpg](https://github.com/typecho/typecho/assets/122712295/56bfd490-2a32-4a98-8a1c-94bd6f5e9290)

**Comment by lcyeric123** [comment]
也不可以



取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________

**Comment by sy-records** [comment]
https://myblog.lcyeric123.repl.co/index.php/start-page.html
![image](https://github.com/typecho/typecho/assets/33931153/4ec11277-e09e-4f60-9c35-d71deb369212)

**Comment by lcyeric123** [comment]
主頁不可以

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________
