### ISSUE TITLE
Typecho的永久链接不支持/?p={cid}这样带问号的格式

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#1637]
我是使用WordpressToTypecho将wp转成了typecho，但wp网址固定格式为`https://url/?p=123`，但我在typecho永久链接设置页面设置相同格式后发现无效，应该是带问号就不行，请问如何解决，主要是文章网址已经被收录了，变更网址不太好

**Comment by sy-records** [comment]
获取pathinfo的时候把参数去掉了，所以匹配不到。

https://github.com/typecho/typecho/blob/b28d5b7babb6e791d8945bb361e764bfa065cb20/var/Typecho/Request.php#L337-L339

**Comment by jrotty** [comment]
感谢，注释掉果然可以了，不知道这样改下有啥后果不😄

**Comment by sy-records** [comment]
得你试试了 不过看起来就是只用在匹配路由的地方了 😅

**Comment by jrotty** [comment]
应该问题不大，十分感谢😁

**Comment by jrotty** [comment]
补充下，还是有影响的，这样直接注释掉，get请求直接废了，主题启动都报错，不过我换了中思路，这样用排除法排除自己需要的参数就行了：
```php
        if (!strpos($requestUri, '?p=')&&!strpos($requestUri, '?cat=')&&!strpos($requestUri, '?page_id=')) {
        if ($pos = strpos($requestUri, '?')) {
            $requestUri = substr($requestUri, 0, $pos);
        }
        }
```
