### ISSUE TITLE
能否增加一个部分加密的功能？

### ISSUE THREAD

**Issue by livepu** [typecho/typecho#1638]
之前提交的一个pull
https://github.com/typecho/typecho/pull/1587
我想部分加密文章，但如果有图片的话，这个加密就会变得凌乱了。
不知如何处理呢？部分加密，还是很有需求的呢。

**Comment by joooqi** [comment]
Typecho 文章部分加密插件（PartiallyPassword）可以实现文章内部分加密的需求
