### ISSUE TITLE
登录时端口被舍弃

### ISSUE THREAD

**Issue by TSYMQMYST** [typecho/typecho#1645]
### 1. 该问题的重现步骤是什么？
需要监听非80端口
然后点击登录按钮
### 2. 你期待的结果是什么？实际看到的又是什么？
看下方的截图
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：mysql5.7
- PHP 版本：
- Typecho 版本：1.2.1
- 浏览器版本：

[//]: # (如有图片请附上截图)

<img width="798" alt="image" src="https://github.com/typecho/typecho/assets/129494079/14e48684-47f4-4d26-922d-9ca7af9064e9">
点击登录时应该携带网站的ip:port
可是实际情况把port忽略了

**Comment by sy-records** [comment]
没复现问题

<img width="320" alt="image" src="https://github.com/typecho/typecho/assets/33931153/227e7d06-8f22-4eac-b13b-ec6ee4588986">

**Comment by sy-records** [comment]
@Mapleshade20 感谢你的反馈，但是依旧没有复现问题。

![image](https://github.com/typecho/typecho/assets/33931153/f49598d7-a895-4fb3-a48b-2d559119800a)

**Comment by WuMe-sicx** [comment]
我也有相同问题。由于公网443和80不可用{IPV6}，我使用的端口是 (https) 441。
我能正常访问所用页面,但是访问后台admin的时候
默认是/admin 就可以正常访问了
但是套了cdn回源441,admin必须为/admin/才能进入后台登录页面

**Comment by WuMe-sicx** [comment]
> 我也有相同问题。由于公网443和80不可用{IPV6}，我使用的端口是 (https) 441。 我能正常访问所用页面,但是访问后台admin的时候 默认是/admin 就可以正常访问了 但是套了cdn回源441,admin必须为/admin/才能进入后台登录页面

### 解决问题了
原因nginx的301问题

**Comment by sy-records** [comment]
一般都是Nginx配置的问题，可以打印一下 `$_SERVER` 看看信息。

issue我先关闭了，有响应后再reopen

**Comment by mia0x75** [comment]
打印$_SERVER能看到什么分析呢？permalink不是应是后台设定的主机地址+typecho根据文章信息生成的片段吗？

```
  ["DOCUMENT_ROOT"]=>
  string(4) "/app"
  ["REMOTE_ADDR"]=>
  string(10) "172.18.0.1"
  ["REMOTE_PORT"]=>
  string(5) "11990"
  ["SERVER_SOFTWARE"]=>
  string(29) "PHP 8.2.18 Development Server"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["SERVER_NAME"]=>
  string(7) "0.0.0.0"
  ["SERVER_PORT"]=>
  string(2) "80"
  ["REQUEST_URI"]=>
  string(1) "/"
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["SCRIPT_NAME"]=>
  string(10) "/index.php"
  ["SCRIPT_FILENAME"]=>
  string(14) "/app/index.php"
  ["PHP_SELF"]=>
  string(10) "/index.php"
  ["HTTP_HOST"]=>
  string(20) "mydomain.com"
.
.
.
```

配置是反向代理，前面是OpenResty。只配置了HTTPS，跟HTTP->HTTPS的301无关吧？不管怎样，后台配置了主机，那permalink就应该只跟typecho有关吧？

**Comment by mia0x75** [comment]
跟 @Mapleshade20 问题一样，在var/Widget/Options.php增加define('__TYPECHO_ROOT_URL__', 'https://domain:port') 的确可以解决前台访问的问题。但后台无法登录。

```
    /**
     * 动态获取根目录
     *
     * @return string
     */
    protected function ___rootUrl(): string
    {
        // echo $this->request->getRequestRoot();
        $rootUrl = defined('__TYPECHO_ROOT_URL__') ? __TYPECHO_ROOT_URL__ : $this->request->getRequestRoot();

        if (defined('__TYPECHO_ADMIN__')) {
            /** 识别在admin目录中的情况 */

            $adminDir = '/' . trim(defined('__TYPECHO_ADMIN_DIR__') ? __TYPECHO_ADMIN_DIR__ : '/admin/', '/');
            // $rootUrl = substr($rootUrl, 0, - strlen($adminDir));
        }

        return $rootUrl;
    }
```
注释掉$rootUrl这行，后台可以访问。保留这行代码，至少针对当前的场景，可以确定一定存在BUG。

然后后台可以正常访问，但不能登录，只要Login就会发生302。
![截图 2024-04-17 17-31-46](https://github.com/typecho/typecho/assets/5111356/dcee797a-2984-405e-9ca0-2701bbaa7b68)

问题就一定是在Login action里面，后来发现
```
    /**
     * 初始化函数
     *
     * @access public
     * @return void
     */
    public function action()
    {
        // protect
        // $this->security->protect();
```

$this->security->protect();会导致302，注释掉就可以登录了。当然，这个仅仅是个治标不治本的办法，更底层的问题，有待owner进一步查证。

总结一下，针对当前这个问题，需要改3处。

**Comment by sy-records** [comment]
@mia0x75 在你的 #1760 下回复。

提供可复现的环境，我可以帮你看。
