### ISSUE TITLE
 Typecho -- IDOR 漏洞

### ISSUE THREAD

**Issue by JTZ-a** [typecho/typecho#1652]
# 描述
在使用管理员登录 typecho 网站后， 我们可以在 `/admin/manage-pages.php` 创建一个独立页面， 同时用户可以在此设置页面是否将文件隐藏， 但是这仅仅是在前端进行了隐藏， 对应的页面 URL 并没有改变， 此时如果用户了解网站创建页面的 URL 结构， 那么依旧可以进行访问
# 验证
首先我们需要创建两个独立页面，观察页面的显示我们可以了解到默认的页面 URL 地址结构 `localhost/index.php/{}.html`
![image-20231128155908645](https://github.com/typecho/typecho/assets/86032434/b1513929-c15d-48a4-afbc-2da16d454d05)
之后选择将其中一个页面进行隐藏
![image-20231128155434629](https://github.com/typecho/typecho/assets/86032434/edd66c53-b37e-4157-9f93-c23723cabb8e)
之后开启一个无痕浏览器重新访问站点， 在这里可以看到网站页面显示两个首页栏， 第二个是我们创建的独立页面， 同时可以发现我创建的隐藏页面并没有显示在其中
![image-20231128155544957](https://github.com/typecho/typecho/assets/86032434/b6baf5e2-c162-4fe0-a3be-003057d6f2d1)
同时查看网站的 URL 地址 `http://localhost/index.php/5.html` , 这里的 5 就是 IDOR 漏洞的位置， 之后开始访问 `http://localhost/index.php/6.html` 我们就可以发现对应的网站页面
![image-20231128155745579](https://github.com/typecho/typecho/assets/86032434/961e1316-9079-47f7-a2c7-1cc616e7c6e0)
# 修复
建议使用文章的 MD5 Hash 值作为页面的标识

**Comment by JTZ-a** [comment]
对的, 我一时没有想好漏洞的名字, 感觉比较像 IDOR , 所以写了此名称

**Comment by sy-records** [comment]
问了一下 @joyqi ，这里目前是设计如此，隐藏的仍然支持访问，如果需要不支持的话，设置为私密。
