### ISSUE TITLE
后台登陆后出现 404

### ISSUE THREAD

**Issue by forskyer** [typecho/typecho#1655]
### 1. 该问题的重现步骤是什么？
后台登录，输入用户名密码后，点击登录后：404 Not Found openresty . 修改过默认admin的路径。
### 2. 你期待的结果是什么？实际看到的又是什么？
可以正常登录。 实际跳转错误页面。
### 3. 问题出现的环境

- 操作系统版本：linux
- Apache/NGINX 版本：OpenResty版本:1.21.4.3-0-focal
- 数据库版本： mysql 版本:5.6.51
- PHP 版本：8.2.10
- Typecho 版本： 1.21.0
- 浏览器版本：chrom newest

[//]: # (如有图片请附上截图)

**Comment by ZYYO666** [comment]
有可能是使用cdn或者内穿之类导致，config.inc.php加上define('__TYPECHO_SECURE__',true);试试

**Comment by forskyer** [comment]
> 有可能是使用cdn或者内穿之类导致，config.inc.php加上define('**TYPECHO_SECURE**',true);试试

谢谢回复，测试了， 没用。

**Comment by sy-records** [comment]
怎么修改的 admin 路径？

登录地址是什么？跳转后的地址是什么？

**Comment by forskyer** [comment]
> 怎么修改的 admin 路径？
> 
> 登录地址是什么？跳转后的地址是什么？

后台登录默认路径是: xxx.xx/admin/  我修改成了  xxx.xx/aabbcc/

后台登录页面是 xxx.xx/aabbcc/login.php  ,登录跳转到 ： xxx.xx/index.php/action/login?=da7181116cb702895284677a18c902eb.  没有跳转后台的 aabbcc路径。 直接是根路径了。

**Comment by sy-records** [comment]
@forskyer 检查检查你伪静态的配置。

修改后台登录目录，修改config了吗？

**Comment by forskyer** [comment]
> @forskyer 检查检查你伪静态的配置。
> 
> 修改后台登录目录，修改config了吗？

不修改Config 是打不开admin登录页面的。我修改了，可以打开登录页面。

 伪静态用的是：
    if (!-e $request_filename) {
        rewrite ^(.*)$ /index.php$1 last;
    }

用其他的都打不开文章，也不能看分类。我也怀疑是伪静态的问题，但水平有限无从下手

**Comment by forskyer** [comment]
谢谢， 更改了伪静态，现在正常了， 以前伪静态用的是默认自带的tyoecho. 改成WP后问题解决了。

**Comment by cheneyxx** [comment]
@forskyer 搞了半天 改成wp就好了。。
