### ISSUE TITLE
一个来自1.2.1的xss漏洞

### ISSUE THREAD

**Issue by ZYYO666** [typecho/typecho#1656]
$this->widget('Widget_Comments_Recent', 'ignoreAuthor=false&pageSize=3')->to($com); 
调用此接口实现调用最新评论，会有xss漏洞，之前修复的漏洞事情评论区和后台的，如果在评论时不加以过滤js代码会在最新评论被执行![b65e17e4fa9b1dd103b4b7690e6ea26d](https://github.com/typecho/typecho/assets/78634166/ed5d4629-0561-4cd9-afd3-09d4a684de51)，如图所示，<script></script>标签没有被过滤

**Comment by sy-records** [comment]
dev 分支的应该已经处理过了。

`$com->content` 已经是 `strip tags` 过的数据。
