### ISSUE TITLE
迁移之后登录不上后台，无报错日志

### ISSUE THREAD

**Issue by ruanun** [typecho/typecho#1657]
### 1. 该问题的重现步骤是什么？
导出程序所在数据库，导入到新环境的数据库中，安装程序时选保留原数据。主页和文章都可以正常展示。后台登录不上，页面无报错提示。进数据库手动**重置密码**后也不行，服务器上没有看到有异常日志。
### 2. 你期待的结果是什么？实际看到的又是什么？
可以正常登录后台，或者如何开启debug排查问题
### 3. 问题出现的环境
- docker镜像版本：joyqi/typecho:1.2.1-php8.0-apache
- nginx version：nginx/1.22.1

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
`define('__TYPECHO_DEBUG__',` true);`

**Comment by ruanun** [comment]
在config.inc.php 中添加上面的代码，`docker logs`没看看到相关日志，这边日志输出到了那里？@sy-records

**Comment by sy-records** [comment]
看你 53579 端口是怎么启动的，这个问题只能你自己排查了

**Comment by ruanun** [comment]
`   proxy_set_header X-Forwarded-Proto $scheme;` 去掉这句就好了
