### ISSUE TITLE
使用cloudflare后sqlite无法写入数据

### ISSUE THREAD

**Issue by ufoproject** [typecho/typecho#1658]
### 1. 该问题的重现步骤是什么？
主机http  通过cf域名代理 https http同时都可以访问，
https访问sqlite无法写入数据，http访问可以写

### 2. 你期待的结果是什么？实际看到的又是什么？
功能优化
### 3. 问题出现的环境

- 操作系统版本：linux
- Apache/NGINX 版本：Apache
- 数据库版本：sqlite3
- PHP 版本：8.2.13 
- Typecho 版本： 1.2.1
- 浏览器版本：firebox chrome

[//]: # (如有图片请附上截图)
比如修改文字，新写文章，https不行 http可以
其他类似程序 都可以 不出现这个问题 比如 phpbb mybb

**Comment by JIeJaitt** [comment]
强制httpa访问看看

**Comment by xiamuguizhi** [comment]
检查Cloudflare SSL/TLS加密模式：Cloudflare提供了几种不同的SSL/TLS加密模式，包括"Off"、"Flexible"、"Full"和"Full (strict)"。如果你的设置是"Flexible"，那么Cloudflare会允许用户通过HTTPS连接到Cloudflare，然后Cloudflare通过HTTP连接到你的服务器。这可能会导致你的服务器收到的所有请求都是HTTP的，而不是HTTPS的。你可以尝试将此设置更改为"Full"或"Full (strict)"，看看问题是否得到解决。


或者 编辑 Typecho 站点根目录下的文件 `config.inc.php` ，加入下面一行配置 强制开启https

`define('__TYPECHO_SECURE__',true); `
