### ISSUE TITLE
1.2.0升级1.2.1提示500错误

### ISSUE THREAD

**Issue by cnluminous** [typecho/typecho#1659]
### 1. 该问题的重现步骤是什么？
删除掉原有 /var /admin 目录，替换index.php,install.php
### 2. 你期待的结果是什么？实际看到的又是什么？
期待完成升级，实际出现500错误

错误内容：
Call to undefined method 
Typecho\Cookie::getDomain()

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx1.22.1
- 数据库版本：5.7.43
- PHP 版本：7.3
- Typecho 版本：1.2.0->1.2.1
- 浏览器版本：Edge

[//]: # (如有图片请附上截图)
![image](https://github.com/typecho/typecho/assets/47070284/537e4382-9dc3-49da-81cb-9ff9b2e566da)

**Comment by cnluminous** [comment]
config.inc.php中添加
 define('__TYPECHO_DEBUG__', true);

后可以进入后台页面，但是外观设置功能出现异常
![image](https://github.com/typecho/typecho/assets/47070284/e1777be2-c091-451d-a89a-d0a22da28809)

**Comment by sy-records** [comment]
看起来你文件没有覆盖完全

**Comment by cnluminous** [comment]
> 看起来你文件没有覆盖完全

我的操作是删除原有文件，重新解压新版本压缩包

**Comment by sy-records** [comment]
检查下文件内容吧

https://github.com/typecho/typecho/blob/43c54328f724055173f2b7b1c67755ca3328d923/var/Widget/Themes/Files.php#L89

https://github.com/typecho/typecho/blob/43c54328f724055173f2b7b1c67755ca3328d923/var/Typecho/Cookie.php#L92

**Comment by cnluminous** [comment]
重新覆盖了一遍var目录可以正常更新操作了。覆盖文件的时候吧usr和var搞混了
