### ISSUE TITLE
进行评论时显示Call to undefined function split()

### ISSUE THREAD

**Issue by Martinxux** [typecho/typecho#1660]
### 1. 该问题的重现步骤是什么？
评论时就会复现
### 2. 你期待的结果是什么？实际看到的又是什么？
能够正常评论，实际上跳转了500页面，显示Call to undefined function split()
### 3. 问题出现的环境
Docker 24.0.7
- 操作系统版本：
- Apache/NGINX 版本：NA
- 数据库版本：mysql:8.2.0
- PHP 版本：7.4
- Typecho 版本： 1.2.1
- 浏览器版本：Edge 116.0.1938.69 

[//]: # (如有图片请附上截图)

**Comment by Martinxux** [comment]
![image](https://github.com/typecho/typecho/assets/90446788/38b38766-b415-4900-aabc-fccc5a846387)

**Comment by sy-records** [comment]
可以打开`debug`看下具体错误信息堆栈

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by Martinxux** [comment]
没有更多信息了

**Comment by sy-records** [comment]
你开debug了吗？

**Comment by Martinxux** [comment]
![image](https://github.com/typecho/typecho/assets/90446788/8c2dfc38-9ed3-4616-8f54-b5e1812035f0)
打开了

**Comment by Martinxux** [comment]
是插件的问题，禁用了两个插件，可以了

**Comment by sy-records** [comment]
打开后，重新评论，还是只显示`Call to undefined function split()`？

检查下你有没有什么评论插件影响了。

**Comment by Martinxux** [comment]
我其实不太清楚这个debug模式，是直接编辑config.inc.php文件就行了吗，然后他自己就会显示更多信息吗

**Comment by Martinxux** [comment]
> 打开后，重新评论，还是只显示`Call to undefined function split()`？
> 
> 检查下你有没有什么评论插件影响了。

是的，刚刚试了下，是有评论插件影响了
