### ISSUE TITLE
Docker版本的自动构建命令已经不动3个月啦～～

### ISSUE THREAD

**Issue by KyoSakuyo** [typecho/typecho#1662]
3个月都没得更新啦～～～

我还想用1.3.0呀
<img width="1284" alt="image" src="https://github.com/typecho/typecho/assets/59904064/3205a668-22ab-44fb-a4dc-96ed50587b85">

**Comment by ifsc01** [comment]
加个自动构建?

**Comment by joyqi** [comment]
我已经恢复了，今晚就会跑起来。那个 repo 很久没有代码提交了，所以 Actions 自动停掉了。
