### ISSUE TITLE
使用最新 nightly-php8.0-apache容器后，~/install.php的初始化页面显示500，server error

### ISSUE THREAD

**Issue by KyoSakuyo** [typecho/typecho#1665]
### 1. 该问题的重现步骤是什么？
```
cd /home/typecho;
docker pull joyqi/typecho:nightly-php8.0-apache;
docker-compose down;
docker-compose up -d;
```
### 2. 你期待的结果是什么？实际看到的又是什么？
期待更新完成后，进入网页后直接进入选择数据库的欢迎页面（像以往的更新一样）
~~如果更新容器之后不需要重新手动选择数据库就好了。。~~

![2023-12-31 13 29 30](https://github.com/typecho/typecho/assets/59904064/8304ad37-2a47-4182-b40b-7ea169c574cc)

![2023-12-31 13 30 05](https://github.com/typecho/typecho/assets/59904064/b0911a95-282c-4fd5-a89e-aefa1664a195)

实际上在~/install.php的初始化页面显示500，server error的提示。

### 3. 问题出现的环境

- 操作系统版本：Debian 10 arm64 Docker nightly-php8.0-apache
- Apache/NGINX 版本：容器内部
- 数据库版本：sqlite
- PHP 版本：容器内部
- Typecho 版本：nightly
- 浏览器版本：Edge 120

**Comment by joyqi** [comment]
这个应该跟 #1663 相同，已经修复了，你可以等今晚 build 完以后再试试

**Comment by KyoSakuyo** [comment]
这个错误解决了，又有新问题了，我开新Issues吧。。
