### ISSUE TITLE
V1.3.0 alpha ，永久链接设置，按分类归档 /{category}/{slug}.html

### ISSUE THREAD

**Issue by sluke** [typecho/typecho#1666]
### 1. 该问题的重现步骤是什么？
V1.3.0 alpha ，永久链接设置，选择按分类归档 /{category}/{slug}.html
{category}取不到分类名称

### 2. 你期待的结果是什么？实际看到的又是什么？
期待：正常显示分类名称/日志名称   /{category}/{slug}.html
实际：仅显示日志  /{slug}.html，导致点击链接会404

**Comment by joyqi** [comment]
duplicate #1672
