### ISSUE TITLE
快捷键发布文章&管理文章置顶

### ISSUE THREAD

**Issue by macrocodea** [typecho/typecho#1667]
建议一：在键盘按下一个快捷键，就可以在编辑器里面发布文章。
这样就省去了鼠标点击发布文章的步骤了，大大提高效率。

建议二：有些陈年老旧的文章需要维护，希望能出一个功能将这些文章置顶到”管理文章“的头部。
方便快速的对这些文章维护。

**Comment by joyqi** [comment]
这个需求过于小众了，除非有其它用户共同需要，否则还是建议开发插件解决
