### ISSUE TITLE
插入代码块时，首行出现多余空格问题

### ISSUE THREAD

**Issue by WANGFYPHYS** [typecho/typecho#1675]
开发者您好，我是 typeo 的新用户，感谢您们开发的这款优秀的 blog 产品。

试用过程中，发现插入代码块时，第一行代码与后面行的代码起始位置相差大约半个空格，效果如下：

![example](https://github.com/typecho/typecho/assets/86274882/4243a742-95ce-4c5c-93cf-4bf2639b8933)

不知这大约半个空格是不是 markdown 解释器的问题产生的？应该如何消除掉？

或者是由于 php 版本问题引起的？我的版本号是 8.1.27。

谢谢！

**Comment by sy-records** [comment]
🤔 哪个位置，截图标识下？

**Comment by libxzr** [comment]
🤔
https://www.zjy.name/code-block-align-problem-in-typecho/

**Comment by WANGFYPHYS** [comment]
已经成功解决问题，感谢各位大佬！
