### ISSUE TITLE
在 Plugin.php config函数里调用  \Widget\Archive::alloc() 报错 \Typecho\Router::$current 调用前未初始化

### ISSUE THREAD

**Issue by benzBrake** [typecho/typecho#1681]
### 1. 该问题的重现步骤是什么？

helloword 插件配置函数里加入  \Widget\Archive::alloc()
进入插件设置页面
报错  \Typecho\Router::$current 调用前未初始化

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：MySQL 8.0.22
- PHP 版本：PHP 8.2
- Typecho 版本：Typecho 1.3 alpha
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
在外部调用 ` \Widget\Archive::alloc()` 时，需要传入参数 `type`

**Comment by joyqi** [comment]
新增了一个异常抛出，不传入 `type` 会直接报错
