### ISSUE TITLE
Typecho1.3 Helper::options()->panelTable 不能获取到最新的panelTable？

### ISSUE THREAD

**Issue by benzBrake** [typecho/typecho#1699]
### 1. 该问题的重现步骤是什么？
插件中尝试注册菜单
```
$menuId = Helper::addMenu(_t('测试菜单'));
Helper::addPanel($menuId, 'Test/admin/Test.php', _t('测试菜单1'), _t('测试菜单1'), 'administrator');
```
### 2. 你期待的结果是什么？实际看到的又是什么？
添加菜单无效
![1](https://github.com/typecho/typecho/assets/11323774/61de0c6b-d321-4573-a120-4f697b7cc1d3)
![2](https://github.com/typecho/typecho/assets/11323774/c763d048-17c6-437f-95c5-5a41dea4d87f)

### 3. 问题出现的环境

- 操作系统版本：Windows11
- Apache/NGINX 版本：
- 数据库版本：MySQL 5.7
- PHP 版本：8.2
- Typecho 版本：1.3 commit [c5ab929](https://github.com/typecho/typecho/commit/c5ab9295f052d4820633d724c56133864796f33e)
- 浏览器版本：Firefox 122

[//]: # (如有图片请附上截图)

**Comment by sy-records** [comment]
插件启用后是有的

<img width="368" alt="image" src="https://github.com/typecho/typecho/assets/33931153/a4910277-3c81-4b60-a358-7a46d0d31913">

**Comment by benzBrake** [comment]
> 插件启用后是有的
> <img alt="image" width="368" src="https://private-user-images.githubusercontent.com/33931153/295455486-a4910277-3c81-4b60-a358-7a46d0d31913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjY3MzMsIm5iZiI6MTcwNDg2NjQzMywicGF0aCI6Ii8zMzkzMTE1My8yOTU0NTU0ODYtYTQ5MTAyNzctM2M4MS00YjYwLWEzNTgtN2E0NmQwZDMxOTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA2MDAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MTgwOTlkMzZkNjY2YTkzNzBiMTY2YzllNDI5N2QxMzBkNDg0NmI5YmQ0YWQxZDE3NmE4Y2ZhMGIzNGIzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cg6uOLHGiWDbkj1Bm7EJKDmHjJbqpTlHlC1_xi_WQbY">

但是 "parent":[]}  ，二级菜单显示不了啊

**Comment by joyqi** [comment]
我在 #1702 提了个 pr，可以验证一下

**Comment by sy-records** [comment]
我这可以了
![image](https://github.com/typecho/typecho/assets/33931153/e9675d56-3dae-47f9-b17d-8eb954d7ffd8)

**Comment by benzBrake** [comment]
菜单正常了
