### ISSUE TITLE
设置外观，报错500

### ISSUE THREAD

**Issue by locolocoer** [typecho/typecho#1705]
## 描述这个 Bug

点击后台的设置外观，报错“Argument 1 passed to Typecho\Widget\Helper\Layout::addItem() must be an instance of Typecho\Widget\Helper\Layout, null given, called in /www/wwwroot/47.97.161.115/var/Typecho/Widget/Helper/Form/Element/Select.php on line 46 ”

### 复现方式

复现的步骤：

1.前往后台
2. 点击 '控制台，外观，设置外观'
3. 看到错误

### 期望的结果

正常使用

### 截图
![图片](https://github.com/typecho/typecho/assets/67625711/ffb97f39-6c59-48d4-a059-e3f1dbaf850e)

https://github.com/typecho/typecho/assets/67625711/36aeb043-c19e-4004-9628-82e9557164d2

### 平台

- 操作系统版本：宝塔Linux面板7.5.1
- Nginx 版本：1.18.0
- 数据库版本：4mysql 5.7.44
- PHP 版本：7.4.33
- Typecho 版本：1.2.1
- 浏览器版本：

**Comment by locolocoer** [comment]
it's my fault.fuck wrong theme name

**Comment by locolocoer** [comment]
ff

**Comment by sy-records** [comment]
看你视频version是1.2.0

这个可能需要主题作者处理下兼容问题？🤔默认主题是好的

**Comment by xiamuguizhi** [comment]
根据我本人本地测试，发现 该主题版本最新为 `v1.2.4`  在 `typecho 1.3.0 ` 启用 正常 没用任何报错！

解决办法 下载最新版本 然后启用 主题！

[https://github.com/fordes123/gleaner/releases/tag/v1.2.4](https://github.com/fordes123/gleaner/releases/tag/v1.2.4)

![image](https://github.com/typecho/typecho/assets/19650297/eed0e41b-763e-4029-9878-8fb343f80e80)

**Comment by locolocoer** [comment]
嗯嗯，由于我对主题代码进行了一些二次开发导致出现问题
