### ISSUE TITLE
typecho 待审核 评论页面 评论链接 建议

### ISSUE THREAD

**Issue by xiamuguizhi** [typecho/typecho#1707]
## 你的改进是否与某个问题有关？请描述

在开启评论分页后

![image](https://github.com/typecho/typecho/assets/19650297/bc2a11eb-aa10-40d1-b257-6cf10fc38752)

`已通过 `评论跳转链接 是 ：

`http://localhost/index.php/2016/02/19/77.html/comment-page-1#comment-135`

`待审核 ` 评论跳转链接 是 ：
http://localhost/index.php/2016/02/19/77.html#comment-135

假设 已通过 评论跳转链接 为 `http://localhost/index.php/2016/02/19/77.html/comment-page-2#comment-135`   第二页时

在 待审核 评论跳转链接 还是 ： `http://localhost/index.php/2016/02/19/77.html#comment-135`

## 描述你想要的解决方案

![image](https://github.com/typecho/typecho/assets/19650297/46d7c859-3b23-4994-82bc-537bf8bb4fa8)

虽然说 `待审核评论 `  在前台是看不到的。 但是我强迫症 发现了以后就比较难受  很纠结这个问题！

如果 待审核 评论跳转链接  改成 和 已通过 的 跳转链接一样？或者 直接取消？  跳转链接？

当然  不影响正常使用！ 只是强迫症。

**Comment by joyqi** [comment]
直接取消链接是比较方便的选择

**Comment by xiamuguizhi** [comment]
@joyqi  我也是这么想的！哈哈。
