### ISSUE TITLE
Failed to enter the backend after changing the backend path  504 error

### ISSUE THREAD

**Issue by Rosemajor** [typecho/typecho#1717]
## 描述这个 Bug
更改后台路径后进后台失败

  admin/menu.php 
` <?php \Typecho\Plugin::factory('admin/menu.php')->call('navBar'); ?>`

### 复现方式
Change this admin to a customized backend path name
将这个admin改成自定义的后台路径名称

### 平台

- 操作系统版本：ubuntu
- Apache/Nginx 版本：
- 数据库版本：5.7
- PHP 版本：8.0
- Typecho 版本：1.2.1
- 浏览器版本：

**Comment by xiamuguizhi** [comment]
不太清楚您具体描述 . 如果你只是想更改Typecho访问后台地址的话, 可以参考一下步骤.

1. **修改配置文件**：找到 Typecho 安装目录下的 `config.inc.php` 文件。

2. **添加自定义后台路径**：在 `config.inc.php` 文件中，添加一个新的定义来指定后台路径。例如，如果你想将后台路径改为 `myadmin`，则添加如下代码：

   ```php
   define('__TYPECHO_ADMIN_DIR__', '/myadmin/');
   ```

3. **保存**：保存更改并上传更新后的 `config.inc.php` 文件到服务器。

4. **修改后台目录**：将 `admin` 目录重命名为你在 `config.inc.php` 中指定的新路径名，例如 `myadmin`。

6. **测试新路径**：打开浏览器，输入新的后台地址(`http://localhost/myadmin`)，验证是否能够正常访问和登录。

**Comment by sy-records** [comment]
修改`config.inc.php`中的`define('__TYPECHO_ADMIN_DIR__', '/admin/');`配置。
改为你修改后的路径。
