### ISSUE TITLE
由 1.2.0 更新到 master 最新版本（1.3.0）评论提交 403

### ISSUE THREAD

**Issue by Stapxs** [typecho/typecho#1725]
<img width="1512" alt="image" src="https://github.com/typecho/typecho/assets/42486439/4050f408-481d-48d2-b470-2946b1472670">

没有找到什么有效的日志 ……

**Comment by sy-records** [comment]
可以打开`debug`查看具体错误信息堆栈，在`config.inc.php`中加入：

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by Stapxs** [comment]
https://github.com/typecho/typecho/issues/999
评论来源页错误 emmmm 找到了个类似的 issues 但是没有解决问题
~~~
评论来源页错误.

Typecho\Widget\Exception: 评论来源页错误. in /www/wwwroot/blog.stapxs.cn/var/Widget/Feedback.php:88
Stack trace:
#0 /www/wwwroot/blog.stapxs.cn/var/Typecho/Router.php(88): Widget\Feedback->action()
#1 /www/wwwroot/blog.stapxs.cn/index.php(23): Typecho\Router::dispatch()
#2 {main}
~~~

**Comment by sy-records** [comment]
那就是没有解析到你的Referer

**Comment by Stapxs** [comment]
哦这么一说我为了解决跨域图片显示改过 referer 头，那就是这个问题了
非常感谢
