### ISSUE TITLE
在编辑文章时，会默认加载所有图片，大图多了导致编辑时很慢

### ISSUE THREAD

**Issue by ScarletDor** [typecho/typecho#1727]
点击编辑文章，因为文章包含很多图片，会卡住一段时间。查看了一下是全屏预览窗口（按钮）加载了图片。

可否使他不再自动加载预览，因为图片多的时候不仅消耗流量而且加载很慢（前端使用了懒加载所以加载很快而且节省流量），感谢

**Comment by sy-records** [comment]
前端的懒加载也不是Typecho自带的吧，扩展一下编辑器页面，加上懒加载就行？

**Comment by ScarletDor** [comment]
> 前端的懒加载也不是Typecho自带的吧，扩展一下编辑器页面，加上懒加载就行？

是呀，我的问题就是怎样让编辑器的预览图片加上懒加载，这样就可以解决加载卡住的问题了qaq

**Comment by ScarletDor** [comment]
@jrotty 是不是可以安心等1.3版本了qaq

**Comment by jrotty** [comment]
@ScarletDor 得看我的提交是否会被合并🙂

**Comment by ScarletDor** [comment]
> @ScarletDor 得看我的提交是否会被合并🙂

不管他了我先用上噗噗噗
