### ISSUE TITLE
加密的文章输入错误的密码，跳转server error

### ISSUE THREAD

**Issue by Charolf** [typecho/typecho#1729]
## 描述这个 Bug

假设现有一篇文章是加密的，文章链接发给一个陌生人。该陌生人如果输入的密码是错误的，页面会跳转到server error。

### 复现方式

复现的步骤：

1. 新建一文章并加密，发布，密码任意。
2. 浏览器隐身模式打开该文章链接。
3. 输入错误的密码。
4. 看到"server error", 应该是403。（POST ... 403 (Forbidden)）

### 期望的结果

如果可以的话，希望是一个类似404那样的界面，比如“密码错误”或者“你没有权限”。只显示server error以为是服务器崩了。

### 平台

- 操作系统版本：Any
- Apache/Nginx 版本：Nginx 1.24.0
- 数据库版本：MySQL 8.0.35
- PHP 版本：8.2
- Typecho 版本：1.3.0
- 浏览器版本：Any

**Comment by cuixiping** [comment]
现在不是只发布了 1.2.1 么? 从哪里来的 Typecho 1.3.0 ?

v1.2.1 正常, 没有发现这个问题

**Comment by Kefoue** [comment]
> 现在不是只发布了 1.2.1 么? 从哪里来的 Typecho 1.3.0 ?
> 
> v1.2.1 正常, 没有发现这个问题

大聪明😂

**Comment by cuixiping** [comment]
知道了, github下载的 1.3.0-alpha
