### ISSUE TITLE
SQLite并发锁库问题

### ISSUE THREAD

**Issue by sheeye** [typecho/typecho#1733]
## 你的改进是否与某个问题有关？请描述

SQLite更新时会锁库，我在nginx日志里发现很多sqlite database is locked报错，前端表现为偶尔的500报错。

## 描述你想要的解决方案

\var\Typecho\Db\Adapter\SQLite.php中加一句就可以解决了：

            $dbHandle = new \SQLite3($config->file);
            $dbHandle->exec("PRAGMA busy_timeout=5000");//加这一句，效果是当数据库被锁时等待
            $this->isSQLite2 = version_compare(\SQLite3::version()['versionString'], '3.0.0', '<');

## 描述你考虑过的替代方案

目前我是在config.inc.php中加了一句：
$db->query('PRAGMA busy_timeout=5000');

**Comment by joyqi** [comment]
非常感谢你提供的解决方案，但这属于数据库优化的问题，SQLite作为嵌入式数据库，在开发之初就不是以高并发作为目标的。所以虽然我们可以通过诸如你所说的这类方法解决问题，但并不知道是否会带来其它的问题，因此这个方案仅作为一种建议提供给使用者。
