### ISSUE TITLE
安装的时候报错这个，未知原因

### ISSUE THREAD

**Issue by JIeJaitt** [typecho/typecho#1736]
## typecho版本1.2.1（最新稳定版）
```bash
Typecho\Router\Parser::__construct(): Argument #1 ($routingTable) must be of type array, bool given, called in /var/task/user/var/Widget/Options.php on line 206
```

**Comment by sy-records** [comment]
可以打开`debug`查看具体错误信息堆栈，在`config.inc.php`中加入：

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by DilucK** [comment]
我也遇到了这个问题，但是看上面的issue还是没有解决方案，报错信息如下
`Typecho\Router\Parser::__construct(): Argument #1 ($routingTable) must be of type array, bool given, called in /app/var/Widget/Options.php on line 206
TypeError: Typecho\Router\Parser::__construct(): Argument #1 ($routingTable) must be of type array, bool given, called in /app/var/Widget/Options.php on line 206 and defined in /app/var/Typecho/Router/Parser.php:45
Stack trace:
#0 /app/var/Widget/Options.php(206): Typecho\Router\Parser->__construct(false)
#1 /app/var/Typecho/Widget.php(155): Widget\Options->execute()
#2 /app/var/Typecho/Widget.php(187): Typecho\Widget::widget('Widget\\Options', NULL, NULL, true)
#3 /app/var/Widget/Init.php(82): Typecho\Widget::alloc()
#4 /app/var/Typecho/Widget.php(155): Widget\Init->execute()
#5 /app/var/Typecho/Widget.php(187): Typecho\Widget::widget('Widget\\Init', NULL, NULL, true)
#6 /app/index.php(17): Typecho\Widget::alloc()
#7 {main}`
