### ISSUE TITLE
v1.3.0-alpha版本Server Error错误

### ISSUE THREAD

**Issue by q498419223** [typecho/typecho#1737]
v1.3.0-alpha版本

debian 12.5
Nginx 1.25.4
Mariadb 10.11.7
PHP 8.3.3
v1.3.0-alpha

网站后台-->设置-->基本设置-->关键词 不能为空
如 关键字 为空，网站首页出现错误Server Error，500 (Internal Server Error)

![Snipaste_2024-02-21_22-28-43](https://github.com/typecho/typecho/assets/20244580/832f507a-488e-430a-9172-02b298aa74bf)

网站首页出现错误：
![Snipaste_2024-02-21_22-31-51](https://github.com/typecho/typecho/assets/20244580/2cea9d79-9ef1-4bc7-a0ef-2f0d181d127c)

**Comment by sy-records** [comment]
你使用的什么主题？

可以打开`debug`查看具体错误信息堆栈，在`config.inc.php`中加入：

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by q498419223** [comment]
> 你使用的什么主题？
> 
> 可以打开`debug`查看具体错误信息堆栈，在`config.inc.php`中加入：
> 
> ```
> define('__TYPECHO_DEBUG__', true);
> ```

我用的是自带的default主题，更换其他主题后问题依然存在，和主题好像没有关系

**Comment by sy-records** [comment]
错误堆栈发出来

**Comment by q498419223** [comment]
> 错误堆栈发出来

我试试，等下上传

**Comment by q498419223** [comment]
> 错误堆栈发出来

![Uploading Snipaste_2024-02-22_20-05-01.png…]()

**Comment by q498419223** [comment]
> 错误堆栈发出来

![Snipaste_2024-02-22_20-05-01](https://github.com/typecho/typecho/assets/20244580/7d69dc53-0f6e-4953-8284-f2793ccc22b1)

**Comment by q498419223** [comment]
经过以上修改，Access插件又出现Server Error了

**Comment by M69W** [comment]
> > 错误堆栈发出来
> 
> ![Snipaste_2024-02-22_20-05-01](https://private-user-images.githubusercontent.com/20244580/306987933-7d69dc53-0f6e-4953-8284-f2793ccc22b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzM3MDksIm5iZiI6MTcwODkzMzQwOSwicGF0aCI6Ii8yMDI0NDU4MC8zMDY5ODc5MzMtN2Q2OWRjNTMtMGY2ZS00OTUzLTgyODQtZjI3OTNjY2MyMmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA3NDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYmY2MmM3YzgzNWM0YzAxMWU0NWRjMWFhYzdkY2Q4YmE1OTYyNGI5MjA1OTdiYzkwN2VhOGEzN2Q2MjIzOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nF6yA6UoJxpvSUfvLMxLijOHv_vOW-qxDO4ONxbzPEE)

@joyqi  有一个小建议，`错误栈` 以 `文字贴出来比较好，便于搜索`。
当然提问者把异常尽量描述出来已达到目的。
比如 https://github.com/typecho/typecho/issues/1734, 同一个问题
