### ISSUE TITLE
1.2.1版本安装后无法登录

### ISSUE THREAD

**Issue by fangchieh** [typecho/typecho#1743]
## 描述这个 Bug

1.2.1版本安装后无法登录

### 复现方式

复现的步骤：

1. 正常安装完成后，打开登录页，填上账号密码，点击登录，还是跳转到登录页

### 期望的结果

正常登录

### 截图

https://github.com/typecho/typecho/assets/33652429/0c79ab28-8777-45cc-96b2-d1fc684d4686

### 平台

- 操作系统版本：window11
- Apache/Nginx 版本：Apache 2.4.54
- 数据库版本：8.0.27-cll-lve
- PHP 版本：7.4
- Typecho 版本：1.2.1
- 浏览器版本：Chrome 版本 122.0.6261.111（正式版本） （64 位）

**Comment by fangchieh** [comment]
安装1.2.0版本没有问题

**Comment by sy-records** [comment]
信息不全，没办法判断。

查看浏览器network里的请求信息，以及打开debug模式。

在`config.inc.php`中加入：

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by fangchieh** [comment]
猜测可能是浏览器缓存导致的，无痕模式能正常登录



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月8日(周五) 晚上6:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [typecho/typecho] 1.2.1版本安装后无法登录 (Issue #1743)




 
信息不全，没办法判断。
 
查看浏览器network里的请求信息，以及打开debug模式。
 
在config.inc.php中加入：
 define('__TYPECHO_DEBUG__', true);

**Comment by kejilion** [comment]
> 信息不全，无法判断。
> 
> 查看浏览器网络里的请求信息，以及打开调试模式。
> 
> 简介`config.inc.php`：
> 
> ```
> define('__TYPECHO_DEBUG__', true);
> ```

我无痕模式也不行 关了浏览器缓存也不行 CF缓存都清理了也无法登录后台 我是小白不太会看调试模式 请见谅！

**Comment by MoXiaoXi233** [comment]
> > 信息不全，无法判断。
> > 查看浏览器网络里的请求信息，以及打开调试模式。
> > 简介`config.inc.php`：
> > ```
> > define('__TYPECHO_DEBUG__', true);
> > ```
> 
> 我无痕模式也不行 关了浏览器缓存也不行 CF缓存都清理了也无法登录后台 我是小白不太会看调试模式 请见谅！

之前遇到过一样的问题是因为伪静态的设置，不确定你的原因是不是这个
