### ISSUE TITLE
安装报错未知字符Response

### ISSUE THREAD

**Issue by tmdakm** [typecho/typecho#1744]
## 描述这个 Bug

我在Release里下了最新的1.3.0alpha然后放xp面板里安装，打开安装网页的时候报错
Parse error: syntax error, unexpected 'Response' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /www/admin/blog.huangyu.win_80/wwwroot/var/Typecho/Response.php on line 73

### 复现方式

复现的步骤：

1. 下载1.3.0alpha
2. 安装

### 期望的结果

成功安装

### 截图

![image](https://github.com/typecho/typecho/assets/96684075/cdb1391c-2fbf-4a6e-bfa0-b549932a771e)
![image](https://github.com/typecho/typecho/assets/96684075/4074e44b-9749-4c75-b64f-e5531b898305)

### 平台

- 操作系统版本：Debian 11
- Apache/Nginx 版本：nginx1.15
- 数据库版本：mysql5.7.27
- PHP 版本：php7.3.8
- Typecho 版本：1.3.0alpha
- 浏览器版本：Microsoft Edge 123.0.2420.41

**Comment by sy-records** [comment]
1.3版本，PHP需要7.4了

**Comment by xcqm12** [comment]
不知道为什么报服务器错误
