### ISSUE TITLE
循环页面列表时, 自定义字段值都一样, 而不是特定页面设置的字段值.

### ISSUE THREAD

**Issue by cuixiping** [typecho/typecho#1746]
## 描述这个 Bug

循环页面(Page)列表时, 自定义字段值都一样, 而不是特定页面设置的字段值.

### 复现方式

复现的步骤：

1 仅单独为某个页面设置自定义字段 fieldName1, 其它页面则不设置该字段.
2 循环页面列表时, 打印出来, 发现每个循环内获取字段值都相同 $this->fields->fieldName1

header.php 加入显示自定义字段的代码:

```php
<?php \Widget\Contents\Page\Rows::alloc()->to($pages); ?>
<?php while ($pages->next()): ?>
    <a<?php if ($this->is('page', $pages->slug)): ?> class="current"<?php endif; ?>
        href="<?php $pages->permalink(); ?>"
        title="<?php $pages->title(); ?>"><?php $pages->title(); ?>
        /<?=$this->fields->fieldName1?>
        </a>
    <?php //endif; ?>
<?php endwhile; ?>
```

### 期望的结果

每个页面读取该页面特定的字段值

**Comment by sy-records** [comment]
代码提供下吧

**Comment by cuixiping** [comment]
> 代码提供下吧

补充了代码

**Comment by sy-records** [comment]
typecho 版本是？

**Comment by cuixiping** [comment]
> typecho 版本是？

Typecho version 1.2.1

**Comment by sy-records** [comment]
使用 `$pages->fields->fieldName1`

**Comment by cuixiping** [comment]
> 使用 `$pages->fields->fieldName1`

这个方法解决了问题, 谢谢!  
但是不太理解为什么 $this->fields->fieldName1 能读到每个一样呢

**Comment by sy-records** [comment]
因为 $this 获取的是当前的，你在迭代器里使用，所以就要用对应的 pages
