### ISSUE TITLE
发现代码里面有一段奇怪的疑似经过混淆后的函数

### ISSUE THREAD

**Issue by ttgml** [typecho/typecho#1761]
## 描述这个 Bug

发现代码里面有一段奇怪的疑似经过混淆后的函数

### 复现方式

复现的步骤：

1. 安装正常流程部署 typecho（从官网下载的包，没有安装其他第三方插件主题)
2. 安装完成后，用 f12 控制台查看主页，发现了一段这样的代码：
![image](https://github.com/typecho/typecho/assets/17313832/79cf6921-d0eb-4ffe-a8b3-da92d75aead9)
3. 看了一下是这里引入的
![image](https://github.com/typecho/typecho/assets/17313832/a52aaa0d-39f9-4852-93e2-7a9b5fa4d2e1)

### 期望的结果

想知道为什么需要这样写JS，感觉没有进行混淆的必要，反而很容易让人感觉不安全。

还有不知道为什么在项目里面搜索这段js的关键词，完全找不到相关的代码块。

### 平台

- 操作系统版本： ubuntu 22
- Apache/Nginx 版本：openresty/1.25.3.1
- 数据库版本： sqlite3
- PHP 版本：8.3.6
- Typecho 版本：1.2.1
- 浏览器版本：chrmoe 124

**Comment by windqyoung** [comment]
我下载安装了一下, 没发现有这段代码. 

是不是你的网站被注入了? 是公网用的http访问么?

最好检查一下那个id=respond-page-8的元素, 看看里面是干嘛的

**Comment by ttgml** [comment]
感谢回复，已经看到了，没啥问题了。
