### ISSUE TITLE
能否让文章列表的日期显示为绝对时间，不要用“N小时前”“N天前”这样的显示

### ISSUE THREAD

**Issue by vimbackground** [typecho/typecho#1762]
## 基本情况 

我是把typecho当笔记系统使用的，经常要查询之前的文章 。

文章列表近几天的内容，目前显示为“N小时前”“N天前”这样的显示方式，不知道这样的意义是什么，只知道还需要自己再算一下这个N天前到底是哪一天。

## 描述你考虑过的替代方案

能否让文章列表的日期全部显示为“4月12日”这样的绝对时间，能同时选择是否显示“14:35”这样的信息更好。

## 顺便问一下

目前的这种一周内的文章，日期显示为“N天前”的原因是什么，对于什么样的场景有意义？

**Comment by sy-records** [comment]
这是主题作者需要干的事情，你是用的默认主题吗？

**Comment by vimbackground** [comment]
我指的列表是系统后台的文章列表，不是指的前台主题。

**Comment by sy-records** [comment]
超过一个星期就是年月日了

https://github.com/typecho/typecho/blob/3caebb3b20da3232ad5592b257d4825de2373ab8/var/Typecho/I18n.php#L82-L129

如果需要显示你的方案，84行直接return

```php
        return date('m月d日 H:i', $from);
```
