### ISSUE TITLE
typecho后台文章编辑无文本框

### ISSUE THREAD

**Issue by LineXic** [typecho/typecho#1770]
## 描述这个 Bug

![Image_1715941043376](https://github.com/typecho/typecho/assets/121679359/964dc04b-2548-40ed-a191-cd463bff648d)
具体问题如上，点管理重新编辑文章后没有出现理想中的文本框编辑

### 复现方式

复现的步骤：

1. 前往 菜单''
2. 点击 '管理'
3. 滚动到 '某一文章'
4. 看到错误

### 期望的结果

打开后即可看到文本框

### 截图

![Image_1715941043376](https://github.com/typecho/typecho/assets/121679359/06ac7937-4e06-4f0b-a7bf-c7f45a10aab4)

### 平台

- 操作系统版本：宝塔Centos8
- Nginx 版本：1.12.1
- 数据库版本：
- PHP 版本：7.4.33
- Typecho 版本：1.2.1
- 浏览器版本：Firefox 125.3.0

**Comment by sodading** [comment]
是不是有js失效或加载慢导致编辑器加载不出来

**Comment by sy-records** [comment]
电脑浏览器查看console有什么错误信息

顺便可以打开`debug`看看有没有什么错误信息，在`config.inc.php`中加入：

```php
define('__TYPECHO_DEBUG__', true);
```
