### ISSUE TITLE
关于插件和命名空间问题

### ISSUE THREAD

**Issue by albaz64** [typecho/typecho#1773]
## 你的改进是否与某个问题有关？请描述

看其他人写的插件一般是 `class XXX_Plugin implements Typecho_Plugin_Interface` 开头的并且没有使用命名空间，HelloWorld 则是没有标识的 `class Plugin implements PluginInterface` 经过排错后发现只有用第二种写法才能使用命名空间，否则就会

```
无法启用插件
Typecho\Widget\Exception: 无法启用插件 in /typecho/var/Widget/Plugins/Edit.php:61
Stack trace:
#0 /typecho/var/Widget/Plugins/Edit.php(313): Widget\Plugins\Edit->activate('AliveTitle')
#1 /typecho/var/Widget/Action.php(71): Widget\Plugins\Edit->action()
#2 /typecho/var/Typecho/Widget.php(155): Widget\Action->execute()
#3 /typecho/var/Typecho/Router.php(85): Typecho\Widget::widget('\\Widget\\Action', NULL, Array)
#4 /typecho/index.php(23): Typecho\Router::dispatch()
#5 {main}
```

并且第二种写法必须搭配使用命名空间才行

## 描述你想要的解决方案

到底哪种写法才是比较推荐的，或者说其实它们是等价的？希望给出一个明确的说明。

此外还有例如 `Typecho_Plugin::factory('admin/menu.php')→navBar = array('HelloWorld_Plugin', 'render');` 和 `\Typecho\Plugin::factory('admin/menu.php')->navBar = __CLASS__ . '::render';` 两种不同的写法。

**Comment by sy-records** [comment]
第二种

https://joyqi.com/typecho/about-typecho-1-2-dev-plan.html
