### ISSUE TITLE
万人血书希望作者出个官方的Restful api功能，太想要这个了。

### ISSUE THREAD

**Issue by mrjucn** [typecho/typecho#1774]
民间自发的Restful api插件大多都是功能不齐全，或者就是随着版本而失效了。太可惜了。

如果出官方的Restful api，那么typecho估计会焕发第二春，哈哈，玩法倍增。这个后台主要是太好用了。没有Restful api尤为可惜呀。

**Comment by sy-records** [comment]
Duplicate of #1225
