### ISSUE TITLE
希望能够新增对 AtomHub 的支持

### ISSUE THREAD

**Issue by AkarinLiu** [typecho/typecho#1781]
## 你的想法是否与某个问题有关？请描述

Docker Hub 镜像站在中国大陆地区全线关闭了，不得不使用其他方式下载镜像。

## 描述你想要的解决方案

让用户从 [AtomHub](https://atomhub.openatom.cn) 下载镜像。

## 描述你考虑过的替代方案

- 自行搭建 Docker Registry
- 使用 GHCR 镜像站
- 转存至阿里云容器镜像服务

**Comment by sy-records** [comment]
atomhub 应该还没对外开放吧，等公开的会提交一下。

**Comment by joyqi** [comment]
目前还不支持公开的提交，待支持以后再考虑实现。
