### ISSUE TITLE
初次使用Docker部署Typecho镜像时关于HTTPS的问题

### ISSUE THREAD

**Issue by z-hanzhe** [typecho/typecho#1783]
## 描述这个 Bug

Docker镜像：joyqi/typecho  nightly-php8.2-apache

我在使用Docker启动项目的时候明确指定了网站地址`-e TYPECHO_SITE_URL=https://xxx.xxx.xxx`，但是在访问首页部署项目时仍然指向了 HTTP 资源，导致资源加载失败无法完成初始化

![image](https://github.com/typecho/typecho/assets/58802604/53003e88-0e09-45b3-a013-c0fb462d2b4a)

**Comment by sy-records** [comment]
`config.inc.php` 中定义下`__TYPECHO_SECURE__`为`true`

**Comment by z-hanzhe** [comment]
`config.inc.php`这个文件应该是项目部署完成后在根目录生成的吧，现在项目处于未部署状态，由于资源加载失败无法继续部署，找不到这个文件....

**Comment by z-hanzhe** [comment]
> `config.inc.php` 中定义下`__TYPECHO_SECURE__`为`true`

我在Docker镜像中没有找到这个文件，之后我下载了Github上的发行版，解压后发现也没有这个文件，然后我网上查了一下了解到`config.inc.php`是PHP的配置文件，不是Typecho的配置文件，了解了一下PHP的语法手写这个文件，结果网页无法访问了....

![image](https://github.com/typecho/typecho/assets/58802604/f9828b2a-efd5-49c4-baf0-a0de72a168b1)

**Comment by sy-records** [comment]
不是.. 它是Typecho安装后生成的配置文件，你在install.php中打印下`$_SERVER`看看

**Comment by z-hanzhe** [comment]
> 不是.. 它是Typecho安装后生成的配置文件，你在install.php中打印下`$_SERVER`看看

这是我的操作流程，域名也在截图中给出来了，截图中 dk 是 docker 的别名，我不懂 PHP 所以不太理解你说的“在install.php中打印“是什么意思，我就单纯在 docker 中打印一下变量了

![image](https://github.com/typecho/typecho/assets/58802604/ef6cedad-700b-4326-8954-0823c87b4c08)

**Comment by sy-records** [comment]
你用的apache镜像，应该还有用了其他的webserver，需要检查一下有没有对应的信息，没匹配到所以才是http

https://github.com/typecho/typecho/blob/31f5192c9d2291071a6919587ce45b7789fcec7f/var/Typecho/Request.php#L455-L463

**Comment by z-hanzhe** [comment]
我明白你的意思了，我用了Nginx将请求转发到typecho容器上，可能问题出在这里了，我研究研究咋回事儿，麻烦啦
