### ISSUE TITLE
部署时报错，Response.php有错

### ISSUE THREAD

**Issue by H4nke2** [typecho/typecho#1784]
## 描述这个 Bug

lnmp部署，php可以正常解析phpinfo.php，但是访问index.php或者install.php时nginx报错：FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'Response'(T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /usr/share/nginx/html/var/Typecho/Response.php on line 73" while reading response header from upstream,

### 复现方式

复现的步骤：

安装nginx，php，并配置好，启动服务。
打开index.php

### 期望的结果

能够正常进入安装页面

### 截图

![image](https://github.com/typecho/typecho/assets/89850465/47c67a3b-a994-4196-87f9-2fd75736f90f)

**Comment by joyqi** [comment]
你的 Typecho 版本和 PHP 版本分别是？

**Comment by H4nke2** [comment]
> 你的 Typecho 版本和 PHP 版本分别是？

typecho是1.2.1换了开发版也不行，php是7.2.24

**Comment by sy-records** [comment]
1.2.1 应该是没问题的，开发版本已经要求PHP7.4了
