### ISSUE TITLE
插件配置检查函数 configCheck 返回错误信息，却未能阻止配置被保存

### ISSUE THREAD

**Issue by cuixiping** [typecho/typecho#1790]
## 描述这个 Bug

插件配置检查函数 configCheck 返回错误信息，却未能阻止配置被保存

### 复现方式

```
class ABC_Plugin implements PluginInterface
{
    //...
    public static function configCheck($settings)
    {
        return '配置无效';
    }
    //...
}
```

### 期望的结果

`configCheck` 返回错误信息时，配置不保存，且页面停留不变, 提示错误信息.

### 平台

- Typecho 版本：1.2 ~ master

**Comment by benzBrake** [comment]
throw new Exception 才会阻止吧

**Comment by sy-records** [comment]
插件里实现`configHandle`就不会自动保存了。

https://github.com/typecho/typecho/blob/3caebb3b20da3232ad5592b257d4825de2373ab8/var/Widget/Plugins/Edit.php#L291
