### ISSUE TITLE
没有媒体库，没有附件上传的入口

### ISSUE THREAD

**Issue by kotonamishion** [typecho/typecho#1791]
## 描述这个 Bug

请问是移除了媒体库或者附件上传的设置了吗？
我并没有看到文件上传的入口，我现在上传文件就编辑一篇文章，然后选旁边的附件，点上传。应该是有附件上传这个功能的吧，为什么我的没有，折腾了几天才安装好了。现在才后知后觉没有媒体库，没有文件上传的功能，请问是移除了还有我的问题

### 复现方式

复现的步骤：

1. 前往 '...'
2. 点击 '....'
3. 滚动到 '....'
4. 看到错误

### 期望的结果

简明扼要地描述你期望看到的结果。

### 截图

如果可以的话，请添加截图或视频以帮助解释你的问题。

### 平台

- 操作系统版本：
- Apache/Nginx 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

**Comment by sy-records** [comment]
Duplicate of #1791
