### ISSUE TITLE
希望可以支持两个或多个博客数据进行上传合并

### ISSUE THREAD

**Issue by ccossmi** [typecho/typecho#1802]
## 你的改进是否与某个问题有关？请描述

本人有两个不同的 typecho 博客，现在为了方便统一管理，想将其中一个合并到另一个上，只是对于数据的迁移略感苦恼，虽然也找到了[相关教程](https://blog.luoli.net/71.html)，但操作起来还是稍显繁琐，尤其对于毫无基础和经验的小白更是无从下手。

## 描述你想要的解决方案

希望有个上传合并功能，比如在 控制台-备份-恢复数据 处，上传文件时可以有 合并 与 覆盖 两重选择。

## 描述你考虑过的替代方案

或者编写相关插件，方便小白用户进行简单的、傻瓜式的一键迁移与合并。

**Comment by joyqi** [comment]
这个功能通过插件解决比较合适
