### ISSUE TITLE
[求助] 迁移服务器之后无法发布文章

### ISSUE THREAD

**Issue by MUKAPP** [typecho/typecho#1811]
点击发布文章之后一直转圈，然后ERR_CONNECTION_CLOSED，或者CF返回服务器超时（524）
看网站日志 POST /action/contents-post-edit?_=XXXXXXXXXX 返回了 499
求大佬们帮忙看看是什么问题

### 截图

![image](https://github.com/user-attachments/assets/05e37fb3-7c03-491b-bab9-44b968a9b0c6)

### 平台

- 操作系统版本：
- Apache/Nginx 版本：Nginx 1.24.0
- 数据库版本：MySQL 5.7.44
- PHP 版本：PHP 7.2.33
- Typecho 版本：1.2.1
- 浏览器版本：Microsoft Edge 129.0.2792.65

**Comment by sy-records** [comment]
把 cf 去掉，直接请求源站看

**Comment by MUKAPP** [comment]
> 把 cf 去掉，直接请求源站看

好像还是一样

**Comment by MUKAPP** [comment]
草稿也是一样的

**Comment by MUKAPP** [comment]
已解决，是AutoTags的问题
