### ISSUE TITLE
开启CDN后，插件管理无法正常使用

### ISSUE THREAD

**Issue by funnycups** [typecho/typecho#1814]
## 描述这个 Bug

在1.2.1版本上，使用Cloudflare，会导致后台对插件的启用、停用出现错误提示
在客户端使用hosts将域名直接指向源IP，则不会报错
开启CDN时，有极小概率可以正常工作，无法复现
开启CDN（或其他原因）似乎还影响到了插件的异步回调，具体表现是异步回调的函数没有被运行，但这点有待更进一步验证

### 复现方式

复现的步骤：

1. 前往 插件管理
2. 点击 启用/禁用
3. 看到错误

### 期望的结果

插件被正确管理

### 截图

<img width="488" alt="image" src="https://github.com/user-attachments/assets/982d303f-7d43-435a-b6fe-1f9f9f931f70">

### 平台

- 操作系统版本：Linux CentOS7
- Apache/Nginx 版本：Nginx 1.20
- 数据库版本：MySQL 5.6
- PHP 版本：8.0
- Typecho 版本：1.2.1
- 浏览器版本：Chrome129.0.6668.100

**Comment by sy-records** [comment]
CDN 不要缓存后台，关闭忽略请求参数。

**Comment by funnycups** [comment]
> CDN 不要缓存后台，关闭忽略请求参数。

cf-cache-status一直是dynamic，也没有开启忽略请求参数，试过清除本地和服务器上的缓存、删除Cookie，但都不行

**Comment by sy-records** [comment]
回源正常就不是 typecho 的 bug 导致的了，所以需要检查 CDN 的问题

**Comment by funnycups** [comment]
> 回源正常就不是 typecho 的 bug 导致的了，所以需要检查 CDN 的问题。
> 
> 在 edit.php 里打断点看看吧。

我研究一下

**Comment by funnycups** [comment]
是cloudflare添加了Speculation-Rules头导致的，插件启用和禁用的请求被发送了两次，导致浏览器跳转页面时事实上插件已经被启用或禁用过了


________________________________

**Comment by funnycups** [comment]
你可以开浏览器的元素审查看看你这边是否有发出两次请求。Speculation-Rules响应头属于试验状态，很多浏览器是不会遵循这个规则的


________________________________

**Comment by funnycups** [comment]
我在手机上的kiwi就没有碰到这个问题，因为kiwi没有遵循这个头去发送请求


________________________________

**Comment by funnycups** [comment]
我注意到cf在四小时前刚刚发布了一个有关speed brain影响wordpress用户的[修复](https://www.cloudflarestatus.com/incidents/vknz38vrw6pv)，我稍后再重新打开speed brain试试看有没有问题

**Comment by funnycups** [comment]
这个问题应该已经被修复了。我重新打开了speed brain，目前没有再出现这个问题
另外，关于开启CDN影响插件异步回调是我的误判，实际原因是getHeader方法只使用HTTP_CONTENT_TYPE而没有用CONTENT_TYPE获取数据类型，从而影响了程序对async请求的校验，更新至开发版后问题解决
