### ISSUE TITLE
开发版如何降级到正式版

### ISSUE THREAD

**Issue by hczcyy** [typecho/typecho#1815]
各位大佬，昨天升级到了1.3开发版，发现主题和部分插件不兼容，请教如何降级到1.2

**Comment by joyqi** [comment]
使用备份工具把数据备份到本地，重新安装 1.2.1 版本，然后把备份数据导入。

**Comment by hczcyy** [comment]
> 使用备份工具把数据备份到本地，重新安装 1.2.1 版本，然后把备份数据导入。

感谢大佬回复，已完成。
