### ISSUE TITLE
feed/atom/ 链接里提示创建动态属性已弃用

### ISSUE THREAD

**Issue by rufei365** [typecho/typecho#1833]
## 描述这个 Bug
在atom链接的页面顶部有一行这样的提示：
<b>Deprecated</b>:  Creation of dynamic property Typecho\Widget\Request::$feed is deprecated in <b>/var/Widget/Archive.php</b> on line <b>253</b>

### 平台

- 操作系统版本：Debian 12
- Apache/Nginx 版本：Nginx 1.26.2
- 数据库版本：MySQL 5.7.43
- PHP 版本：PHP 8.2.24
- Typecho 版本：1.2.1
- 浏览器版本：Google Chrome 131.0.6778.86

**Comment by sy-records** [comment]
开发版应该修复过了
