### ISSUE TITLE
Typecho_Http_Client_Adapter_Curl请求报错

### ISSUE THREAD

**Issue by binjoo** [typecho/typecho#226]
![qq20140418122209](https://cloud.githubusercontent.com/assets/219092/2739491/2142d80c-c6b1-11e3-841a-095512324a10.png)

发送HTTPS请求的时候报错，需要在·Typecho_Http_Client_Adapter_Curl·的·httpSend·方法加入

``` php
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
```

才不会报错。。

资料参考：(http://blog.csdn.net/clh604/article/details/8528787)

**Comment by denglitong** [comment]
我在微信也遇到这个问题，分享朋友圈后查看评论出现500，Query database fail,
