### ISSUE TITLE
关于安装过程提示的数据库连接的信息

### ISSUE THREAD

**Issue by kaizhuQin** [typecho/typecho#239]
> 对不起，无法连接数据库，请先检查数据库配置再继续进行安装   

在选择数据库适配器类型为"Mysql 原生函数适配器"和"Pdo 驱动 Mysql 适配器"的时候.总会提示上面的信息.相应的扩展确认是已经安装了的.不知道是不是少安装了什么扩展?

![2014-05-03 10 13 11](https://cloud.githubusercontent.com/assets/4590307/2869364/848a6e12-d268-11e3-8906-f11b43b6a52b.png)

**Comment by lurruery** [comment]
需要自己新建数据库的

**Comment by xiabeifeng** [comment]
# **找到原因了。**

我也遇到了同样的问题，后来在文件中var_dump(mysql_errno()); 和var_dump(mysql_error());，得到的结果是mysql 2002错误。

2002 (CR_CONNECTION_ERROR) - Can't connect to local MySQL server through socket '%s' (%d)。

我自己本机的开发环境配置了很多虚拟主机，但是在安装的时候默认填写的是localhost，导致报错，后来把localhost改成我本机配置的虚拟主机名称www.typecho.test就好了。

**Comment by kramon** [comment]
试试把数据库密码控制在8位数以内。

**Comment by anphorea** [comment]
有的是因为目录权限的问题。
chown -R www-data /var/www/html

**Comment by pluveto** [comment]
我解决了。
https://www.pluvet.com/linux/apache-php-can-not-write-despite-777-permission.html

**Comment by ufolux** [comment]
> 需要自己新建数据库的

这个是正解，问题解决

**Comment by pluveto** [comment]
自建数据库治标不治本，根本还是权限问题


 
---原始邮件---
发件人: "ufolux"<notifications@github.com>
发送时间: 2019年7月2日 00:46:36
收件人: "typecho/typecho"<typecho@noreply.github.com>;
抄送: "pluveto"<reg@pluvet.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [typecho/typecho] 关于安装过程提示的数据库连接的信息 (#239)


 
需要自己新建数据库的
  
这个是正解，问题解决

**Comment by GalaxySuze** [comment]
今天遇到相同问题，需要自己在mysql中建立名为「typecho」的数据库解决了

**Comment by cimadream** [comment]
分以下几步骤排查问题：
1.是否装有pdomsql适配
2.数据库中是否typecho数据库
3.如果是以docker启动项目的情况下：
docker run方式：
`docker run --link mysql01 -p 80:80 -d
`
数据库地址：mysql01:3306，数据库主机：mysql01
同理，docker-compose编排容器方式的话，只需要看docker-compose.yml文件中link mysql的名称

其实主要问题就是数据库地址的问题

**Comment by aiAdzari** [comment]
排查所有问题均为无误但还是无法解决的时候不妨试试这个方法：
将localhost改为127.0.0.1
此方法是在本地安装测试时，后台具体错误为：`SQLSTATE[HY000] [2002]`
