### ISSUE TITLE
升级至 1.0 正式版出现的一些问题

### ISSUE THREAD

**Issue by sanddudu** [typecho/typecho#289]
主页无法正常加载，似乎是因为特定文章的原因

但是在后台可以加载，而且即使将这篇文章存为草稿，主页依然显示

出现了下面的错误日志

```
2014/10/09 20:33:30 [error] 24670#0: *4824820 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function mb_strtoupper() in /****/var/CommonMark/Reference/Reference.php on line 90" while reading response header from upstream, client: 218.5.15.9, server: blog.****, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:****", host: "blog.*****", referrer: "http://blog.****/admin/index.php"
```

在访问主页，和这个文章页面时都会出现

此外访问所有 category 都为 Database Query Error

以上问题在 1.0 测试版中均未出现

**Comment by bsed** [comment]
Argument 1 passed to Widget_Archive::indexHandle() must be an instance of Typecho_Db_Query, null given, called in /data/www/web/var/Widget/Archive.php on line 1368

**Comment by 121238960** [comment]
为什么突然报错？Argument 1 passed to Widget_Archive::indexHandle() must be an instance of Typecho_Db_Query, null given, called in /data/www/web/var/Widget/Archive.php on line 1368
