### ISSUE TITLE
Markdown 扩展语法

### ISSUE THREAD

**Issue by JokerQyou** [typecho/typecho#298]
Typecho 是完全不支持任何扩展语法吗？如果支持的话，具体支持哪些呢？
比如 http://microjo.github.io/2012/markdown_ext.html 这里所写的扩展语法，类似 `{: #someid .someclass somekey='some values' }` 这种对指定元素加属性的方式会很实用（之前个人有用在图片延迟加载上）。

**Comment by JixunMoe** [comment]
同意 强烈要求添加 `~~删除线~~` 功能 （

**Comment by aneasystone** [comment]
@JixunMoe 我很早的时候提交了一个支持删除线的 PR #382 ，不过迟迟没有人 Merge :-(，你可以手工修改下 :ghost:

**Comment by JixunMoe** [comment]
@aneasystone 我在看到你這條評論之前直接把整個 Markdown 解析器換成了另外一個..

https://github.com/erusev/parsedown

具体的修改代码:
```
<?php if (!defined('__TYPECHO_ROOT_DIR__')) exit;
include_once __DIR__ . '/Parsedown.php';

class Markdown
{ 
    public static function convert($text)
    {
        static $Parsedown;

        if (empty($Parsedown)) $Parsedown = new Parsedown();

        return $Parsedown->text($text);
    }
}
```

**Comment by joyqi** [comment]
我计划在HyperDown稳定后更换
https://github.com/SegmentFault/HyperDown
