### ISSUE TITLE
Typecho1.0 中<pre>标签内仍然进行markdown解析？

### ISSUE THREAD

**Issue by XGFan** [typecho/typecho#299]
好吧，标题确实很乱
在0.9中
<pre>
# 代码注释
代码
</pre>
会显示为

<pre>
# 代码注释  
代码
</pre>

在1.0中就会变成了
<pre>
代码注释（这句会变成一级标题）
代码
<pre>

**Comment by leonacwa** [comment]
这个问题官方没解决时只能自己解决，我自己修改了源代码里的 MarkDown 组件，替换为 Parsedown 组件，然后添加代码，将html特殊字符转移，比如 < > 。
