### ISSUE TITLE
求助typecho nginx子目录伪静态规则

### ISSUE THREAD

**Issue by seovery** [typecho/typecho#302]
http:///www.xxx.com/blog/
子目录 blog 的伪静态试了好几个方法都不行，404错误页面，应该怎么解决呢。

无效方法一：

```
location /blog/ {
if (!-e $request_filename){
rewrite ^/blog/(.*)$ /blog/index.php;
}
}
```

无效方法二：
```
location /blog/ {
if (-f $request_filename/index.html){
rewrite (._) $1/index.html break;
}
if (-f $request_filename/index.php){
rewrite (._) $1/index.php;
}
if (!-f $request_filename){
rewrite (.*) /blog/index.php;
}
}
```

难道是服务器nginx.conf需要什么地方修改吗？

**Comment by tanliansheng** [comment]
以前一直是 cgi.fix_pathinfo = 1 .后来忘记在哪看的,说nginx官方对php-fpm的支持有了优化,具体是fix_pathinfo =0然后 nginx配置里加了fastcgi_split_path_info 这一项.
location ~ [^/]\.php(/|$) { 
fastcgi_split_path_info ^(.+?\.php)(/.*)$; 
fastcgi_pass unix:/var/run/php5-fpm.sock; 
fastcgi_index index.php; 
include fastcgi_params; }
我测试可行.有兴趣的可以试试.

**Comment by nishuo** [comment]
@ilaotan 困扰几天的问题。。解决了 感谢。

**Comment by dearco** [comment]
@ilaotan 解决了。。。网上的都没用。。谢谢

**Comment by coocro** [comment]
伪静态设置
默认的typecho网页链接中总带着一个index.php，那么有没有办法把这个链接美化一下呢？我们需要开启typecho的伪静态。首先编辑nginx的站点文件，在server大括号中加入

if (-f $request_filename/index.html){
rewrite (.*) $1/index.html break;
}
if (-f $request_filename/index.php){
rewrite (.*) $1/index.php;
}
if (!-f $request_filename){
rewrite (.*) /index.php;
}
