### ISSUE TITLE
无法修改站点地址

### ISSUE THREAD

**Issue by movable** [typecho/typecho#311]
小站用了https，没有办法修改站点地址。

通过后台-->设置-->站点地址 修改提交之后，出现错误提示：
![siteurl](https://cloud.githubusercontent.com/assets/1259564/4668562/431c1bde-5566-11e4-924c-eba795891992.jpg)
特意去数据库里面看了一下，发现option表里的siteUrl字段确实更新了。
然而实际上通过$this->options->siteUrl()获取到的还是http而不是正确的https.

版本 1.0 (14.10.10)

**Comment by zoand** [comment]
是这样定义么？
define('TYPECHO_SECURE',true);
