### ISSUE TITLE
当将“父分类”添加到“子分类”，那么问题来了。

### ISSUE THREAD

**Issue by skiy** [typecho/typecho#318]
啥也不说。看 metas 表吧。
1是2的父分类，2是3的父分类，3是1的父分类。。。

数据库中：
![](http://www.tu265.com/di-5f54158bda25443660d97c7a1be5a1b3.png)

后台中
![](http://www.tu265.com/di-dab3e837d6cee365dede2a29c755ec23.png)

按理说，如果当前是某子分类的父分类，那么它这个添加到“父级分类”这里不应该显示其“子分类”。不过不知道官方的开发版是否已经处理了这个BUG。

**Comment by cvmax** [comment]
在修改某个目录的父目录时，就不应该出现当前目录的子目录。版本 1.0 (14.10.10) 。刚刚复现了这个问题。
