### ISSUE TITLE
Windows Live Writer离线发布日志带图片时出错

### ISSUE THREAD

**Issue by husx** [typecho/typecho#334]
发布图片日志提示：
从日志服务器接收的对 metaWeblog.newMediaObject 方法的响应无效:
Invalid response document returned from XmlRpc server

纯文字日志正常

**Comment by snmoney** [comment]
遇到相同的问题，版本 1.1
看源码 car\Widget\XmlRpc.php 是有处理的
L: 2320
'metaWeblog.newMediaObject' => array($this, 'mwNewMediaObject'),                  

但不知道出于什么原因可能是不兼容？
