### ISSUE TITLE
头像被墙了，建议换成多说的

### ISSUE THREAD

**Issue by m4html** [typecho/typecho#344]
乳蹄

**Comment by shuxiao9058** [comment]
github中最新的代码支持自定义头像url前缀了，在config.inc.php加入如下内容即可：

``` php
/** 自定义gravatar url前缀 */
define('__TYPECHO_GRAVATAR_PREFIX__', 'http://gravatar.duoshuo.com/avatar/');
```

**Comment by AirScr** [comment]
Typecho不是一个专为大陆开发的产品，所以采用Gravatar作为默认获取头像。

Typecho is not a product which is aim at mainland China. So they decided to set Gravatar as default avatar.

**Comment by Pochinki98** [comment]
so sad this site is also down now.
