### ISSUE TITLE
最新版无法上传图片，没有提示，也没有看到上传的，safari上

### ISSUE THREAD

**Issue by LINAICAI** [typecho/typecho#347]
最新版无法上传图片，没有提示，也没有看到上传的，safari上
各种bug伤心

**Comment by packingbox** [comment]
我这里也有这个问题, (safari和chorome都试过)上传附件经常失败, 但是不知怎么样自己又会好了, 可能不知道下一次又不行了, 如果上传失败了, 再传就说重复文件.

**Comment by packingbox** [comment]
我大概知道什么问题了, mac编辑导出图片后缀名为大写的PNG或者JPG, 上传时就会不符合文类后缀失败, 因为区分大小写. 把后缀名字改成小写的png或者jpg就成功上传, 如果用mac截图得到的图片又是小写的后缀png, 终于找到了有时上传可以有时失败的原因. 

希望下一版修正这个bug, 上传检查前把文件后缀名转换小写, 再去检查上传文件类型是否合法.
