### ISSUE TITLE
1.0的版本，数据库没有办法备份

### ISSUE THREAD

**Issue by jeanbi** [typecho/typecho#353]
不管我是备份在本地还是备份在服务器，界面都是空白的。然后FTP上服务器看，目录下也没有生成相应的文件。
之前的版本没有存在这个问题。

**Comment by fenbox** [comment]
你的数据备份应该是用的插件把，请联系插件作者

**Comment by yuangu** [comment]
<br />
<b>Warning</b>:  sizeof(): Parameter must be an array or an object that implements Countable in <b>C:\xampp\htdocs\var\Widget\Backup.php</b> on line <b>218</b><br />
<br />
<b>Warning</b>:  sizeof(): Parameter must be an array or an object that implements Countable in <b>C:\xampp\htdocs\var\Widget\Backup.php</b> on line <b>218</b><br />
<br />
<b>Warning</b>:  sizeof(): Parameter must be an array or an object that implements Countable in <b>C:\xampp\htdocs\var\Widget\Backup.php</b> on line <b>218</b><br />
<br />
<b>Warning</b>:  sizeof(): Parameter must be an array or an object that implements Countable in <b>C:\xampp\htdocs\var\Widget\Backup.php</b> on line <b>218</b><br />
<br />
<b>Warning</b>:  sizeof(): Parameter must be an array or an object that implements Countable in <b>C:\xampp\htdocs\var\Widget\Backup.php</b> on line <b>218</b><br />
<br />
