### ISSUE TITLE
markdown 粘贴内容有网址时造成浏览器假死

### ISSUE THREAD

**Issue by opswill** [typecho/typecho#355]
使用的是开发版，在编辑文章时，粘贴的内容中有网址时，会造成浏览器假死，无法操作
去掉网址在粘贴时就正常了

**Comment by willis55** [comment]
相同的情况还有：
 代码块  、、、     、、、
html注释 
Chrome firefox最新款都会无响应

**Comment by chachachade** [comment]
建议不要直接在线上使用开发版，本地测试一下就好
