### ISSUE TITLE
文章内容 typecho_contents 表的 text 字段，默认使用 Text 类型太小

### ISSUE THREAD

**Issue by maemual** [typecho/typecho#358]
文章内容使用 Text 类型太小，只有 64 K，大约写一万多字就超了。建议改成 MediumText。

**Comment by shingchi** [comment]
你写过一万字的文章？发来看看...

**Comment by maemual** [comment]
@shingchi 翻译的[论文](http://maemual.me/index.php/archives/15/)

**Comment by shingchi** [comment]
@maemual 汗，这情况太特殊了，可以分多篇来发，不行自己就改下数据库字段类型吧。程序针对的是一般，而非针对特殊。

**Comment by maemual** [comment]
嗯，也是。
