### ISSUE TITLE
关于 rootUrl 和 siteUrl 的问题

### ISSUE THREAD

**Issue by JasinYip** [typecho/typecho#360]
问题是这样遇到的：
之前我一直是使用 Apache ，最近因为还需要做一个 Node 的环境，而 Apache 配置端口转发有点麻烦，于是我在外面套了一层 Nginx，然后 Apache 配置 Listen 127.0.0.1:8080。

于是问题来了，`/admin/` 下的 css（比如 grid.css 和 normalize.css）的 `href` 的路径都是类似 `localhost:8080:8080/admin/css/normalize.css` 这样的。

我找同事帮我查了一下，他最后将 `var/Widget/Options.php` 的 `___adminUrl()` 方法里的

`__TYPECHO_ADMIN_DIR__ : '/admin/', $this->rootUrl);`

改为

`__TYPECHO_ADMIN_DIR__ : '/admin/', $this->siteUrl);`

就没问题了。

不知道这是 Typecho 的 bug 还是我的 Nginx/Apache 配置有问题，所以想反馈一下，不然以后更新怕是还会有问题。

最后感谢你们做了一个这么好用的博客程序！我和几个朋友都非常喜欢，并且经常向别人推荐 ^_^！辛苦啦~~

**Comment by joyqi** [comment]
你可以试一试最新的开发版
