### ISSUE TITLE
編輯狀態為草稿的問題

### ISSUE THREAD

**Issue by Mutsuki** [typecho/typecho#361]
不知道只有我一個人有這樣的問題還是？

就在剛才我發佈文章後，再將文章狀態編輯為“草稿”，然後狀態保存為“草稿”，但文章依舊是發佈的狀態。

**Comment by fenbox** [comment]
如果是已发布的文章，那么草稿相当于基于这篇文章的副本，除非把草稿发布了，否则原文不会更新
