### ISSUE TITLE
关于如何使用七牛加速静态资源

### ISSUE THREAD

**Issue by Sengxian** [typecho/typecho#362]
请问如何将网站里面的静态资源(非上传的附件)如CSS,JS等采用七牛cdn加速，例如我的网站一个js地址为http://www.xxx.com/usr/themes/xx/js/tools.js 我只要把地址替换为 http://cdn.xxx.com/usr/themes/xx/js/tools.js 就可以了，请问有什么方法替换地址，对主题和插件里的静态文件进行加速？

**Comment by AirScr** [comment]
在GitHub上，您也应该注意到了这个是Issues的位置。是解决Typecho错误的地方。在这里提这种问题并不能得到有效地帮助，请注意。

This place is for issues. We are here to solve problems about Typecho. You can go right place to complete your own request.

**Comment by bohanyang** [comment]
http://developer.qiniu.com/download/index.html#plugin
下载typecho插件安装
