### ISSUE TITLE
TypEcho 在中文版 Windows 2012 R2，IIS 8.5 上，中文 URL 工作异常。

### ISSUE THREAD

**Issue by Chenyao168** [typecho/typecho#364]
具体表现为，默认安装的情况下，搜索中文、打开中文 Tag 等，但凡 URL 涉及到中文，TypEcho 就会出现 404 错误，如果我设置伪静态，那么问题不会发生，请问这个问题当以何种方式解决？

**Comment by chachachade** [comment]
既然你都说了“如果我设置伪静态，那么问题不会发生”，那样直接开启固定链接啊，这就是解决办法。我认为这是你的环境配置问题。

**Comment by ejzhang** [comment]
把下面内容保存为web.config放入Typecho文件夹下即可。
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Default" patternSyntax="Wildcard">
                    <match url="*" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>`
