### ISSUE TITLE
申请用户时，有脚本注入的风险

### ISSUE THREAD

**Issue by LeToNode** [typecho/typecho#374]
显示screenName 设置为：    `leton<script>alert('abc(test)'`

引发的问题是用户管理页面不能正常显示了。

**Comment by joyqi** [comment]
你确定这个名字能注册？注册时已经检测过特殊字符了

**Comment by LeToNode** [comment]
额。是我网站上面有个用户的资料就是这个

**Comment by joyqi** [comment]
你的网站开放注册了么？

**Comment by LeToNode** [comment]
我自己测试了下，确实不能注册。问了那个用户，他说是比较早注册的，已经忘记了怎么搞的。估计后面我有升级过。关闭掉吧。我也看了代码，确实有检查。

**Comment by StoneMoe** [comment]
我认为在输出的时候应该也进行一遍过滤
