### ISSUE TITLE
Markdown语句在文章中不能与html代码混写

### ISSUE THREAD

**Issue by Sang0214** [typecho/typecho#378]
如题，混写后html后面的markdown语句会失效

**Comment by rakernel** [comment]
就是在html块里面插入markdown？这样当然不可以啊，处理的时候会将标签内的内容当作文本处理而不是markdown语法。

**Comment by joyqi** [comment]
我们只支持在markdown中混写部分html，包括`table`，`strong`，`a`等等。其它的不支持
