### ISSUE TITLE
不支持在PHP7.0 BETA版本

### ISSUE THREAD

**Issue by dsus4plus** [typecho/typecho#385]
Ubuntu14.04+Nginx+PHP7.0+MariaDB
显示502，但Nginx并没有输出错误日志
PHP显示Segmentation fault
WordPress正常，看来不是PHP的锅……

**Comment by kokororin** [comment]
Beta3表示后台登录后502，其他没问题

**Comment by joyqi** [comment]
能否把错误日志打开，并提供更多的细节

**Comment by joyqi** [comment]
php7版本测试没有问题，如果你还有问题，请尝试把所有插件删掉
