### ISSUE TITLE
<br> 遇到 <!--more--> 会自动添加</br>

### ISSUE THREAD

**Issue by kookxiang** [typecho/typecho#399]
例：

``` markdown
Test<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<!--more-->
Test
```

首页：

``` html
<p>Test<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></p>
</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>
<p class="more"><a href="http://127.0.0.1/typecho/index.php/archives/3/" title="未命名文档">- 阅读剩余部分 -</a></p>
```

然后 Chrome 会把 `</br>` 当成 `<br>` 处理，于是就出现了一大堆的空行

**Comment by aofall** [comment]
<br> 与  之间多加一个换行呢？

**Comment by kookxiang** [comment]
这个原因是因为用 more 隔开之后 typecho 会检查一遍标签闭合，然后好像并没有把 br 加进白名单

参考：
 - https://github.com/typecho/typecho/blob/master/var/Widget/Abstract/Contents.php#L119
 - https://github.com/typecho/typecho/blob/master/var/Typecho/Common.php#L524-L562

**Comment by Zhiping-Zhou** [comment]
我用的自信版，看上面的改动都有了，为啥还有这个问题。

http://910216.com/page/4/
使用openssl工具测试服务端支持的curves
