### ISSUE TITLE
如何支持表格

### ISSUE THREAD

**Issue by biezhi** [typecho/typecho#400]
我使用markdown，github上编写的文件里包含形如
```markdown
| 配置| 描述|
| --- |-----|
| aaa |vvvv |
```
在typecho里显示不正常

**Comment by virusdefender** [comment]
typecho 使用的 php markdown 的版本比较低，可以参考这里 http://forpikus.com/blog/archives/5/ 自己升级一下

**Comment by styra** [comment]
@biezhi 升级到最新开发版就行了。
