### ISSUE TITLE
无法发布编辑文章

### ISSUE THREAD

**Issue by liumingye** [typecho/typecho#404]
sae搭建的
点击发布文章后跳到http://www.liumingye.top/action/contents-post-edit?_=95f60a7461a7c5bb38889fc31b6fae19

**Comment by hainuo** [comment]
请问是否开启了伪静态支持

**Comment by TrueMacho** [comment]
@hainuo 我也出现了这个问题，对已有文章进行编辑或者发表文章时，点击跳转404错误。使用最近几个版本，包括最新的Typecho 1.1(15.5.12)，使用的是阿里云虚拟主机，开启了伪静态支持。
`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
Options -Indexes
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L]
</IfModule>`

**Comment by BKDOnions** [comment]
我也有这个问题
