### ISSUE TITLE
Config.php 70行有问题

### ISSUE THREAD

**Issue by skiy** [typecho/typecho#418]
https://github.com/typecho/typecho/blob/master/var/Typecho/Config.php#L70
第70行中的```$params```这个变量在哪里来的？
![qq 20151125155326](https://cloud.githubusercontent.com/assets/3362147/11391476/b59b4f0c-938d-11e5-9c1a-a029cd2f52b5.png)

**Comment by kokororin** [comment]
```php
void parse_str ( string $str [, array &$arr ] )
```
 **arr**
    If the second parameter arr is present, variables are stored in this variable as array elements instead.

**Comment by changlor** [comment]
我来翻译一下楼上大神的话，大概就是，$params是存放parse_str()处理$config后的字符，如果结果是一个数组，那么就拿他来替换原来的$config

**Comment by skiy** [comment]
我想说的是，这第二个参数没定义啊😱Skiychan 
            在2015年11月25日 16:22，空樱酱 写道:void parse_str ( string $str [, array &$arr ] )

arr
    If the second parameter arr is present, variables are stored in this variable as array elements instead.

**Comment by kokororin** [comment]
@skiy 不需要定义，请看官方文档

**Comment by skiy** [comment]
@kokororin 不在前面声明的话，不会报错？
```$params```它本身也不是参数，且前面也没有声明。这样也行？

**Comment by ldsink** [comment]
@skiy 我觉得你应该先好好学学PHP再来具体的项目提 Issues。：P
这类问题你大可以在自己的电脑上尝试。本机构建环境，可以用 PHP 的正则函数 preg_ 相关的( preg_match, preg_match_all )，都是这样的。

**Comment by skiy** [comment]
抱歉。粗心了。

第二个参数是接收参数，之前看文档时没有注意到，以为是分割参数。
