### ISSUE TITLE
关于分类

### ISSUE THREAD

**Issue by virink** [typecho/typecho#421]
是否能*缩进*二级目录。另外，是否能隐藏分类？例如该目录中的文章为0的时候不显示。

**Comment by hongweipeng** [comment]
你在电脑新建文件夹，系统也不会因为新建了空的文件夹就隐藏它啊

**Comment by virink** [comment]
我的意思是建立了大量二级目录、然后文章还没有发表、、这样显示一堆0感觉不太美观。
目前隐藏分类的问题已解决，加个首页判断，然后在前台隐藏，后台显示。。

**Comment by hongweipeng** [comment]
确实一大推空的栏目不好看，解决了就好，棒棒的

**Comment by joyqi** [comment]
这个可以自己在前台模版中加入判断解决
