### ISSUE TITLE
https ssl加密之后gravatar 头像不能正常载入

### ISSUE THREAD

**Issue by leehz** [typecho/typecho#432]
具体代码 见：
https://github.com/typecho/typecho/blob/master/var/Typecho/Common.php#L942

可以使用 https://gravatar.com/avatar/hashCode 来访问；
同时 也建议吧 http://www.gravatar.com 替换为 http://gravatar.com 来访问

**Comment by wangqiliang** [comment]
建议开发者强制让头像以HTTPS方式加载，以提高效率

**Comment by JShadowMan** [comment]
HTTPS的访问速度普遍比HTTP方式访问的速度慢

**Comment by wangqiliang** [comment]
@JShadowMan 其实个人认为这种慢可以忽略一大半。

**Comment by JShadowMan** [comment]
那让头像以HTTPS方式加载，如何说可以提高效率呢？

**Comment by JShadowMan** [comment]
@wangqiliang 那让头像以HTTPS方式加载，如何说可以提高效率呢？

**Comment by wangqiliang** [comment]
@JShadowMan 个人以为，这个地方是个判断语句，少判断一下效率自然提升一些。
对于现代浏览器来说，HTTPS对于访问的延时影响不大。（AES等对于CPU压力已经减少。）
基于此我提出上面的建议，欢迎反驳。

**Comment by JShadowMan** [comment]
@wangqiliang 单单判断所花的时间和HTTPS建立所需要的握手时间相比，我想应该可以忽略不计吧？

**Comment by wangqiliang** [comment]
@JShadowMan 主要是Gravatar明文连接在国内因为EdgeCast CDN原因，无法正常连接。在这种情况下，握手都不正常。所以这样的效率似乎更有保障 。 你怎么看？

**Comment by wangqiliang** [comment]
@leehz 其实secure.gravatar.com是正常的，你再看看？

**Comment by leehz** [comment]
https://github.com/wangqiliang 我这边访问是证书错误，不能正确访问到头像，gravatar现在应该不支持这种头像访问了，
