### ISSUE TITLE
截断符 <!--more--> 失效

### ISSUE THREAD

**Issue by viosey** [typecho/typecho#438]
编辑时候的预览有提示
![](http://ww3.sinaimg.cn/large/006aSYbtgw1f0r74tqq76j31fu0gtjsi.jpg)

但是到了首页就没有效果了，而且截断符位置应有的"continue reading"跑到了文章底部
![](http://ww4.sinaimg.cn/large/006aSYbtgw1f0r751yg6jj30p20bjq3g.jpg)

**Comment by joyqi** [comment]
你应该用的是开发版，我今天已经修复这个问题了
