### ISSUE TITLE
pre 与 ``` 

### ISSUE THREAD

**Issue by loozx** [typecho/typecho#443]
![1](http://ww1.sinaimg.cn/large/7c98397dgw1f10rmhypi4j20nk0afgo0.jpg)
![2](http://ww3.sinaimg.cn/large/7c98397dgw1f10rnfs6tuj20iv0a3abn.jpg)

不能用pre套住包括```在内的代码。

**Comment by kookxiang** [comment]
pre 是浏览器端的，\`\`\`是 markdown，会被转换成 pre 输出，你应该用 \\ 把 \' 转义了

**Comment by fenbox** [comment]
你可以使用 ``` 代替 `<pre>`，或者直接使用 `<pre>`，二者最好别混用
