### ISSUE TITLE
1.0不支持markdown的atx 形式

### ISSUE THREAD

**Issue by zhaodedong** [typecho/typecho#444]
1.0版本用markdown写文章的时候，不识别atx 形式的标题了，我一直习惯，用###来作为标题，但是这个版本貌似只支持==了。
我最近正在选型博客，我不太想因为博客本身来改变我的书写习惯，而且atx 本身就比较方便，感觉比另一个好多了
求问一下这个有办法解决吗？

**Comment by RocFang** [comment]
应该支持啊，我每篇文章的标题都是用#的，是否没加空格？

**Comment by fenbox** [comment]
一直都支持的
