### ISSUE TITLE
上传文件问题

### ISSUE THREAD

**Issue by TanLingxiao** [typecho/typecho#463]
设置上传其它文件格式后仍然不能上传

**Comment by hongweipeng** [comment]
目录是否有给写的权限

**Comment by TanLingxiao** [comment]
有权限。我觉得是系统本身的问题

**Comment by syrte** [comment]
在[后台][基本设置][允许上传的文件类型][其他格式] 填 `py`，点击[保存设置]，然后 `py` 就会消失不见。我填好几个文件类型，别的都没事，就 `py` 会不见。奇怪了。
有没有人遇到同样的问题？
我用的是 github 上11月份的开发版。

**Comment by hongweipeng** [comment]
说来也奇怪，文件不能上传的时候我跟踪代码，在`file-upload-js.php`不断alert，发现比方设置cpp格式允许，后台上传cpp一个请求都没有。后台把alert代码删掉。竟然就能上传了。太幽灵了。发生了什么。。。我什么都没做啊。。。。

**Comment by DT27** [comment]
@syrte py 会消失不见是因为 Typecho 把可执行文件都过滤掉了，如图：

![](http://i.imgur.com/DATH2An.jpg)

**Comment by syrte** [comment]
@DT27 谢谢。本来想上传 .py 的附件呢。
如果我手动把这个文件（Widget/Options/General.php）里的 py 去掉，会产生安装隐患吗？
