### ISSUE TITLE
安装后所有连接点击都是显示about:blank，怎么解决？

### ISSUE THREAD

**Issue by mangitleung** [typecho/typecho#464]
说明一下配置环境，Nginx+php5.5+mysql5.1.73，是安装在路由器上
实际情况请点击下面网址
http://mangit.ddns.info:85/typecho/

**Comment by itrainfox** [comment]
你自己看看源码的链接你就发现问题了`http://mangit.ddns.info:85:85/typecho/index.php/archives/1/ ` 这里面有两个85的端口号

**Comment by itrainfox** [comment]
路由器都来搭建博客，你反正那么喜欢折腾，你就使用HSTS技术吧，https的443端口电信又没封。

**Comment by mangitleung** [comment]
谢谢itrainfox，原来是端口重复；引用网上的解决方法
问题文件地址：\var\Typecho\Request.php（222-223行）
`elf::$_urlPrefix = (self::isSecure() ? 'https' : 'http') . '://' . (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : ($_SERVER['SERVER_NAME']).(in_array($_SERVER['SERVER_PORT'], array(80, 443)) ? '' : ':' . $_SERVER['SERVER_PORT']));`
把：array(80,443)改成array(80,443,8080)解决问题。

**Comment by mangitleung** [comment]
itrainfox  路由器搭建方便自己啊，反正家里的路由器除了停电就不会关，电费还是一样，我还在上面安装了XX-NET翻墙

**Comment by itrainfox** [comment]
可以是可以，但是还是用服务器来好得多，既然你用路由器来玩，那建议你上HTTPS，HSTS的方式，这样访问，就不用加端口号，更爽！
