### ISSUE TITLE
后台点击插件管理出错，请问怎么解决？

### ISSUE THREAD

**Issue by mangitleung** [typecho/typecho#465]
错误提示：
Fatal error: Call to undefined function token_get_all() in /opt/www/typecho/var/Typecho/Plugin.php on line 195

**Comment by cizel** [comment]
解决办法

1.vi  /usr/local/php/lib/php.ini

2.增加 extension=tokenizer.so

3.重启apache

**Comment by mangitleung** [comment]
@cizel 谢谢，按照你的方法已解决
