### ISSUE TITLE
安装过程中提示无法连接到MySQL

### ISSUE THREAD

**Issue by SnowWalkerJ** [typecho/typecho#475]
如题，提示：

> 对不起，无法连接数据库，请先检查数据库配置再继续进行安装

但是账号和密码都确认是没有问题的，安装的phpmyadmin也能正常登录，另外一个程序也能正常在mysql写入，始终不明白怎么回事。

目前服务端配置是Ubuntu14.04 64位 + nginx1.4.6 + php5.5.9 + MySQL5.5.49

感觉这个博客程序非常棒，希望各位大大能帮忙解决一下，谢谢！

**Comment by warjiang** [comment]
你要先在数据库中建立一个typecho的数据库，然后再安装就可以了
