### ISSUE TITLE
Typecho 1.1(15.5.12)php7.5上安装失败，无法连接数据库

### ISSUE THREAD

**Issue by v-leonhou** [typecho/typecho#478]
安装一直提示“对不起，无法连接数据库，请先检查数据库配置再继续进行安装”，数据库我测试连接没有问题，服务正常，而且数据库我也已经建好了

**Comment by lifehome** [comment]
#459

**Comment by lkxlaz** [comment]
@v-leonhou Sorry can't type chinese. Did you create a database called typecho manually? I had this same issue and fixed that by manually creating the db.
