### ISSUE TITLE
超链接怎么实现在新标签打开

### ISSUE THREAD

**Issue by khs1994** [typecho/typecho#489]
网上搜到的方法 找不到文件

**Comment by kokororin** [comment]
```html
<base target="_blank"/>
```

**Comment by DT27** [comment]
楼上方法是强制页面上所有超链接都新标签页打开

**Comment by khs1994** [comment]
加到那个文件啊

**Comment by kokororin** [comment]
header.php

**Comment by khs1994** [comment]
感谢

**Comment by hujy23** [comment]
楼上方法不太好，可以实现只让文章里的链接在新标签页打开：[参考这篇文章](http://www.ywlib.com/archives/38.html)

**Comment by hujy23** [comment]
您的邮件已收到，我会尽快处理。This is an automatic reply, confirming that your e-mail was received.Thank you
