### ISSUE TITLE
CentOS 7.2 安装v1.0时卡在空白页面

### ISSUE THREAD

**Issue by laopangzi** [typecho/typecho#498]
全新安装typecho时卡在空白页，处理了一段时间未解决，且不懂PHP语言，在此求助一下。

> 注：记得1.0版本发布没多久时成功安装过，未遇到该状况。
### 状况：
- 安装到install.php?start时卡住，整个页面空白。
- 查看数据库时发现数据库为空，未创建任何表。
- php-fpm及php的error log中无错误信息。

> 注：未启用OPcache，XCache等PHP加速器。
> &emsp;&emsp;使用雅黑探针连接mariadb数据库正常。
### 环境：
- typecho 1.0 (14.10.10) 官网链接下载
- DigitalOcean VPS、Virtualbox虚拟机
- CentOS 7.2
- Nginx 1.10.1
- mariadb-server 5.5.50
- PHP 5.4.16
- php-fpm 5.4.16
- php-pdo 5.4.16
- php-mysqlnd 5.4.16
- php-mbstring 5.4.16

**Comment by YinHeng89** [comment]
我跟你遇到的类似 不过我是OpenMediaVault安装的时候出现这种情况  要么白屏…要么链接全部错误  ，都是404

**Comment by drakven** [comment]
数据库引擎选择错了吧

**Comment by laopangzi** [comment]
@drakven 没选错，mysql的三种连接方式都试过

**Comment by kokororin** [comment]
index.php中加入`ini_set('display_errors',1);`看详细的出错信息

**Comment by wangzaikk** [comment]
请问你解决了么？我也遇到的相同的问题

**Comment by wangzaikk** [comment]
刚刚解决了，看了一下nginx的错误日志，说session没有写入权限。于是查看/var/lib/php/session 目录的权限设置，发现用户组为apache ，改成nginx就好了。

**Comment by ykla** [comment]
发现没有nginx组

**Comment by aiwb** [comment]
一样的问题，求问怎么解决
