### ISSUE TITLE
开启Https后旧博文里面图片引用地址不会自动变成https

### ISSUE THREAD

**Issue by ghost** [typecho/typecho#501]
第一次用博客就选择用typecho，喜欢typecho的简洁！
近期学着开启https安全访问，不过开启后发原来的旧博文访问量仍旧显示不安全。查明后发现原来是旧博文里引用图片的地址没有自动变成https，需要手动改一下。文章少还好，多的话只能改数据库，不太安全对于新手来说，希望官方能改进！启用https旧博文里面图片地址会自动改为https开头。

**Comment by neoFelhz** [comment]
后台界面内的设置，博客的主页的默认链接改为https头了吗？

**Comment by iNebular** [comment]
改了的啊。

Sent by Kevin's iPhone

**Comment by qianduanmei** [comment]
可用这个插件解决：https://plugins.typecho.me/plugins/CompressHTML.html
设置替换 http://www.your.com=https://www.your.com

**Comment by mierhuo** [comment]
自动替换内容就可以吧，也可以看一下我鼓捣的这个插件：
[https://github.com/mierhuo/SimpleCDN](https://github.com/mierhuo/SimpleCDN)
另外就是，平常养成多用 // 自适应协议类型的习惯吧

**Comment by jeklau** [comment]
可见发文时用内部链接是多么重要啊 ^_^

**Comment by loststar** [comment]
数据库批量改
