### ISSUE TITLE
gravatar头像

### ISSUE THREAD

**Issue by drakven** [typecho/typecho#502]
使用gravatar简直就是一大败笔，国内互联网环境大家都心中有数，为什么还会使用gravatar拖慢速度，使用typecho冲着这个简洁来的，本以为速度也会和这简洁一样令人惊喜，可惜！速度提不上去的话，对比wp，优势在哪？

**Comment by kokororin** [comment]
define('__TYPECHO_GRAVATAR_PREFIX__', 'http://gravatar.duoshuo.com/avatar/');

**Comment by khs1994** [comment]
头像地址启用https怎么解决啊

**Comment by drakven** [comment]
还是改成本地文件好了

**Comment by neoFelhz** [comment]
直接把config.php，第379行，把两个链接的www.改成cn.或者secure.即可。注意cn.的在前面，secure.的在后面。

**Comment by neoFelhz** [comment]
至于你浑身夸耀WordPress，你为什么不去用WordPress？专门给啥都不懂的小白上手。用好Typecho，一来必须学markdown二来必须至少会一些php。

**Comment by drakven** [comment]
我这有吹嘘wp什么，我之前用过wp，就是觉得wp臃肿才考虑换blog程序，从市场占有率看，wp自有他的优势，但是从wp迁移的也自知道wp的劣势和不足。
