### ISSUE TITLE
typecho默认编辑器，我能说不大好用么。。。。

### ISSUE THREAD

**Issue by yuzhaoge** [typecho/typecho#504]
如果使用过csdn博客提供的编辑器的话，想必两者就很容易比较优劣。。。typecho编辑调整格式太难调整格式。另外，能不能提供编辑器画表格的功能！！！

**Comment by drakven** [comment]
非常不好用，在输入代码行的时候非常不方便，而且不提供源码查看

**Comment by logoove** [comment]
学习 md以后 编辑爽yy

**Comment by fenbox** [comment]
typecho 支持 markdown 语法，你可以使用 markdown 进行编写，很好用的

**Comment by drakven** [comment]
markdown的使用者也只能是少数派吧

**Comment by drakven** [comment]
ckeditor会更受欢迎吧

**Comment by logoove** [comment]
markdown是最简单语法  只要不是傻子 都会用 # 我说是吗

**Comment by neoFelhz** [comment]
markdown对于用户还是太难，虽然我自己写了一篇10分钟上手markdown的博客，但是一个好一点的编辑器用来生成markdown语法更好。我就在用Editor.MD插件。

**Comment by drakven** [comment]
扯，你让一个没学过html和markdown的人写看你在文字当中加入<li><pre>……标签看他什么反应

**Comment by kokororin** [comment]
那去用 WordPress吧， Typecho就是给稍微懂点代码的同学用的

**Comment by DT27** [comment]
@yuzhaoge @drakven 
https://github.com/DT27/EditorMD/

![](https://dt27.org/usr/uploads/2016/03/2477390697.png)

**Comment by yuzhaoge** [comment]
@DT27   Thanks,还是这个比较好用，以后就用它了 https://github.com/DT27/EditorMD/

**Comment by cumtsd** [comment]
Markdown好用，问题是默认编辑器支持并不完整，比如并不支持TOC/TOCM

**Comment by scvoet** [comment]
> TOCM

TOC 并不是标准的 markdown 语法。

**Comment by cumtsd** [comment]
> > Markdown好用，问题是默认编辑器支持并不完整，比如并不支持TOC/TOCM
> 
> TOC 并不是标准的 markdown 语法。

反正默认编辑器支持的真的很少，我用的editorMD，也有些其他毛病，与我的代码高亮插件冲突，烦人
