### ISSUE TITLE
添加 markdown 回车换行语法

### ISSUE THREAD

**Issue by fenbox** [typecho/typecho#51]
[GitHub Flavored Markdown: Newlines](https://help.github.com/articles/github-flavored-markdown#newlines)

目前需要才结尾加两个空格后回车才能启用新行，两个空格在编辑器中根本是无法肉眼直接观察出来的，希望有回车符号后直接换行。
### 示例

The next paragraph contains two phrases separated by a single newline character:

```
Roses are red
Violets are blue
```

becomes

Roses are red
Violets are blue

**Comment by lanceleefeng** [comment]
连续两个回车换行很差劲，界面显示只有一个换行，但源码中就加上了两个空行。
换行又是最常用需求之一，熟悉之后也就无所谓了。
以前是不知道两个空格换行，知道之后需要换行会直接加上，影响不大。
<br />虽然也能换行，但跟两个回车一样，源码不好看了。

![image](https://cloud.githubusercontent.com/assets/26383223/24714280/9f185838-1a5a-11e7-9c7a-08879b6cac5c.png)

**Comment by guanjianqiang0408** [comment]
![image](https://user-images.githubusercontent.com/103730408/200452490-03ee9012-15a9-4c57-9ba2-9c3862b10399.png)
![image](https://user-images.githubusercontent.com/103730408/200452508-534f3057-6444-4e75-840c-d1710bc1a510.png)
这个问题是否能够解决？或者应该怎么处理接口中的markdown格式内容，才能支持将响应数据内容直接放md文档中，能够按照标签格式正常响应？
