### ISSUE TITLE
TYPECHO还在开发吗?求给个准确答复..

### ISSUE THREAD

**Issue by liqimore** [typecho/typecho#513]
论坛里管理员已经不见好久了..各大版主也是均2年左右不上线...不知道这个程序是不是还在开发,,还是就放了.. 毕竟用户也有不少呢? 求给个准确答复

**Comment by Vayn** [comment]
Typecho 已经很稳定了，估计各位开发者热情不高，建议修修补补的动作自己动手好了

**Comment by Linger2** [comment]
把1.1放出来把。

**Comment by neoFelhz** [comment]
@Vayn @Linger2 我就是直接用开发版的。
Typecho感觉很多都得自己修。。。

**Comment by Vayn** [comment]
嗯嗯，最近从 Hexo 迁过来深有同感。我一直用 MWeb 写好，再用 Metaweblog API 发布。升级到最新开发版就歇菜了……

周末花了2小时好好查了下，终于找到原因，迅速修好后 [blame 了一下……](https://github.com/typecho/typecho/commit/65637a33d18b6db9378d11a77145521aa9e3a1fe#comments)

**Comment by chriiess** [comment]
版本 1.0 (14.10.10)设置文章分类为什么总是变成默认的分类？

**Comment by liqimore** [comment]
@chriiess 没看懂你说的是什么意思?

**Comment by mildnes** [comment]
@Vayn 请教一下，MWeb如何对接到typecho呢。。我每次都是在MWeb写完了然后复制进去的。。但是发现有些标签还是不支持！

**Comment by joyqi** [comment]
当然在开发

**Comment by liqimore** [comment]
@joyqi 
感谢你的回复,真心的希望typecho能越来越棒!

**Comment by Vayn** [comment]
@mildnes 直接用 MetaWeblog API，也就是 xmlrpc.php

**Comment by dpy06** [comment]
希望这个播放器可以集成到官方版本中.
