### ISSUE TITLE
Github 最新的源码，typecho无法评论

### ISSUE THREAD

**Issue by aimuz** [typecho/typecho#515]
如题，把文件换成稳定版的就正常了

**Comment by brentybh** [comment]
但是稳定版也有各种bug真是难受

**Comment by joyqi** [comment]
我可以评论啊，有报错么，还是进垃圾箱了

**Comment by aimuz** [comment]
没有报错，提交评论后，就刷新那个被评论页面，一开始还以为主题问题，然后重装之后复现。弄得我现在都使用 Disqus
