### ISSUE TITLE
在php7.1下install.php进行第二步"初始化配置"空白

### ISSUE THREAD

**Issue by ClayMoreBoy** [typecho/typecho#518]
在php7.1下install.php进行第二步"初始化配置"空白

**Comment by ykla** [comment]
我也是

**Comment by a1010841065** [comment]
最新代码在Debian8下php5也有同样问题，所有文件权限设置777依旧空白，下载之前1.1稳定版就能正常安装，请作者及时修复。

**Comment by joyqi** [comment]
已经修复

**Comment by neighbads** [comment]
@joyqi 现在还是有这个问题。第二步 还是空白的 

PHP 5.4.16

**Comment by cj1324** [comment]
遇到相同的问题， 测试了 最新 master 分支仍然有问题。
