### ISSUE TITLE
最新版代码无法上传文件

### ISSUE THREAD

**Issue by a1010841065** [typecho/typecho#522]
最新版代码无法上传文件，简单测试之后可能是因为没有写文件的权限，可服务器中我已经将整个站点的权限设为777，用户名和用户组都改过了，依然没权限。测试稳定版代码没有此问题，请及时修复。

**Comment by lengxx** [comment]
同遇到，手动创建config.inc.php后到后台以表文章时附件上传不了，主题文件无法修改

> 安装程序无法自动创建 config.inc.php 文件
> 您可以在网站根目录下手动创建 config.inc.php 文件, 并复制如下代码至其中

**Comment by ZHWXME** [comment]
官网上有附件上传不了的解决办法

发自我的 iPhone

在 2017年1月3日，10:48，lengxx <notifications@github.com<mailto:notifications@github.com>> 写道：


同遇到，手动创建config.inc.php后到后台以表文章时附件上传不了，主题文件无法修改

安装程序无法自动创建 config.inc.php 文件
您可以在网站根目录下手动创建 config.inc.php 文件, 并复制如下代码至其中

**Comment by huming2207** [comment]
已有人发文，亲测有效：https://www.lvtao.net/dev/github-new-typecho-upload-error.html
原文博主说是因为这个isAppEngine()函数有问题，我不会PHP不太懂这个。

anyway，需要屏蔽这两行：
170~172:
```
//if ($content['attachment']->type != $ext || Typecho_Common::isAppEngine()) {
//  return false;
//}
```

97~99:
```
//if (!self::checkFileType($ext) || Typecho_Common::isAppEngine()) {
//   return false;
//}
```

**Comment by huming2207** [comment]
typecho作者们请注意一下，这个问题还是蛮严重的，不是仅仅config.inc.php上传不了，而是所有文件都上传不了！现在屏蔽了那两段代码，就能用了，但有没有引发别的问题，我不知道。

**Comment by a1010841065** [comment]
以下内容转自http://www.muun.cn/code/start.html

心血来潮想写博客，一直都很喜欢轻量简洁，无疑Typecho是一个非常不错的选择，服务器和域名准备多年终于可以派上用场了，安装的过程还算顺利，没啥难度，在写下第一篇文章的时候却发现文件死活无法上传显示上传失败，愁死宝宝了...

一开始还以为是目录权限的问题，给uploads 777的权限，但是发现问题依旧，开始怀疑不是权限的问题而是代码的问题，因为是开发版的原因，有点BUG在所难免，开始跟踪上传的的过程。

按设计上传成功后应该返回附件信息的数组，但实际是返回了False，经过跟踪发现在

/var/Widget/Upload.php 97行左右

if (!self::checkFileType($ext) || Typecho_Common::isAppEngine()) {
    return false;
}
运行到这里返回了False，checkFileType返回的是文件的类型（后缀），这里是没有问题的，基本可以定位到问题是出现在Typecho_Common::isAppEngine()上面了，继续跟踪代码

/var/Typecho/Common.php 824行左右

public static function isAppEngine()
{
    return !empty($_SERVER['HTTP_APPNAME'])                     // SAE
        || !!getenv('HTTP_BAE_ENV_APPID')                       // BAE
        || !!getenv('SERVER_SOFTWARE')                          // BAE 3.0
        || (ini_get('acl.app_id') && class_exists('Alibaba'))   // ACE
        || (isset($_SERVER['SERVER_SOFTWARE']) && strpos($_SERVER['SERVER_SOFTWARE'],'Google App Engine') !== false) // GAE;
}
这个函数的作用是检测是否在app engine上运行，屏蔽某些功能，问题就是出现在这个函数里了，BAE3.0的判断代码

!!getenv('SERVER_SOFTWARE') 
获取的并不是BAE3.0独有的环境变量，而是获取了服务器的通用标识，在任何服务器上运行基本都会返回True，经过二次取返后返回True，于是乎程序就认为是运行在BAE 3.0的环境而屏蔽了上传功能，最终导致了上传失败，既然知道问题所在，那么修复起来就很简单了，只需要将

 !!getenv('SERVER_SOFTWARE')  替换为  !!getenv('HTTP_BAE_LOGID') 
问题即可迎刃而解！

**Comment by flyisnow** [comment]
我是2020年下载的代码，这个问题还是没有解决，我修改了/var/Typecho/Common.php里面的isAppEngine(),让其直接`return false;`，重新加载页面也解决了
