### ISSUE TITLE
作者为什么从2014年就停滞开发了？

### ISSUE THREAD

**Issue by wenqibo** [typecho/typecho#528]
另外，用手机方法界面不是很友好，请问有开发计划吗？

**Comment by wenqibo** [comment]
补充一下，应该是2014年以后就看不到作者的博客更新了

**Comment by jzwalk** [comment]
几名开发者都有繁重的正式工作，typecho完全是业余时间的兴趣产物，没有计划性的资金和人力投入当然也只能走走停停，显然这两年70成家后精力很难集中到这里了;) 好在1.0是个比较完备的版本，普通用户要求太多显然不现实，只能期待有更多高手贡献代码，甚至能接手主要的开发工作吧~

**Comment by virusdefender** [comment]
感觉typecho功能上够用了，毕竟定位就是精简的blog系统，而不像是WordPress一样的cms系统。

**Comment by xiaofami** [comment]
typecho最初的目标已经基本实现了，简洁而强大。廉价VPS拿来搭梯子之余还能装个博客乐呵一下，资源开销非常之小，wordpress就只能呵呵了。

**Comment by smartpippin** [comment]
我也有同感，typecho作为个人博客平台，真的很不错。已经很完善了

2017-03-10 13:55 GMT+08:00 xiaofami <notifications@github.com>:

**Comment by tanhaipeng** [comment]
对个人来说完全够用了

**Comment by syrte** [comment]
要集成插件商店就完美了。

**Comment by fanghongxing** [comment]
主要是后台不适合手机写博客~要这个能改一下，那就很不错了！

**Comment by jayan2358** [comment]
个人认为插件商店，还是免了吧。**勿忘初心**
