### ISSUE TITLE
如果文章的发布时间为零点00:00，访问文章的时候会产生404错误

### ISSUE THREAD

**Issue by snailium** [typecho/typecho#532]
1.0 (14.10.10) 稳定版
时区为-5区
rewrite打开，链接样式设为/{year}/{month}/{day}/{slug}

如果将文章的发布时间设为正正好好午夜零点，访问的时候就会出现404错误

**Comment by zivlamp** [comment]
我试了一下，真是这样。这都能发现……猜测问题出在{day}

**Comment by ihewro** [comment]
这个错误听起来蛮恐怖的😱
