### ISSUE TITLE
Writing post does not work properly in international time zone

### ISSUE THREAD

**Issue by lkxlaz** [typecho/typecho#533]
Time zone selected via Typecho admin console is Beijing.
Time zone I am currently in is Sydney (Beijing Time + 3h).

what happened is that the post was delayed for an hour to be seen on home page after I published it with setting publish time. While what makes it even more strange is that the posting article works fine (can be seen on the home page right after I published it) without I set the publish time for it. 

The reason why is that the publish time is generated by a JS script called timepicker.js (which can be found in admin/js/ directory). This script probably just picks the current time as the publish time from the OS of my PC which is using Sydney time, and that publish time would be sent to the remote server (Tencent cloud VPS) to be processed by php program. The php program picks the Sydney time and process it in a wrong way, which caused the article cannot be posted on the right time.

**Comment by joyqi** [comment]
fixed at 3b9ae9c4988a222757d9a92aac708c4e628b1199

**Comment by lkxlaz** [comment]
@joyqi 非常感谢你的回复。通过你给你提示，现在问题已经解决了。开源程序维护者真的不容易，给你点赞！
