### ISSUE TITLE
服务器时区未考虑夏时制

### ISSUE THREAD

**Issue by lkxlaz** [typecho/typecho#534]
[夏时制，又称夏至时间。全世界有多个国家采纳，美国，澳大利亚，新西兰，等。WIKI的定义，](https://zh.wikipedia.org/wiki/%E5%A4%8F%E6%97%B6%E5%88%B6)

> 一般在天亮较早的夏季人为将时间调快一小时
以我所在的城市悉尼为例，悉尼的_标准时区_为GMT +10，相比北京时间（GMT +8）快两个小时。但，考虑到现在是夏时制，我的实际时间要比北京快3个小时。由于服务器时区并没有考虑到夏时制的存在，就导致了我现在发的一篇博文，要在一个小时之后才能显示在主页上。为了能在让刚刚发布的博文立刻显示，我人为的把时区向后调整（设置里）一位，也就是GMT +11 （可能是太平洋某岛国了，囧）。

为什么会出现这样的问题呢？原因出在发博文时发布时间的指定上，当我们选择以当前的时间发布，这个时候发生了什么？有一个js脚本叫timepicker （admin/js/timepicker.js)会生成一个当前浏览器的默认时间来当作当前时间，这里我测试了一下，google chrome是可以检测到夏令时的，也就是说，浏览器给我生成了基于夏时制的时间（相当于GMT +11标准时间），并把这个时间post到服务器作为这篇博文的发布时间，服务器端拿到这个时间后，却由于考虑不到夏时制的一小时时差，按照标准时间（非夏时，GTM +10）发布。换句简单的话说，我相当于把博文设置到未来一小时后发布了，囧。

我估计这个问题但凡是在海外夏时制国家的人都会遇到。希望是在不远的将来，typecho的开发者大大们打算把国际化做好，并把这个问题解决（我自己尝试过解决，但是我的知识和能力有限，还没有通读typecho代码并修改的能力）。谢谢！

**Comment by solarhell** [comment]
i18n其实是一个约定的问题，2种解决办法：
1: 数据库、php都使用同一时区（一般为UTC或UTC+8）,前端展示为用户选择的时区。
2:数据库、php、前端全部为同一时区。
