### ISSUE TITLE
nginx 1.10.2 &mysql 5.1.73 &PHP 5.6.29 登录后台出现404错误

### ISSUE THREAD

**Issue by tsingui** [typecho/typecho#543]
### 1. 该问题的重现步骤是什么？
登录后台管理出现404错误，怎么登录进步了，前台首页正常显示，但关于页面也是找到404错误。
### 2. 你期待的结果是什么？实际看到的又是什么？
期待正常使用。
### 3. 问题出现的环境

- 操作系统版本：Linux（嵌入式设备，路由tomato ARM，内核2.6.34）
- Apache/NGINX 版本：nginx 1.10.2
- 数据库版本：mysql 5.1.73
- PHP 版本：5.6.29
- Typecho 版本：github 上最新版，老版本也是一样。
- 浏览器版本：Firefox 51.0.1最新版本

[//]: # (如有图片请附上截图)
页面空白，404错误，产生连接地址MD5值

**Comment by FaithPatrick** [comment]
Nginx的伪静态规则没有配置好，参考官方的nginx配置信息。

**Comment by fenbox** [comment]
http://docs.typecho.org/faq#nginx服务器无法登录后台_点击前台链接或者后台登录时出现_404_not_found

**Comment by buggithubs** [comment]
如果是lnmp-1.3 一键包，使用以下步骤
打开这个文件：`/usr/local/nginx/conf/vhost/**yousite**.conf `
将`include enable-php.conf;` 修改为` include enable-php-pathinfo.conf;`
注意：检查此文件是否有`include typecho.conf;` 参数，如果没有需要添加。
然后重启nginx：`lnmp nginx restart`

**Comment by jeklau** [comment]
如果你用的是lnmp.org的一键包，将 include enable-php.conf;  替换为 include enable-php-pathinfo.conf;

**Comment by tsingui** [comment]
多谢各位指导，已解决，确实是伪静态出问题！

**Comment by hxdyj** [comment]
@jeklau 请问我配置伪静态无效是为什么啊，可以帮我看一下吗？
`server
    {
        listen 80;
        #listen [::]:80;
        server_name www.wingblog.top;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/typecho;
        include typecho.conf;
        include enable-php-pathinfo.conf;
        include typecho2.conf;
`
