### ISSUE TITLE
注册任意用户名的问题

### ISSUE THREAD

**Issue by guoshaoxia** [typecho/typecho#546]
在Register.php文件中，截获验证异常时使用了$this->response->goBack()来跳出注册流程，但是goBack()方法中没有处理$referer不存在的情况，导致了注册流程中的验证失效，从而注册任意用户名（包括空用户名）

解决方法也简单
在Register.php文件中，将$this->response->goBack()改为
`$this->response->goBack('register',$this->security->getAdminUrl('register.php'));`

**Comment by joyqi** [comment]
在开发版中的goBack方法已经修复了此功能，不管有没有referer，都会强行中断后续的操作
