### ISSUE TITLE
打开`使用 Markdown 语法编辑和解析内容`功能后，文章不解析html标签

### ISSUE THREAD

**Issue by buggithubs** [typecho/typecho#547]
php 7版本，typecho 最新开发版。

----

后台打开`使用 Markdown 语法编辑和解析内容`功能后，文章内无法解析html标签，如`audio`、`video`等
后台关闭`使用 Markdown 语法编辑和解析内容`功能后，文章内可正常解析html标签。

后台关闭`使用 Markdown 语法编辑和解析内容`功能后，文章内写入的markdown语法无法解析，保留内容，再次打开`使用 Markdown 语法编辑和解析内容`功能后，文章内markdown语法仍旧不解析。需要在打开功能的情况下，重新输入内容。

打开功能的情况下，在编辑器仅支持部分标签解析，如`div`、`ul`、`li`、`a`等此类标签。

在markdown内写入`<html></html>`标签，标签内的内容不解析，标签本身也被识别为文本。

在标签前部加入转移符，如`\<html\>\<\/html\>`后，转移符被解析，标签依旧为文本类。

---- 

F12后，发现在打开`使用 Markdown 语法编辑和解析内容`功能期间，发布的html 标签，均被`p`标签包围，使其变成了文本内容。

----

请问这个如何做互相嵌套，如 在打开功能后，依旧可以解析`<html></html>`标签，或者在关闭功能后，可以解析markdown内容。

**Comment by joyqi** [comment]
hi，新的markdown编辑器禁用了很多html标签的自动解析，如果你想强制使用html标签

请用三个感叹号包裹内容

```
!!!
<video ...>
!!!
```

请更新到最新版

**Comment by ajfg93** [comment]
> hi，新的markdown编辑器禁用了很多html标签的自动解析，如果你想强制使用html标签
> 
> 请用三个感叹号包裹内容
> 
> ```
> !!!
> <video ...>
> !!!
> ```
> 
> 请更新到最新版

这个强制使用html的功能应该写在文档里面。。我没找到这个功能然后自己写了一个脚本。你这个方便多了
