### ISSUE TITLE
使用离线编辑工具发布文章时不会默认编译Markdown语法.

### ISSUE THREAD

**Issue by ideacco** [typecho/typecho#549]
版本:1.0正式版

## 问题1:
如使用Mweb等离线编辑器,通过Metaweblog API 发布博客,
发布后正文显示的文章没有被自动转译成 md格式的.这时如通过后台进入文章会提示:本文不是MD格式文章,是否需要激继续,这时点击确定再保存后,文章才会被转义.

是否可以默认识别并转译成MD版本的?

## 问题2:
通过Metaweblog API 发布博客时,图片内容不会被上传到服务器.

**Comment by joyqi** [comment]
更新到最新的开发版，在个人profile页有个设置 XMLRPC接口使用Markdown ，然后在用离线编辑器发布的时候，选择发布为Markdown即可
