### ISSUE TITLE
下一个正式版什么时候放？

### ISSUE THREAD

**Issue by zhyt0520** [typecho/typecho#550]
请问下一个正式版的 release 有计划吗，大概什么时候会再放新的正式版？

**Comment by tanhaipeng** [comment]
现在Typecho进入维护期了吧

**Comment by zhyt0520** [comment]
维护期怎么理解，不放新版了？直接用GitHub上最新的代码么

**Comment by ldsink** [comment]
这么多的维护，改了很多东西的。建议 Release 一个正式版本。
