### ISSUE TITLE
无法上传附件与图片

### ISSUE THREAD

**Issue by ihewro** [typecho/typecho#553]
### 1. 该问题的重现步骤是什么？

上传图片的时候，按F12，控制台报错信息见图片：

![qq 20170331210532](https://cloud.githubusercontent.com/assets/20165605/24551737/36ff261c-1656-11e7-9ea5-a41293e9ea60.jpg)

```
moxie.js?v=14.10.10:1 POST http://****.com/index.php/action/upload?_=6373e1d3544eaf891a767f2001ba098f 500 (Internal Server Error)
```

### 2. 问题出现的环境

- 服务器：Windows Server 2008 R2 Enterprise SP1 x64  IIS7
- PHP 版本：5.6
- Typecho 版本：1.0 /1.1 都用了，都出现错误
- 浏览器版本：都是这样的

**Comment by ihewro** [comment]
看错误信息是index.php/action/upload?_=6373e1d3544eaf891a767f2001ba098f 这个脚本无法打开，500错误，不知道是什么原因导致的，求解

**Comment by joyqi** [comment]
这个看起来是iis的配置问题，你的500报错页面有输出吗，或者任何的错误日志也可以。要不然完全看不出来啊

**Comment by ihewro** [comment]
打开500页面，返回403，显示的是没有权限查看该页面

**Comment by joyqi** [comment]
你可以把php的错误日志打开，看看有没有内容

**Comment by ihewro** [comment]
开发环境重建了，现在没办法重现了，暂时关闭此issue
