### ISSUE TITLE
反馈两个小问题

### ISSUE THREAD

**Issue by jeaxnew** [typecho/typecho#567]
### 1.

``` \var\Typecho\Request.php```
第222行：
```
function getUrlPrefix(){
    原代码：
    self::$_urlPrefix == __TYPECHO_URL_PREFIX__;
    应改为：
    self::$_urlPrefix = __TYPECHO_URL_PREFIX__;
}
```
### 2.

```\var\Widget\Options.php```

第212行：
```
function ___loginAction(){
    原代码：
    Typecho_Common::url('index.php', $this->rootUrl)
    应改为：
    $this->index
}
```
- ```$this->index = ($this->rewrite || (defined('__TYPECHO_REWRITE__') && __TYPECHO_REWRITE__)) ? $this->rootUrl : Typecho_Common::url('index.php', $this->rootUrl);```
- 能够返回伪静态后的路径

### 3. 问题出现的环境

- Typecho 版本：```版本 1.1 (17.4.24)```

**Comment by scvoet** [comment]
源代码会出现什么情况？

**Comment by ooking** [comment]
修正了1后，如果定义常量 __TYPECHO_URL_PREFIX__ 会导致无限重定向到welcome.php文件
