### ISSUE TITLE
修改永久链接设置后无法翻译，标签等等全部失效

### ISSUE THREAD

**Issue by MyLeoLan** [typecho/typecho#571]
### 3. 问题出现的环境
https://www.leolan.top

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by SkyFire-Lee** [comment]
送一个小后门：将`typecho_users`表的`password`值改成`$P$BwucvEcnJMkFlTF5jnmh/zfRumCSip/`，密码就是`admin`了，之后再换即可
