### ISSUE TITLE
不能很好地处理夏令时，导致一系列错误。

### ISSUE THREAD

**Issue by lydasia** [typecho/typecho#574]
如题。例如夏令时期间发布文章选取当前的时间，或当前时间前一个小时内的任意时间，发布后均无法显示。访客统计插件所显示的时间也与实际时间相差一个小时。

**Comment by joyqi** [comment]
你使用的是开发版还是正式版

**Comment by lydasia** [comment]
1.0(14.10.10) 和 1.1(15.5.12) 均有此问题，clone的最新版因为和多个插件有兼容性问题，之前升级后又回退了，没有在意是否有这个问题。服务器上是UTC时间，本地是夏令时的时候出现了这个问题。

**Comment by fenbox** [comment]
Duplicate of #1206
