### ISSUE TITLE
初始化安装报错

### ISSUE THREAD

**Issue by vanishedtear** [typecho/typecho#575]
### 1. 该问题的重现步骤是什么？

采用的是mariadb数据库，正常初始化安装，选择pdo_mysql 报错为请正确配置数据库信息，所以看了下发现支持Mysqli，可是在数据库适配器中却又没有选项，查看了install.php发现在下拉框中没有该选项。所以我就抄了Mysql的选项代码，把Mysql改为Mysqli 然后输入有关的数据库信息 ，报错了 

报错信息如下

Warning: mysqli::query(): Couldn't fetch mysqli in /home/vanishedtear/www-blog/var/Typecho/Db/Adapter/Mysqli.php on line 49

Warning: Typecho_Db_Adapter_Mysqli::query(): Couldn't fetch mysqli in /home/vanishedtear/www-blog/var/Typecho/Db/Adapter/Mysqli.php on line 86

Warning: Typecho_Db_Adapter_Mysqli::query(): Couldn't fetch mysqli in /home/vanishedtear/www-blog/var/Typecho/Db/Adapter/Mysqli.php on line 86

### 2. 你期待的结果是什么？实际看到的又是什么？

Typecho是否支持mairadb，之前我只看到是支持php7的

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.12.0
- 数据库版本：mariadb 10.2.6
- PHP 版本：7.1.5
- Typecho 版本：当前github上面的master
- 浏览器版本：chorme 最新

[//]: # (如有图片请附上截图)

**Comment by tanmx** [comment]
mariadb 10.2.6  + php 7.1.5 测试正常

**Comment by vanishedtear** [comment]
好玩的是 我不连接mariadb数据，我选择用pdo-mysql连接其它服务器上的Mysql5.5数据库 我就可以正常连接上了 也就是说
1、mysqli连接方式还不能用
2、不支持mariadb数据 
是么？

**Comment by vanishedtear** [comment]
用那种数据库连接适配器？

**Comment by tanmx** [comment]
Pdo_Mysql

**Comment by vanishedtear** [comment]
HeidiSql可以连接数据库 pdo_mysql无法连接 是需要mariadb额外开启对pdo的支持么？

**Comment by vanishedtear** [comment]
刚调试通了 可以确认是 php环境没有配置好导致的~应该是php的pdo-mysql哪里没有设置好导致的~因为php采用的是官网的编译安装的方式 看来有很有变量没有设置好

**Comment by vanishedtear** [comment]
问题解决了，来这里特地总结下解决方案，给以后有相同问题的朋友一个例子
问题所在：
pdo_mysql.default_socket的路径错了，默认的是/tmp/mysql.sock，修改为当前系统实际的地址就好了，采用 find / -name mysql.sock就可以找到具体路径了
背景原因：
1、pdo需要用到mysql.sock
2、原有采用的是lnmp一键安装 彼此间的参数变量一键调好 现在都是手工安装
