### ISSUE TITLE
关于开发版的MarkDown是不是对html原生标签不支持了

### ISSUE THREAD

**Issue by Moidea** [typecho/typecho#580]
有些时候文章想直接编写html代码，比如
某篇文章将一张图片居中
```
<p style="text-align:center;">
<img src="******">
</p>
```
最后解析出来的时候P标签代码会显示出来，正式版是没有问题的

有些人可能会觉得，为什么要用硬代码直接布局呢，为什么不用CSS？
可是有些时候有些需求就是这么奇葩[/摊手]

为什么不换Ueditor编辑器呢？
太庞大不喜欢[/摊手]

非常对不起，又给大家添蘑菇了

**Comment by bsed** [comment]
``` 这种特权模式你可以试一下

**Comment by Moidea** [comment]
谢谢，我回头自己试试，昨天又改成正式版了

**Comment by bsed** [comment]
客气啦， ^.^

**Comment by jcorg** [comment]
怎么加 超级html模式？才能3感叹包着正常解析html

**Comment by bsed** [comment]
@jcorg 
![qq 20171103162309](https://user-images.githubusercontent.com/10845087/32364966-c5569be6-c0b2-11e7-8b73-a302055ab8f7.png)
![qq 20171103162219](https://user-images.githubusercontent.com/10845087/32364973-ca728036-c0b2-11e7-995a-502d3dbe0e09.png)

**Comment by Moidea** [comment]
然而一个比较糟糕的事，过去的文章中的好多div标签和img还有一些内联CSS样式表都失效了，在新版typecho版本上不被支持，如果统一改成那个！！！包裹也是一个不小的工程

**Comment by joyqi** [comment]
试试最新的开发版

**Comment by jcorg** [comment]
@bsed  可以了，我原来是!!!<p class="">文字</p>!!! 这样包的，我说咋一直不行呢

**Comment by jcorg** [comment]
这个用!!!包起来，链接不起作用了
`
!!!
<p class="duan">参考自 [让Nginx支持CGI执行Bash,Python等脚本][1] 文章，详细的原理和内容请看此篇文章。</p>
!!!
`

**Comment by Moidea** [comment]
还是有些混乱，比如过去的文章中的这样的写法： 
`<span style="text-align:center;">---------------网站历史---------------</span>`
还有另类的内联css：
```
<style>.friend{padding: 5px 20px;
    border-radius: 34px;
    background: #f3f3f3;
    line-height: 26px;
    display: inline-block;
    margin-bottom: 10px;
    font-size: 14px;
    border: 1px solid #f3f3f3;}</style>
<a class="friend" href="http://blog.kilvn.com/" target="_blank" alt="">東子部落格</a>
```
还有奇葩的表格标签：
```
<tr>
  <th>主题</th>
  <th>又名</th>
  <th>版本</th>
  <th>作者</th>
  <th>联系</th>
  <th>QQ 群</th>
  <th>演示</th>
</tr>
```

这些种写法在过去的版本上中是被MD支持的

**Comment by Moidea** [comment]
@上面列出的是最新的开发版本仍有的问题，我查看了我过去的typecho版本中的var文件 @joyqi 也许会有比较完美的解决办法，来解决这个编辑器对过去的MD文章兼容的问题，同时未来我也将更加规范化的使用MD

![qq 20171103180008](https://user-images.githubusercontent.com/2386071/32368655-7017aa30-c0c1-11e7-932a-98cc72071280.png)

**Comment by LinuxEA-Mark** [comment]
有些文章已经不兼容了，出现乱码之类的
