### ISSUE TITLE
开发版的编辑器li标签有问题

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#581]
用编辑器器写出这个格式
```
 - 你好世界
```
输出的的结果为
```
<ul><li><p>你好世界</p></li></ul>
```
里面多了个p标签，开1.0版本里没有的，只有现在的开发版有，感觉是bug

**Comment by kokororin** [comment]
HyperDown就是这么设计的，换个解析器就好了

**Comment by jrotty** [comment]
@kokororin 我就是感觉这个很不合理，其实我自己用正则给换掉了，哈哈

**Comment by bsed** [comment]
@joyqi 他换md解析器，有些问题解决了，但是又出现很多bug [#578](https://github.com/typecho/typecho/issues/578)
