### ISSUE TITLE
查看文档时，500错误

### ISSUE THREAD

**Issue by Akityo** [typecho/typecho#583]
### 1. 该问题的重现步骤是什么？
安装时，填写的域名是xn-***  中文域名
然后查看文章的时候，500错误
![image](https://user-images.githubusercontent.com/16974004/27857424-2d274e82-61a4-11e7-93e7-ceb68de8ad73.png)

目测就是因为这个问题

### 2. 你期待的结果是什么？实际看到的又是什么？

500。。。
### 3. 问题出现的环境

- 操作系统版本：Debian 8
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：最新版（正式）
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by SkyFire-Lee** [comment]
500错误在服务器上会有错误日志输出，最好把错误日志贴出来，说不定不是中文域名的问题

**Comment by Akityo** [comment]
@SkyFire-Lee 我发现了，好像不是中文域名的问题，好像是php的问题 debian 7 默认装的php7.0
那我还能正常用吗

**Comment by SkyFire-Lee** [comment]
@Akityo 我也是linux的深度系统，用的是php7.1.2，并没遇到问题，这应该和php版本没关系吧，最好还是把服务器的日志贴出来才能帮你查看问题

**Comment by Akityo** [comment]
@SkyFire-Lee 我安装了php-curl 然后也enable了，不知道为什么。。

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_curl.dll' - /usr/lib/php/20151012/php_curl.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Wed Jul 05 13:10:54.460147 2017] [mpm_prefork:notice] [pid 6513] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Jul 05 13:10:54.460284 2017] [core:notice] [pid 6513] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 05 13:11:02.904192 2017] [:error] [pid 6517] [client :13399] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Typecho_Common::exceptionHandle() must be an instance of Exception, instance of Error given in /var/www/html/var/Typecho/Common.php:235\nStack trace:\n#0 [internal function]: Typecho_Common::exceptionHandle(Object(Error))\n#1 {main}\n  thrown in /var/www/html/var/Typecho/Common.php on line 235`

**Comment by SkyFire-Lee** [comment]
CRUL扩展看看是不是打开错了？按道理Linux下面应该so文件，而不是dll文件

**Comment by joyqi** [comment]
@Akityo 用开发版试一下
