### ISSUE TITLE
安装到第三步时白屏

### ISSUE THREAD

**Issue by boxsnake** [typecho/typecho#587]
安装到第三步时候白屏，是因为触发了这个部分，但是此时数据库还没创建，可能是因为第二歩时候SESSION没设置成功导致第三步一开始`$_SESSION['typecho']`为空，希望给出比较好的修改方案
```php
if (!isset($_GET['finish']) && file_exists(__TYPECHO_ROOT_DIR__ . '/config.inc.php') && empty($_SESSION['typecho'])) {
    exit;
}
```

**Comment by neighbads** [comment]
我第二步就白了。。。数据库也没创建  官网release 和 这里的 release 都不行

**Comment by neighbads** [comment]
install.php?start

**Comment by joyqi** [comment]
最新的开发版已经不再依赖session判断
