### ISSUE TITLE
对于带有端口号的地址，URL处理不一致

### ISSUE THREAD

**Issue by boxsnake** [typecho/typecho#588]
* 本地安装，地址带端口号
* 安装过程中填写的地址为`http://172.16.0.10:3002/`
* 安装完之后所有的链接如下（多了一个`:3002`），但是所有的资源（CSS/JS）路径正常
![image](https://user-images.githubusercontent.com/3257783/28656557-2daddffa-72d5-11e7-959f-bf4e145f8b0e.png)
![image](https://user-images.githubusercontent.com/3257783/28656606-7c4e36f0-72d5-11e7-96d1-93a2b8f59d97.png)
* 如果去掉配置中的`:3002`，那么所有的资源路径错误，链接路径正常

**Comment by Linger2** [comment]
你用网址访问默认是80端口，没有端口怎么可能找到资源。

**Comment by majialin** [comment]
- 出现同样的问题，虚拟机中安装，带端口号
- 安装过程中填写http://192.168.191.134:81 或是 http://192.168.191.134 均会出现问题
- 完成后的链接如http://192.168.191.134:81:81/admin/login.php，导致无法点击链接。

**Comment by joyqi** [comment]
@boxsnake @majialin 你们用的是哪个版本

**Comment by majialin** [comment]
@joyqi  使用的是1.0 (14.10.10)版本 typecho.org 。
抱歉，发现在最新开发版已无此问题。

**Comment by joyqi** [comment]
对，我们已经修复了
