### ISSUE TITLE
文章内容过大保存或者发布的时候出现Database Query Error

### ISSUE THREAD

**Issue by yancheng199287** [typecho/typecho#593]
### 1. 该问题的重现步骤是什么？
发布文章的时候，内容过大，导致错误，Database Query Error
### 2. 你期待的结果是什么？实际看到的又是什么？
我期待顺利保存成功，实际看到的是 页面报错 Database Query Error
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：apache2
- 数据库版本：
- PHP 版本：php5
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
请在config.inc.php里加上一行

```
define('__TYPECHO_DEBUG__', true);
```

获取了详细的错误信息后贴上来

**Comment by yancheng199287** [comment]
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'text' at row 1

exception 'Typecho_Db_Query_Exception' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'text' at row 1' in /var/www/html/typecho/var/Typecho/Db/Adapter/Pdo.php:93
Stack trace:
#0 /var/www/html/typecho/var/Typecho/Db.php(319): Typecho_Db_Adapter_Pdo->query(Object(Typecho_Db_Query), Object(PDO), 2, 'INSERT')
#1 /var/www/html/typecho/var/Widget/Abstract/Contents.php(296): Typecho_Db->query(Object(Typecho_Db_Query))
#2 /var/www/html/typecho/var/Widget/Contents/Post/Edit.php(264): Widget_Abstract_Contents->insert(Array)
#3 /var/www/html/typecho/var/Widget/Contents/Post/Edit.php(733): Widget_Contents_Post_Edit->publish(Array)
#4 /var/www/html/typecho/var/Widget/Contents/Post/Edit.php(909): Widget_Contents_Post_Edit->writePost()
#5 /var/www/html/typecho/var/Widget/Do.php(81): Widget_Contents_Post_Edit->action()
#6 /var/www/html/typecho/var/Typecho/Widget.php(222): Widget_Do->execute()
#7 /var/www/html/typecho/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#8 /var/www/html/typecho/index.php(23): Typecho_Router::dispatch()
#9 {main}

**Comment by joyqi** [comment]
你的文章长度超过了text字段的最大限度，你可以尝试把contents表里的text字段类型由`TEXT`改为`LONGTEXT`

**Comment by tanmx** [comment]
```
mysql> desc typecho_contents;
+--------------+------------------+------+-----+---------+----------------+
| Field        | Type             | Null | Key | Default | Extra          |
+--------------+------------------+------+-----+---------+----------------+
| cid          | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| title        | varchar(200)     | YES  |     | NULL    |                |
| slug         | varchar(200)     | YES  | UNI | NULL    |                |
| created      | int(10) unsigned | YES  | MUL | 0       |                |
| modified     | int(10) unsigned | YES  |     | 0       |                |
| text         | mediumtext       | YES  |     | NULL    |                |
| order        | int(10) unsigned | YES  |     | 0       |                |
| authorId     | int(10) unsigned | YES  |     | 0       |                |
| template     | varchar(32)      | YES  |     | NULL    |                |
| type         | varchar(16)      | YES  |     | post    |                |
| status       | varchar(16)      | YES  |     | publish |                |
| password     | varchar(32)      | YES  |     | NULL    |                |
| commentsNum  | int(10) unsigned | YES  |     | 0       |                |
| allowComment | char(1)          | YES  |     | 0       |                |
| allowPing    | char(1)          | YES  |     | 0       |                |
| allowFeed    | char(1)          | YES  |     | 0       |                |
| parent       | int(10) unsigned | YES  |     | 0       |                |
+--------------+------------------+------+-----+---------+----------------+
```
修改 text 类型 为 longtext试试

**Comment by yancheng199287** [comment]
可以了，回复好及时啊，谢谢啊， 不过希望在后面版本中直接用这个类型吧，我看好多人报这个错

**Comment by joyqi** [comment]
已经修复

**Comment by 1MYAGE1** [comment]
能帮我看一下这是什么问题吗？ 谢谢
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1 no such table: typecho_options in /usr/local/apache/htdocs/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /usr/local/apache/htdocs/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('SELECT *  FROM ...', Object(PDO), 1, 'SELECT')
#1 /usr/local/apache/htdocs/var/Typecho/Db.php(384): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /usr/local/apache/htdocs/var/Widget/Options.php(358): Typecho_Db->fetchAll(Object(Typecho_Db_Query), Array)
#3 /usr/local/apache/htdocs/var/Typecho/Widget.php(221): Widget_Options->execute()
#4 /usr/local/apache/htdocs/var/Widget/Init.php(27): Typecho_Widget::widget('Widget_Options')
#5 /usr/local/apache/htdocs/var/Typecho/Widget.php(221): Widget_Init->execute()
#6 /usr/local/apache/htdocs/index.php(20): Typecho_Widget::widget('Widget_Init')
#7 {main}
