### ISSUE TITLE
更换域名后文章内的图片链接不变，请问开发版解决了吗？

### ISSUE THREAD

**Issue by jozhn** [typecho/typecho#594]
### 1. 该问题的重现步骤是什么？
更换域名后文章内的图片链接没有改变

### 2. 你期待的结果是什么？实际看到的又是什么？
希望文章内的图片链接也能自动改变，但实际没有，只有附件的改变了

### 3. 问题出现的环境
跟环境无关。。。
- 操作系统版本：
- Apache/NGINX 版本：Nginx1.12
- 数据库版本：Mysql5.5
- PHP 版本：5.4
- Typecho 版本：1.0
- 浏览器版本：Chrome60.0

[//]: # (如有图片请附上截图)

**Comment by Mushan3420** [comment]
本地图片最好用相对路径。绝对路径的图片可能不是本站域名下的，所以不会自动变更域名。

**Comment by JohnStinky** [comment]
@Mushan3420 但插入图片是生成的都是绝对路径啊。Typecho这样不方便CDN我感觉，当然可以通过修改数据库实现替换链接，但还是觉得麻烦了。

**Comment by Mushan3420** [comment]
是的，默认是绝对路径，所以每次插入本地图片，我都把它改成相对路径，以免以后麻烦。

**Comment by Mushan3420** [comment]
另外，WordPress默认也是绝对路径。如果你要把你的网站打包成小程序的话，只支持绝对路径和图片。

**Comment by Mushan3420** [comment]
CDN 怎么了？相对路径只是后端的一种表示方法。如果CDN是从外部访问，抓取图片的话，那么从前端访问到的图片地址会自动补全域名的。

**Comment by JohnStinky** [comment]
这么说很有道理。。。那么说问题应该是让插入图片时生成相对路径！

**Comment by Mushan3420** [comment]
但你要是调用程序本身的接口来读取图片，那读取到的就是原始代码，相对路径的地址是不会补全的。

**Comment by papiJohn** [comment]
@Mushan3420 我是希望比如博客用xx.com域名，而静态cdn使用cdn.xx.com域名，相对路径的话就始终使用xx.com了，目前typecho的cdn都是通过正则匹配archive->content中的链接实现的，对相对路径根本无效啊

**Comment by Mushan3420** [comment]
那就用绝对路径呗

**Comment by papiJohn** [comment]
所以希望typecho能根据域名改变而变换文章中的图片链接嘛~还是谢谢你了，我改成相对路径之后不想改回去了，cdn改成替换'/usr/uploads/'为'https://cdn.xx.com/usr/uploads/'了。这样也可以实现

**Comment by gouchaoer** [comment]
这个问题简单的说就是设置静态资源URL的问题，图片+附件全部默认用相对路径存储，如果静态资源URL没有设施就相对路径，如果设置了那么就用cdn.xxx.com/uploads/1.png这样来

**Comment by fenbox** [comment]
批量更新 URL
- https://soft.amai.cc/index.php/archives/81/
- https://www.321002.com/809.html
- https://9sb.net/archives/typecho-website-batch-modifies-article-images-and-file-link-addresses.html

![image](https://github.com/typecho/typecho/assets/360618/596aa4d7-2fd0-4f46-96a8-4796165e19b6)
