### ISSUE TITLE
分类父子级问题

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#597]
子分类里面的文章数量，默认不算在父分类上，除非发布文章时勾选同时勾选父分类，额，我说的可能比较模糊，举个例子

发布一篇文章，然后只勾选子分类，然后发布。

父分类输出分类的文章数量，并没有包含这个新发布的文章

同时该文章输出分类名字时，没办法输出父分类名字

**Comment by joyqi** [comment]
第一个问题暂时无法解决，第二个问题你可以输出`$this->directory`这个数组

**Comment by jrotty** [comment]
<a href="d">d</a>间隔<a href="�">�</a>

子分类的文章输出结果如上，父分类显示`<a href="d">d</a>`子分类显示`<a href="�">�</a>`，只有父分类的文章显示`<a href="d">d</a>`

我是采用删除admin，var，index.php然后重新上传新的这三个东西的方式升级的。演示地址http://beta.qqdie.com/index.php/archives/8/
