### ISSUE TITLE
拼写错误导致无法正确验证token

### ISSUE THREAD

**Issue by jiangmuzi** [typecho/typecho#599]
https://github.com/typecho/typecho/blob/0ba45f10063a89eeb43e7486a302a7a9e2c59d44/var/Widget/Security.php#L90

**Comment by joyqi** [comment]
这真是令人尴尬的BUG

**Comment by S8Cloud** [comment]
改正过后的版本会导致无法登陆后台，改回 `if ($this->enabled && $this->request->get('_') != $this->getToken($this->request->getReferer()))` 后成功登陆。

**Comment by joyqi** [comment]
我登录正常啊

**Comment by S8Cloud** [comment]
会跳转到 https://mydomain.com/index.php/action/login?_=<token> 页面，无法进入后台

**Comment by S8Cloud** [comment]
会跳转到 `https://mydomain.com/index.php/action/login?_=<token>` 页面，无法进入后台

**Comment by joyqi** [comment]
跳转到这个页面啥意思，停住了么？

**Comment by S8Cloud** [comment]
是的，页面为空白，不能进入后台

**Comment by joyqi** [comment]
@S8Cloud 能否看到错误日志，我怀疑是哪里出错了

**Comment by S8Cloud** [comment]
已经开启错误日志，但并未返回任何结果
