### ISSUE TITLE
父子分类模糊问题

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#603]
A是B和C的父级分类，且B分类文章为最新发布的文章

则在分类页面下（指的是A分类页面下），

输出`<?php $this->directory(' > ',true,''); ?>`则会显示A>B

输出`<?php echo $this->category; ?><?php $this->category(',', true, ''); ?>`则会显示B分类的缩略名和B分类的名字

说的比较乱，实际我就是想在父分类下，输出分类名字和缩略名，但是输出结果只会显示最新文章子分类的名字和缩略名

**Comment by joyqi** [comment]
能否截图加以说明

**Comment by jrotty** [comment]
父分类地址https://tool.qqdie.com/category/own/
子分类地址https://tool.qqdie.com/category/other/和https://tool.qqdie.com/category/word/

在父分类地址中`<?php $this->directory(' > ',true,''); ?>分类缩略名:<?php echo $this->category; ?>分类名字:<?php $this->category(',', true, ''); ?>`会输出子分类的名字和缩略名而不是自己的名字和缩略吗

**Comment by joyqi** [comment]
请使用
<?php echo $this->getArchiveTitle(); ?>
<?php echo $this->getArchiveSlug(); ?>
来获取
