### ISSUE TITLE
难道官方不打算维护下数据库组件吗？

### ISSUE THREAD

**Issue by turnmind** [typecho/typecho#612]
我一直在用typecho 的DB组件，真的很方便，支持各种适配器和数据库，语法简洁。
但是它扔停留在 mysql 的连接操作，新版已经开始采用 mysqli 了，希望更新下。。

**Comment by joyqi** [comment]
开发版早已经支持mysqli了

**Comment by leesandao** [comment]
请问支持Pdo方式了，我用1.0版“对不起，无法连接数据库”
环境是Ubuntu 16.04 Nginx 1.13.5  PHP7.0  PHP7.0-fpm Mysql 5.7.19

还不懂php，查到Pdo.php那边看不懂了。。
 ```
public function connect(Typecho_Config $config)
    {
        try {
            $this->_object = $this->init($config);
            $this->_object->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            return $this->_object;
        } catch (PDOException $e) {
            /** 数据库异常 */
            throw new Typecho_Db_Adapter_Exception($e->getMessage());
        }
    }

```

**Comment by turnmind** [comment]
@leesandao 可能是无法连接数据库吧，检查一下坏境是否符合Pdo连接。

**Comment by jrotty** [comment]
把 config.inc.php 文件中的

$db = new Typecho_Db('Mysql', 'typecho_');
改为

$db = new Typecho_Db('Pdo_Mysql', 'typecho_');

**Comment by leesandao** [comment]
多谢jrotty，我的config.inc.php是正确的。

还是需要先进入mysql,自己create databases typecho才可以进行下去，我也不明白为什么
