### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by Pengzf** [typecho/typecho#616]
Warning: file_exists(): open_basedir restriction in effect. File(/www/wwwroot/usr/themes/GreenGrapes-master.zip/index.php) is not within the allowed path(s): (/www/wwwroot/:/tmp/:/proc/) in /www/wwwroot/var/Widget/Themes/List.php on line 63

注意file “GreenGrapes-master.zip/index.php”
一个小bug.文件过滤一下就好！
文件解压后没删除就这样！

**Comment by Pengzf** [comment]
<img src="http://0d077ef9e74d8.cdn.sohucs.com/qyjo71N_png.png"/>
/var/Widget/Themes/List.php on line 63

**Comment by benzBrake** [comment]
这不是bug，这是防跨目录的锅，你用的lnmp一键包吧

**Comment by Pengzf** [comment]
@benzBrake 你去看看/var/Widget/Themes/List.php这个的源码吧！遍历目录文件后返回数组，包含文件和目录，然而他没有过滤文件。
防跨目录表示这个锅，我们不背！
