### ISSUE TITLE
1.1(17.10.24) beta版本中代码显示的错误

### ISSUE THREAD

**Issue by Wechatoff** [typecho/typecho#623]
### 1. 该问题的重现步骤是什么？
升级到1.1(17.10.24)beta后，出现了代码显示错误。当文章的代码中含有`<blockquote></blockquote>`，显示的却是引用，而不是代码。
### 2. 你期待的结果是什么？实际看到的又是什么？
在1.0版本中无这个错误。

原代码：
```
    <blockquote>
    本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/cn/" target=_blank>知识共享署名-非商业性使用-禁止演绎 3.0 中国大陆许可协议</a>进行许可。
    <br/>
    转载请注明：转自<a href="<?php $this->options->siteUrl(); ?>"><?php $this->options->title() ?></a><br/>
    原文链接：<a href="<?php $this->permalink() ?>"><?php $this->permalink() ?></a>
    </blockquote>
```
编辑器内编辑时的状态：

![screenshot](https://user-images.githubusercontent.com/32946306/32042465-37538ea6-ba6a-11e7-8bc7-0dbf08fd9cfb.png)

1.1 beta显示效果：

![screenshot2](https://user-images.githubusercontent.com/32946306/32042499-551c6642-ba6a-11e7-957e-31f2f07e4fa1.png)

请修复，谢谢！你们辛苦了！

截图原地址：https://linhai1990.com/archives/133/

**Comment by wechatoff** [comment]
我忘记标记了，是1.1(17.10.24）版本。打开XMLRPC也是无法修正这个错误的。

**Comment by wechatoff** [comment]
楼上的，我是使用的typecho编辑器里的“代码”。要不是你说，我都不知道有这个写法。
