### ISSUE TITLE
Database Query Error

### ISSUE THREAD

**Issue by jeanbi** [typecho/typecho#625]
### 1. 该问题的重现步骤是什么？
保存文章（不管是新增还是修改）都会出现
### 2. 你期待的结果是什么？实际看到的又是什么？
不报错
### 3. 问题出现的环境
- 操作系统版本：
- Apache/NGINX 版本：1.11
- 数据库版本：5.6
- PHP 版本：7.0
- Typecho 版本：17.10.24（该问题从14.10.10开始都存在）

**Comment by joyqi** [comment]
在config.inc.php里加入一行
```
define('__TYPECHO_DEBUG__', true);
```

然后把报错的具体信息贴上来

**Comment by jeanbi** [comment]
```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'u_com.m.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Typecho_Db_Query_Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'u_com.m.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/ucom/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /var/www/ucom/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('SELECT cid,name...', Object(PDO), 1, 'SELECT')
#1 /var/www/ucom/var/Typecho/Db.php(384): Typecho_Db->query('SELECT cid,name...', 1)
#2 /var/www/ucom/usr/plugins/BaiduSubmit/inc/sitemap.php(326): Typecho_Db->fetchAll('SELECT cid,name...')
#3 /var/www/ucom/usr/plugins/BaiduSubmit/inc/sitemap.php(190): BaidusubmitSitemap::get_category_by_cid('194')
#4 /var/www/ucom/usr/plugins/BaiduSubmit/inc/sitemap.php(76): BaidusubmitSitemap::get_post_info_by_cid('194')
#5 /var/www/ucom/usr/plugins/BaiduSubmit/Action.php(102): BaidusubmitSitemap::gen_elenment_by_cid('194')
#6 /var/www/ucom/var/Typecho/Plugin.php(489): BaiduSubmit_Action::send_add_xml(Array, Object(Widget_Contents_Post_Edit), NULL)
#7 /var/www/ucom/var/Widget/Contents/Post/Edit.php(737): Typecho_Plugin->__call('Widget_Contents...', Array)
#8 /var/www/ucom/var/Widget/Contents/Post/Edit.php(910): Widget_Contents_Post_Edit->writePost()
#9 /var/www/ucom/var/Widget/Do.php(82): Widget_Contents_Post_Edit->action()
#10 /var/www/ucom/var/Typecho/Widget.php(221): Widget_Do->execute()
#11 /var/www/ucom/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#12 /var/www/ucom/index.php(23): Typecho_Router::dispatch()
#13 {main}
```

**Comment by joyqi** [comment]
看起来是你的 sitemap 插件出了问题

**Comment by 5h4w** [comment]
Duplicate entry 'theme:typecho-theme-NexTPisces-m-0' for key 'PRIMARY'
exception 'Typecho_Db_Query_Exception' with message 'Duplicate entry 'theme:typecho-theme-NexTPisces-m-0' for key 'PRIMARY'' in /www/wwwroot/www.5haw.me/var/Typecho/Db/Adapter/Mysql.php:88
Stack trace:
#0 /www/wwwroot/www.5haw.me/var/Typecho/Db.php(354): Typecho_Db_Adapter_Mysql->query('INSERT INTO typ...', Resource id #29, 2, 'INSERT')
#1 /www/wwwroot/www.5haw.me/var/Widget/Abstract/Options.php(56): Typecho_Db->query(Object(Typecho_Db_Query))
#2 /www/wwwroot/www.5haw.me/var/Widget/Themes/Edit.php(130): Widget_Abstract_Options->insert(Array)
#3 /www/wwwroot/www.5haw.me/var/Widget/Themes/Edit.php(176): Widget_Themes_Edit->config('typecho-theme-N...')
#4 /www/wwwroot/www.5haw.me/var/Widget/Do.php(82): Widget_Themes_Edit->action()
#5 /www/wwwroot/www.5haw.me/var/Typecho/Widget.php(221): Widget_Do->execute()
#6 /www/wwwroot/www.5haw.me/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#7 /www/wwwroot/www.5haw.me/index.php(23): Typecho_Router::dispatch()
#8 {main}
