### ISSUE TITLE
Error 500 无法启用插件 APlayer

### ISSUE THREAD

**Issue by Mushan3420** [typecho/typecho#627]
### 1. 该问题的重现步骤是什么？
启用插件 APlayer ( https://github.com/MoePlayer/APlayer-Typecho )

### 2. 你期待的结果是什么？实际看到的又是什么？
预期：这个插件是25天之前更新的，以为不会出错。
结果：彻底不能启用，直接500了。（所以在插件和程序的git都提交了issue）
>无法启用插件
Typecho_Widget_Exception: 无法启用插件 in /var/Widget/Plugins/Edit.php:98
Stack trace:
#0 /var/Widget/Plugins/Edit.php(308): Widget_Plugins_Edit->activate('APlayer')
#1 /var/Widget/Do.php(82): Widget_Plugins_Edit->action()
#2 /var/Typecho/Widget.php(221): Widget_Do->execute()
#3 /var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#4 /index.php(23): Typecho_Router::dispatch()
#5 {main}
### 3. 问题出现的环境
- 操作系统版本：CentOS 7.4
- Apache/NGINX 版本：Nginx 1.12.1
- 数据库版本：MySQL 5.7.20 （已关闭严格模式）
- PHP 版本：7.1.10
- Typecho 版本：1.1 (17.10.27)
- 浏览器版本：Google Chrome 63.0.3239.18

**Comment by joyqi** [comment]
你把插件的目录名从`APlayer`改成`Meting`
