### ISSUE TITLE
文章内加入emoji表情以后内容丢失

### ISSUE THREAD

**Issue by ly360** [typecho/typecho#629]
### 3. 问题出现的环境

- 操作系统版本：linux
- Apache/NGINX 版本：
- 数据库版本：5.5.56
- PHP 版本：5.6
- Typecho 版本：版本 1.1 (17.10.28)
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by a1010841065** [comment]
将数据库的编码改成utf8mb4_general_ci即可。

**Comment by joyqi** [comment]
开发版中已经增加了对utf8mb4格式的支持
