### ISSUE TITLE
themeUrl使用siteUrl而不是rootUrl，绑定不同域名时导致静态资源跨域请求

### ISSUE THREAD

**Issue by yanhuichao** [typecho/typecho#630]
主域名example.com和子域名www.example.com，均指向同一站点，主题引入使用themeUrl，themeUrl的实际上使用的是siteUrl，而非rootUrl，将导致在非siteUrl会产生跨域请求。

themeUrl使用rootUrl会不会更合适呢？

**Comment by joyqi** [comment]
直接修改为rootUrl，会对某些设置反向代理的用户产生兼容性影响，我增加了一个常量，你升级后把它添加在 `config.inc.php` 里即可

```
define('__TYPECHO_DYNAMIC_SITE_URL__', true);
```
