### ISSUE TITLE
/install.php?config 空白

### ISSUE THREAD

**Issue by imxcai** [typecho/typecho#634]
安装过程出现空白。
阿里云虚拟主机
- PHP 版本：5.5
- Typecho 版本：1.1正式版

**Comment by imxcai** [comment]
后来我安装0.9，然后根据升级的步骤，把版本升级上去了。

**Comment by chengjianxi** [comment]
我也遇到了同样的错误

**Comment by fang-d** [comment]
我也遇到了同样的错误。我的环境是Ubuntu Server 20.04 for Raspberry + Nginx 1.18.0 + MySQL 8.0.19 + PHP7.4.3，Typecho的版本为1.1-17.10.30-release。
