### ISSUE TITLE
新版本时间不对

### ISSUE THREAD

**Issue by hczcyy** [typecho/typecho#635]
### 1. 该问题的重现步骤是什么？
后台时区设置成+8，结果显示时间提前8小时
### 2. 你期待的结果是什么？实际看到的又是什么？
我在16时发布的评论，显示是8时发布的
### 3. 问题出现的环境
我的centos系统时间是正确的，输入date -R能够显示正确的时间
- 操作系统版本：centos
- Apache/NGINX 版本：1.17
- 数据库版本：5.6
- PHP 版本：5.7
- Typecho 版本：1.1
- 浏览器版本：
https://mrhe.net，这是我的博客，请管理看一下是什么情况
[//]: # (如有图片请附上截图)

**Comment by hczcyy** [comment]
看到了更新日志，说对夏令时的支持，现在找遍了后台，没看到夏令时相关的设置

**Comment by joyqi** [comment]
第一个确实是个bug，我将发布一个修复版。夏令时不需要你设置，如果你处在夏令时时区，我们会从你的浏览器检测出来。

**Comment by hczcyy** [comment]
反馈速度真快，赞一个！
