### ISSUE TITLE
1.1正式版 文章添加摘要分割线后 出现好多换行符号

### ISSUE THREAD

**Issue by noisky** [typecho/typecho#636]
### 1. 该问题的重现步骤是什么？
文章添加摘要分割线后 出现好多换行符号
### 2. 你期待的结果是什么？实际看到的又是什么？
文章添加摘要分割线后 中间应没有多余的换行符 应直接在文章下面显示 - 阅读剩余部分 - ，
### 3. 问题出现的环境

- 操作系统版本：centos6.9
- Apache/NGINX 版本：nginx/1.12.1
- 数据库版本： 5.7.19
- PHP 版本：7.1.9
- Typecho 版本：1.1
- 浏览器版本：Chrome 62.0.3202.75

使用最新正式版1.1纯净安装和默认主题
[//]: # (如有图片请附上截图)
测试地址：https://beta.ffis.me/

**Comment by joyqi** [comment]
无法复现你的错误，你的文章内容是什么

**Comment by jrotty** [comment]
他在论坛详细做了描述http://forum.typecho.org/viewtopic.php?f=4&t=10472

**Comment by joyqi** [comment]
嗯，确实是个bug
