### ISSUE TITLE
1.1 正式版文章列表错误

### ISSUE THREAD

**Issue by Dreamer-Paul** [typecho/typecho#639]
### 1. 该问题的重现步骤是什么？
发布几篇文章... 内容不限，其中cid3和4重新修改过发布时间
http://paul.gq/blog/

### 2. 你期待的结果是什么？实际看到的又是什么？
这个blog是全新安装的。文章列表（包括后台）顺序显示错误，没有按发布时间排序。修改过发布时间直接就导致直接访问博客首页的时候，那两篇修改过的文章神奇的消失了，链接访问也是 404

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：应该是 Apache 1.3，Hostinger 的虚拟空间
- 数据库版本：未知，是 Hostinger 的虚拟空间
- PHP 版本：5.6
- Typecho 版本：1.1（Github 获取的）
- 浏览器版本：Chrome 61.0.3163.100

[//]: # (如有图片请附上截图)
http://paul.gq/blog/1.png 图一所示我发布了四篇文章
http://paul.gq/blog/2.png 图二所示首页只显示了两篇（在发一篇的cid是5，直接新建的）
http://paul.gq/blog/3.png 图三为cid4，没有设置权限

**Comment by joyqi** [comment]
今天早上三点的版本更新了么

奇趣保罗 <notifications@github.com>于2017年10月30日 周一上午9:48写道：

**Comment by Dreamer-Paul** [comment]
我刚刚九点多安装的程序，直接在这个项目 Clone 的

**Comment by joyqi** [comment]
报一下
1. 你本人浏览器PC的时区
2. 以及服务器本身的时区
3. 还有服务器上PHP设置的社区

**Comment by Dreamer-Paul** [comment]
我用的是虚拟空间，没办法看服务器时间...
不过我当前时间是 14：46 的时候，PHP 返回的是 06：31

**Comment by Moidea** [comment]
@Dreamer-Paul 可能是服务器时区导致的，可以在主题文件 function.php 里设置时区试试：

`date_default_timezone_set('Asia/Shanghai'); //设置时区 解决时间错误`

**Comment by GuchengCN** [comment]
我也出现这个问题了，而且搞也明白了，我在欧洲比中国-7小时，我发布的文章修改之后，如果不重新点发布日期计算时间，我这边就显示不了了。@joyqi

**Comment by joyqi** [comment]
@GuchengCN 却是时区问题，我在最近的开发版中已经修复了这个错误

**Comment by GuchengCN** [comment]
@joyqi 我使用的就是Typecho 1.1(17.10.30)，还是有这个问题呀，比如说我在北京时间17:30发布的文章，我这里的时间是10:30，然后我修改的时候，文章上的发布日期我没有修改，点保存之后，文章就消失了，这个时候再点击编辑文章，发布日期就变成了24:30,也就是第二天了

**Comment by GuchengCN** [comment]
@joyqi 我把code打包下载试了试，确实解决了，能告诉我改了哪个文件么我覆盖一下
