### ISSUE TITLE
markdwon解析错误

### ISSUE THREAD

**Issue by 61mon** [typecho/typecho#640]
我使用的前一个版本是1.0-14.10.10，今更新为稳定版1.1，出现问题如下：

markdown原文如下：

```
1. B+树的磁盘读写代价更低

  因为B+树的所有keys终究都会出现在最底层的叶子结点，所以对于非叶子结点，我们只需存储"基于比较所用的关键字"即可（仅仅作为索引），相比B树，一个结点可以存储更多的keys，也就是说，IO读写次数降低了。

2. B+树的查询效率更稳定

  由于非叶子结点并不是最终指向文件内容的结点，而只是叶子结点中关键字的索引。所以任何关键字的查找必须走一条从根结点到叶子结点的路。所有关键字查询的路径长度相同，导致每一个数据的查询效率相当。
```

在1.0-14.10.10版本显示如下：

![qq 20171030141537](https://user-images.githubusercontent.com/23718763/32157176-dfbb4a9c-bd7c-11e7-81fb-1ade33be1d1d.png)

现在的1.1版本显示如下：

![55](https://user-images.githubusercontent.com/23718763/32157194-faa93e9a-bd7c-11e7-8d38-8883e22df6e9.png)

可否给下解决方案，具体修改的文件，如何修改？

**Comment by ppoot** [comment]
是啊 我的也是 
我的一个插件是这样调用的
`<player id="player" src=""></player>`
老本本可以调用插件输出 
刚刚升级到新版源码变这样了
`<p>&lt;player id=&quot;player&quot; src=&quot;&quot;&gt;&lt;/player&gt;</p>`
导致无法解析了 
希望回到原来的版本
