### ISSUE TITLE
markdown无法解析原来的html标签

### ISSUE THREAD

**Issue by postbird** [typecho/typecho#641]
### 1. 该问题的重现步骤是什么？

更新`Typecho 1.17.30后`原来的文档中存在的html标签基本解析失效，如一些使用`<div>/<font color="red"></red>` 或者其他自定义标签如“<red>”均无法解析，导致一些旧的文档完全失效。

某些使用 html 构建的单页面也无法更好的呈现

### 2. 你期待的结果是什么？实际看到的又是什么？

是否能够提供某种解析的选择，针对markdown的html标签可以选择是否解析或不解析。

目前从1.17.30又回滚到了1.14.x版本

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：2.4
- 数据库版本：mariaDB10
- PHP 版本：7.1
- Typecho 版本：1.17.30
- 浏览器版本：全部

[//]: # (如有图片请附上截图)

**Comment by ydq** [comment]
删除标签页不支持，之前比如某段文章大段的整段的都要删除线，之前只需要用`<s></s>`来包裹就好了，现在必须要每一段每一段的去使用`~~`，而且之前的`<s></s>`包裹的代码块也有删除线的效果，现在的使用`~~`是无法显示删除线的

**Comment by postbird** [comment]
@ydq @joyqi  换了markdown的解析引擎之后，html标签中只有少数的几个能够支持。虽然说使用markdown的话，肯定会使用markdown语法写写文章，但是markdown并不是万能的。因此这虽然不是typecho本身存在bug，但也是一个问题。很多迁移到typecho的文章都无法正确呈现，而如果使用typecho开发的企业站中如果使用**单页面**构建的站点都无法升级。

**Comment by joyqi** [comment]
试一下最新的开发版

postbird <notifications@github.com>于2017年10月31日 周二下午12:44写道：

**Comment by postbird** [comment]
@joyqi 已解决
