### ISSUE TITLE
在Coding Pages的动态Pages环境下Typecho 1.1正式版安装失败

### ISSUE THREAD

**Issue by LiarOnce** [typecho/typecho#642]
### 1. 该问题的重现步骤是什么？
提示错误，如图：
![error](https://dn-coding-net-production-pp.qbox.me/7b732fed-9a43-4f8c-9036-9f5883d7ccc3.png)

### 2. 你期待的结果是什么？实际看到的又是什么？
我期待的是安装成功界面，实际上提示了上图的错误，无法继续安装。  
但通过导入本地环境的数据库并修改`config.inc.php`中的数据库选项并没有发现问题，可以正常使用，包括发布文章。

### 3. 问题出现的环境

这是Coding Pages动态Pages功能的运行环境:
![snipaste_20171031_213359.png](https://i.loli.net/2017/10/31/59f87c1059830.png)

- Typecho 版本：1.1/17.10.30正式版

其实在最近的开发版中就已经有这样的问题了，以为是偶然问题，没有在意。   
这是在Coding上的项目以及测试网站：
[https://coding.net/u/liaronce/p/TypechoTest/git](https://coding.net/u/liaronce/p/TypechoTest/git)
[https://c8d0e51a-04b6-425a-81fb-027fb76417ee.coding.io/](https://c8d0e51a-04b6-425a-81fb-027fb76417ee.coding.io/)

**Comment by Saimen-Luo** [comment]
同样遇到新版本安装错误问题，环境为LEDE 17.01.4 x86_64  ，参考
[OpenWrt/PandoraBox/LEDE搭建Typecho](https://www.4c8t.com/archives/60)
![image](https://user-images.githubusercontent.com/31783769/32228939-97b21334-be8a-11e7-9fb7-1ab49a1cd198.png)
旧稳定版安装成功没问题。

**Comment by dxxt** [comment]
同样问题
数据库版本：10.1.28-MariaDB
PHP 版本：php7.1

**Comment by joyqi** [comment]
因为某些环境禁用了ini_get函数，导致可能出现上述问题，我已经在开发版修复了

**Comment by LiarOnce** [comment]
@joyqi 我发现事情好像没那么简单，我把最新开发版覆盖了上去还是一样的问题
![snipaste_20171101_174303.png](https://i.loli.net/2017/11/01/59f99743b7197.png)
