### ISSUE TITLE
bug 反馈，自定义首页报错

### ISSUE THREAD

**Issue by kindevil** [typecho/typecho#654]
![image](https://user-images.githubusercontent.com/846488/32414090-fb718cbc-c1e4-11e7-8b71-00149fa5e851.png)

### 1. 该问题的重现步骤是什么？
       站点首页设置为自定义页面，且自定义页面设置了自定义模版之后会出现这种情况
### 2. 你期待的结果是什么？实际看到的又是什么？
      实际看到的情况如上面的截图
### 3. 问题出现的环境

- 操作系统版本：Centos 7.3
- Apache/NGINX 版本：nginx 1.12.1
- 数据库版本：Mysql 5.5.56
- PHP 版本：7.0.21
- Typecho 版本：版本 1.1 (17.10.30)
- 浏览器版本：Chrome 61

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
请把你的自定义首页文件发上来

**Comment by kindevil** [comment]
找到问题了，模版的问题，已经解决了，谢谢
