### ISSUE TITLE
开发、正式版本<pre>标签无法正确解析且markdown代码段也无法正确解析

### ISSUE THREAD

**Issue by sailor103** [typecho/typecho#655]
比如这个段文章（pre版本）：

![g1](https://user-images.githubusercontent.com/2821687/32421767-64d93fb4-c2d6-11e7-8f76-1215ba902060.png)

结果是这个样子

![g2](https://user-images.githubusercontent.com/2821687/32421755-4c82f43c-c2d6-11e7-80fb-773112d1a458.png)

同样的markdown文本下也有bug，比如这个文章段：

![g3](https://user-images.githubusercontent.com/2821687/32421899-67129e5a-c2d7-11e7-97ab-58d18163948b.png)

效果如图

![g4](https://user-images.githubusercontent.com/2821687/32421904-6fb52dd4-c2d7-11e7-9703-dfd708c39469.png)

问题：有什么方法可以切换成老版本的解析器，新版本的解析器好像不稳定，希望解决。因为当时没测试好就升级了，现在回不到老版本了。

**Comment by jcorg** [comment]
先用!!! 包着html代码用吧！
```
<h1>标题</h1>
```
这样用

**Comment by sailor103** [comment]
@jcorg 之前的文章太多，从wordpress转换过来的，这样改太伤筋动骨了。

**Comment by jcorg** [comment]
我的升级完1.1解析器就不行了，我又换回1.0的原来的文件了

**Comment by sailor103** [comment]
@jcorg 我也是一样的问题，通过主机商的自动备份功能，我又恢复成1.0了。
