### ISSUE TITLE
安装错误。1.1版本

### ISSUE THREAD

**Issue by forskyer** [typecho/typecho#656]
确认您的配置

数据库配置

Warning: Cannot modify header information - headers already sent by (output started at /home/ynmcpcn/public_html/book/install.php:205) in /home/ynmcpcn/public_html/book/var/Typecho/Cookie.php on line 102

Warning: Cannot modify header information - headers already sent by (output started at /home/ynmcpcn/public_html/book/install.php:205) in /home/ynmcpcn/public_html/book/install.php on line 584

----------以上是错误提示-------

虚拟空间 全新安装

PHP版本（php_version）： | 5.5.33

服务器版本： 5.5.58-cll - MySQL Community Server (GPL)

typecho 1.1版本

数据库名称，数据库用户名和密码 检查无误

**Comment by joyqi** [comment]
使用开发版试试
