### ISSUE TITLE
下载了最新版，但是后显示还是不是最新版。取哪里下载最新版？

### ISSUE THREAD

**Issue by salmon3g** [typecho/typecho#657]
后台显示：
您当前使用的版本是 1.0-14.10.10
官方最新版本是 1.1-17.10.30（https://github.com/typecho/typecho/releases/tag/v1.1-17.10.30-release）

点击了上边的连接下载了最新版，重新安装后还是显示：
您当前使用的版本是 1.0-14.10.10
官方最新版本是 1.1-17.10.30（https://github.com/typecho/typecho/releases/tag/v1.1-17.10.30-release）

来来回回安装了3次了，无限循环。。。。。到底去哪里下载最新版？

**Comment by joyqi** [comment]
http://typecho.org/download
