### ISSUE TITLE
markdown的二级列表解析有问题

### ISSUE THREAD

**Issue by 61mon** [typecho/typecho#658]
markdown原文为：

```
我们知道二分的思想就是每次取一半，想象一下，不管给我们的数组有多长，每次取一半，最终都会被压缩成长度为1的数组，然后在这个长度为1的数组里判断并返回，所以我们可以直接用长度为1的数组来测试程序。以上述的"问题3：给定一个有序的数组，查找第一个大于等于value的下标，都比value小则返回-1"为例。

- 若找不到。例如数组为{ 0 }，value = 1，则left = 1，right = 0，left越界；

- 若可以找到；
  - 找到等于value的。例如数组为{ 0 }，value = 0，则left = 0，right = -1，right越界；
  - 找到大于value的。例如数组为{ 0 }，value = -1，则left = 0，right = -1，right越界；

对比程序最后的返回语句`return (left < n) ? left : -1`，代码正确。
```

在**最新开发版中**显示如下：

![default](https://user-images.githubusercontent.com/23718763/32536845-1410a0ba-c49b-11e7-9e52-47e307b707a7.png)

我找了一个显示正常的md编辑器，它本应该是这样显示的：

![default](https://user-images.githubusercontent.com/23718763/32536873-2aa2243e-c49b-11e7-8001-2ecdfb4ac215.png)

**Comment by joyqi** [comment]
有什么问题？

**Comment by 61mon** [comment]
空格间距，你仔细对比下。

二级列表中，第一级与第一级的空格间距是比正常内容分段产生的间距稍微小点的。

**Comment by joyqi** [comment]
这个没有问题，只是解析行为的差别，因为我们在li内部，如果除了文本还有其它的块（比如这里的二级列表），我们将对文本做<p>包裹，如果你想调整这里的视觉差距，可以用css控制

```css
li p:first-child {
    margin: 0
}
```

**Comment by 61mon** [comment]
好吧，不过确实是丑了点
