### ISSUE TITLE
markdown 代码段 + 标题无法解析

### ISSUE THREAD

**Issue by sailor103** [typecho/typecho#659]
文章内容如下：

![qq 20171108225333](https://user-images.githubusercontent.com/2821687/32555419-a5a8fbf8-c4d7-11e7-990c-03facf695346.png)

渲染不出第二个二极标题来，请教应该如何解决。

**Comment by joyqi** [comment]
请用开发版试试

**Comment by sailor103** [comment]
@joyqi 大大，我使用的就是开发版本哈，刚刚和朋友一起测试了有这个问题。

**Comment by joyqi** [comment]
把原文发上来不要发图片

**Comment by sailor103** [comment]
## CPEN新构造函数

    CPen( 
        int nPenStyle, 
        int nWidth, 
        const LOGBRUSH* pLogBrush, 
        int nStyleCount = 0, 
        const DWORD* lpStyle = NULL  
    );

## 参数介绍

这是我的测试文本，不知道会不会被吃

**Comment by sailor103** [comment]
@joyqi 不好意思，被github转义了。我挂了一个地址：https://yqc.im/test.md，方便的话帮忙看看，麻烦了。
`
