### ISSUE TITLE
外部链接添加 nofollow 和 target 属性

### ISSUE THREAD

**Issue by purple11261126** [typecho/typecho#661]
### 1. 该问题的重现步骤是什么？
希望给文章中出现的外部链接添加 nofollow 和 target 属性
### 2. 你期待的结果是什么？实际看到的又是什么？
期待结果：typecho0.9 版本可以通过修改 /var/CommonMark/HtmlRenderer.php 这个文件，自动给外部链接加上 nofollow 和 target 属性，教程在这里：https://www.qiansw.com/add-the-nofollow-and-target-properties-to-the-typecho-article-url.html
实际看到的：1.0 版本去掉了这个文件，想问下怎么实现这个效果。谢谢管理员。
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
直接写一个插件，正则匹配`<a href="xxx">`标签，然后替换内部内容加上你要的属性后再输出即可
