### ISSUE TITLE
安装无法进行

### ISSUE THREAD

**Issue by cnyyk** [typecho/typecho#663]
### 1. 该问题的重现步骤是什么？
下载最新代码，直接安装，无法进行

### 2. 你期待的结果是什么？实际看到的又是什么？
正常进行，有按钮进入下一步

### 3. 问题出现的环境
MAMP PRO 4.3.1
PHP 7.1.8
MySQL 5.6

- 操作系统版本：
- Apache/NGINX 版本：2.4.0
- 数据库版本：MySQL 5.6
- PHP 版本：7.1.8
- Typecho 版本：1.1.0.17.10.30
- 浏览器版本：Safair

[//]: # (如有图片请附上截图)
<img width="1680" alt="qq20171111-175817 2x" src="https://user-images.githubusercontent.com/275233/32688356-2d75eb16-c70a-11e7-81e3-96845d18cec6.png">

**Comment by joyqi** [comment]
下载开发版试试

**Comment by ky0ncheng** [comment]
+1 正式版確實安裝完成之後跳轉不正常，設置的管理員賬戶密碼也無法登入後臺

**Comment by mapann** [comment]
出现同样的现象+1

**Comment by ky0ncheng** [comment]
@mapann #667 如果上了https, 試試看

**Comment by mapann** [comment]
并没有上https。

---

我换了开发版就可以用了，稳定版不行。
- [x] 使用的是万网的免费云虚拟主机
> PHP5.5,数据库：
> mysql 5.1.48-log

**Comment by aveyuan** [comment]
在万网把php.ini所有的功能都打开

**Comment by cnyyk** [comment]
我是本机 mamp pro，稳定版确定不行。。

**Comment by pnp200** [comment]
# +1 补个log
```
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/build/install.php:202) in /var/www/html/build/var/Typecho/Cookie.php on line 102
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/build/install.php:202) in /var/www/html/build/install.php on line 584
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/build/install.php:202) in /var/www/html/build/var/Typecho/Cookie.php on line 102
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/build/install.php:202) in /var/www/html/build/install.php on line 584
```

**Comment by hustjiangtao** [comment]
Github直接clone最新代码，可以使用+1，最新的正式版出现此问题：1.1 (17.10.30)。
