### ISSUE TITLE
markdown一级列表，二级列表距离

### ISSUE THREAD

**Issue by 61mon** [typecho/typecho#664]
好吧，又来了。（这是我第三次就 md 列表的问题来到这里了，我真心希望 tc 做的越来越好，毕竟我是铁粉，进入正题）

首先我说下我想说的，

正文分段之间距离           （1）
一级与一级列表之间距离（4）
二级与二级列表之间距离（3）
一级与二级列表之间距离（2）

见下图。

![default](https://user-images.githubusercontent.com/23718763/32689399-edcd7b04-c71e-11e7-9972-358da687ca8b.png)
![qq 20171110094858](https://user-images.githubusercontent.com/23718763/32689400-f122e0a0-c71e-11e7-86dc-553d841f2bd9.png)

这四个距离**不是**一样大的，但就以目前 github 上的最新版来说，我更新完看了下，竟是一样大的。

我截图了，在下面。

![455646](https://user-images.githubusercontent.com/23718763/32689473-978073e4-c720-11e7-92c8-f17f1a623a09.png)

我们平时写文章之所以要对文章进行分段，一是为了阅读视觉的体验，二是每段内容讲的是不同的内容，方便读者整理文章逻辑。

使用列表其实就是一个分段，它们的距离不应该相等，应该是稍微小点的，这具体小多少，小的比例多大我也不清楚，我们只需参考下做的比较好的 md 编辑器（例如Typora，cmd markdown）即可。

我截个图，是cmd markdown的显示。

![qq 20171111204924](https://user-images.githubusercontent.com/23718763/32689546-e07e129e-c721-11e7-9a5a-5f314ac14a9f.png)

**Comment by joyqi** [comment]
这个用CSS就可以控制很好地控制

```css
p { maring-bottom: 20px  }
ul li p { margin-bottom: 10px }
ul li li p { margin: 0 }
```

**Comment by 61mon** [comment]
可以在 tc 中更改下么

**Comment by joyqi** [comment]
这个不太适合在解析中修改，你可以在皮肤的css里自定义一下，我看了下，markdown解析出来的html是标准的
