### ISSUE TITLE
Feed不能正常输出

### ISSUE THREAD

**Issue by holmesian** [typecho/typecho#665]
### 1. 该问题的重现步骤是什么？
从1.0升级到1.1 (17.10.30)
[问题FEED地址](https://holmesian.org/feed/)

[评论rss输出正常](https://holmesian.org/feed/comments)

### 2. 你期待的结果是什么？实际看到的又是什么？
期望feed正常输出，无法正常输出feed

与主题无关，更换为默认主题时问题依旧。
只对主题文件进行修改，程序本身未进行任何修改。

### 3. 问题出现的环境

- 操作系统版本：CentOS7
- Apache/NGINX 版本：nginx/1.12.2
- 数据库版本：mariadb-5.5.56
- PHP 版本：7.1.8
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Chrome  62.0.3202.89

请帮忙分析问题出在哪里，感谢。

**Comment by joyqi** [comment]
你使用了什么插件么

**Comment by holmesian** [comment]
@joyqi  感谢 回复。

所有插件全部禁用后问题依旧

曾经使用过的插件如下图：

![default](https://user-images.githubusercontent.com/1128377/32727286-fe96fafc-c8b6-11e7-94a7-74a025d83558.PNG)

**Comment by holmesian** [comment]
经过交叉测试已经找到原因，曾经被某插件修改了 typecho_contents 表的 allowFeed 字段，全部改回来问题解决。

    UPDATE `typecho_contents` SET `allowFeed`=1 WHERE `type`='post'
