### ISSUE TITLE
typecho1.1(2017.10.30)不支持html解析

### ISSUE THREAD

**Issue by droomo** [typecho/typecho#668]
### 1. 该问题的重现步骤是什么？
在以前版本中写的文章中用了许多html标签，我期望升级后依然可以解析这些标签。
由于在升级log中提到替换了markdown引擎，因此我不想使用第三方插件，请问有没有配置选项可以让解析器正常解析htm tag。

### 2. 你期待的结果是什么？实际看到的又是什么？
期望能在不使用插件的情况下正常解析html tag文章。
实际直接显示出了raw html。

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：无关信息
- 数据库版本：无关信息
- PHP 版本：PHP 5.4.16
- Typecho 版本：typecho1.1(2017.10.30)
- 浏览器版本：无关信息

**Comment by mo10** [comment]
加!!!
例如
```
!!!
<h1>test</h1>
!!!
```

**Comment by aveyuan** [comment]
用最新的开发版，已经已经解决了大部分问题。

**Comment by postbird** [comment]
该Issue已经closed，最新的开发版已经解决问题。
[#641](https://github.com/typecho/typecho/issues/641)

[http://www.ptbird.cn/typech-11730-html-tags.html](http://www.ptbird.cn/typech-11730-html-tags.html)

**Comment by xiahuaijia** [comment]
遇到同样问题,更新到开发版解决了
