### ISSUE TITLE
TinyMCE Editor在开启自动保存后有错误

### ISSUE THREAD

**Issue by lizheming** [typecho/typecho#67]
下面这段代码，控制台会报`Uncaught TypeError: Object [object Object] has no method 'getParent' `这个错误，看了下，这个代码应该还是老代码，`Typecho`对象里头已经没`autoSave`这个函数了。

<del>这个错误导致后面的js都没法执行了，求速改。</del>

	    tinyMCE.init({
	    // General options
	    mode : 'exact',
	    elements : 'text',
	    theme : 'advanced',
	    skin : 'typecho',
	    plugins : 'safari,morebreak,inlinepopups,media,coder',
	    extended_valid_elements : 'code[*],pre[*],script[*],iframe[*]',
	    
	    init_instance_callback : function(ed) {
	        
	        ed.setContent("");
	        autoSave = new Typecho.autoSave($('text').getParent('form').getProperty('action'), {
	            time: 60,
	            getContentHandle: tinyMCE.activeEditor.getContent.bind(ed),
	            messageElement: 'auto-save-message',
	            leaveMessage: '您的内容尚未保存, 是否离开此页面?',
	            form: $('text').getParent('form')
	        });
	    },
	    
	    onchange_callback: function (inst) {
	        if ('undefined' != typeof(autoSave)) {
	            autoSave.onContentChange();
	        }
	    },
	    
	    save_callback: function (element_id, html, body) {
	        if ('undefined' != typeof(autoSave)) {
	            autoSave.saveRev = autoSave.rev;
	        }
	        
	        return html;
	    },
	    
	    // Theme options
	    theme_advanced_buttons1 : 'bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,blockquote,|,link,unlink,image,media,|,forecolor,backcolor,|,morebreak,code',
	    theme_advanced_buttons2 : '',
	    theme_advanced_buttons3 : '',
	    theme_advanced_toolbar_location : 'top',
	    theme_advanced_toolbar_align : 'left',
	    convert_urls : false,
	    language : 'typecho'
	});

**Comment by fenbox** [comment]
插件不再维护了

**Comment by lizheming** [comment]
fen大... 三年前的 bug 啊...见过挖坟贴没见过挖坟 issue 的...也是福气T_T

**Comment by fenbox** [comment]
获得考古成就 🙈
