### ISSUE TITLE
后台打开一些页面显示：Argument 1 passed to Typecho_Widget::push() must be of the type array, null given

### ISSUE THREAD

**Issue by solitaryDon** [typecho/typecho#674]
### 1. 该问题的重现步骤是什么？
打开控制下的概览，管理下的文章，独立页面，发布文章等都会出现这个问题
### 2. 你期待的结果是什么？实际看到的又是什么？
打开上述页面出现error页面，显示：Argument 1 passed to Typecho_Widget::push() must be of the type array, null given, called in /usr/local/apache/htdocs/bolg/var/Widget/Abstract/Contents.php on line 762
### 3. 问题出现的环境

- 操作系统版本：centos 7.4（64）
- Apache/NGINX 版本：2.4.23
- 数据库版本：5.7.17
- PHP 版本：7.0.12
- Typecho 版本：1.1
- 浏览器版本：最新谷歌

[//]: # (如有图片请附上截图)

**Comment by solitaryDon** [comment]
这个应该是我的环境的问题，没有安装必要的拓展

**Comment by joyqi** [comment]
在 config.inc.php 里面加入一行

```
define('__TYPECHO_DEBUG__', true);
```

然后看看结果

**Comment by solitaryDon** [comment]
谢谢你们能给我发邮件，问题我已经解决了，是安装的插件的问题。
因为我对那几个插件不是很需要，所有没有做你们回复给我的消息中的方法，还是非常感谢。

________________________________

――愿汝安好！！！

发件人： joyqi<mailto:notifications@github.com>
发送时间： 2017-11-23 21:49
收件人： typecho/typecho<mailto:typecho@noreply.github.com>
抄送： solitaryDon<mailto:bo.Don@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [typecho/typecho] 后台打开一些页面显示：Argument 1 passed to Typecho_Widget::push() must be of the type array, null given (#674)

在 config.inc.php 里面加入一行

define('__TYPECHO_DEBUG__', true);


然后看看结果

―
