### ISSUE TITLE
升级了Typecho 1.1(17.10.30)，预发布的文章时间到了也不显示。

### ISSUE THREAD

**Issue by eedba** [typecho/typecho#678]
### 1. 该问题的重现步骤是什么？
写了篇日志，然后将发布时间调整在当前时间之后，比如明天上午，然后到了第二天。也没有发布。
服务器的时间与我本地的时间都是同步的，PHP输出的时间也与我本地的时间是一样的。很奇怪
数据库里保存的时间戳均正确，但是过了这个时间了，还是没有发布。post类型，状态publish

### 2. 你期待的结果是什么？实际看到的又是什么？
希望到时间能发布，没升级之前是可以的...

### 3. 问题出现的环境

- 操作系统版本： CentOS 6.9 x86_64
- Apache/NGINX 版本：nginx 1.11.2
- 数据库版本：mysql 5.5
- PHP 版本：php7.1.5 + Zend OPcache v7.1.5
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：safari 11.0.1 (13604.3.5)

<img width="1153" alt="2017-11-24 13 45 30" src="https://user-images.githubusercontent.com/3281114/33197017-c7ecf780-d11d-11e7-8700-292340a1cdea.png">

**Comment by joyqi** [comment]
我试了一下没有重现这个bug，从数据库的数据来看也没有任何问题，你可以试试开发版能否解决
