### ISSUE TITLE
1.1版本文章不会自动存草稿？且会让重新登陆，辛辛苦苦敲的文章没了。

### ISSUE THREAD

**Issue by CHN-STUDENT** [typecho/typecho#679]
### 1. 该问题的重现步骤是什么？

如题，我登陆后台在线敲了一篇文章，点击存草稿或者发布的时候，会重新让我登陆，我之前敲的文章没了。也不会自动存成草稿，我还需要重新敲。

### 2. 你期待的结果是什么？实际看到的又是什么？

因为我没有在本地敲完在发布的习惯，我登陆后台慢慢敲了一篇文章，可能由于时间有点长，cookies过期了？又让我重新登陆，这样我刚敲好的文章一下就没了，而且没有保存草稿什么的，我还需要重新敲。
而且期间我一直在敲文章，也没有点出登出什么操作的，就这样还让我重新登陆？

### 3. 问题出现的环境

- 操作系统版本：CentOS7.3
- Apache/NGINX 版本：1.12
- 数据库版本：Mysql 5.7.20
- PHP 版本：PHP7.1
- Typecho 版本：Typecho1.1(17.10.30)
- 浏览器版本：Chrome 62

[//]: # (如有图片请附上截图)

**Comment by CHN-STUDENT** [comment]
![tim 20171124172946](https://user-images.githubusercontent.com/21209416/33204127-73b3202a-d13d-11e7-8087-6efbd4099613.jpg)
我刚一直敲文章也没有自动存储。
![tim 20171124173220](https://user-images.githubusercontent.com/21209416/33204128-73e00c02-d13d-11e7-839f-bf4235f19cc4.png)
而我们学长的博客敲文章却能自动存储。

**Comment by joyqi** [comment]
你的个人设置里打开了自动保存选项没

**Comment by CHN-STUDENT** [comment]
抱歉抱歉，之前都没意识到还有这个开关，不记得自己是否把这个开关关上了，现在打开了。
