### ISSUE TITLE
关于 typecho_comments 表 agent 字段的长度问题

### ISSUE THREAD

**Issue by shansing** [typecho/typecho#682]
在 1.1 正式版中，agent 的类型为 VARCHAR(200)，即长度为 200 字符。我看到最新开发版中已经改为了 150 字符，参阅 issue #651 和 commit [fee8bcc63c6ad475d3b6a5c35116b28468b37b67](https://github.com/typecho/typecho/commit/fee8bcc63c6ad475d3b6a5c35116b28468b37b67#diff-046f6bf44f4df7092270bc4281f7ed26)。看起来像是为了解决 utf8mb4 InnoDB 安装失败的问题。但是我就有一个疑问了：

**150 字符真的够用吗？**

比如手机 QQ 内置浏览器的 UA 可能如下：

> Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 QQ/7.2.9.404 V1_IPH_SQ_7.2.9_1_APP_A Pixel/750 Core/UIWebView Device/Apple(iPhone 6s) NetType/4G QBWebViewType/1

已经超过 220 字符了。某些 Android 设备甚至能更长，因而我甚至觉得原来的 200 字符都可能不够用。这样在 QQ 里提交评论的时候会出现 Database Query Error 的吧。（我这里确实出现了，当我在正式版环境下把数据库字符集改为 utf8mb4 后。于是我把 agent 改成了 varchar(300)。时间问题，没做更多测试。 ）我不太懂数据库，请问我哪里理解错了吗？

请指教，先谢谢了。

**Comment by joyqi** [comment]
确实有这个问题，我可以考虑改成text
