### ISSUE TITLE
Warning: Cannot modify header information - headers already sent 

### ISSUE THREAD

**Issue by xsaiting** [typecho/typecho#683]
### 1. 该问题的重现步骤是什么？
000webhost，安装
Warning: Cannot modify header information - headers already sent by (output started at /storage/ssd4/046/3819046/public_html/install.php:202) in /storage/ssd4/046/3819046/public_html/var/Typecho/Cookie.php on line 102

Warning: Cannot modify header information - headers already sent by (output started at /storage/ssd4/046/3819046/public_html/install.php:202) in /storage/ssd4/046/3819046/public_html/install.php on line 584

### 2. 你期待的结果是什么？实际看到的又是什么？
见图

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Apache2handler
- 数据库版本：MySQL
- PHP 版本：7.1
- Typecho 版本：1.1-17.10.30-release.tar.gz
- 浏览器版本：Chrome
![tim 20171201235921](https://user-images.githubusercontent.com/24364401/33490947-b70bd2c0-d6f3-11e7-9a14-747b9f72c5ab.png)
![tim 20171201235954](https://user-images.githubusercontent.com/24364401/33490960-c2bf94f8-d6f3-11e7-91ad-67ca6743acfa.png)

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
正式版的bug，请使用开发版

**Comment by alub518** [comment]
![12_20240603194136](https://github.com/typecho/typecho/assets/10952526/186ea8d6-8ba4-474e-9213-1fed38da7b29)
开发版也有问题，正式版还可以正常连接数据库，下了开发版就一直卡在这里了
