### ISSUE TITLE
数据库用户名和密码都是root时无法连接数据库，用户名密码都正确

### ISSUE THREAD

**Issue by guoshuohui** [typecho/typecho#684]
奇怪了，我本地用的是MAMP，数据库用户名和密码都是root，旧版本的typecho安装没有问题，1.1 (17.10.30)新版本的老是提示“对不起，无法连接数据库，请先检查数据库配置再继续进行安装”

**Comment by liumuxin** [comment]
http://typecho.org/download ^_^

**Comment by guoshuohui** [comment]
我本地新建了个测试地址，叫typecho.dev，然后这个却可以，但是提交时到这一页却变成这样了
<img width="900" alt="wx20171204-170225 2x" src="https://user-images.githubusercontent.com/2731396/33544267-19994d8c-d915-11e7-8e52-f21cd2229aac.png">

**Comment by guoshuohui** [comment]
@liumuxin 就是官网下的

**Comment by joyqi** [comment]
用开发版试试

**Comment by guoshuohui** [comment]
@joyqi 好，我试一下

**Comment by guoshuohui** [comment]
@joyqi 开发版果然可以，这个是什么问题造成的？

**Comment by joyqi** [comment]
修复了之前的一个bug

**Comment by guoshuohui** [comment]
@joyqi 预计什么时候会推出新的正式版？
