### ISSUE TITLE
使用Sqlite3安装失败

### ISSUE THREAD

**Issue by xiaofami** [typecho/typecho#686]
### 运行环境
4.14.0-1.el7.elrepo.x86_64 #1 SMP Sun Nov 12 20:21:04 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
sqlite3  3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668
lighttpd/1.4.47 (ssl) - a light and fast webserver
PHP 5.4.16 (cli) (built: Nov 15 2017 16:33:54)

### 问题
提示“安装失败！安装程序检查到原有数据表已经存在.” 此时无论选择“删除原有数据”还是“使用原有数据”都会提示 **Database Query Error**。数据库已经提前手动建立了。

#### 选择删除原有数据时的错误信息

> SQLSTATE[HY000]: General error: 1 no such table: typecho_comments

> exception 'Typecho_Db_Query_Exception' with message 'SQLSTATE[HY000]: General error: 1 no such 
>  table: typecho_comments' in /var/www/lighttpd/var/Typecho/Db/Adapter/Pdo.php:105
    Stack trace:
>  #0 /var/www/lighttpd/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('DROP TABLE type...', Object(PDO), 1, 'SELECT')
>  #1 /var/www/lighttpd/install.php(428): Typecho_Db->query('DROP TABLE type...')
> #2 {main}

#### 选择使用原有数据时的错误信息

> SQLSTATE[HY000]: General error: 1 no such table: typecho_options

> exception 'Typecho_Db_Query_Exception' with message 'SQLSTATE[HY000]: General error: 1 no such table: typecho_options' in /var/www/lighttpd/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /var/www/lighttpd/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('UPDATE typecho_...', Object(PDO), 2, 'UPDATE')
#1 /var/www/lighttpd/install.php(436): Typecho_Db->query(Object(Typecho_Db_Query))
#2 {main}

### config.inc.php文件
`<?php
/**
 * Typecho Blog Platform
 *
 * @copyright  Copyright (c) 2008 Typecho team (http://www.typecho.org)
 * @license    GNU General Public License 2.0
 * @version    $Id$
 */

/** 定义根目录 */
define('__TYPECHO_ROOT_DIR__', dirname(__FILE__));

/** 定义插件目录(相对路径) */
define('__TYPECHO_PLUGIN_DIR__', '/usr/plugins');

/** 定义模板目录(相对路径) */
define('__TYPECHO_THEME_DIR__', '/usr/themes');

/** 后台路径(相对路径) */
define('__TYPECHO_ADMIN_DIR__', '/admin/');

/** 设置包含路径 */
@set_include_path(get_include_path() . PATH_SEPARATOR .
__TYPECHO_ROOT_DIR__ . '/var' . PATH_SEPARATOR .
__TYPECHO_ROOT_DIR__ . __TYPECHO_PLUGIN_DIR__);

/** 载入API支持 */
require_once 'Typecho/Common.php';

/** 载入Response支持 */
require_once 'Typecho/Response.php';

/** 载入配置支持 */
require_once 'Typecho/Config.php';

/** 载入异常支持 */
require_once 'Typecho/Exception.php';

/** 载入插件支持 */
require_once 'Typecho/Plugin.php';

/** 载入国际化支持 */
require_once 'Typecho/I18n.php';

/** 载入数据库支持 */
require_once 'Typecho/Db.php';

/** 载入路由器支持 */
require_once 'Typecho/Router.php';

/** 程序初始化 */
Typecho_Common::init();

/** 定义数据库参数 */
$db = new Typecho_Db('Pdo_SQLite', 'typecho_');
$db->addServer(array (
  'file' => '/var/www/lighttpd/usr/echodata.db',
), Typecho_Db::READ | Typecho_Db::WRITE);
Typecho_Db::set($db);
`

**Comment by niaiai** [comment]
给数据库添加权限
'/var/www/lighttpd/usr/echodata.db',

cd /var/www/lighttpd/usr
chmod 777 echodata.db

**Comment by xiaofami** [comment]
@niaiai 试了一下，还是提示`Database Query Error`

**Comment by niaiai** [comment]
/var/www/lighttpd 文件夹都给权限 就可以了
cd /var/www/
chmod -R 777 lighttpd

**Comment by xiaofami** [comment]
@niaiai 多谢指点，果然是权限的问题。不过更好的办法是把lighttpd目录的用户和组改为lighttpd：
`chown -R lighttpd:lighttpd /var/www/lighttpd/`，这样就解决了。**lighttpd.conf**中的user和group都要改成**lighttpd**
