### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by morainzh** [typecho/typecho#687]
### 1. 该问题的重现步骤是什么？
安装时反复出现“确认您的配置-数据库配置”的error；
### 2. 你期待的结果是什么？实际看到的又是什么？
正常结果是安装成功，已多次确认信息准确性，实际看到的是“确认您的配置-数据库配置”的error；
### 3. 问题出现的环境
- 操作系统版本：（阿里云主机）
- Apache/NGINX 版本：CentOS 6.5 64位
- 数据库版本：Mysql 5.1.73
- PHP 版本：5.5
- Typecho 版本：latest（1.1）
- 浏览器版本：chrome最新版

![image](https://user-images.githubusercontent.com/32979611/33795535-703b13e8-dd1e-11e7-84ac-4eb2bffd1782.png)

**Comment by joyqi** [comment]
请使用最新的开发版安装
