### ISSUE TITLE
备份文件恢复出现错误

### ISSUE THREAD

**Issue by Too-Naive** [typecho/typecho#689]
### 1. 该问题的重现步骤是什么？
上传之前网站的备份文件

### 2. 你期待的结果是什么？实际看到的又是什么？
期望:恢复成功
实际:`Column not found: 1054 Unknown column 'views' in 'field list'`
![](https://user-images.githubusercontent.com/16496671/33925525-28719a06-e015-11e7-836c-1caf404ed980.png)

### 3. 问题出现的环境

- 操作系统版本：CentOS release 6.9 (Final)
- Apache/NGINX 版本：nginx/1.10.2
- 数据库版本：mysql  Ver 14.14 Distrib 5.1.73
- PHP 版本：PHP 7.1.11 (fpm-fcgi) (built: Oct 29 2017 17:48:12)
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Chrome 63.0.3239.84 (Official Build)

**Comment by Too-Naive** [comment]
网站的备份文件是二进制文件，是否可以通过直接读取得到之前的内容？

**Comment by Too-Naive** [comment]
用記事本檢視了文件之後 發現有一個欄位  
```
...parent":1,"views":1}...
```
添加了一個文章，重新check資料表之後，發現`typecho_contents`表中並沒有所謂的`views`欄位

做了以下嘗試添加`views`欄位:
```mysql
ALTER TABLE `typecho_contents`
	ADD COLUMN `views` UNSIGNED INT NULL AFTER `parent`;
```
再重新恢復後，恢復成功

**Comment by Too-Naive** [comment]
更正: 我用備份時用的源碼tar打包後重新安裝的 應與版本無關

**Comment by joyqi** [comment]
这应该是因为你之前安装过浏览数插件，我想我需要加强一下这里的判断

**Comment by Too-Naive** [comment]
(站不是我的，原本他安裝了什麼我並不知道)原來是和這個有關係 見識了

**Comment by wanglongbiao** [comment]
我没有安装过浏览数插件，恢复的时候也出这个错了，用的最新的版本
