### ISSUE TITLE
可否增加开发版的自动升级渠道

### ISSUE THREAD

**Issue by noisky** [typecho/typecho#691]
RT.
现在开发版也挺不错的，不过我现在每次都是官方最新开发版的打包下载之后重新上传的
可否增加开发版渠道的自动更新，跟随官方最新打包的开发版进行同步更新呢
两个渠道分开更新
这样会很方便的~
支持一下~

**Comment by zgq354** [comment]
如果是vps的话我觉得可以直接 git clone，然后有更新的时候用 git pull 更新一下，不过会有 .git 目录暴露在网站根目录，感觉不是很好

**Comment by skytt** [comment]
@zgq354 GQ学长也在(坏笑

**Comment by StarryFK** [comment]
@zgq354 其实可以设置 `.git` 目录的权限吧，目录设置为 700 就没有安全方面的问题了？
