### ISSUE TITLE
开发版无法进入后台

### ISSUE THREAD

**Issue by JonjsGithub** [typecho/typecho#692]
### 1. 该问题的重现步骤是什么？
安装开发版时，引擎未见有MySQL(话说前一次下载安装却见得有)，于是选择了Pdo驱动MySQL(服务器有环境的)，安装成功了，但始终无法进入后台
### 2. 你期待的结果是什么？实际看到的又是什么？
尝试更换过1.1，但无法安装，选择了开发版进行安装
安装成功了，但无法进入后台(.../admin/)
### 3. 问题出现的环境

- 操作系统版本：Linux  内核版本：3.10.0-714.10.2.lve1.4.77.el7.x86_64
- Apache/NGINX 版本：2.4.0
- 数据库版本：5.6.36-cll-lve - MySQL Community Server (GPL)
- PHP 版本：5.6.30
- Typecho 版本：最新开发版
- 浏览器版本：Chromium内核55.0.2883.87(非正式版)(360浏览器9)

![i1](https://i.loli.net/2017/12/16/5a34b00ae8ff2.png)

**Comment by JonjsGithub** [comment]
试了一下1.0也不行
我检查一下环境

**Comment by papiJohn** [comment]
可能是nginx rewrite的问题吧。
如果是小白建议用军哥lnmp一键安装包，自带typecho的conf文件，或者各种面板，都不需要手动配置。

**Comment by JonjsGithub** [comment]
已经解决了，Apache的rewrite还是有一点问题
