### ISSUE TITLE
1.1 (17.10.30) 后台版本请求报错

### ISSUE THREAD

**Issue by jinlidashu** [typecho/typecho#693]
### 1. 该问题的重现步骤是什么？
进入后台
index.php:277 Uncaught TypeError: Cannot read property 'available' of null

update.available 请求后返回的变量是null造成的报错
### 2. 你期待的结果是什么？实际看到的又是什么？
希望解决
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by dzy0302** [comment]
我也遇到同样问题

**Comment by joyqi** [comment]
Hi，你可以试试开发版，已经解决了这个问题
