### ISSUE TITLE
建议在后台添加收录情况一览

### ISSUE THREAD

**Issue by LiuGuoGY** [typecho/typecho#694]
可否在文章总览的界面加一栏收录情况，便于站长查看收录

**Comment by mingyue2017** [comment]
这个不现实吧！毕竟搜索引擎的API调用对服务器资源也是一种损耗的！并且API接口有时候会有变动和故障的，如果集成到系统里会造成不必要的故障的！

**Comment by LiuGuoGY** [comment]
@mingyue2017 可以实现的，只需要几行代码，不需要api，用PHP之类的就可以了，相当于上个网页的流量。
