### ISSUE TITLE
未能正确获取到插件目录

### ISSUE THREAD

**Issue by jiangmuzi** [typecho/typecho#696]
https://github.com/typecho/typecho/blob/2ff40c486990e7f6d9d182ae40270a84f250df28/var/Widget/Options.php#L500

**Comment by joyqi** [comment]
有什么问题么？

**Comment by jiangmuzi** [comment]
`$plugin` 参数必须却并不能获取到指定插件的目录

**Comment by joyqi** [comment]
已修复
