### ISSUE TITLE
分类下无文章时获取的分类名与slug为NULL

### ISSUE THREAD

**Issue by jozhn** [typecho/typecho#699]
### 问题
某一个分类的页面下，如默认分类下没有文章的时候：
`$this->category();`与`$this->categories[0]['slug']`输出为空(NULL)
### 环境
centos7，lnmp
代码放在主题文件的`category.php`中，正式版本1.0-1.1都不行。
### 建议
2016年就有人提出这个问题了，但是至今还没解决~
麻烦开发者看一下能否解决这个问题！或者给出什么取巧的解决方法。

**Comment by joyqi** [comment]
`$this` 输出的永远是当前的文章，当分类下没有文章时它的输出当然总是空了，这时候你需要避免输出文章，用`<?php if ($this->have()): ?> ... <?php endif; ?>`来判断当前的文章是不是为空就好了

**Comment by jozhn** [comment]
@joyqi 请问那这样在一个没有文章的分类页面如何显示此分类的名称与slug呢~

**Comment by gogobody** [comment]
```
$this->getPageRow()
```
其实api给了。。。
