### ISSUE TITLE
搜索功能自动去掉空格

### ISSUE THREAD

**Issue by bojone** [typecho/typecho#705]
比如
http://kexue.fm/search/simpler%20glove/
或
http://kexue.fm/search/simpler glove/
都会自动退化为
http://kexue.fm/search/simplerglove/
从而无法搜索到结果。

**Comment by bojone** [comment]
我暂时通过修改var/Widget/Archive.php的源码来修正了。

**Comment by jrotty** [comment]
您好，请问您是如何避开程序对于空格等特殊字符的过滤的，最近研究写个搜索插件，这个成了阻碍。

**Comment by bojone** [comment]
```
$keywords = $this->request->filter('url', 'search')->keywords;
```
改为
```
$keywords = $this->request->keywords;
```

**Comment by S4MUELSKULL** [comment]
> ```
> $keywords = $this->request->filter('url', 'search')->keywords;
> ```
> 
> 
> 改为
> 
> 
> ```
> $keywords = $this->request->keywords;
> ```

谢谢老哥指点，另有问题，必须我搜索“A B”，那可以搜索到文章中“AxxxxB”的文章，但是如果搜索“B A” 就搜索不到了，能不能改成顺序自由排列的呢？

**Comment by fenbox** [comment]
Duplicate of #499
