### ISSUE TITLE
typecho.org无法访问

### ISSUE THREAD

**Issue by mo10** [typecho/typecho#707]
docs.typecho.org forum.typecho.org也跟着一起挂了,但是静态内容还能访问,猜测是PHP进程死了.
![qq 20180120012729](https://user-images.githubusercontent.com/9402279/35163259-19e90d1e-fd81-11e7-9160-cec23afb6f76.png)
![qq 20180120013133](https://user-images.githubusercontent.com/9402279/35163422-aa27e4d6-fd81-11e7-9070-cb61f0eae418.png)

**Comment by RedL0tus** [comment]
同時 HTTPS 的證書成了 namebeta.com 的了。

**Comment by mo10** [comment]
http恢复了访问,但是https还是迷之证书(

**Comment by joyqi** [comment]
我们还没有加上https的模式，需要等到 letsencrypt 支持泛域名证书
