### ISSUE TITLE
normalize.min.css 出现405错误

### ISSUE THREAD

**Issue by yylzcom** [typecho/typecho#711]
### 1. 该问题的重现步骤是什么？
正常安装即可

### 2. 你期待的结果是什么？实际看到的又是什么？
//cdnjscn.b0.upaiyun.com/libs/normalize/2.1.3/normalize.min.css
这个文件出现405错误

**Comment by ShangJixin** [comment]
又拍的缓存规则没做好 请自行进又拍的控制台处理 应该是被反盗链了你没处理好

**Comment by yylzcom** [comment]
这个文件是写在typecho源码里发布的，而且我注册了右拍云也无法修改这个文件的反盗链规则
https://github.com/typecho/typecho/blob/master/usr/themes/default/header.php

我认为是作者的问题，不应该使用者安装完之后一次一次手动修改源吧

**Comment by ShangJixin** [comment]
#706 有人pull request了 你照着改一下吧 改这个不涉及改内核 只是默认的主题文件改一下就OK

**Comment by yylzcom** [comment]
嗯，看来正确姿势应该是修改发pull request
my fault

:+1:
