### ISSUE TITLE
 1.1 (17.10.30)升级到当前最新开发版一直是“完成升级”提示！

### ISSUE THREAD

**Issue by imydl** [typecho/typecho#713]
### 1. 该问题的重现步骤是什么？
我只覆盖上传了如下三个目录：
/admin/
/var/
/index.php
来完成的升级更新的。
登陆后台一直都是“升级程序”那个页面让完成升级。点击“完成升级”后无任何跳转，一直都在这个页面。
### 2. 你期待的结果是什么？实际看到的又是什么？
期待的是升级成功提示，可以正常进入 Typecho 控制面板“网站概要”。
### 3. 问题出现的环境

- 操作系统版本： CentOS 7.3 64位
- Apache/NGINX 版本：1.13.8
- 数据库版本：MySQL 5.5
- PHP 版本：7.2.0
- Typecho 版本： 1.1 (17.10.30)
- 浏览器版本：Chrome 版本 64.0.3282.140（正式版本）
![qq 20180204180349](https://user-images.githubusercontent.com/26796220/35776357-d083cb58-09d5-11e8-9adf-462786220f9e.png)

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
看一下控制台，有木有错误输出

**Comment by mingyue2017** [comment]
我又关闭所有插件后试了一下，依然是这样！
并且Chrome浏览控制台里没有任何的错误提示！

**Comment by mingyue2017** [comment]
前端浏览都正常，就是无法“完成升级”！郁闷死了都！

**Comment by joyqi** [comment]
点击的时候控制台没有任何输出么？

**Comment by mingyue2017** [comment]
我给你截个图看看！

**Comment by mingyue2017** [comment]
无法上传图片，囧！能不能加我QQ，远程看一下：1974718430

**Comment by mingyue2017** [comment]
很遗憾，我停掉主题启用默认主题，听到了所有的插件依然是这个问题！

**Comment by joyqi** [comment]
可以加我telegram
https://t.me/joyqi70

**Comment by mingyue2017** [comment]
亲呀，我无论是翻墙还是正常访问都无法打开这个telegram的！Chrome里都是“ERR_CONNECTION_TIMED_OUT”这个提示的！

**Comment by joyqi** [comment]
还木解决么，加我 997155

**Comment by mingyue2017** [comment]
是呀，还没有解决呢！我已经加你QQ了！1974718430

**Comment by mingyue2017** [comment]
终于解决了，原来是又拍云造成的！
感谢 @joyqi 在QQ上的帮助！
