### ISSUE TITLE
文章列表页title标签的干预

### ISSUE THREAD

**Issue by ShangJixin** [typecho/typecho#729]
站点首页
 显示最新发布的文章
 使用  页面作为首页
 同时将文章列表页路径更改为 
/docs/
(就当上面的是图)
我这么设置之后 title那块只输出站点名称 我想让他输出为"文章中心 - 站点名称"的格式 应该怎么做比较好

**Comment by jrotty** [comment]
你可能需要这个判断
```
<?php if($this->is('front')): ?>这里是文章列表页<?php endif; ?>
```
