### ISSUE TITLE
恢复数据出现错误

### ISSUE THREAD

**Issue by Lvmoo** [typecho/typecho#731]
### 1. 该问题的重现步骤是什么？
typecho后台的备份页面
http://site/admin/backup.php
在3月1日进行了一个**备份**并下载到本地（.dat文件）
今天使用这个页面的 **恢复数据** 进行恢复时出现**恢复数据出现错误**

### 2. 你期待的结果是什么？实际看到的又是什么？

我使用编辑器打开.dat文件发现里面的文章，评论完整（备份文件完整）
我期待进行恢复时，恢复完我的文章以及评论等信息完整。

实际看下来，部分文章导入成功，评论没有导入，其他标签、分类等也未导入

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 16.04.3 LTS
- Apache/NGINX 版本：nginx version: nginx/1.12.2 
- 数据库版本：mysql  Ver 14.14 Distrib 5.7.21
- PHP 版本：PHP 7.2.1 (cli) 
- Typecho 版本：Typecho 强力驱动, 版本 1.1 (17.10.30)
- 浏览器版本：Google Chrome ) 版本 64.0.3282.186（正式版本） （64 位）

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/20103297/37277738-99bfaa4e-2620-11e8-8f03-3702f06b882a.png)

**Comment by joyqi** [comment]
请使用最新的开发版试试

**Comment by Lvmoo** [comment]
一样的，只恢复了部分文章以及（独立页面恢复正常、评论未恢复）。需要提供什么日志吗？

**Comment by joyqi** [comment]
你的数据方便发给我么 info@joyqi.com

**Comment by joyqi** [comment]
gmail现实里面包含病毒，无法接收
能否上传到一个临时的地方，把地址再发我邮箱呢

**Comment by Lvmoo** [comment]
可以通过这个地址下载 拜托了！
https://wwww.lvmoo.com/usr/uploads/2018/03/1647699717.dat



在 joyqi <notifications@github.com>，2018年3月14日 下午8:01写道：

gmail现实里面包含病毒，无法接收
能否上传到一个临时的地方，把地址再发我邮箱呢

**Comment by Lvmoo** [comment]
已发送，拜托QAQ

**Comment by joyqi** [comment]
好的，你可以删掉了

**Comment by joyqi** [comment]
你的备份文件貌似在中间损坏了，能重新导出一份试试么

**Comment by Lvmoo** [comment]
不能了，不小心用这个文件还原了一下，结果傻了



在 joyqi <notifications@github.com>，2018年3月14日 下午9:24写道：

你的备份文件貌似在中间损坏了，能重新导出一份试试么

**Comment by Lvmoo** [comment]
怎么会中间损坏嘛，就是直接导出的。
本来想导入到我另一个环境当中，结果导回了自己博客，然后就傻眼了。
重点是，数据库的备份脚本这一段时间也停了，绝望。



在 joyqi <notifications@github.com>，2018年3月14日 下午9:24写道：

你的备份文件貌似在中间损坏了，能重新导出一份试试么

**Comment by joyqi** [comment]
https://github.com/typecho/typecho/commit/13c1986f0253ffc0150ebaa9f9110ee67b5d63f1

已经新增了一个纠错模式，你可以在备份面板看到了，恢复备份的时候把这个钩上

**Comment by joyqi** [comment]
@Lvmoo 反馈一下效果

**Comment by Lvmoo** [comment]
完全🆗

可以关闭，非常感谢！

**Comment by arbaleast** [comment]
> [13c1986](https://github.com/typecho/typecho/commit/13c1986f0253ffc0150ebaa9f9110ee67b5d63f1)
> 
> 已经新增了一个纠错模式，你可以在备份面板看到了，恢复备份的时候把这个钩上

你好这个纠错陌模式是开发版中的吗？
