### ISSUE TITLE
文章重新编辑时时间会变成是原发布时间向前一分钟

### ISSUE THREAD

**Issue by nicholascw** [typecho/typecho#732]
### 1. 该问题的重现步骤是什么？
> 撰写文章 -> 发布文章 -> 点回去重新编辑
### 2. 你期待的结果是什么？实际看到的又是什么？
> 原时间;原时间-1分钟
### 3. 问题出现的环境

- 操作系统版本：Linux 4.15.5-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
- Apache/NGINX 版本：nginx version: nginx/1.12.2
- 数据库版本：Archlinux: extra/mariadb 10.1.31-1
- PHP 版本：PHP 7.2.3 (fpm-fcgi) (built: Mar  1 2018 16:50:10)
- Typecho 版本：git repo commit: 38481769906e049dfb9ad1b11925197b4c4bf2fa (Feb 2, 2018)
- 浏览器版本：Chromium 65.0.3325.162 

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
我试了好多遍，并没有出现这个情况啊

我编辑之前的文章，然后点击发布，时间并没有改变

**Comment by nicholascw** [comment]
测试了一下，依然存在并且稳定复现。将发布日期设置为1970-01-01 08:02 后点发布文章数据库中实际created的数值是60也就是08:01，再去编辑看到的也是08:01，再点发布created就是0了。

**Comment by nicholascw** [comment]
此外 unix stamp 为零的情况无法保存
