### ISSUE TITLE
默认主题 normalize.min.css 加载失败 405 错误

### ISSUE THREAD

**Issue by yueqiumao** [typecho/typecho#734]
### 1. 该问题的重现步骤是什么？
刷新页面

### 2. 你期待的结果是什么？实际看到的又是什么？
默认主题种的css文件无法加载成功，显示 405 错误，，，

### 3. 问题出现的环境
mac safiri

- 操作系统版本：mac
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)
http://cdnjscn.b0.upaiyun.com/libs/normalize/2.1.3/normalize.min.css
405 Not Allowed

**Comment by Heier2013** [comment]
#726

**Comment by joyqi** [comment]
已经在开发版里修复了，请等待正式版发布
