### ISSUE TITLE
可否增加加入统计代码的功能。

### ISSUE THREAD

**Issue by qwerty250** [typecho/typecho#740]
### 1. 该问题的重现步骤是什么？
N/A
### 2. 你期待的结果是什么？实际看到的又是什么？
建议加入全局统计代码的功能。
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by qwerty250** [comment]
希望在后台界面中添加相应设置。毕竟有WebUI更直观。

**Comment by wangdaodao** [comment]
统计工具得用第三方的，如果在后台加，无疑是做了一个小的统计系统……

**Comment by fenbox** [comment]
可以修改模板添加个 field 实现后台添加统计代码 http://docs.typecho.org/themes/custom-themefields
