### ISSUE TITLE
下次自动登录无效

### ISSUE THREAD

**Issue by licxisky** [typecho/typecho#741]
### 1. 该问题的重现步骤是什么？
用户登录时，点击下次自动登录

### 2. 你期待的结果是什么？实际看到的又是什么？
本机再次登录时自动登录
再次登录时还是要输入用户名密码，无法自动登录

### 3. 问题出现的环境

- 操作系统版本：Windows NT DESKTOP-AVTC9JU 10.0 build 16299 (Windows 10) i586
- Apache/NGINX 版本：Apache/2.4.29 (Win32) OpenSSL/1.1.0g
- 数据库版本：MySQL 5.6
- PHP 版本： PHP/7.2.0
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Chrome 65.0.3325.181（正式版本） （64 位）

### 4. 备注
看了一下Login.php的代码，似乎并没有在登录的时候从Cookie中取出以前存储的用户信息

**Comment by bestony** [comment]
有的， 在这一行检测是否登录https://github.com/typecho/typecho/blob/c2a71c2f1943242e6cc9ee4e4759861ff6af7fa3/admin/login.php#L4
回溯到  
https://github.com/typecho/typecho/blob/c2a71c2f1943242e6cc9ee4e4759861ff6af7fa3/admin/common.php#L21
最后定位到这个函数
https://github.com/typecho/typecho/blob/c2a71c2f1943242e6cc9ee4e4759861ff6af7fa3/var/Widget/User.php#L219-L242
可以看到是有检查的。至于为什么你没有自动登录，可以下载一个 Cookie 编辑器，看一下登录时，是否有`__typecho_uid`这个 Cookie

**Comment by licxisky** [comment]
谢谢，应该是之前有些操作的问题，TE本身没有问题
