### ISSUE TITLE
前台打开 category 数据库报错

### ISSUE THREAD

**Issue by maplesky** [typecho/typecho#744]
### 1. 该问题的重现步骤是什么？
访问 category 页面出现 Database Query Error 错误.

### 2. 你期待的结果是什么？实际看到的又是什么？
正确访问 category 页面及索引相关数据

### 3. 问题出现的环境
- 操作系统版本：CentOS 6.9 x86
- Nginx 版本：1.12.2
- 数据库版本：PostgreSQL / 8.4.20
- PHP 版本：5.3.3 (fpm-fcgi)
- Typecho 版本：Typecho 1.1(17.10.30)
- 浏览器版本：Google Chrome v65.0.3325.181

[//]: # (如有图片请附上截图)
![screenshot](https://user-images.githubusercontent.com/2759383/38434470-06e824b8-3a01-11e8-96df-44b43ec1fa1c.png)

**Comment by joyqi** [comment]
请试一下最新的开发版，我们已经修复这个问题了
