### ISSUE TITLE
密码保护的文章提交密码无效

### ISSUE THREAD

**Issue by leeqw123** [typecho/typecho#753]
### 1. 该问题的重现步骤是什么？

创建受密码保护的文章，在前台文章页面输入密码并点击提交。

### 2. 你期待的结果是什么？实际看到的又是什么？

期待结果是：进入文章内容显示的页面。

实际看到的：仍旧位于输入密码的页面，浏览器像是只是简单的刷新了一下，URL后面没有?_=****参数字符串。手动刷新时不提示是否重新提交POST请求。

但是当我在浏览器地址栏URL后面手动输入随机的参数字符串，如?aaaaaaaaaaaaa并回车之后，再输入密码并点击提交时，可以正常进入文章页面。

### 3. 问题出现的环境

- 操作系统版本：CentOS 7.2 x64
- Apache/NGINX 版本：nginx/1.14.0
- 数据库版本：mariadb-5.5.56
- PHP 版本：PHP 5.4.16
- Typecho 版本：最新正式版
- 浏览器版本：所有浏览器

[//]: # (如有图片请附上截图)

**Comment by logofun** [comment]
同样问题，密码保护无效。即便输入正确密码（后台数据库查看无误），仍反映密码错误

**Comment by logofun** [comment]
一个有趣的现象：typecho1.1正式版录入密码可以查看到密码保护文章。而开发版却不能显示（提示密码错误）！

**Comment by logofun** [comment]
@joyqi
版主能否看下是什么原因？

**Comment by JoyChou93** [comment]
有个小问题：提交密码后才会set-cookie，所以提交密码的请求还是会提示密码错误，需要再次访问一次页面。
