### ISSUE TITLE
使用搜索框搜索中文关键字，没有结果，跳转到404页面

### ISSUE THREAD

**Issue by fhefh2015** [typecho/typecho#760]
1. 该问题的重现步骤是什么？
搜索的内容里包含中文字符,无法跳转/search/内容,而是直接跳转/search,进入了404

2. 你期待的结果是什么？实际看到的又是什么？
本来应该出现搜索的结果,结果出现了404

3. 问题出现的环境
操作系统版本：
Apache/NGINX 版本：最新版本
数据库版本：5.7
PHP 版本：7.1
Typecho 版本：1.1
浏览器版本：所有浏览器都这样（跟浏览应该没什么关系）

**Comment by thriken** [comment]
刚刚本地搭建了AMP测试
完全没有问题
http://typecho/index.php/search/欢迎/
apache2.4+php5.5+mysql5.6  WIN10

**Comment by liyiliang** [comment]
我也遇到这个问题。
    /**
     * 将url中的非法字符串
     *
     * @param string $url 需要过滤的url
     * @return string
     */
    public static function safeUrl($url)
    {
        //~ 针对location的xss过滤, 因为其特殊性无法使用removeXSS函数
        //~ fix issue 66
var_dump($url);
        $params = parse_url(str_replace(array("\r", "\n", "\t", ' '), '', $url));
var_dump($params);die();
        /** 禁止非法的协议跳转 */
        if (isset($params['scheme'])) {
            if (!in_array($params['scheme'], array('http', 'https'))) {
                return '/';
            }
        }else{
            unset($params);
            $params['path'] = $url;
        }

        /** 过滤解析串 */
        $params = array_map(array('Typecho_Common', '__removeUrlXss'), $params);
        return self::buildUrl($params);
    }
这个parse_url 有问题，
string(6) "中文" array(1) { ["path"]=> string(6) "中�__" }

**Comment by wuyow** [comment]
我的也搜索不了中文
我的站点：
[vrok.tk/tc](http://vrok.tk/tc)

**Comment by fhefh2015** [comment]
@wuyow 
我重装了Typecho 换了一个主题~ 现在可以用了~
版本 1.1 (17.10.30)

**Comment by chaihahaha** [comment]
我也遇到了这个问题，不只是中文，希腊字母等也会404

    操作系统版本：windows server
    Apache/NGINX 版本：
    数据库版本：Ms/MySQL
    PHP 版本：ASP PHP7.0
    Typecho 版本：版本 1.1 (17.10.30)
    浏览器版本：Firefox 71.0 (64位)

我的网址是: chaihahaha.55555.io
