### ISSUE TITLE
协助完成插件GoogleAuthenticator，两步验证登录

### ISSUE THREAD

**Issue by isky100** [typecho/typecho#761]
已经基本可用，但是不符合插件规范，不清楚typecho里的插件写法
地址：https://github.com/isky100/typecho
master分支，fork的本项目，最后一次提交是添加插件
修改了文件admin/login.php、var/Widget/Login.php
user表添加了一个字段googleCode
没有人研究就算了，反正我已经用上了

**Comment by chengs2035** [comment]
做成插件比较好

**Comment by jzwalk** [comment]
https://github.com/weicno/typecho-Authenticator
