### ISSUE TITLE
主题和插件

### ISSUE THREAD

**Issue by zhangxiaobai250295** [typecho/typecho#764]
在服务器上传了两个主题和一个插件，但在typecho的后台都看不到上传的主题和插件是怎么回事？

**Comment by Xing-Chuan** [comment]
目录不对, 就是命名不对, 文件权限也有可能造成这个问题

**Comment by jqqzzz** [comment]
我也是同样的问题，想知道怎么解决。检查了目录，命名，权限等似乎都没有问题

**Comment by yzwlnb** [comment]
解决了吗 我也是这样
