### ISSUE TITLE
评论页面无法输出评论状态

### ISSUE THREAD

**Issue by foxnes** [typecho/typecho#768]
### 1. 该问题的重现步骤是什么？
使用默认主题，开启评论审核，然后退出登录，随便打开一篇文章进行评论

### 2. 你期待的结果是什么？实际看到的又是什么？
期待：输出评论状态（就是提示```您的评论在等待审核```）
实际：页面URL hash指向了评论ID，但是评论状态却没有被输出，也就是页面无变化，但是后台能看到要审核的评论

### 3. 问题出现的环境

- 操作系统版本： WIN7 32
- Apache 版本：Apache/2.4.23（Win32）
- 数据库版本：5.5.53
- PHP 版本：5.6.27
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Chrome 67.0.3396.99（正式版本）（32 位）

**Comment by beyondtop** [comment]
我用的1.2版本，也出现此问题，没有输出评论状态，<?php $singleCommentOptions->commentStatus(); ?>在模板加上这一句，页面直接打不开，提示commentStatus() null。有什么方法解决吗？

**Comment by jrotty** [comment]
@beyondtop `<?php if ('waiting' == $comments->status) { ?><span class="text-muted">您的评论需管理员审核后才能显示！</span><?php } ?>`我是这样写的

**Comment by beyondtop** [comment]
> @beyondtop `<?php if ('waiting' == $comments->status) { ?><span class="text-muted">您的评论需管理员审核后才能显示！</span><?php } ?>`我是这样写的

非常感谢，测试有效。
