### ISSUE TITLE
文档发布后丢失后部分内容

### ISSUE THREAD

**Issue by klpek** [typecho/typecho#771]
文章发布后,丢失数据.可能原因是文章太长.已经丢失很多回

**Comment by joyqi** [comment]
请问你的文章大概有多少个字呢？typecho目前的版本里保存文本使用的是`longtext`类型，可以保存非常非常非常多的字，一本书都没有问题。但是需要注意的是你的服务器设置，他们往往对POST请求体的大小会有所限制，在nginx里这个设置叫 `client_max_body_size`

**Comment by pxw2002** [comment]
我用的稳定版 之前有限制  后来数据库换成 SQLite 就好了
