### ISSUE TITLE
Typecho 搜索中文404

### ISSUE THREAD

**Issue by littledavid-tech** [typecho/typecho#777]
### 1. 该问题的重现步骤是什么？
在网站中搜索英文是可以正常显示的，但是如果搜索中文的话就404错误了
### 2. 你期待的结果是什么？实际看到的又是什么？
能够正常搜索中文关键字，目前不能正常搜索中文，如果搜索中文会出现404错误
### 3. 问题出现的环境

- 操作系统版本：win2008
- Apache/NGINX 版本： 使用的IIS7.5
- 数据库版本：MySQL 5.7
- PHP 版本：5.4
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：所有的浏览器

[//]: # (如有图片请附上截图)

**Comment by littledavid-tech** [comment]
没有找到解决办法，已经迁移到了 Linux环境。通过宝塔面板配置环境。

**Comment by bestony** [comment]
有测试站点的 URL 么？

**Comment by bestony** [comment]
根据你描述的情况，应该是 IIS 的请求转发过程中出现了问题。

**Comment by littledavid-tech** [comment]
@bestony  不好意思的哈，原来的服务器环境给炸掉了，已经换成Linux环境了。。Linux下正常

**Comment by kangclassmate** [comment]
还没有解决方案吗
