### ISSUE TITLE
错误日志中的一句话

### ISSUE THREAD

**Issue by linhaii** [typecho/typecho#787]
### 1. 该问题的重现步骤是什么？

主机错误日志里面，生成了很多行如下文字：

PHP Notice:  Undefined variable: result in /home/（用户名）/public_html/var/Widget/Ajax.php on line 71

### 2. 你期待的结果是什么？实际看到的又是什么？

如何解决这个问题？不耽误正常使用，只是问问。
![errorlog](https://user-images.githubusercontent.com/32946306/46281779-31762400-c5a2-11e8-98eb-a088d74ef771.png)

### 3. 问题出现的环境

- 操作系统版本：虚拟主机，不清楚
- Apache/NGINX 版本：未知
- 数据库版本： 5.6
- PHP 版本： 7.1
- Typecho 版本：1.1(17.11.30）
- 浏览器版本：火狐、谷歌最新版

[//]: # (如有图片请附上截图)

**Comment by Zhangzijing** [comment]
这个是因为访问 http://typecho.org/version.json 获取失败.

**Comment by linhaii** [comment]
> 这个是因为访问 http://typecho.org/version.json 获取失败.

谢谢！
