### ISSUE TITLE
文章路径更改 slug 导致路由丢失无法访问文章

### ISSUE THREAD

**Issue by Anankke** [typecho/typecho#796]
### 1. 该问题的重现步骤是什么？
永久链接设置里开启 rewrite，自定义文章路径使用包含 slug 变量的链接。
发布文章可正常查看文章，编辑器中更改文章 slug 访问新链接无法查看。
Update：即使更新文章内容也会导致原链接直接丢失路由。
本例中 使用了 `/w/{slug}` 作为自定义链接。
![image](https://user-images.githubusercontent.com/40639066/47096061-6b7b3300-d1fc-11e8-9f13-96ce24352ec9.png)

### 2. 你期待的结果是什么？实际看到的又是什么？
预期结果：使用新的链接可查看原页面。
实际结果：使用新的链接无法找到页面，开启 debug 后发现路由无法找到。
![image](https://user-images.githubusercontent.com/40639066/47096188-aaa98400-d1fc-11e8-8c8e-819076e37c3d.png)
![image](https://user-images.githubusercontent.com/40639066/47096218-b301bf00-d1fc-11e8-886a-861e7fc5e05f.png)

### 3. 问题出现的环境

- 操作系统版本：Centos 7 内核版本：4.9.127-32.el7.x86_64
- Apache/NGINX 版本：Nginx 1.14.0
- 数据库版本：Mysql 8.0.11
- PHP 版本：PHP 7.2.6
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Google Chrome  70.0.3538.67（64 位）

并未能找到路由无效的原因

[//]: # (如有图片请附上截图)

**Comment by Anankke** [comment]
这是不是没办法了这个 bug（雾

**Comment by nagatoyk** [comment]
伪静态规则贴出来啊

**Comment by Anankke** [comment]
@nagatoyk 
```
if (!-e $request_filename) {
    rewrite ^(.*)$ /index.php$1 last;
}
```

**Comment by Anankke** [comment]
开发版玄学解决了问题，感谢。
