### ISSUE TITLE
发布文章后，报错：Typecho_Db_Query_Exception: ERROR:  syntax error at or near ")"

### ISSUE THREAD

**Issue by end-e** [typecho/typecho#803]
### 1. 该问题的重现步骤是什么？
发布文章后
### 2. 你期待的结果是什么？实际看到的又是什么？
找到了错误语句：
`SELECT
	COUNT (typecho_contents."cid") AS "num"
FROM
	typecho_contents
WHERE
	(
		typecho_contents."created" > 
	)
AND (
	typecho_contents."type" = 'post'
)
AND (
	typecho_contents."authorId" = '1'
)`

缺少条件值
`typecho_contents."created" > `

修改为以下，本地测试通过 
 `typecho_contents."created" > 0`
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：NGINX
- 数据库版本：PostgreSQL 9.6
- PHP 版本：PHP 7
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by end-e** [comment]
堆栈信息：

Typecho_Db_Query_Exception: ERROR:  syntax error at or near ")"
LINE 1: ...ho_contents WHERE  (typecho_contents."created" >  ) AND (typ...
                                                             ^ in /var/www/html/typecho/build/var/Typecho/Db/Adapter/Pgsql.php:96
Stack trace:
#0 /var/www/html/typecho/build/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pgsql->query('SELECT COUNT(ty...', Resource id #3, 1, 'SELECT')
#1 /var/www/html/typecho/build/var/Typecho/Db.php(431): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /var/www/html/typecho/build/var/Widget/Abstract/Contents.php(245): Typecho_Db->fetchObject(Object(Typecho_Db_Query))
#3 /var/www/html/typecho/build/var/Widget/Contents/Post/Edit.php(193): Widget_Abstract_Contents->getPageOffset('created', NULL, 'post', NULL, '1')
#4 /var/www/html/typecho/build/var/Widget/Contents/Post/Edit.php(752): Widget_Contents_Post_Edit->getPageOffsetQuery(NULL)
#5 /var/www/html/typecho/build/var/Widget/Contents/Post/Edit.php(910): Widget_Contents_Post_Edit->writePost()
#6 /var/www/html/typecho/build/var/Widget/Do.php(82): Widget_Contents_Post_Edit->action()
#7 /var/www/html/typecho/build/var/Typecho/Widget.php(221): Widget_Do->execute()
#8 /var/www/html/typecho/build/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#9 /var/www/html/typecho/build/index.php(23): Typecho_Router::dispatch()
#10 {main}

**Comment by joyqi** [comment]
这是PGSql的一个bug，已经在开发版里修复了，你试试开发版

**Comment by end-e** [comment]
> 这是PGSql的一个bug，已经在开发版里修复了，你试试开发版

好的，我试试
