### ISSUE TITLE
隐藏独立页面失败

### ISSUE THREAD

**Issue by skys215** [typecho/typecho#805]
我在把独立页面设置为隐藏，并点击保存的时候，发现报错了。
`Database Query Error`
把mysql错误打印出来显示为`...have syntax error near order=0....`
把sql打印出来发现该处直接拼接为`$columns[] = "$key = $val";`[源代码](https://github.com/typecho/typecho/blob/3050aa98ab788f560e4f1ff185921882d746804b/var/Typecho/Db/Query.php#L552)
之前我也把字段名设置为order过，此处应当添加"\`"反引号括住字段名，修改为：
```php
$columns[] = "`$key` = $val";
```
即可。

order字段相关页面：[link](https://github.com/typecho/typecho/blob/master/var/Widget/Abstract/Contents.php#L324)

**Comment by skys215** [comment]
改了之后发现保存不了草稿了…
调试一番，我又改了一下：
如果你有做上面的操作的话，先复原上面的操作。
然后在372行处：
```php
    public function rows(array $rows)
    {
        foreach ($rows as $key => $row) {
            $this->_sqlPreBuild['rows'][$this->filterColumn($key)] = is_null($row) ? 'NULL' : $this->_adapter->quoteValue($row);
        }
        return $this;
    }
```
中，把`$this->filterColumn($key)`改为：
```
'`'.trim($this->filterColumn($key)).'\`'
```

我看其他地方也有$this->filterColumn($key)这种用法，怀疑都需要修改。
坐等官方修复。

**Comment by skys215** [comment]
@joyqi

**Comment by skys215** [comment]
现在是保存不了分类了…

**Comment by skys215** [comment]
```
class Typecho_Db_Query
{
    /** 数据库关键字 */
    const KEYWORDS = '*PRIMARY|AND|OR|LIKE|BINARY|BY|DISTINCT|AS|IN|IS|NULL|ORDER';//<--少了ORDER
```

**Comment by skys215** [comment]
好像上面的还不够，
我修改了`DB/Query.php` 中的`__toString()`方法，其中对case为INSERT的情况由：
```php
. '( ' . implode(', ', array_keys($this->_sqlPreBuild['rows'])) . ')'
```

修改为：
```php
. '( `' . implode('`, `', array_keys($this->_sqlPreBuild['rows'])) . '`)'
```

**Comment by fenbox** [comment]
无法复现
