### ISSUE TITLE
close

### ISSUE THREAD

**Issue by zerokeeper** [typecho/typecho#809]
close

**Comment by mierhuo** [comment]
Typecho默认给了登录用户较大权限，可以在线直接编辑主题文件(如果有读写权限)，可以设定评论标签白名单，编辑器也有 `!!!`语法。

**Comment by logofun** [comment]
!!!这三个感叹号是什么语法
!!!求教

**Comment by joyqi** [comment]
typecho 对作者自己输入的内容不做过滤 xss 处理，就跟上面说的一样，还可以通过特殊语法输出完整的html内容。因为按照逻辑，作者要 xss 自己并没有什么其它危害，属于个人自由。
