### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by Hiyuu-cc** [typecho/typecho#812]
### 1. 该问题的重现步骤是什么？
如何使用docker image安装typecho，如何填写内容？

1.image     :  image:tag
2.Options  :  -e XXX -p XX:XX

### 2. 你期待的结果是什么？实际看到的又是什么？

成功安装typecho至VPS

### 3. 问题出现的环境
安装过程

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

img：https://i.loli.net/2018/11/30/5c0111c249b92.png
[//]: # (如有图片请附上截图)

**Comment by Vndroid** [comment]
No official docker image, you can create it yourself. For example, you can use PHP nginx mysql docker image to deploy blog environment.
