### ISSUE TITLE
使用Dockerfile文件构建时下载速度过慢

### ISSUE THREAD

**Issue by z1064244797** [typecho/typecho#814]
### 1. 该问题的重现步骤是什么？
> docker build -t typecho:0.1 .
### 2. 你期待的结果是什么？实际看到的又是什么？
使用 mirrors.aliyun.com替代原Dockerfile的源
### 3. 问题出现的环境
- 操作系统版本：Ubuntu 16.04
- Typecho 版本：1.1
-  安装方式：Docker
![image](https://user-images.githubusercontent.com/32192232/49297286-672d7f80-f4f5-11e8-9073-1e637a2d22d6.png)

**Comment by codesensi** [comment]
请问具体是怎么解决的呢，能贴一下代码吗，谢谢

**Comment by Nyaasu66** [comment]
> 请问具体是怎么解决的呢，能贴一下代码吗，谢谢



> 请问具体是怎么解决的呢，能贴一下代码吗，谢谢

使用 mirrors.aliyun.com替代原Dockerfile的源
具体我忘记了，请百度
