### ISSUE TITLE
markdown编辑器不支持表格

### ISSUE THREAD

**Issue by wenfer** [typecho/typecho#822]
1.1 (17.10.30) 版的，表格显示的还是Markdown语法

**Comment by zengxiaofei** [comment]
我的版本是正常的
比如：
```
|最小非零正数   |最小有限值   |最大有限值   |
|:-----------:|:-----------:|:----------:|
|2.225074e-308|-1.797693e308|1.797693e308|
```
最终效果：

|最小非零正数   |最小有限值   |最大有限值   |
|:-----------:|:-----------:|:----------:|
|2.225074e-308|-1.797693e308|1.797693e308|

**Comment by fenbox** [comment]
现在应该正常了
