### ISSUE TITLE
升级到开发版提示 no such table

### ISSUE THREAD

**Issue by zcat95** [typecho/typecho#824]
### 1. 该问题的重现步骤是什么？
从 1.1 (17.10.30) 升级为 1.2 (18.1.29)
按照官方文档操作，进入 admin/upgrade.php
点击完成升级
提示
`SQLSTATE[HY000]: General error: 1 no such table: typecho_zcatmetas`

### 2. 你期待的结果是什么？实际看到的又是什么？
应该正常完成升级，而不是提示找不到数据库。

### 3. 问题出现的环境
debian 9 x64 | caddy | sqlite 3.16.2 | PHP7
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Chrome 71.0.3578.98

[//]: # (如有图片请附上截图)

**Comment by qy117121** [comment]
同样的这个问题

**Comment by scvoet** [comment]
那么实际上存在这一数据表吗

**Comment by qy117121** [comment]
> 那么实际上存在这一数据表吗

没有这个表

**Comment by scvoet** [comment]
从报错中看提示不存在的表是`typecho_zcatmetas`，但实际上表名应为`typecho_metas`，由此可以猜测是数据表前缀设置出了问题，建议看一下 config.inc.php 中的设置是否正确。 @qy117121

**Comment by qy117121** [comment]
> 从报错中看提示不存在的表是`typecho_zcatmetas`，但实际上表名应为`typecho_metas`，由此可以猜测是数据表前缀设置出了问题，建议看一下 config.inc.php 中的设置是否正确。 @qy117121

表前缀是typecho默认的，并没有修改

本地安装了一个新的测试还是这样的结果 

刚安装后的数据库备份 https://s2.ax1x.com/2020/01/03/lUUnUI.jpg

升级开发版出错后  https://s2.ax1x.com/2020/01/03/lUUNan.jpg
