### ISSUE TITLE
首页点击文章链接，实际显示还是首页内容

### ISSUE THREAD

**Issue by yanjingtu** [typecho/typecho#826]
### 1. 该问题的重现步骤是什么？
创建issue的时候发现了这个#675，应该是相同的问题。

访问首页：
http://jingles.top:8888/blog/
随便点击一个文章链接，例如：
http://jingles.top:8888/blog/index.php/archives/21/

### 2. 你期待的结果是什么？实际看到的又是什么？
首页点击文章链接之后发现实际显示出来的还是首页

### 3. 问题出现的环境
在不启用地址重写的情况下是以上情况。

- 操作系统版本：
- Apache/NGINX 版本：nginx/1.15.2
- 数据库版本：SQLite 3.x database（看了下，好像是这样的，安装的时候没有配置过数据库）
- PHP 版本：PHP 7.2.9 (cli) (built: Aug 27 2018 11:40:42) ( ZTS )
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：Google Chrome 70.0.3538.67（正式版本） （64 位）

- nginx部分配置：
       if (!-e $request_filename) {
           rewrite ^(.*)/blog/(.*)$ $1/blog/index.php/$2 last;
       }

       location ~ .*\.php(\/.*)*$ {
               fastcgi_pass   127.0.0.1:9000;
               fastcgi_index  index.php;
               fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
               fastcgi_param  SCRIPT_NAME  $fastcgi_script_name;
               include        fastcgi_params;
       }

请问大家，还需要检查什么？

**Comment by yanjingtu** [comment]
试过更改主题，目前已经是在用官方自带的主题了，还是不行。
试过禁用所有的插件，目前已经把所有插件都禁用了，还是不行。
还需要做哪些检查来核实呢？

**Comment by yanjingtu** [comment]
可能是sqlite数据库中option表里面的routingTable这个项的值有问题？初始化网站的时候我弄错配置了？

**Comment by yanjingtu** [comment]
试着重新换了一个目录部署，还是相同的情况，文章页面打不开，只能看着首页和后台页面。包括尝试将网站的备份导入，或者是不导入备份的空网站，都是不行的。
我准备找一个nginx+php的docker容器试一把。

**Comment by KeNorizon** [comment]
测试了一下尝试进行了复现和修复，原因应该是 nginx 的配置书写有误。

你的配置内容如下：
第一段
```
if (!-e $request_filename) {
rewrite ^(.)/blog/(.)$ $1/blog/index.php/$2 last;
}
```

第二段
```
 location ~ .*\.php(\/.*)*$ {
         fastcgi_pass   127.0.0.1:9000;
         fastcgi_index  index.php;
         fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
         fastcgi_param  SCRIPT_NAME  $fastcgi_script_name;
         include        fastcgi_params;
 }
```

你的预期目标：
不启用地址重写下正常打开文章页。

其中有如下几个问题：
1.  第一段配置内容是对地址重写进行支持，在不开启地址重写的情况下这段配置只会起到反作用。应当删去。（其实其中第二行有一点问题， `.*` 错写成了 `.`，所以这段配置可以视作无效）
2. 第二段 fastcgi 配置部分中，没有给出正确的PATH_INFO配置。（Typecho 依赖于 PATH_INFO 进行路由）
  参考代码：
  https://github.com/typecho/typecho/blob/master/var/Typecho/Request.php#L444
  https://github.com/typecho/typecho/blob/master/var/Typecho/Request.php#L581

Nginx + php-fpm 下可以通过以下配置给出正确的 PATH_INFO 
```
fastcgi_split_path_info ^((?U).+.php)(/?.+)$;
```
参考文档：
https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_split_path_info

综上，不启用地址重写的情况下，前面提及的 Nginx 配置改为以下内容应该可以正常工作（本地 Nginx 1.14.2 + PHP 7.3.1 环境测试可以修复上述问题）

```
location ~ .*\.php(\/.*)*$ {
         fastcgi_pass   127.0.0.1:9000;
         fastcgi_index  index.php;
         fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
         fastcgi_param  SCRIPT_NAME  $fastcgi_script_name;
         fastcgi_split_path_info  ^((?U).+\.php)(/?.+)$;
         include        fastcgi_params;
 }
```

**Comment by yanjingtu** [comment]
> 测试了一下尝试进行了复现和修复，原因应该是 nginx 的配置书写有误。
> 
> 你的配置内容如下：
> 第一段
> 
> ```
> if (!-e $request_filename) {
> rewrite ^(.)/blog/(.)$ $1/blog/index.php/$2 last;
> }
> ```
> 第二段
> 
> ```
>  location ~ .*\.php(\/.*)*$ {
>          fastcgi_pass   127.0.0.1:9000;
>          fastcgi_index  index.php;
>          fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
>          fastcgi_param  SCRIPT_NAME  $fastcgi_script_name;
>          include        fastcgi_params;
>  }
> ```
> 你的预期目标：
> 不启用地址重写下正常打开文章页。
> 
> 其中有如下几个问题：
> 
> 1. 第一段配置内容是对地址重写进行支持，在不开启地址重写的情况下这段配置只会起到反作用。应当删去。（其实其中第二行有一点问题， `.*` 错写成了 `.`，所以这段配置可以视作无效）
> 2. 第二段 fastcgi 配置部分中，没有给出正确的PATH_INFO配置。（Typecho 依赖于 PATH_INFO 进行路由）
>    参考代码：
>    https://github.com/typecho/typecho/blob/master/var/Typecho/Request.php#L444
>    https://github.com/typecho/typecho/blob/master/var/Typecho/Request.php#L581
> 
> Nginx + php-fpm 下可以通过以下配置给出正确的 PATH_INFO
> 
> ```
> fastcgi_split_path_info ^((?U).+.php)(/?.+)$;
> ```
> 参考文档：
> https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_split_path_info
> 
> 综上，不启用地址重写的情况下，前面提及的 Nginx 配置改为以下内容应该可以正常工作（本地 Nginx 1.14.2 + PHP 7.3.1 环境测试可以修复上述问题）
> 
> ```
> location ~ .*\.php(\/.*)*$ {
>          fastcgi_pass   127.0.0.1:9000;
>          fastcgi_index  index.php;
>          fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
>          fastcgi_param  SCRIPT_NAME  $fastcgi_script_name;
>          fastcgi_split_path_info  ^((?U).+\.php)(/?.+)$;
>          include        fastcgi_params;
>  }
> ```

感谢您的解答，经过测试，增加fastcgi_split_path_info之后，文章页面访问正常了，是本人由于nginx配置不熟悉导致的配置错误的问题，不是typecho功能存在问题。
经过以上调整之后，文章页面可以正常打开了。
再次感谢KeNorizon的上述解答！感谢您！
另外同时感谢typecho贡献了这个简洁的博客程序！
