### ISSUE TITLE
Markdown 列表项间的缩进只有一行有效

### ISSUE THREAD

**Issue by yujincheng08** [typecho/typecho#830]
### 1. 该问题的重现步骤是什么？
输入这样的文本
```markdown
- ABS
123
456
```
### 2. 你期待的结果是什么？实际看到的又是什么？
我觉得应该是这样的效果：
- ABS
123
456

但是却是这样的结果：
- ABS
123

456

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 18.04.1 LTS
- Apache/NGINX 版本：Apache/2.4.29
- 数据库版本：Mysql  Ver 14.14 Distrib 5.7.24
- PHP 版本：PHP 7.2.10-0ubuntu0.18.04.1
- Typecho 版本：Typecho 1.1(17.10.30)
- 浏览器版本：Chrome Version 71.0.3578.98 (Official Build) (64-bit)

![screenshot from 2019-01-22 22-54-24](https://user-images.githubusercontent.com/5022927/51543548-c4f89b00-1e98-11e9-9d3a-716a9876e743.png)

**Comment by chengjianxi** [comment]
现在的Markdown解析确实有很多问题

**Comment by hxuf** [comment]
换个解析器就OK了。Markdown暂时没有统一标准。

**Comment by yujincheng08** [comment]
@hxuf 有什么推荐的解析器吗？谢谢！

**Comment by hxuf** [comment]
> @hxuf 有什么推荐的解析器吗？谢谢！

我用的这个https://github.com/mrgeneralgoo/typecho-markdown

**Comment by yujincheng08** [comment]
@hxuf thx!

**Comment by lonepair** [comment]
> 
> 
> 换个解析器就OK了。Markdown暂时没有统一标准。

有人想搞，还惹怒了 Markdown 创始人
https://younghz.github.io/Markdown/
http://blog.codinghorror.com/standard-markdown-is-now-common-markdown/
