### ISSUE TITLE
Adapter Typecho_Db_Adapter_Pdo_SQLite is not available

### ISSUE THREAD

**Issue by benzBrake** [typecho/typecho#836]
### 1. 该问题的重现步骤是什么？
重装系统还原备份数据typecho无法正常运行
使用PDO SQLite适配器，报错Pdo_SQLite对象不存在
```
Adapter Typecho_Db_Adapter_Pdo_SQLite is not available
Typecho_Db_Exception: Adapter Typecho_Db_Adapter_Pdo_SQLite is not available in /home/wwwroot/32mb.cn/var/Typecho/Db.php:123
Stack trace:
#0 /home/wwwroot/32mb.cn/config.inc.php(34): Typecho_Db->__construct('Typecho_Db_Adap...', 'typecho_')
#1 /home/wwwroot/32mb.cn/index.php(11): include_once('/home/wwwroot/3...')
#2 {main}
```
### 2. 你期待的结果是什么？实际看到的又是什么？

正常运行；2.14单身狗对象不存在

### 3. 问题出现的环境

- 操作系统版本： Debian Jessie
- Apache/NGINX 版本： nginx/1.14.2
- 数据库版本：sqlite 3.8.7.1
- PHP 版本：PHP 7.0.33-1~dotdeb+8.1 (cli) ( NTS )
- Typecho 版本：起不来不知道怎么看
- 浏览器版本：无关紧要

[//]: # (如有图片请附上截图)

**Comment by benzBrake** [comment]
自己弄好了，php没装好

**Comment by jc911** [comment]
我也是。通过phpinfo发现没有pdo_sqlite。。。单装sqlite好像很麻烦

**Comment by keuin** [comment]
我在php.ini里启用了sqlite3和sqlite，然后仍然出现这个提示，最后用phpinfo发现并没有安装成功，于是用apt安装php-sqlite，然后就可以了
