### ISSUE TITLE
能够通过评论注销管理员账户 - bug

### ISSUE THREAD

**Issue by hydingsy** [typecho/typecho#845]
### 1. 该问题的重现步骤是什么？

在支持 Markdown 的评论系统中发布 `![](/action/logout)`，管理员登录情况下一旦图片加载完成，则自动注销管理员账户。

### 2. 你期待的结果是什么？实际看到的又是什么？

可以防止此类攻击（如果要删除评论只能通过修改数据库）。实际上 Typecho 并没有任何措施。

### 3. 问题出现的环境

- 操作系统版本：Linux - Ubuntu 16.04（64 位）
- Apache/NGINX 版本：nginx 1.14
- 数据库版本：mysql 5.5
- PHP 版本：php 7.1
- Typecho 版本：Typecho 1.1 (17.10.30)
- 浏览器版本：Chromium 72.0.3626.12

[//]: # (如有图片请附上截图)

**Comment by gcmwhite** [comment]
我试了一下，确实被注销了
这问题严重了

**Comment by yifan68** [comment]
快两年了，什么时候更新版本啊
