### ISSUE TITLE
如何更改typecho端口

### ISSUE THREAD

**Issue by kirainl** [typecho/typecho#851]
### 1. 该问题的重现步骤是什么？

正常的lnmp安装

### 2. 你期待的结果是什么？实际看到的又是什么？

期待进入安装界面，但是因为80口被封了，当然是183错误。

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx
- 数据库版本：meriaDB
- PHP 版本：7.2
- Typecho 版本：1.1
- 浏览器版本：.。。

[//]: # (如有图片请附上截图)

**Comment by imlison** [comment]
端口不是typecho管理的，是由web软件决定的

**Comment by quartz010** [comment]
你的 web 服务器选的是什么,在里面进行配置

**Comment by kirainl** [comment]
谢啦，已解决。
通过lnmp安装的，通过修改vhost配置文件就行了。
主要是之前google到的结果都让我去改typecho内部的配置文件。。。
