### ISSUE TITLE
对不起，无法连接数据库，请先检查数据库配置再继续进行安装

### ISSUE THREAD

**Issue by P7XXTMX** [typecho/typecho#861]
centos7
php72w
apache
Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 24 2019 13:45:48
mysql Ver 14.14 Distrib 5.7.24,
已在/var/www/html 给予777权限
已在数据库中建立typecho数据库
测试数据没问题，就是连接不上

**Comment by P7XXTMX** [comment]
![123123](https://user-images.githubusercontent.com/39622042/58003249-fd407b00-7b12-11e9-8400-ce82173ad3bb.PNG)

![1558336662(1)](https://user-images.githubusercontent.com/39622042/58003091-9de26b00-7b12-11e9-9892-2a1567a9af5c.jpg)
![1558336782(1)](https://user-images.githubusercontent.com/39622042/58003144-bc486680-7b12-11e9-80c0-573f411db799.jpg)

**Comment by wbh1226** [comment]
先查一下连接的账号主机名是localhost还是%。建议%，连接ip建议用127.0.0.1。

**Comment by P7XXTMX** [comment]
> 先查一下连接的账号主机名是localhost还是%。建议%，连接ip建议用127.0.0.1。

数据库连接没问题，我在虚拟机中用mysql -h ip -u -p命令连接测试过，数据库在我的vps里，我在本地用Navicat连接都正常用，我准备先在本地布置一下的，没想到碰到这个问题

**Comment by wbh1226** [comment]
连接的账号有远程连接的权限吗。建立typecho库的时候最好给同名权限

**Comment by P7XXTMX** [comment]
> 连接的账号有远程连接的权限吗。建立typecho库的时候最好给同名权限

在本地虚拟机用命令都连上了当然有权限，今天我又测了一边发现虚拟机中的新安装的数据库能连上，远程数据还是不能连上

**Comment by BinZhiZhu** [comment]
我也遇到一直提示数据库配置问题 后来貌似看到一个issue有说过 尝试把数据库地址localhost改为ip地址即可  我改为127就可以了

**Comment by ycg31** [comment]
<?php
$con = mysql_connect("localhost:3306","root","********");
if (!$con)
  {
  die('Could not connect: ' . mysql_error());
  }
 
echo "!!!";
 
mysql_close($con);
?>  我用这些代码测试都是能连上的，typecho就不行  奇怪了

**Comment by P7XXTMX** [comment]
这个问题可以关闭了，我已经解决了，彻底关闭SELinux,我用命令能连通，在java应用也可以，就是php不行，后来我从谷歌搜索到关闭SELinux，这个问题就解决了，WordPress安装也是数据库连接不上，也是关闭SELinux就解决了
