### ISSUE TITLE
安装成功后除了首页、登录页其他页面全部404

### ISSUE THREAD

**Issue by BinZhiZhu** [typecho/typecho#866]
### 1. 该问题的重现步骤是什么？
 安装成功后点击返回首页，可以看到正常的页面，返回登录也是正常的登录页面，登录后跳转404，首页的链接全部404，点击控制面板页面也是404
### 2. 你期待的结果是什么？实际看到的又是什么？
 这些链接的页面不是自动生成的吗？？？全部都是404
### 3. 问题出现的环境
除了首页、登录页 其他全部404
- 操作系统版本：
- Apache/NGINX 版本：nginx/1.17.0
- 数据库版本：8.0
- PHP 版本：PHP 7.1.26 (cli)
- Typecho 版本：最新版本 
- 浏览器版本：Google Chrome 版本 74.0.3729.157（正式版本） （64 位）

[//]: # (如有图片请附上截图)

![image](https://user-images.githubusercontent.com/35824900/58364836-a78e1900-7eec-11e9-9401-54095c4c0ff4.png)
![image](https://user-images.githubusercontent.com/35824900/58364842-c55b7e00-7eec-11e9-8865-3d290e7f8a9d.png)
![image](https://user-images.githubusercontent.com/35824900/58364843-d4dac700-7eec-11e9-862d-7a13539ced43.png)
![image](https://user-images.githubusercontent.com/35824900/58364845-dc01d500-7eec-11e9-830f-aa8ddaab6238.png)

**Comment by BinZhiZhu** [comment]
已解决 伪静态配置问题

**Comment by hrj5032188** [comment]
请问这里怎么解决的？我刚安装的，也遇到了一样的问题
