### ISSUE TITLE
PHP警告：Undefined index: cid in

### ISSUE THREAD

**Issue by fxzxmicah** [typecho/typecho#868]
### 1. 该问题的重现步骤是什么？
发布文章时出现此提示
### 2. 完整提示：
PHP Notice:  Undefined index: cid in D:\inetpub\wwwroot\var\Widget\Contents\Post\Edit.php on line 256
### 3. 问题出现的环境

- 操作系统版本：Windows10 17763
- IIS 版本：10
- 数据库版本：8.0
- PHP 版本：7.2
- Typecho 版本：1.1
- 浏览器版本： 74.0.3729.169

[//]: # (如有图片请附上截图)

**Comment by eyson** [comment]
应该是脏数据，没有找到对应的分类ID。重新安装下或重置数据库数据试试

**Comment by fxzxmicah** [comment]
嗯，谢谢，已经重装解决了 @eyson
