### ISSUE TITLE
RestApi支持

### ISSUE THREAD

**Issue by fcwys** [typecho/typecho#877]
后续会支持RestApi吗？

**Comment by majorlin** [comment]
应该不会了，已经凉凉~

**Comment by fcwys** [comment]
好吧，目前还有插件能用

**Comment by yumindeckard** [comment]
有插件，但我知道你的意思，想要native支持，但这里的话，就会引入另一个新的问题： auth

rest api，如果read only，当然可以的，不需要auth，但你如果发表评论，或者你作为admin来写新的文章，当然是要考虑auth，那样的话，其实就麻烦了，即便是wordpress，也会有比较麻烦的问题。

是运行的一个oauth server ？还是支持第三方登录？

这个feature不太好加，即便作者有心情加
