### ISSUE TITLE
使用https后主页CSS加载失败，后台CSS加载正常

### ISSUE THREAD

**Issue by XueMeijing** [typecho/typecho#878]
### 1. 该问题的重现步骤是什么？
弄好https证书和Apache配置文件，在config.inc.php开启https，重启服务器，访问域名主页无法加载css，后台可以正常加载css
![微信图片_20190729143255](https://user-images.githubusercontent.com/35559153/62026609-0d10c580-b20e-11e9-841e-b9d6f91097d1.png)
![微信图片_20190729143324](https://user-images.githubusercontent.com/35559153/62026635-1bf77800-b20e-11e9-9339-16be2c7c1092.png)

### 2. 你期待的结果是什么？实际看到的又是什么？
期待看到主页正常显示，实际CSS加载失败
### 3. 问题出现的环境

- 操作系统版本：Debian9.0
- Apache/NGINX 版本：Apache2
- 数据库版本：
- PHP 版本：PHP7.0
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by ShangJixin** [comment]
`<link href="https://118.25.196.10/usr/themes/pinghsu/style.min.css?20170331" rel="stylesheet">`
后台找设置 把站点链接改成`aihanyan.com`
118.25.196.10 未配置SSL证书 所以不会加载

**Comment by XueMeijing** [comment]
可以了可以了，谢谢大佬！！




------------------ 原始邮件 ------------------
发件人: "尚寂新"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 中午12:07
收件人: "typecho/typecho"<typecho@noreply.github.com>;
抄送: "我好菜啊"<50608771@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [typecho/typecho] 使用https后主页CSS加载失败，后台CSS加载正常 (#878)




<link href="https://118.25.196.10/usr/themes/pinghsu/style.min.css?20170331" rel="stylesheet">
 后台找设置 把站点链接改成aihanyan.com
 118.25.196.10 未配置SSL证书 所以不会加载
