### ISSUE TITLE
页面返回错误

### ISSUE THREAD

**Issue by hugoyue** [typecho/typecho#884]
### 1. 该问题的重现步骤是什么？
任意使用typecho的网站检测一个不存在的页面，例如访问 https://主页地址/任意四位数/ 

### 2. 你期待的结果是什么？实际看到的又是什么？
正常情况应返回404状态，实际显示xxxx年，错误返回200状态 判定为正常页面

### 3. 问题出现的环境

- 操作系统版本：CentOS 6.x
- Apache/NGINX 版本：1.14.1
- 数据库版本：
- PHP 版本：7.2
- Typecho 版本： 1.1 (17.10.30)
- 浏览器版本：Chrome

**Comment by ShangJixin** [comment]
最新版开发版成功复现

**Comment by AlanDecode** [comment]
该类路由触发了 Typecho 按年归档的功能，返回 200 不能算错误处理吧（搜索时如果没有结果也是返回 200）。

不过可以把太离谱的数字过滤掉，比如 9999 年之类的……

**Comment by ShangJixin** [comment]
@AlanDecode 
我说的呢 刚才我拿的2333试的，成功复现题主的情况。看你的说完了之后，又试了下2018，果然都是2018年的文章...
也是个小特征吧 之前不太知道😂
