### ISSUE TITLE
文章发布后，内容再编辑发布后，文章内容没有改变，请教一下是什么问题

### ISSUE THREAD

**Issue by JunqiFu** [typecho/typecho#885]
### 1. 该问题的重现步骤是什么？
后台管理文章编辑页面，发布后的文章，内容修改后保存草稿和发布文章都无法保存，发布日期还是显示第一次发布的时间，无更新

### 2. 你期待的结果是什么？实际看到的又是什么？
文章发布之后我需要修改文章内容，重新编辑够能够发布，看到的实际情况是文章内容再次编辑后发布，内容无改变

### 3. 问题出现的环境

- 操作系统版本：CentOS Linux 7.6.1810 (Core)　
- Apache/NGINX 版本：Nginx1.16
- 数据库版本：MySQL 5.6.44
- PHP 版本：PHP7.2
- Typecho 版本：1.1-17.10.30
- 浏览器版本：版本 76.0.3809.100（正式版本） （64 位）

[//]: # (如有图片请附上截图)
已发布后，再修改编辑
![01](https://user-images.githubusercontent.com/34265930/63496501-9f964300-c4f4-11e9-80b4-b20f375247e8.png)
修改完成后再次发布，发布时间未改变
![02](https://user-images.githubusercontent.com/34265930/63496505-a2913380-c4f4-11e9-927d-42f252e2c201.png)
进入文章查看，内容为上次一次内容，未更新
![03](https://user-images.githubusercontent.com/34265930/63496512-a58c2400-c4f4-11e9-88c5-c5fedbc00386.png)

**Comment by ShangJixin** [comment]
发布时间和最后修改时间是两个日期

可以选择检查一下看看前台或者是数据库表内记录的时间戳是否发生正确的变化

**Comment by gfwyuexia** [comment]
很明显，emoji表情的锅；
方法一，改数据库，使得数据库支持emoji，网上教程很多
方法二，删除文章中的emoji表情

**Comment by renothing** [comment]
数据库编码改为utf8mb4就行了
