### ISSUE TITLE
能不能加上暂停网站

### ISSUE THREAD

**Issue by dyt5AAUI** [typecho/typecho#891]
### 1. 该问题的重现步骤是什么？
无
### 2. 你期待的结果是什么？实际看到的又是什么？
希望加上此功能，基于现在的网络安全环境复杂，可以让站长在重大节日期间关闭网站
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by eallion** [comment]
印象中有这样的插件

**Comment by dyt5AAUI** [comment]
> 印象中有这样的插件

所以 求插件

**Comment by luhe0625** [comment]
面板里挂起或者暂停解析就是了
