### ISSUE TITLE
当文章长度达到某一长度时，会导致保存失败

### ISSUE THREAD

**Issue by T-Oner** [typecho/typecho#892]
### 1. 该问题的重现步骤是什么？
发布二楼的文字到博客，在发布的时候报错。
### 2. 你期待的结果是什么？实际看到的又是什么？
期待：正常保存发布
实际：报错：
Notice: Unknown: file created in the system's temporary directory in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0

Warning: Cannot modify header information - headers already sent in /www/var/Typecho/Response.php on line 199

Warning: Cannot modify header information - headers already sent in /www/var/Typecho/Response.php on line 290
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：7.3.6-fpm
- Typecho 版本：最新开发版
- 浏览器版本：

[//]: # (如有图片请附上截图)
<img width="811" alt="WX20191011-175003@2x" src="https://user-images.githubusercontent.com/20234820/66642571-95b8d280-ec4f-11e9-9472-c238567a6897.png">

**Comment by T-Oner** [comment]
# 速评

这本书是针对发展阅读书的技巧而写，相对实用，但是比较理想化。

整书对阅读划分了层次，并对各层次的阅读给出了具体的方法论，但是所提出的方法论较为繁琐，读者可根据自己的理解和需要发展出自己的一套方法论。

# 阅读的目标

为了获得咨询而读，以及为求得理解而读。

其实我阅读的目标分三种：

1. 提升自己的技术
2. 扩展自己的知识面，企图发展出自己的思维
3. 放松

目标不同选择的读物也不同。

# 基础方法论

> 这里是读一本书的基本方法论，下面不同层次的阅读会对这个方法论做简单的增删或者改动，但是基本思想是相符的。
> 阅读的规则是多样化的，这意味着要养成一个习惯的复杂度，而非表示要形成许多个不同的习惯。

这里是读懂一本书的**基本方法论**，不同层次的阅读会对这个方法论做简单的增删或者改动，但是基本思想是相符的。

在阅读的时候提出**四个基本问题**

1. 整体来说，这本书到底在讲些什么？
2. 作者都细说了什么？怎么说的？
3. 这本书说的有道理吗？全部有道理，还是部分有道理？
4. 这本书和你有什么关系？

**不仅要学会提出问题，更要学会怎么解答这些问题**

如何帮助自己**回答**这些问题？

1. 画底线 —— 在主要的重点或重要又有力量的句子下画线
2. 在画底线处的栏外再加画一条线 —— 某一段很重要，或者需要提炼出这句中的重点
3. 在空白处做星号或者其他符号 —— 慎用，一本书强调十来个就行。
4. 在空白处编号 —— 作者成串的论述
5. 在空白处记下其他页面 —— 强调整本书中相关的论点，或者与此处有所不同的地方，方便后续提炼整书的思想
6. 将关键字或句圈出来
7. 在书页的空白处做笔记

**其实这些都是小学语文老师教过的。**

可以看到阅读的规则是多样化的，这意味着要养成一个习惯的复杂度，而非表示要形成许多个不同的习惯。

# 阅读的层次

> 1. 基础阅读

2. 检视阅读
3. 分析阅读
4. 主题阅读

## 基础阅读

阅读准备阶段，理解字符的含义以及语法文法。

## 检视阅读

有系统的略读或粗读（注意：我发现我在读书的时候总会在心里默念一遍，导致我读书很慢，但是看的比较细，这就是小时候阅读训练没有认真做导致的）

### 阅读方法

1. 先看书名页，如果有序就先看序
2. 研究目录页
3. 如果书中附有索引，也检阅一下
4. 如果书包着书衣，读一下出版者的介绍

### 需要回答的问题

1. 这是一本什么样的书
2. 整本书都在谈论什么？
3. 作者是借着什么样的整体架构来发展他的观点或者陈述他对这个主题的理解？

## 分析阅读

### 第一阶段

1. 知道自己在读的是哪一类书（不同类别的书有不同的读书方法）
2. 使用最简单的文字说明整本书在谈什么
3. 列出整本书的大纲
4. 找出作者要问的问题：作者想要解决什么？

至于各个分类的具体读法，还是去看书里的比较好

### 第二阶段

1. 找出重要的关键字，并正确理解这些关键字，透过它们与作者达成共识
2. 找出书中最重要的句子，找出其中的主旨
3. 找出作者的论述方式，架构出论述的前因后果，明白作者的推理过程
4. 找出作者的解答，确定作者已经解决了什么问题，还有哪些问题没有解决，未解决的问题中哪些是作者认为自己无法解决的。

### 第三阶段

正确的、理性的评价一本书。

## 辅助阅读（题外）

这部分主要讲解怎么阅读辅导读物，我对此的需求不大，没有详细阅读，但是我提炼出了我认为最重要的东西，也是不论阅读什么都很重要的东西：

**你要有自己的想要解答的问题，否则任何辅导书都帮助不了你。**

## 主题阅读

在我看来这个阅读方式是搞学术的人会使用的方法，在我的领域内实在比较勉强使用。解释一下什么叫主题阅读：

在做主题阅读的时候，读者会读很多书，而不是一本书，并列举出这些书之间的相关之处，提出一个所有的书都谈到的主题。借助这些书，读者需要架构出一个可能在任何一本书中都没有提过的主题分析，就像写论文一样。

介绍后相信主题阅读的要领也不言自明了：**找到你想要理解的主题，根据主题找到相关的书籍，观察并吸收这些书籍中的观点、论述，加上自己的理解，最终输出自己对这一主题的理解。**

# 另

## 如何做一个自我要求的读者？

1. 明确自己阅读的目标：获得利益 —— 不论是心灵或精神上
2. 保持主动，同时做一番努力（带着问题阅读，并解答这些问题）
3. 学会了方法论后要主动培养习惯，就跟书不能解决任何问题一样，他只能帮助你，让你去解决问题。（~~花钱买的书为什么还要花时间去读？~~）

## 公正的评断一本书

> 很重要，不仅仅在评论书方面

1. 先完整的了解一本书，不要急着开始批评
2. 不要争强好辩或盲目反对
3. 将知识上的不同意见看作是大体上可以解决的问题
4. 如果理解不了也要经过一番努力才能说自己理解不了
5. 如果作者确实写得太烂了，在反对的时候也要有理有据

**Comment by T-Oner** [comment]
```
# 速评

这本书是针对发展阅读书的技巧而写，相对实用，但是比较理想化。

整书对阅读划分了层次，并对各层次的阅读给出了具体的方法论，但是所提出的方法论较为繁琐，读者可根据自己的理解和需要发展出自己的一套方法论。

# 阅读的目标

为了获得咨询而读，以及为求得理解而读。

其实我阅读的目标分三种：

1. 提升自己的技术
2. 扩展自己的知识面，企图发展出自己的思维
3. 放松

目标不同选择的读物也不同。

# 基础方法论

> 这里是读一本书的基本方法论，下面不同层次的阅读会对这个方法论做简单的增删或者改动，但是基本思想是相符的。
> 阅读的规则是多样化的，这意味着要养成一个习惯的复杂度，而非表示要形成许多个不同的习惯。

这里是读懂一本书的**基本方法论**，不同层次的阅读会对这个方法论做简单的增删或者改动，但是基本思想是相符的。

在阅读的时候提出**四个基本问题**

1. 整体来说，这本书到底在讲些什么？
2. 作者都细说了什么？怎么说的？
3. 这本书说的有道理吗？全部有道理，还是部分有道理？
4. 这本书和你有什么关系？

**不仅要学会提出问题，更要学会怎么解答这些问题**

如何帮助自己**回答**这些问题？

1. 画底线 —— 在主要的重点或重要又有力量的句子下画线
2. 在画底线处的栏外再加画一条线 —— 某一段很重要，或者需要提炼出这句中的重点
3. 在空白处做星号或者其他符号 —— 慎用，一本书强调十来个就行。
4. 在空白处编号 —— 作者成串的论述
5. 在空白处记下其他页面 —— 强调整本书中相关的论点，或者与此处有所不同的地方，方便后续提炼整书的思想
6. 将关键字或句圈出来
7. 在书页的空白处做笔记

**其实这些都是小学语文老师教过的。**

可以看到阅读的规则是多样化的，这意味着要养成一个习惯的复杂度，而非表示要形成许多个不同的习惯。

# 阅读的层次

> 1. 基础阅读

2. 检视阅读
3. 分析阅读
4. 主题阅读

## 基础阅读

阅读准备阶段，理解字符的含义以及语法文法。

## 检视阅读

有系统的略读或粗读（注意：我发现我在读书的时候总会在心里默念一遍，导致我读书很慢，但是看的比较细，这就是小时候阅读训练没有认真做导致的）

### 阅读方法

1. 先看书名页，如果有序就先看序
2. 研究目录页
3. 如果书中附有索引，也检阅一下
4. 如果书包着书衣，读一下出版者的介绍

### 需要回答的问题

1. 这是一本什么样的书
2. 整本书都在谈论什么？
3. 作者是借着什么样的整体架构来发展他的观点或者陈述他对这个主题的理解？

## 分析阅读

### 第一阶段

1. 知道自己在读的是哪一类书（不同类别的书有不同的读书方法）
2. 使用最简单的文字说明整本书在谈什么
3. 列出整本书的大纲
4. 找出作者要问的问题：作者想要解决什么？

至于各个分类的具体读法，还是去看书里的比较好

### 第二阶段

1. 找出重要的关键字，并正确理解这些关键字，透过它们与作者达成共识
2. 找出书中最重要的句子，找出其中的主旨
3. 找出作者的论述方式，架构出论述的前因后果，明白作者的推理过程
4. 找出作者的解答，确定作者已经解决了什么问题，还有哪些问题没有解决，未解决的问题中哪些是作者认为自己无法解决的。

### 第三阶段

正确的、理性的评价一本书。

## 辅助阅读（题外）

这部分主要讲解怎么阅读辅导读物，我对此的需求不大，没有详细阅读，但是我提炼出了我认为最重要的东西，也是不论阅读什么都很重要的东西：

**你要有自己的想要解答的问题，否则任何辅导书都帮助不了你。**

## 主题阅读

在我看来这个阅读方式是搞学术的人会使用的方法，在我的领域内实在比较勉强使用。解释一下什么叫主题阅读：

在做主题阅读的时候，读者会读很多书，而不是一本书，并列举出这些书之间的相关之处，提出一个所有的书都谈到的主题。借助这些书，读者需要架构出一个可能在任何一本书中都没有提过的主题分析，就像写论文一样。

介绍后相信主题阅读的要领也不言自明了：**找到你想要理解的主题，根据主题找到相关的书籍，观察并吸收这些书籍中的观点、论述，加上自己的理解，最终输出自己对这一主题的理解。**

# 另

## 如何做一个自我要求的读者？

1. 明确自己阅读的目标：获得利益 —— 不论是心灵或精神上
2. 保持主动，同时做一番努力（带着问题阅读，并解答这些问题）
3. 学会了方法论后要主动培养习惯，就跟书不能解决任何问题一样，他只能帮助你，让你去解决问题。（~~花钱买的书为什么还要花时间去读？~~）

## 公正的评断一本书

> 很重要，不仅仅在评论书方面

1. 先完整的了解一本书，不要急着开始批评
2. 不要争强好辩或盲目反对
3. 将知识上的不同意见看作是大体上可以解决的问题
4. 如果理解不了也要经过一番努力才能说自己理解不了
5. 如果作者确实写得太烂了，在反对的时候也要有理有据
```

**Comment by eallion** [comment]
https://eallion.com/eight-hundred-and-ninetytwo 好像没有问题也

**Comment by T-Oner** [comment]
> https://eallion.com/eight-hundred-and-ninetytwo 好像没有问题也

懵逼了，我自己尝试乱打字，超过一定长度也会导致这个问题，不清楚是不是php环境导致的。没学过 PHP，碰到问题束手无策，都不知道怎么 debug

**Comment by EthsonLiu** [comment]
查看一下你的数据库，保存文章内容的那个字段，可以设置的更大一点。

**Comment by joyqi** [comment]
看起来应该是你的设置问题，你要把nginx的fastcgi_buffer_size设置大一点，另外最好看看nginx的错误日志

**Comment by T-Oner** [comment]
> 看起来应该是你的设置问题，你要把nginx的fastcgi_buffer_size设置大一点，另外最好看看nginx的错误日志

尝试设置 fastcgi_buffer_size 为 64k 仍旧不行，
下面是 nginx 的 error log
`2019/11/04 05:23:09 [warn] 6#6: *1 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 113.139.106.150, server: blog.fxcdev.com, request: "POST /action/contents-post-edit?_=e04cbf759e3580d455f81551cb8bbed5 HTTP/1.1", host: "blog.fxcdev.com", referrer: "https://blog.fxcdev.com/admin/write-post.php?cid=55"
2019/11/04 05:23:09 [error] 6#6: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0" while reading response header from upstream, client: 113.139.106.150, server: blog.fxcdev.com, request: "POST /action/contents-post-edit?_=e04cbf759e3580d455f81551cb8bbed5 HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "blog.fxcdev.com", referrer: "https://blog.fxcdev.com/admin/write-post.php?cid=55"
2019/11/04 05:23:09 [error] 6#6: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0" while reading upstream, client: 113.139.106.150, server: blog.fxcdev.com, request: "POST /action/contents-post-edit?_=e04cbf759e3580d455f81551cb8bbed5 HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "blog.fxcdev.com", referrer: "https://blog.fxcdev.com/admin/write-post.php?cid=55"
2019/11/04 05:23:09 [error] 6#6: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent in /www/var/Typecho/Response.php on line 199PHP message: PHP Warning:  Cannot modify header information - headers already sent in /www/var/Typecho/Response.php on line 290" while reading upstream, client: 113.139.106.150, server: blog.fxcdev.com, request: "POST /action/contents-post-edit?_=e04cbf759e3580d455f81551cb8bbed5 HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "blog.fxcdev.com", referrer: "https://blog.fxcdev.com/admin/write-post.php?cid=55"`

**Comment by T-Oner** [comment]
解决了。
将 `php.ini` 文件中的
`upload_tmp_dir = /tmp/files` 注释掉就可以了，可能是权限的问题？具体原因不太清楚
