### ISSUE TITLE
如何让文章内容直接输出markdown源码，而不是被渲染成html内容

### ISSUE THREAD

**Issue by note4** [typecho/typecho#895]
想 文章详情不被渲染，直接显示markdown的源码，这个如何改模板可以实现？

**Comment by joyqi** [comment]
可以直接输出

```php
<?php $this->text(); ?>
```

**Comment by note4** [comment]
> 可以直接输出
> 
> ```
> <?php $this->text(); ?>
> ```



谢谢大佬，已经好残忍的动了源码


`/var/HyperDown.php` 第104行修改
修改前
 `       $html = $this->parse($text);`
修改后
 `       $html = $this->initText($text);`

😹😂
