### ISSUE TITLE
请问master分支上行的代码可以日常使用吗

### ISSUE THREAD

**Issue by lePig** [typecho/typecho#897]
官网下载的压缩包还停留在1.1 (17.10.30)，但是master分支上看作者还经常更新。请问下我能直接克隆master分支上的代码部署个人博客吗？ 

如果作者更新我就可以直接pull代码更新了。

**Comment by joyqi** [comment]
如果你要日常使用，可能要保持日常更新，这个版本可能出现有些功能只开发了一半

**Comment by lePig** [comment]
好的 明白了。 感谢大大
