### ISSUE TITLE
网站更新建议

### ISSUE THREAD

**Issue by xiaodingding** [typecho/typecho#899]
1.管理分类无法排序。
2.网站没有后裔没有友情链接设置功能。
3.建议标签可以根据文章的标题生成，或者可以由在文章的编辑界面右侧的标签栏自动生成。
4。后台的主题，支持自己进行二次开发吗？
5.以上仅仅为自己的建议哈。

**Comment by scvoet** [comment]
2. 可以通过插件实现
3. 可以通过插件实现
4. 后台主题可以自行二次开发，但不利于版本更新
