### ISSUE TITLE
开发板如何下载呀

### ISSUE THREAD

**Issue by maxiaohong-m** [typecho/typecho#905]
### 1. 该问题的重现步骤是什么？
安装时出现问题
### 2. 你期待的结果是什么？实际看到的又是什么？
正常安装
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：7.1
- Typecho 版本：
- 浏览器版本：1.1

[//]: # (如有图片请附上截图)

**Comment by fenbox** [comment]
![image](https://user-images.githubusercontent.com/360618/72201829-efb97600-3492-11ea-8d70-0a5caa3b1d85.png)

见截图中右边的按钮
