### ISSUE TITLE
文章正文中的script标签被解析

### ISSUE THREAD

**Issue by ytoworld** [typecho/typecho#909]
### 当文章中出现引用中的<script>标签时，script标签会被浏览器解析。
![image](https://user-images.githubusercontent.com/24632029/70918754-90667280-205a-11ea-868a-96228f9ddafe.png)

![image](https://user-images.githubusercontent.com/24632029/70918625-56956c00-205a-11ea-80c0-3bfcf68cd161.png)

### 预期结果
看到script被当作正文处理。
从稳定版升级到开发版之后，之前的文章因此炸了…

###  问题出现的环境

- Ubuntu 1804
- Apache2 2.4.18
- 数据库版本：
- PHP 版本：mysql  Ver 14.14 Distrib 5.7.28
- Typecho 版本：18.10.23
- 浏览器版本：Chrome 79.0.3945.79

**Comment by ytoworld** [comment]
这是最近从稳定版升级到开发版后出现的。

**Comment by ytoworld** [comment]
测试：https://ytoworld.tk/index.php/archives/1/
会alert("XSS");

**Comment by ytoworld** [comment]
试了一下，不在引用中也会解析为script标签
难道这是新版的feature?

**Comment by AlanDecode** [comment]
XSS 不是这个意思，文章正文是作者控制的，当然有自由插入 script 标签。

**Comment by ytoworld** [comment]
> XSS 不是这个意思，文章正文是作者控制的，当然有自由插入 script 标签。

是的，我后来发现这似乎是一个feature
不过它在稳定版中不是这样的(稳定版中script标签不会解析)，升级之后要逐一改文章…

**Comment by Vndroid** [comment]
用代码块 `<scripts>` 引起来就好了，不过可能需要批量修改一下了。
