### ISSUE TITLE
how to switch from japanese to english?

### ISSUE THREAD

**Issue by avierr** [typecho/typecho#924]
Hi 
Thank you for this software, it is indeed very beautiful.
sorry if I am naive but I can't find an option to switch to english. 

こんにちは
このソフトウェアをありがとう、それは確かに非常に美しいです。
素朴なのに申し訳ありませんが、英語に切り替えるオプションが見つかりません。

**Comment by scvoet** [comment]
Hey, This software is in Chinese. You can download en_US.po from [typecho/languages](https://github.com/typecho/languages), and remove it to software root/usr/langs directory. After Typecho is in English.
More detail should go to README.md in typecho/languages to read.
