### ISSUE TITLE
为什么不推出正式版

### ISSUE THREAD

**Issue by mingzaily** [typecho/typecho#933]
正式版一直是1.1，开发版为什么不转正式版

**Comment by jiid** [comment]
> 念念不忘，必有回响
因为回声有点长😅

**Comment by praming** [comment]
别提了，去年就说要发布了，结果现在还没信呢，非常时期按说时间应该充足啊。

**Comment by ClayMoreBoy** [comment]
开发版感觉已经可以满足需求

**Comment by Writeup001** [comment]
说好三年，三年又三年，美国总统都要换届了还没推出正式版:rofl:

**Comment by 10963273** [comment]
是时候退出正式版了

**Comment by mingzaily** [comment]
如果不去关注git仓库，只看官网的话，会让人以为停止维护和更新了

**Comment by langonginc** [comment]
> 说好三年，三年又三年，美国总统都要换届了还没推出正式版🤣

拜登都赢了呢。。。

**Comment by cikiChe** [comment]
特朗普又准备上台了

**Comment by mingzaily** [comment]
又过了一年了

**Comment by langonginc** [comment]
> 又过了一年了

快了，Dev 已经推出 beta.2 了

**Comment by fenbox** [comment]
敬请期待 🙊
