### ISSUE TITLE
php7.4访问后台登录网址admin/login.php报错

### ISSUE THREAD

**Issue by imycard** [typecho/typecho#944]
### 1. 该问题的重现步骤是什么？
php从7.3升级到7.4后访问后台登录网址xxx.com/admin/login.php报错。

### 2. 你期待的结果是什么？实际看到的又是什么？
期待在php7.4下正常登录。
报错PHP Notice:  Trying to access array offset on value of type null in D:\Web\typecho\admin\common.php on line 32

### 3. 问题出现的环境

- 操作系统版本：Windows Server 2019
- Apache/NGINX 版本：Microsoft-IIS/10.0
- 数据库版本：MariaDB 10.4.12
- PHP 版本：7.4.4
- Typecho 版本：最新开发板
- 浏览器版本：Chrome 80.0.361.109

[//]: # (如有图片请附上截图)

**Comment by MliKiowa** [comment]
位于 typecho/var/Widget/Menu.php
296行 返回数组NULL
位于 typecho\admin\common.php
32行操作了这个空数组 
PHP7.4规范了这里 直接操作null导致报错

**Comment by StubbornYang** [comment]
> 位于 typecho/var/Widget/Menu.php
> 296行 返回数组NULL
> 位于 typecho\admin\common.php
> 32行操作了这个空数组
> PHP7.4规范了这里 直接操作null导致报错

那请问一下我该怎么解决这个问题呢

**Comment by licxisky** [comment]
将 admin\common.php 32 行改一下就可以了
`$params = parse_url(isset($currentMenu[2]) ? $currentMenu[2] : null);`

**Comment by imycard** [comment]
fix #1049
