### ISSUE TITLE
搜索报错: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'talble.contents.authorId' in 'where clause

### ISSUE THREAD

**Issue by CberYellowstone** [typecho/typecho#945]
### 1. 该问题的重现步骤是什么？
搜索时报错
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'talble.contents.authorId' in 'where clause'
Typecho_Db_Query_Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'talble.contents.authorId' in 'where clause' in /var/www/typecho/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /var/www/typecho/var/Typecho/Db.php(367): Typecho_Db_Adapter_Pdo->query()
#1 /var/www/typecho/var/Typecho/Db.php(398): Typecho_Db->query()
#2 /var/www/typecho/var/Widget/Archive.php(1260): Typecho_Db->fetchAll()
#3 /var/www/typecho/var/Widget/Archive.php(1407): Widget_Archive->query()
#4 /var/www/typecho/var/Typecho/Widget.php(221): Widget_Archive->execute()
#5 /var/www/typecho/var/Typecho/Router.php(135): Typecho_Widget::widget()
#6 /var/www/typecho/index.php(23): Typecho_Router::dispatch()
#7 {main}`
### 2. 你期待的结果是什么？实际看到的又是什么？
我希望能正常搜索
而现在它报错,上面是开启debug后的输出
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Server version: Apache/2.4.43 (codeit)
- 数据库版本：10.5.1-MariaDB MariaDB Server
- PHP 版本：PHP 7.4.4 (cli)
- Typecho 版本：版本 1.2 (18.10.23)
- 浏览器版本：Chromium 78.0.3904.108

[//]: # (如有图片请附上截图)

**Comment by CberYellowstone** [comment]
清除cookies后恢复正常

**Comment by joyqi** [comment]
已修复，请重新检出代码
