### ISSUE TITLE
md编辑器表情导致文字丢失

### ISSUE THREAD

**Issue by sakura-he** [typecho/typecho#958]
### 1. 该问题的重现步骤是什么？
在编辑器里面输入不被识别的表情（例如安卓或ios的emoji），表情后面的文字会在保存后全部丢失
### 3. 问题出现的环境
5ba2f03206824e33036a56bad0cf46ac318d6a77
1.1 (17.10.30)
- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
5ba2f03206824e33036a56bad0cf46ac318d6a77
1.1 (17.10.30)
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by scvoet** [comment]
您所使用的 SQL 编码是 `uft8mb4` 吗？如果不是的话应修正。
