### ISSUE TITLE
找不到删除按钮

### ISSUE THREAD

**Issue by WinExp** [typecho/typecho#962]
### 1. 该问题的重现步骤是什么？
管理文章里找不到删除按钮找不到删除按钮
### 2. 你期待的结果是什么？实际看到的又是什么？
我以为会有删除按钮，可是没有
### 3. 问题出现的环境
CentOS 8.1.1911
宝塔面板免费版 7.2.0
- 操作系统版本：
- Apache/NGINX 版本：1.16.1
- 数据库版本：5.6.47
- PHP 版本：7.3
- Typecho 版本：1.1
- 浏览器版本：Microsoft Edge 81.0.416.72

[//]: # 
![image](https://user-images.githubusercontent.com/55543397/82004150-c6a13000-9694-11ea-854a-7886fe5ed38d.png)

**Comment by dyt5AAUI** [comment]
![image](https://user-images.githubusercontent.com/26762239/82022427-3debb980-96bf-11ea-935c-9a9056335cd5.png)
