### ISSUE TITLE
已发布的文章只能删除，以后会增加隐藏文章功能吗

### ISSUE THREAD

**Issue by XueMeijing** [typecho/typecho#969]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by jrotty** [comment]
编辑器右下角高级设置里有隐藏功能与密码功能

**Comment by XueMeijing** [comment]
看到了，谢谢大哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jrotty"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 下午4:57
收件人:&nbsp;"typecho/typecho"<typecho@noreply.github.com&gt;;
抄送:&nbsp;"惊涛"<50608771@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [typecho/typecho] 已发布的文章只能删除，以后会增加隐藏文章功能吗 (#969)





 
编辑器右下角高级设置里有隐藏功能与密码功能
