### ISSUE TITLE
Database Query Error

### ISSUE THREAD

**Issue by starsareintherose** [typecho/typecho#973]
### 1. 该问题的重现步骤是什么？
转移后出现500，重新安装php后，就出现Database Query Error
### 2. 你期待的结果是什么？实际看到的又是什么？
重新访问
### 3. 问题出现的环境
Nginx 1.18.0 
MySQL 5.5.62
PHP-7.4 
Pure-Ftpd 1.0.49
phpMyAdmin 
Linux工具箱
宝塔SSH终端

- 操作系统版本：CentOS 7
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：Edge Chromium 最新

[//]: # (如有图片请附上截图)

**Comment by sodading** [comment]
是否已经解决？大概率是环境配置问题

**Comment by starsareintherose** [comment]
已解决，忘备份emmm，打扰了，只是单纯下载文件
