### ISSUE TITLE
文章中的链接地址均为ip，而非主站域名

### ISSUE THREAD

**Issue by hdtopku** [typecho/typecho#976]
类似这篇文章的问题：https://www.imooc.com/wenda/detail/507150

### 1. 该问题的重现步骤是什么？
docker 环境
```
docker run -d -p 8006:80 --name typecho -v /mydata/typecho:/var/www/html yangxuan8282/typecho:php
```
#### nginx中的server配置
```
server {
    listen    80;
    server_name v.taojingling.cn;
    rewrite ^(.*)$  http://$host$1 permanent;
    location / {
      proxy_pass http://106.14.82.34:8006;
    }
  }
```

### 2. 你期待的结果是什么？实际看到的又是什么？
期待文章中的链接都是域名，而非ip

### 3. 问题出现的环境
使用docker镜像，yangxuan8282/typecho

![image](https://user-images.githubusercontent.com/14859466/85240748-c8b49680-b46b-11ea-8732-0c06797b0309.png)

![image](https://user-images.githubusercontent.com/14859466/85240717-ab7fc800-b46b-11ea-8a4f-f75dcabc4717.png)

[//]: # (如有图片请附上截图)

**Comment by Jkkoi** [comment]
Nginx 配置 `proxy_pass http://106.14.82.34:8006;` 上方 添加一行 `proxy_set_header Host $http_host;`

即
```
server {
    listen    80;
    server_name v.taojingling.cn;
    rewrite ^(.*)$  http://$host$1 permanent;
    location / {
      proxy_set_header Host $http_host;
      proxy_pass http://106.14.82.34:8006;
    }
  }

```

**Comment by biuaxia** [comment]
> 类似这篇文章的问题：https://www.imooc.com/wenda/detail/507150
> 
> ### 1. 该问题的重现步骤是什么？
> docker 环境
> 
> ```
> docker run -d -p 8006:80 --name typecho -v /mydata/typecho:/var/www/html yangxuan8282/typecho:php
> ```
> 
> #### nginx中的server配置
> ```
> server {
>     listen    80;
>     server_name v.taojingling.cn;
>     rewrite ^(.*)$  http://$host$1 permanent;
>     location / {
>       proxy_pass http://106.14.82.34:8006;
>     }
>   }
> ```
> 
> ### 2. 你期待的结果是什么？实际看到的又是什么？
> 期待文章中的链接都是域名，而非ip
> 
> ### 3. 问题出现的环境
> 使用docker镜像，yangxuan8282/typecho
> 
> ![image](https://user-images.githubusercontent.com/14859466/85240748-c8b49680-b46b-11ea-8732-0c06797b0309.png)
> 
> ![image](https://user-images.githubusercontent.com/14859466/85240717-ab7fc800-b46b-11ea-8a4f-f75dcabc4717.png)

代理没弄好，楼上已经给出解决方案了。
