### ISSUE TITLE
xmlrpc支持自定义字段设置么

### ISSUE THREAD

**Issue by nlysh007** [typecho/typecho#977]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
据我所知，xmlrpc协议目前并不支持自定义字段

**Comment by Timchacode** [comment]
这个问题有可以细说的大佬嘛！我阅读源码，是源码部分没有写入xmlrpc 关于自定义字段设置的增删改。是因为协议不支持源码不不写的嘛？
