### ISSUE TITLE
请问使用sqlite数据库的路径可以改为相对路径吗，方便迁移

### ISSUE THREAD

**Issue by BapiGso** [typecho/typecho#982]
### 1. 该问题的重现步骤是什么？
无
### 2. 你期待的结果是什么？实际看到的又是什么？
希望sqlite数据库路径变为相对路径，比如这样$_SERVER['DOCUMENT_ROOT'].'/usr/xxxxxxxxxxxxx.db',
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx1.16.1
- 数据库版本：sqlite3
- PHP 版本：7.3
- Typecho 版本：1.1正式版
- 浏览器版本：chrome76

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
这是个很好的建议，我可以实现一下。

**Comment by BapiGso** [comment]
> 这是个很好的建议，我可以实现一下。

感谢，期待今年夏天的正式版哦，祝您生活愉快
