### ISSUE TITLE
是否支持 Serverless 环境部署？

### ISSUE THREAD

**Issue by renbaoshuo** [typecho/typecho#989]

**Comment by JupiterJun** [comment]
支持，我已经成功部署在阿里云函数计算上了，借助NAS存储，用官方部署WP的方法把代码换成Tyepcho的即可。
https://www.hzgeek.top/

**Comment by renbaoshuo** [comment]
> 支持，我已经成功部署在阿里云函数计算上了，借助NAS存储，用官方部署WP的方法把代码换成Tyepcho的即可。
> https://www.hzgeek.top/

衡中大佬！！！石家庄二中的路过
