### ISSUE TITLE
rss订阅可免密查看加密文章

### ISSUE THREAD

**Issue by ZGGSONG** [typecho/typecho#993]
### 1. 该问题的重现步骤是什么？

使用rsshub订阅，feedly阅读器可查看加密文章内容

### 2. 你期待的结果是什么？实际看到的又是什么？

期待：当然是加密的被完好的加密
实际：加密内容可随意查看

### 3. 问题出现的环境

- 操作系统版本：winodws10/mac os10.15.3
- Apache/NGINX 版本：NGINX:1.12.2
- 数据库版本：5.6.37
- PHP 版本：5.6
- Typecho 版本：开发版1.2
- 浏览器版本：Chrome 84.0.4147.89（正式版本） （64 位）

### 4.截图

![rss_1](https://user-images.githubusercontent.com/49741009/88272541-7638f500-cd0b-11ea-85f3-62873eaeb7cc.png)

![rss_2](https://user-images.githubusercontent.com/49741009/88272551-7802b880-cd0b-11ea-8343-5b3fe9783e94.png)

![rss_3](https://user-images.githubusercontent.com/49741009/88272555-7933e580-cd0b-11ea-8a33-904ce265ed2f.png)

**Comment by wuxianucw** [comment]
无法复现。请确认是否有插件更改了文章的 hidden 状态。

**Comment by ZGGSONG** [comment]
看了下，应该是没有的，这是我录得gif：https://cdn.jsdelivr.net/gh/zggsong/cdn/blog/bitwarden-chrome.gif

**Comment by ZGGSONG** [comment]
此外，已删除的文章也能在这里看到

**Comment by wuxianucw** [comment]
那是否有使用 cdn 缓存之类的产品呢？错误的 cdn 缓存配置也可能会导致此类问题。

**Comment by ZGGSONG** [comment]
使用又拍云CDN，配置的话，应该是没有问题按照官方的步骤来的。但是只有https://cdn.zggsong.cn/2020/08/08/3418d9389439b.png这个配合feedly才能看到。其他的RSS阅读器则看不到

**Comment by ZGGSONG** [comment]
Referer防盗链，允许referer空
