### ISSUE TITLE
官网被墙了？

### ISSUE THREAD

**Issue by PencilCore** [typecho/typecho#997]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by scvoet** [comment]
并没有，浙江电信
![图片](https://user-images.githubusercontent.com/45708948/88747758-0949b300-d182-11ea-8edb-c4a574353cad.png)

**Comment by wangdaodao** [comment]
北京联通无法访问，只能梯子上

**Comment by LiuShaoYe-173** [comment]
江西联通、移动可以访问
